### ISSUE TITLE
[Question] How to use with private classes?

### ISSUE THREAD

**Issue by mhmdanas** [rrousselGit/freezed#100]
For example, how do I do the following:
```dart
@freezed
abstract class Person with _$Person {
  factory Person({ String name, int age }) = _Person;
}
```
but with the class name `_Person` instead of `Person`?

**Comment by rrousselGit** [comment]
The class name and the name of the redirected constructor are whatever you want.

So there's no specific instruction here. Just make it private as usual

**Comment by mhmdanas** [comment]
But if I do it like this:
```dart
@freezed
abstract class _Person with _$Person {
  factory _Person({ String name, int age }) = _Person;
}
```
Won't the constructor names conflict?

**Comment by rrousselGit** [comment]
Replace the second _Person by whatever you want.

**Comment by mhmdanas** [comment]
So I can use whatever name there and it won't matter?

**Comment by rrousselGit** [comment]
Yes, it won't matter.

**Comment by mhmdanas** [comment]
Ok, thanks for the quick reply! Closing this issue.
