### ISSUE TITLE
  @JsonSerializable(includeNullInJsonIfSetNull: true)

### ISSUE THREAD

**Issue by catalunha** [rrousselGit/freezed#1004]
See this small example repository. But I describe each part below
https://github.com/catalunha/freezed_json

file: bin/models/product_model.dart
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'product_model.freezed.dart';
part 'product_model.g.dart';

@freezed
abstract class ProductModel with _$ProductModel {
  @JsonSerializable(includeIfNull: false)
  factory ProductModel({
    required String prop1,
    @Default('P2') String prop2,
    String? prop3,
    String? prop4,
  }) = _ProductModel;
  factory ProductModel.fromJson(Map<String, dynamic> json) =>
      _$ProductModelFromJson(json);
}
```
file: bin/freezed_json.dart
```dart
import 'models/product_model.dart';

void main(List<String> arguments) {
  ProductModel prod1 = ProductModel(prop1: 'p1', prop3: 'p3');
  print(prod1);
  print(prod1.toJson());
  prod1 = prod1.copyWith(prop3: null);
  print(prod1);
  print(prod1.toJson());
}
```
Output:
```
Connecting to VM Service at ws://127.0.0.1:44969/0KXhRXoodnI=/ws
ProductModel(prop1: p1, prop2: P2, prop3: p3, prop4: null)
{prop1: p1, prop2: P2, prop3: p3}
ProductModel(prop1: p1, prop2: P2, prop3: null, prop4: null)
{prop1: p1, prop2: P2}

Exited.
```
See that I marked `@JsonSerializable(includeIfNull: false)`
The resulting json has prop1 as it is required. Correct.
The resulting json has prop2 as it has a default value. Correct.
The resulting json has prop3 as it is null but was assigned a value. Correct.
The resulting json does not have prop4 as it is null and was not assigned a value. Correct.
But now I assign the value null to prop3.
So the json should show this value as `{..."prop3":null ...}`. Because in the API I really want to assign null to this variable as I did in the model.
It would be an important feature. Because in my case I have to create a json outside the model to have this feature.
Was I clear?
Would it be possible to implement this important feature?

**Comment by rrousselGit** [comment]
You used `  @JsonSerializable(includeIfNull: false)` but I assume you wanted to use `   @JsonSerializable(includeIfNull: true)`

**Comment by catalunha** [comment]
Thank you for your precious attention.
No.
If I put `@JsonSerializable(includeIfNull: true)` in freezed I would have the following:
```dart
   prod1 = prod1.copyWith(prop3: null);
```
The following output:
```
{prop1: p1, prop2: P2, prop3: null, prop4: null}
```
See that in the model I only need prop3 as null, but prop4 also goes as null.
If I think in terms of sending to an API.
It will mark prop4 as null, but that's not what I want. Not what I did in the model.
So the model and json have different variables.
 
What I ask for your analysis would be if you could make an appointment
`@JsonSerializable(includeNullInJsonIfSetNull: true)`
So with:
```dart
   prod1 = prod1.copyWith(prop3: null);
```
The following output:
```
{prop1: p1, prop2: P2, prop3: null}
```

**Comment by rrousselGit** [comment]
That's not how it works. copyWith has nothing to do with toJson

Maybe you want to use JsonKey field 3 to set the flag for that specific field.

**Comment by catalunha** [comment]
Ok. I understand and trust your analysis. Thanks.
