### ISSUE TITLE
Expose static getters to get fields names

### ISSUE THREAD

**Issue by lirantzairi** [rrousselGit/freezed#1005]
Sometimes we need the field name as a string. It's particularly useful with Firestore's field queries. For example:
```dart
@freezed
class User with _$User {
  const factory User({
    required String name,
    required int age,
  }) = _User;

  factory User.fromJson(Map<String, Object?> json) =>
      _$UserFromJson(json);
}

void getAllUsersOfAge30() {
  FirebaseFirestore.instance.collection('users').where('age', isEqualTo: 30).snapshots()...
}
```
If freezed generates a static getter like `static String get fieldAge => 'age'` then I could use `where(User.fieldAge, isEqualTo: 30)` and avoid possible runtime errors due to the use of explicit strings (e.g, if the field age gets renamed in the future).

**Comment by rrousselGit** [comment]
I have no plans to include such a thing. It's more in the scope of a separate code generator.

Note that I've implemented `cloud_firestore_odm`. You may want to look into that, as it solves this issue and more

**Comment by lirantzairi** [comment]
@rrousselGit Thanks for the reference, can you please show me where `cloud_firestore_odm` solves this issue? If you look at https://github.com/firebase/flutterfire/blob/52c53f5c470aeca32e652cb0d477c5fc2bba7812/packages/cloud_firestore_odm/cloud_firestore_odm/example/lib/movies_screen.dart#L172C67-L172C67 (movies_screen.dart line 172), where you use batch.update(), you actually use the string 'likes' in the json which is exactly what I'm trying to avoid.

**Comment by lirantzairi** [comment]
Thank you
