### ISSUE TITLE
InvalidType generated

### ISSUE THREAD

**Issue by tlserver** [rrousselGit/freezed#1006]
**Describe the bug**
The following code can generate `.freezed.dart` but it contain Error. The generated code contain a non-exist type `InvalidType`.

**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.freezed.dart';

@freezed
class A with _$A {
  const factory A.a1() = A1; // note that A1 is public
// const factory A.a2() = A2;
// const factory A.a3() = A3;
// ...
}

@freezed
class B with _$B {
  // These two factories only accept A1 but not A, .freezed.dart file generated but contain error
  const factory B.b1(A1 a1) = _B1;
  const factory B.b2(A1 a1) = _B2;
}
```

I try to find the boundary, the following cases work.

```dart
@freezed
class C with _$C {
  // Work if accept A
  const factory C.d1(A a) = _C1;
  const factory C.d2(A a) = _C2;
}

@freezed
class D with _$D {
  // Work if only one factory
  const factory D(A1 a1) = _D;
}

@freezed
class E with _$E {
  // Work if different name
  const factory E.e1(A1 a1) = _E1;
  const factory E.e2(A1 a1DifferentName) = _E2;
}

@freezed
class F with _$F {
  // Work if adding other factory that do not have a1 parameter
  const factory F.e1(A1 a1) = _F1;
  const factory F.e2(A1 a1) = _F2;
  const factory F.e3(String s) = _F3;
}
```

**Expected behavior**
The generated code should have `A1` but not `InvalidType` as type of field `a1` .

**Comment by rrousselGit** [comment]
There are quite a few issues about it already.

Generated types as fields of a Freezed class are not supported.They don't exist at the time of the generation, so they come-up as InvalidType.
Some workarounds were put in place for specific scenarios, but not all of them can be handled easily.

Once we have macros, that should be fixed on its own. So I won't fix this before then
