### ISSUE TITLE
Missing fromJson and toJson methods for classes in freezed union

### ISSUE THREAD

**Issue by oyen-bright** [rrousselGit/freezed#1007]
I am encountering an issue with the generated code using freezed and json_serializable. The error is related to missing fromJson and toJson methods for the generated classes in the freezed union.
```

part of 'wallet_cubit.dart';


@freezed
class WalletState with _$WalletState {
  const factory WalletState.noWallet() = NoWallet;
  const factory WalletState.hasWallet({
    required WalletType walletType,
    required String walletAddress,
  }) = HasWallet;

  factory WalletState.fromJson(Map<String, dynamic> json) =>
      _$WalletStateFromJson(json);
}

```
am getting this error on the generated file 

The method '_$$NoWalletImplFromJson' isn't defined for the type '_$NoWalletImpl'.
Try correcting the name to the name of an existing method, or defining a method named '_$$NoWalletImplFromJson'.

The method '_$$NoWalletImplToJson' isn't defined for the type '_$NoWalletImpl'.
Try correcting the name to the name of an existing method, or defining a method named '_$$NoWalletImplToJson'.

The method '_$$HasWalletImplToJson' isn't defined for the type '_$HasWalletImpl'.
Try correcting the name to the name of an existing method, or defining a method named '_$$HasWalletImplToJson'.

**Comment by rrousselGit** [comment]
Make sure you've added the .g.dart part
Chances are you have the .freezed.dart one but not the   .g.dart


If not, you'll have to make a git repository to reproduce the issue. Because the error is likely something I can't know like that

**Comment by oyen-bright** [comment]
![Screenshot 2023-11-14 at 00 06 35](https://github.com/rrousselGit/freezed/assets/35768100/b61cda9f-dc49-4f76-b2f6-0d78e9c1216f)
![Screenshot 2023-11-14 at 00 06 49](https://github.com/rrousselGit/freezed/assets/35768100/ee8c7f4a-2b19-4de8-b775-36162e5ab35f)
![Screenshot 2023-11-14 at 00 07 09](https://github.com/rrousselGit/freezed/assets/35768100/24605fa3-0491-4fa3-ac43-675f21c3ee3e)
![Screenshot 2023-11-14 at 00 07 19](https://github.com/rrousselGit/freezed/assets/35768100/7dffdb8f-f265-442b-bbfe-bb75bf03397a)
