### ISSUE TITLE
Cannot pass result of ToJson() to FromJson()

### ISSUE THREAD

**Issue by PvtPuddles** [rrousselGit/freezed#1009]
**Describe the bug**
Using freezed_annotation 2.4.1, freezed 2.4.5

Freezed does not deeply convert objects to json, so trying to pass the object directly back into .fromJson() fails.

**To Reproduce**

I have a class called Location, that looks similar to:

```dart
@freezed
class Location with _$Location {
  const Location._();

  const factory Location({
    String? someField,
    String? someOtherField,
    Address? address,
  }) = _Location;

  factory Location.fromJson(Map<String, Object?> json) =>
      _$LocationFromJson(json);
}
```
Where address is another freezed class with lots of fields.  I need a function similar to copyWith, except that a null value overrides a non-null value, which looks something like:
```dart
final json = Location.toJson()
    ..["someField"] = "someVal"
    ..["someOtherField"] = null;
return Location.fromJson(json);
```

`toJson` results in the address field being an `_$AddressImpl`, whereas `fromJson` expects it to be a `Map<String, dynamic>?`, culminating in the following error:
```
flutter: type '_$AddressImpl' is not a subtype of type 'Map<String, dynamic>' in type cast
flutter: #0      _$$LocationImplFromJson (location/location.g.dart:22:49)
flutter: #1      new _$LocationImpl.fromJson (location/location.freezed.dart:352:7)
flutter: #2      _$LocationFromJson (location/location.freezed.dart:18:24)
flutter: #3      new Location.fromJson (location/location.dart:38:7)
```

**Expected behavior**
I expect to be able to pass the result of toJson immediately to fromJson, as in `return Location.fromJson( location.toJson() );`.

As a work around, I have to use an intermediary step:
```dart
final String json = jsonEncode( location.toJson() );
final Location newLocation = jsonDecode( json );
```

**Comment by rrousselGit** [comment]
You must enable `explicitToJson` 

See https://github.com/rrousselGit/freezed#fromjson---classes-with-multiple-constructors
