### ISSUE TITLE
Generated freezed classes expand == operator parameter to be nullable (dynamic)

### ISSUE THREAD

**Issue by srawlins** [rrousselGit/freezed#1016]
Generated freezed classes declare an `operator ==` override which expands the parameter type (from `Object`, on `Object.==`) to a nullable type (`dynamic`). For example:

```dart
  @override
  bool operator ==(dynamic other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ListIndexPath &&
            const DeepCollectionEquality().equals(other.index, index));
  }
```

No Dart runtime passes a `null` value to an `==` implementation. Explicitly expanding the parameter type does not seem to serve a purpose, and can lead to confusion that the function will ever see a `null` argument value. These implementation should not have an expanded parameter type of `dynamic`.

**To Reproduce**

Generate a freezed class.

**Expected behavior**

The class should not expand `operator ==`'s parameter type from `Object`.

**Comment by rrousselGit** [comment]
What's the downside to this exactly?
