### ISSUE TITLE
Generated toJson not using dependent objects toJson

### ISSUE THREAD

**Issue by DFreds** [rrousselGit/freezed#102]
I have a class Atest and class Btest like so:

```dart
@freezed
abstract class Atest with _$Atest {
  factory Atest({
    @required Btest btest,
    @required String name,
  }) = _Atest;

  factory Atest.fromJson(Map<String, dynamic> json) => _$AtestFromJson(json);
}
```

```dart
@freezed
abstract class Btest with _$Btest {
  factory Btest({
    @required int id,
    @required String name,
  }) = _Btest;

  factory Btest.fromJson(Map<String, dynamic> json) => _$BtestFromJson(json);
}
```

When I use the Atest.toJson(), it is not calling the toJson generated by Btest. This is the output for toJson in the Atest class.

```dart
Map<String, dynamic> _$_$_AtestToJson(_$_Atest instance) =>
    <String, dynamic>{
      'btest': instance.btest,
      'name': instance.name,
    };
```

This throws some issues for me, specifically with NoSQL databases that don't know how to handle a Btest type object. 

Is it possible to automatically call toJson if it's implemented for a property?

**Comment by rrousselGit** [comment]
See https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html

**Comment by DFreds** [comment]
I see. That seems to work for me. Thanks!
