### ISSUE TITLE
Check runtimeType of an object to get object in Map

### ISSUE THREAD

**Issue by KhanhPham0102** [rrousselGit/freezed#1023]
I have a problem checking the runtimeType of an object to send through HTTP.

I create a list of objects with map (The objects were generated by freezed).

> Map<Type, dynamic> lists = {
>     Email : Email(),
>     Password : Password(), 
>     Settings : Settings(),
> }

When I check the runtimeType of the object then the result is like this _$EmailImpl, _$PasswordImpl and _$SettingsImpl.

Then I want to get the above object through the key and get an error.

> 
> lists[Email] -> Correct
> lists[_$EmailImpl] -> Error
> 

So is there any way I can get the base object "Email" instead of "_$EmailImpl".

**Comment by rrousselGit** [comment]
No, that's not feasible.

You probably shouldn't be relying on runtimeType in your case then

**Comment by KhanhPham0102** [comment]
I'm using your Freezed library with Chopper library. I need to convert the body to send it. You can see it at the link below.

https://github.com/lejard-h/chopper/blob/develop/converters/converters.md

In convertRequest function, I need convert body to String. The body here could be an Object or a Map or other data types. So,  I can only get the Type of body through runtimeType to convert to the correct data type.

Do you have any solution or any idea for my problem?
