### ISSUE TITLE
Generate freezed class with generic variable name

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/freezed#1025]
I want to consume this API [here](https://docs.codemagic.io/rest-api/applications/#retrieve-all-applications) and unfortunately this is not a very well structured API, the `workflows` key has an object value, and that objecte's key is also a value:

```json
"workflows": {
	  "5d85f242e941e00019e81bd2": {
	    "name": "Android Workflow"
	   }
	}
```

I like to use freezed for my API requests and responses, along with the retrofit package, but I think I won't be able for this API.

The only solution I can imagine is if freezed could have an anoutation that breaks-down the `5d85f242e941e00019e81bd2` into another object that has a name and a value, where 5d85f242e941e00019e81bd2 is the name and it's object is the value.

I am not 100% sure about this, but maybe this might be useful for others, I kinda believe this is bad practice and maybe shouldn't be implemented. Thoughts?

**Comment by rrousselGit** [comment]
A varying variable name makes no sense. How would Freezed know that name before the program runs?

What you want is a map. Like:

```dart
@freezed
class Workflows with _$Workflows {
  factory Workflows(Map<String, Workflow> workflows}) = _Workflow;
}

@freezed
class Workflow with _$Workflow {
  factory Workflow(String name) = _Workflow;
}
```

**Comment by feinstein** [comment]
Omg, I didn't see this was a map 🤦🏼... Yeah I also think it doesn't make any sense, but wanted to ask anyway since I might be missing something... And I was lol, thanks Remi!
