### ISSUE TITLE
[Enhancement] Support lazy properties in const classes via Expando

### ISSUE THREAD

**Issue by znjameswu** [rrousselGit/freezed#103]
Currently '@lazy' getters does not support const classes.

But it may be achievable by using `Expando` class

Rather than generating
```
class _$_Data implements _Data {
  // ...
  bool _didproperty = false;
  BuiltList<SyntaxNode> _property;

  @override
  PropertyType get property {
    if (_didproperty == false) {
      _didproperty = true;
      _property = compute();
    }
    return _property;
  }
//...
```

We could instead generate
```
class _$_Data implements _Data {
  // ...
  static final _didproperty = Expando<bool>();
  static final _property = Expando<int>();

  @override
  PropertyType get property {
    if(_didproperty[this] == true) {
      return _property[this];
    }
    _didproperty[this] = true;
    final res = a;
    _property[this] = res;
    return res;
  }
//...
```

Then in theory we can use const constructor for this class. In theory, Expando has weak reference property, so it won't cause a memory leak. The lookup time in `Expando` may be a draw back, but we can use this solution only for const classes and keep the current solution for non-const classes.

This solution comes from [here](https://stackoverflow.com/questions/33218987/how-to-do-lazy-evaluation-in-dart).

**Comment by znjameswu** [comment]
As a probably related topic, the Dart language team [consider it an error](https://github.com/dart-lang/language/issues/657) if a `late final` field with an initializer appear in const classes.

But since the `@late` getter for freezed works on a different level, probably we can implement this.

**Comment by rrousselGit** [comment]
Using a static cache leads to memory leaks. 
The cache content would never ever be cleared

**Comment by znjameswu** [comment]
> Using a static cache leads to memory leaks.
> The cache content would never ever be cleared

From some limited source, it seems that `Expando` has weak reference characteristic. [Link](https://stackoverflow.com/a/26823878/10657409)

I have not tested it on DartVM, but if the weak reference is true, then when the object is inaccessible, the `Expando` entry will be cleared, similar to a Javascript `WeakMap`, which is said to be the polyfill for `Expando` in Dart2JS.

**Comment by rrousselGit** [comment]
Interesting. But the lookup time is fearsome. 

Why do you need both `@late` and a const constructor to begin with?

**Comment by znjameswu** [comment]
Const classes can be canonicalized, so some heavy computation may be deduplicated. 

Also, freezed can have a more coherent style. On the README page, almost every factory constructor is or can be made into `const`, except the one appeared in the [`late`](https://github.com/rrousselGit/freezed#late) section.

We have to admit we have no idea about how did DartVM implement `Expando`. IF they implemented it by adding inaccessible properties on each object (like in Javascript V8 or in some Javascript polyfill solutions), then there is no lookup time. If they didn't, then the lookup time is indeed problematic.

**Comment by znjameswu** [comment]
Well, I've just run some experiments on `Expando` on DartVM 2.7.0 on 'windows-x64' and debugged using Dart Observatory. 
Basically I generate 10,240,000 `Key` objects and `Value` objects and put them into `Expando`. The GC behavior is as expected, after run completed, only ~50,000 `Key` and `Value` object survives. After a manual GC trigger, only 1 object of each type survives. No leak.

However, it seems that they used a list-like structure as cache inside `Expando`, not binding data to objects. The heap snapshot is bascally like this:
![expando-3](https://user-images.githubusercontent.com/61373469/76693157-f17ff100-661d-11ea-9ada-1aa697a39bfd.png)
Also, there seems to be some memory bug on `Expando`, it stores 72.2MB of `_WeakProperty` filled with `null`s at the end and cannot be collected, even if its data is long gone.

If you feel this feature is not necessary, you can close this issue for now. @rrousselGit

**Comment by rrousselGit** [comment]
I'll close this

The idea is interesting but doesn't seem very reliable.
And to begin with, the `@late` decorator is only temporary and will be deprecated as soon as we have the actual `late` keyword.
