### ISSUE TITLE
optional field that has a custom fromJson can not handle null values

### ISSUE THREAD

**Issue by muratcankaracabey** [rrousselGit/freezed#1030]
**Describe the bug**

```
class Item with _$Item {
  const Item._();

  const factory Item({
    @JsonKey(fromJson: fromJsonString) Map<String, dynamic>? meta,
  }) = _Item;

  factory Item.fromJson(Map<String, Object?> json) => _$ItemFromJson(json);
```

**To Reproduce**

Just use the Item model above. The item.g.dart has no longer support for optional meta field.

```
$ItemImpl _$$ItemImplFromJson(Map<String, dynamic> json) => _$ItemImpl(
      meta: fromJsonString(json['meta'] as String),
```

As it now casts to String and not String?
**Expected behavior**
It should cast to String?

Or ofc. I am open to suggestions If there is a correct way of using this.

**Comment by rrousselGit** [comment]
This is a json_serializable issue, not a Freezed one.

Also, it looks to me like your fromJsonString is the issue. json_serializable generates `as String?` only if your fromJsonString accepts a `String?`. If it accepts a `String`, it'd generate `as String`
