### ISSUE TITLE
Compiling error with sealed classes

### ISSUE THREAD

**Issue by vptcnt** [rrousselGit/freezed#1031]
**Describe the bug**
I got an error in a local package using freezed to create the models.
The error message is :
Error: The 'sealed-class' language feature is disabled for this library.

I can generate the .frezzed.part and g.part with build_runner without a problem, but trying to compile does not work.
If I removed the keyword stealed, everything is fine, and I can compile the app.

**To Reproduce**
'''dart
stealed class DiscountApplication with _$DiscountApplication {
  const factory DiscountApplication({
    required DiscountApplicationAllocationMethod allocationMethod,
    required DiscountApplicationTargetSelection targetSelection,
    required DiscountApplicationTargetType targetType,
  }) = DiscountApplicationData;

  @FreezedUnionValue('AutomaticDiscountApplication')
  const factory DiscountApplication.automatic({
    required DiscountApplicationAllocationMethod allocationMethod,
    required DiscountApplicationTargetSelection targetSelection,
    required DiscountApplicationTargetType targetType,
    required String title,
  }) = AutomaticDiscountApplication;

  @FreezedUnionValue('DiscountCodeApplication')
  const factory DiscountApplication.code({
    required DiscountApplicationAllocationMethod allocationMethod,
    required DiscountApplicationTargetSelection targetSelection,
    required DiscountApplicationTargetType targetType,
    required String code,
    required bool applicable,
  }) = DiscountCodeApplication;

  factory DiscountApplication.fromJson(Map<String, dynamic> json) =>
      _$DiscountApplicationFromJson(json);
}
'''

**Expected behavior**
My dart sdk is 3.2.3, flutter 3.16.4
I am using FVM

Any ideas?

**Comment by rrousselGit** [comment]
Sounds like your app doesn't have sealed classes enabled.

That's unrelated to Freezed.  Chances are any sealed class, even without using Freezed, would have this error. So closing :)
