### ISSUE TITLE
toJson method is not working when Map values are freezed classes

### ISSUE THREAD

**Issue by LCostaN** [rrousselGit/freezed#1042]
**Describe the bug**
When you have a Map<String, FreezedClass>, method toJson doesn't call .toJson from the FreezedClass.

This might be a problem on JsonSerializable instead of Freezed, but as I'm not sure I'm putting it here as I'm using the freezed package.

If this should be handled in JsonSerialize, please copy this issue there.

**To Reproduce**

```dart
// This code was not compiled so might have errors, but the idea is the architecture
// ...............

@freezed
class Foo with _$Foo {
  const Foo._();

  const factory Foo(
   Map<String, Bar> items,
  ) = _Foo;

  factory Foo.fromJson(Map<String, Object?> json) => _$FooFromJson(json);
}

@freezed
class Bar with _$Bar{
  const Bar._();

  const factory Bar(
   String key,
  ) = _Bar;

  factory Bar.fromJson(Map<String, Object?> json) => _$BarFromJson(json);
}

// If you check .toJson implementation of Foo, you will see it doesn't call .toJson from Bar.
// That means, the map is not being serialized
//
// BTW, Deserialization is working as expected
```

**Expected behavior**

Expected that collections (List, Map,Set) would would .toJson method for each child applicable too

**Comment by rrousselGit** [comment]
You need to enable explicit_to_json from json_serializable.
