### ISSUE TITLE
Uses deprecated `@JsonKey(ignore: true)` annotation for `copyWith` and `hashCode`

### ISSUE THREAD

**Issue by lrsvmb** [rrousselGit/freezed#1043]
When generating serializable classes, freezed uses the deprecated  `@JsonKey(ignore: true)` on `copyWith` and `hashCode`. This has been deprecated since `json_serializable: ^6.6.0` and I suggest updating to the most recent way :
`@JsonKey(includeFromJson: false, includeToJson: false)`

**Comment by rrousselGit** [comment]
Fancy making a PR?
