### ISSUE TITLE
`JsonKey.fromJson` seems to be ignored

### ISSUE THREAD

**Issue by busslina** [rrousselGit/freezed#1058]
Original issue: https://github.com/rrousselGit/freezed/issues/1058

I copy this `json_serializable` issue here because its repo issues seems abandoned.

**Comment by busslina** [comment]
https://github.com/google/json_serializable.dart/issues/1409

**Comment by rrousselGit** [comment]
I am not responsible for `JsonKey.fromJson`. I'd suggest waiting for the maintainer of json_serializable to respond
