### ISSUE TITLE
Support for dynamic path on generated files

### ISSUE THREAD

**Issue by Danopie** [rrousselGit/freezed#106]
Right now Freezed generates ***.freezed.dart in the same directory as the source file. In time the directory would be filled with them which decreases readability.

This could be improved by letting the generated file path be dynamic:

`part '../../generated/***.freezed.dart';`

**Comment by rrousselGit** [comment]
This is not in the scope of Freezed, but instead build/build_runner/source_gen

Consider making an issue on these repo instead

**Comment by esDotDev** [comment]
I looked through the various bug base, but it seems like they consider this possible already and closed an issue in 2017 on it.

It would be nice to make this work, its a shame to have 2 extra files cluttering up the data package. Really dissuades you from making things as granular as maybe they should be. And anything to reduce scrolling in the Explorer is always appreciated. 

I tried `--output <directory name>` but it copied the entire folder.

**Comment by rrousselGit** [comment]
Just hide generated files in your explorer

**Comment by esDotDev** [comment]
That works too, but is not the best on a team of 4 devs. Thanks for the tip though, I'll do that.

Is this just not possible?? Builder is so hard to understand and the docs very sparse.

**Comment by rrousselGit** [comment]
Well this is not something in the scope of freezed.

There's nothing _I_ can do.

**Comment by esDotDev** [comment]
Thanks Remi, I understand, was just hoping maybe you might know the api better and have some ideas.
