### ISSUE TITLE
2.4.8 release introduced a new bug: LateInitializationError: Local 'unit' has not been initialized.

### ISSUE THREAD

**Issue by tylervanderhoef** [rrousselGit/freezed#1062]
**Describe the bug**
Running `dart pub build_runner build` on our project using the newly released 2.4.8 results in a handful of messages indicating that `Local 'unit' has not been initialized`. 
![Screenshot 2024-04-05 at 11 46 06 AM](https://github.com/rrousselGit/freezed/assets/104478095/9e752e47-3632-47cd-92e7-460e899f6fba)

Offending code it seems: https://github.com/rrousselGit/freezed/commit/c5377a9fc1b876fd617bc1d1469348ac109e05e7

![image](https://github.com/rrousselGit/freezed/assets/104478095/2811ee7d-5e00-4bb7-99a7-d3ef21ab9927)

**To Reproduce**

- Use version 2.4.8 of freezed
- run `dart run build_runner build` on a project that has previously worked when generating models using 2.4.7
- Observe errors

**Expected behavior**

The generator to run without errors.

## Workaround
Reverting to 2.4.7 works just fine, but after updating to 2.4.8 you will see the issues.

**Comment by PvtPuddles** [comment]
I also experience this issue, and I just wanted to add that for use it was more sever than just errors in the console:

Freezed files failed to generate for large portions of our codebase.  I believe it had something to do with multi-part libraries, where the top level library has the 'part' directive.

Single-file libraries seemed to generate O.K. still.

**Comment by tylervanderhoef** [comment]
For us it seemed to only fail on around 4-5 classes, but it was blowing up our build server. That was about as far as I could take it right now though.

**Comment by rrousselGit** [comment]
Hum, let me fix that.
