### ISSUE TITLE
Equals with functions/closures

### ISSUE THREAD

**Issue by doc-rj-celltrak** [rrousselGit/freezed#107]
The generated == operator always returns false for functions or closures. I'm using freezed for viewmodel classes with Redux,  and these viewmodel classes contain functions. I just noticed that my widgets are being rebuilt more often that they should be, because the equality comparison isn't working as expected. Example viewmodel:
```
  const factory HomeViewModel({
    int selectedPage,
    Function onPageChanged,
    Function onForceLocalAuth,
    Function onSignOut,
  }) = _HomeViewModel;
```
Any suggestions for this? Could the generated == operator somehow ignore functions? I've seen other implementations that do something like that. Thanks.

**Comment by rrousselGit** [comment]
The == is working as expected.
What you should instead do is cache the function.

Altering the == to return true when the objects are effectively different is a very bad idea

**Comment by doc-rj-celltrak** [comment]
Thanks @rrousselGit. When you suggest caching the function, are you suggesting something along [these lines](https://stackoverflow.com/questions/16875895/dart-member-function-equality-rules/16876415#16876415)?

I think I understand -- even if the closure has the same code, "each time a function expression is evaluated, it creates a new closure value that is not known to be equal to other closures created by the same expression." [reference here](https://api.dart.dev/stable/2.7.1/dart-core/Function/operator_equals.html).

However, caching functions would be a lot of extra overhead for the simple use case.

What about the possibility of an annotation that tells freezed to exclude a field for equals and hash code generation? This is similar to what the async_redux package does in it's BaseModel class -- "selective equals" implementation:

```
  BaseModel({this.equals = const [], this.widget})
      : assert(_onlyContainFieldsOfAllowedTypes(equals));

  /// Fields should not contain functions.
  static bool _onlyContainFieldsOfAllowedTypes(List equals) {
    equals.forEach((Object field) {
      if (field is Function)
        throw StoreException...
```

**Comment by rrousselGit** [comment]
No. Tricking == is very dangerous and bad practice.

Depending on what you mean by "my widgets are being rebuilt more often that they should be", there are many solutions.\
Caching is one of those. You could also have a wait to "pick"/"select" a subset of the state, or more these functions out of this object.

**Comment by doc-rj-celltrak** [comment]
Ok. I come from Java-world, where "selective equals and hash code" is standard practice. Maybe dart-land is very different.

I think there should be a way to exclude Functions. Basically, Functions cannot be immutable, but they are often needed in classes where the other values are immutable -- therein lies the conundrum! :)

ViewModels are the way to 'select' a subset of the state. Redux does an equals comparison between two instances of the viewmodel, and if they differ, it will re-build widgets under the StoreConnector (Provider).

Anyhow, thanks. I'll have to switch to using async_redux BaseModel for my viewmodel classes, and i can still use freezed for the state classes.
