### ISSUE TITLE
Setting the flag `@Freezed(toJson: false)` creates an error in the generated freezed files when we define a custom `toJson`.

### ISSUE THREAD

**Issue by PackRuble** [rrousselGit/freezed#1070]
**Describe the bug**
Let's assume that we need our own `fromJson` and `toJson` definitions for the `Model`. We set the appropriate flags in the `@Freezed(fromJson: false, toJson: false)` annotation. However, the generated files produce an error:
```dart
// analyzer: Missing concrete implementation of 'Model.toJson'.

class _$ModelImpl implements _Model {
  const _$ModelImpl();

  @override
  String toString() {
    return 'Model()';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is _$ModelImpl);
  }

  @override
  int get hashCode => runtimeType.hashCode;
}
```

**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';

@Freezed(fromJson: false, toJson: false)
class Model with _$Model {
  const factory Model() = _Model;

  factory Model.fromJson(Map<String, dynamic> json) => Model();

  Map<String, dynamic> toJson() => {};
}

```

**Expected behavior**
Adding a constant private constructor solves this problem, because our `toJson` method becomes an ordinary method of the `Model` class directly. So it turns out that we have to proceed according to the documentation [Adding getters and methods to our models](https://pub.dev/packages/freezed#adding-getters-and-methods-to-our-models). Is this probably expected behavior?

**Comment by rrousselGit** [comment]
That's expected. You defined a method, so you need to follow the "adding methods" protocol and add the empty/private constructor.

Otherwise Freezed cannot use your custom toJson.
