### ISSUE TITLE
Why not integrate a annotation to rename JSON fields (like in JsonSerializable)?

### ISSUE THREAD

**Issue by iqthuc** [rrousselGit/freezed#1077]
```dart
@freezed
class Player with _$Player {
  @JsonSerializable(fieldRename: FieldRename.snake)
  const factory Player({
    final int? id,
    final String? firstName,
  }) = _Player;

  factory Player.fromJson(Map<String, dynamic> json) => _$PlayerFromJson(json);
}
```
I thought there would be something similar to that @ Freezed(jsonFieldRename: JsonFieldRename.snake)

**Comment by rrousselGit** [comment]
You mean rename the generated field?

That'd be different from how most people use fieldRename

**Comment by iqthuc** [comment]
> You mean rename the generated field?
> 
> That'd be different from how most people use fieldRename

sorry about that, I've rewritten the description

**Comment by rrousselGit** [comment]
Freezed supports writing what you did in your code-snippet. 

```dart
@freezed
class Player with _$Player {
  @JsonSerializable(fieldRename: FieldRename.snake)
  const factory Player({
    final int? id,
    final String? firstName,
  }) = _Player;

  factory Player.fromJson(Map<String, dynamic> json) => _$PlayerFromJson(json);
}
```

Cf https://github.com/rrousselGit/freezed/?tab=readme-ov-file#deserializing-generic-classes
