### ISSUE TITLE
Confusing legacy tag for "Union types and Sealed classes"

### ISSUE THREAD

**Issue by romatallinn** [rrousselGit/freezed#1078]
## Context
The documentation marks the whole chapter of [Union types and Sealed classes](https://pub.dev/packages/freezed#legacy-union-types-and-sealed-classes) as Legacy. It gives an impression that this whole thing should be avoided and be better done in native dart. It gives a note explaining the details, and the case for `map/when` vs `switch` is clear and contains accurate reasoning. 

## Problem 
Nevertheless, if I am not mistaken, Union types and Sealed classes themselves are not outdated and are still relevant? It's just `map/when` should be replaced with `switch` and alike? 

Relevant use-case for union types: parsing json and convert it to a specific model by `unionKey`.

## Solution
Re-structure chapter in the way that block about `map/when` specifically is noted as legacy, but not union types as a whole.

## Additional context
As of Dart 3, Dart now has built-in pattern-matching using sealed classes.
As such, you no-longer need to rely on Freezed's generated methods for pattern matching. Instead of using when/map, use the official Dart syntax.

**Comment by romatallinn** [comment]
I can imagine it's me missing a common way to replace this functionality with dart-native, but then it should be outlined in the chapter as well (e.g., how to migrate freezed union type to dart union type).

**Comment by rrousselGit** [comment]
It's just map/when that's legacy. Unions are still supported.

**Comment by adriank** [comment]
Any chance for change in docs? Currently, it says:

> (Legacy) Union types and Sealed classes

Should be

> Union types and Sealed classes
> (Legacy) Using pattern matching to read non-shared properties](https://pub.dev/packages/freezed#using-pattern-matching-to-read-non-shared-properties

**Comment by rrousselGit** [comment]
Sure, feel free to make a PR
