### ISSUE TITLE
Switch from a model M1 to a model M2

### ISSUE THREAD

**Issue by ThomasDevApps** [rrousselGit/freezed#1079]
Hello, 

The models generated by Freezed are very useful for many developers, including me ! So first of all, thank you for this package.
However, there's one feature that might be nice to implement, that's the ability to switch from a model M1 to a model M2 : 

```dart
@freezed
sealed class User with _$User {
  const factory User.toInsert({
    required String username,
  }) = UserToInsert;

  const factory User.data({
    required String id,
    required String username,
    required DateTime createdAt,
  }) = UserData;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
```
 We will therefore have a method for switching from UserToInsert to UserData and vice versa. 

**Note : Similar fields do not need to be redefined**.

```dart
const userToInsert = UserToInsert(username: 'toto');
final newUserData = userToInsert.toUserData(
  id: '1-e5',
  // No need to redefine username
  createdAt: DateTime.now(),
);
```
```dart
const userData = UserData(
  id: '4-f8',
  username: 'toto',
  createdAt: DateTime.now(),
);
final newUserToInsert = userData.toUserToInsert();
```

Currently the workaround is : 

```dart
extension UserToDataExtension on UserData {
  UserToInsert toUserToInsert() {
    return UserToInsert(username: username);
  }
}
```

```dart
extension UserToInsertExtension on UserToInsert {
  UserData toUserData({
    required String id,
    required DateTime createdAt,
  }) {
    return UserData(
      id: id,
      username: username,
      createdAt: createdAt,
    );
  }
}
```
Using this method, you can have models for insertions into databases (where the id and other fields are given directly in the backend) and easily convert them into a "normal" model.

However, static metaprogramming may be mandatory for this type of method.

**Comment by rrousselGit** [comment]
This sort of logic isn't simple to implement, because it's common that two models aren't fully compatible.

The code-generator wouldn't know how to solve the possible conflict. Doing things by hand is generally the best here I think.
