### ISSUE TITLE
Using macros insted build_runner

### ISSUE THREAD

**Issue by TheLastFlame** [rrousselGit/freezed#1091]
_It's been a day since the test implementation of macros was introduced, but there is still no issue with a suggestion to use them._

Perhaps it is not optimal to develop an implementation based on them before the macros api is released in stable.
But I am creating this issue to be able to keep track of updates on this topic.

**Comment by rrousselGit** [comment]
There's already an issue and I already closed it ;) 

As I said in the other issue:
Macros are lacking too many features to post Freezed as is.

I'm working on some stuffs, with workarounds and stuff. We'll see.
But there's not really a point in having this issue around for now.
