### ISSUE TITLE
freezed and macros

### ISSUE THREAD

**Issue by manlyman29** [rrousselGit/freezed#1092]
Today Flutter team announced macros for Flutter bringing the benefits of meta programming to dart without the performance drawback of code generation. I was wondering how would that place freezed in the future.

From my understanding macros once stabilized can do all common data class functionalities (like this package https://github.com/felangel/data_class). That leaves freezed with union type which I don't know a nice syntax like what freezed offers for that.

My question is whether freezed can/will eventually be based on macros?

**Comment by rrousselGit** [comment]
Yes, this is in progress. Give me a day or two.
