### ISSUE TITLE
freezed 2.5.3 analyzer 6.5.0 problem

### ISSUE THREAD

**Issue by mehrdad1990** [rrousselGit/freezed#1093]
Hi
the problem is when you run build_runner command to generate related classes. but after upgrading there are some conflicts.
Error: Required named parameter 'withNullability' must be provided.
              .map((e) => e.getDisplayString())
freezed-2.5.3/lib/src/templates/parameter_template.dart:16:45: Error: Required named parameter 'withNullability' must be provided.
      generics.map((e) => e.getDisplayString()).toList(),

is there any way to fix this or we should downgrade?

**Comment by rrousselGit** [comment]
You need an analyzer version >= 6.5.0

**Comment by mehrdad1990** [comment]
> You need an analyzer version >= 6.5.0

of course I did. but it confilcts with flutter_test, flutter_localization and flutter because of "meta:1.14.0" package.
I tried everything but didn't find a solution to ignore these errors while using build_runner.
could you try and give me an applicable solution or a walkthrough?

**Comment by rrousselGit** [comment]
Then you'll have to wait until Flutter upgrade, or use a lower Freezed version.

**Comment by anlumo** [comment]
What is the latest version of freezed that works with flutter?

**Comment by mehrdad1990** [comment]
> What is the latest version of freezed that works with flutter stable?

freezed 2.5.2 worked for me

**Comment by anlumo** [comment]
Could I make a kind request to freezed to please not break builds with a minor version update? This issue has taken three unplanned work days for me to look into so far.

**Comment by rrousselGit** [comment]
Freezed didn't break anything here.
It specifies `analyzer: ^6.5.0`. So if you're trying to use Freezed with an analyzer version that's lower than 6.5.0, I can't help it.
