### ISSUE TITLE
Support getters

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/freezed#11]
This will not compile, or at least, no _$Person will be created.
Is this something you don't want/or is impossible  to support? 

```dart
@immutable
abstract class Person with _$Person {
  const factory Person(String firstName, String lastName) = _Person;

  String get fullName => '$firstName $lastName';
}
```

**Comment by rrousselGit** [comment]
Getters can't work. There's no way to support them since `Person` is _implemented_ not _extended_.

But you can use extensions:

```dart
@immutable
abstract class Person with _$Person {
  const factory Person(String firstName, String lastName) = _Person;
}

extension on Person {
  String get fullName => '$firstName $lastName';
}
```

**Comment by rrousselGit** [comment]
I wonder if it's possible to have the generator "copy-paste" the source code of getters to the generated classes though

**Comment by smiLLe** [comment]
I was thinking the same but this feels kind of too much magic.

creating an extension is absolutely fine :) i didn't event think about it.

**Comment by rrousselGit** [comment]
I'll experiment with it anyway.
That would be a big improvement to the syntax.

The class is immutable and type-safe anyway. It should be safe.

**Comment by smiLLe** [comment]
maybe something like this? 

```dart
@memo
String get fullName => '$firstName $lastName';
}
```

**Comment by rrousselGit** [comment]
Why `@memo`?

**Comment by smiLLe** [comment]
to make it more obvious.

it could generate code
```dart
String _fullName;
String get fullName => _fullName ??= '$firstName $lastName';
```

**Comment by rrousselGit** [comment]
Hum, I'm not sure caching the result is a good idea.

I'd prefer and wait for the 2.8 with `late`:

```dart
late final fullName = '$firstName $lastName';
```

**Comment by smiLLe** [comment]
alright :) 

do you see any advantage by "copy paste" the getter instead of using a simple extension?

**Comment by rrousselGit** [comment]
It's more natural. That's your first attempt after-all right?

And extensions require a new name + they are located in a different place.
A getter removes the need for a name and keeps things together.

**Comment by smiLLe** [comment]
The naive me was like " this getter must automatically work ".
The problem i see with "copy paste" the getter is, that people will change their getter without thinking about rebuilding, because it is not obvious.

forcing them to annotate the getter might help.

**Comment by rrousselGit** [comment]
Hum I don't mind that.
After all, Flutter tries to support code-generators natively to run them automatically for you.

It's only a matter before we fully stop the `build_runner` thing

**Comment by smiLLe** [comment]
I am +1 for annotation until build_runner really became obsolete.

**Comment by rrousselGit** [comment]
An annotation package is _horrible_ to maintain. Unless there's a very obvious reason to use an annotation, I would refrain from making one.

**Comment by smiLLe** [comment]
I understand. Then i'll +1 for the easiest possible implementation and wait if people "forget" about rebuilding

**Comment by winterDroid** [comment]
Honestly I think extension functions are just easy enough to use!

**Comment by rrousselGit** [comment]
Extensions functions aren't part of the object prototype.


```dart
abstract class Foo {
  String get fullName;
}


@immutable
abstract class Model with _$Model implements Foo {
  factory Model(String firstName, String lastName) = _Model;
}

extension ModelExtension on Model {
  String get fullName => '$firstName $lastName';
}
```

That won't work

**Comment by rrousselGit** [comment]
Hum. Thinking about it, this wouldn't work with breakpoints.

So I'll postpone this until I find a better compromise.

**Comment by rrousselGit** [comment]
Another thought:

This would allow the generator to add these to the `toString`/`debugFillProperties` implementation.

```dart
@immutable
abstract class Person with _$Person {
  const factory Person(String firstName, String lastName) = _Person;

  String get fullName => '$firstName $lastName';
}

class _Person {

  @override
  String toString() {
    return 'Person(firstName: '$firstName', lastName: '$lastName', fullName: '$fullName');
  }
}
```

**Comment by rrousselGit** [comment]
I think I'll cancel this and just wait for `late` (which we can already use actually):

```dart
@immutable
abstract class Person with _$Person {
  const factory Person(String firstName, String lastName) = _Person;

  late final String fullName = '$firstName $lastName';
}
```

**Comment by rrousselGit** [comment]
Reopening this as it may be possible without dirty copy-paste trick after all.

We could have:

```dart
@immutable
abstract class Person with _$Person {
  const Person._();
  const factory Person(String firstName, String lastName) = _Person;

  String get fullName => '$firstName $lastName';
}
```

**Comment by rrousselGit** [comment]
Closing in favor of #83

**Comment by shilangyu** [comment]
> ```dart
> @immutable
> abstract class Person with _$Person {
>   const factory Person(String firstName, String lastName) = _Person;
> 
>   late final String fullName = '$firstName $lastName';
> }
> ```

How would one do something similar but for a specific union case? Extensions don't allow to introduce properties
