### ISSUE TITLE
[0.10.0] 'extends' clause after 'with' clause in generated code

### ISSUE THREAD

**Issue by znjameswu** [rrousselGit/freezed#110]
Using freezed 0.10.0

In some cases, we get the following generated code

```
class _$_Test with DiagnosticableTreeMixin extends _Test {
  //...
}
```
Dart analyzer will report that "extends" clause must be before "with" clause (with_before_extends). And it will cause the console to output following during code generation.

```
[SEVERE] freezed:freezed on lib/src/parser/ast/nodes.dart:
Error formatting generated source code for package:dartex/src/parser/ast/nodes.dart which was output to lib/src/parser/ast/nodes.freezed.dart.
This may indicate an issue in the generated code or in the formatter.
Please check the generated code and file an issue on source_gen if appropriate.
Could not format because the source could not be parsed:

line 96, column 50: The extends clause must be before the with clause.
   ╷
96 │ class _$_SupSubNode with DiagnosticableTreeMixin extends _SupSubNode {
   │                                                  ^^^^^^^
   ╵
```

This problem seems to originate from [here](https://github.com/rrousselGit/freezed/blob/42c2bf78dba61836f452d626c1c23d9c446a1521/packages/freezed/lib/src/templates/concrete_template.dart#L63).

**Comment by rrousselGit** [comment]
Thanks for the report.

It's an easy fix, you indeed found the problem. 
Do you want to make a PR? 😊

**Comment by znjameswu** [comment]
> Thanks for the report.
> 
> It's an easy fix, you indeed found the problem.
> Do you want to make a PR? 😊

Sorry I didn't know much about freezed codebase and code generator stuff. You can do the PR. Thx.
