### ISSUE TITLE
[0.10.1] Concrete members in const class creates error

### ISSUE THREAD

**Issue by znjameswu** [rrousselGit/freezed#111]
Using 0.10.1

The example given in the README won't generate correct output, due to the non-const private constructor `Person._()` was used in a const scenario in the generated code .

Code:
```
@freezed
abstract class Person with _$Person {
  Person._(); // Added constructor
  const factory Person(String name, {int age}) = _Person;

  void method() {
    print('hello world');
  }
}
```
Generated Code:
```
//...
abstract class _Person extends Person {
  const _Person._() : super._();
  //                        ^
  // Error: A constant constructor can't call a non-constant super constructor.
  const factory _Person(String name, {int age}) = _$_Person;

  @override
  String get name;
  @override
  int get age;
  @override
  _$PersonCopyWith<_Person> get copyWith;
}
```

I didn't see a particularly good way of solving this. We can't make `Person._()` const because for no apparent reasons Dart is preventing const construtors for classes with mixins that declare getters.

**Comment by rrousselGit** [comment]
The mixin is just an interface, so you don't have to use `with` and can use `implements`\
The doc uses `with` because it's shorter, but that's about it.

So you can write:

```dart
@freezed
abstract class Person implements _$Person {
  const Person._();
  const factory Person(String name, {int age}) = _Person;

  void method() {
    print('hello world');
  }
}
```

**Comment by znjameswu** [comment]
> The mixin is just an interface, so you don't have to use `with` and can use `implements`
> The doc uses `with` because it's shorter, but that's about it.
> 
> So you can write:
> 
> ```dart
> @freezed
> abstract class Person implements _$Person {
>   const Person._();
>   const factory Person(String name, {int age}) = _Person;
> 
>   void method() {
>     print('hello world');
>   }
> }
> ```

The problem is that, you might need to modify the [example code](https://github.com/rrousselGit/freezed#custom-getters-and-methods) provided in README document because it doesn't work. @rrousselGit
