### ISSUE TITLE
Namespace not respected as generics type

### ISSUE THREAD

**Issue by westito** [rrousselGit/freezed#1114]
**Describe the bug**
<img width="473" alt="Képernyőfotó 2024-07-29 - 15 42 07" src="https://github.com/user-attachments/assets/74ab807b-8333-4bd5-b656-52017e7bd076">

<img width="412" alt="Képernyőfotó 2024-07-29 - 15 41 52" src="https://github.com/user-attachments/assets/b37a5a2b-99b6-4ee1-925a-a1607b046829">

**To Reproduce**

Use namespace (import prefix) on a class as generics type.

**Expected behavior**
Generics type paramter also gets the prefix.

**Comment by rrousselGit** [comment]
Supporting prefixes for generics is too difficult as it is. I won't support it before we have macros.
