### ISSUE TITLE
implements vs @Implements

### ISSUE THREAD

**Issue by debiotech4ayo** [rrousselGit/freezed#1126]
```
import 'package:freezed_annotation/freezed_annotation.dart';

// Use the following command to regenerate the freezed file:
// dart run build_runner build
part '../../generated/domain/entities/implemented.freezed.dart';

abstract class Implemented {
  int get value;

  /// Compute a value
  int compute();
}

@freezed
class ImplementedClass with _$ImplementedClass implements Implemented {
  @Implements<Implemented>()
  const factory ImplementedClass({
    required int value,
  }) = _ImplementedClass;

  const ImplementedClass._();

  @override
  int compute() => value;
}
```

I have some questions about inheritance / implementation with freezed after reading this [part ](https://pub.dev/packages/freezed#mixins-and-interfaces-for-individual-classes-for-union-types)and testing a bit.

Does it make sense to mix `implements` keyword with `@Implements` ? `implements` keyword permit me to retrieve the base class documentation.

Additionally it seems we can use `implements` without `@Implements` which could be counter-intuitive as missing `@Implements` makes the generated code not adding the `implements Implemented`.

```
@freezed
class ImplementedClass with _$ImplementedClass implements Implemented {
  const factory ImplementedClass({
    required int value,
  }) = _ImplementedClass;

  @override
  int compute() => value;
}
```

Gives : 

```
abstract class _ImplementedClass implements ImplementedClass {
  const factory _ImplementedClass({required final int value}) =
      _$ImplementedClassImpl;

  [...]
}
```
 However, no error is raised.

I'm not sure to understand...

**Comment by debiotech4ayo** [comment]
However, it's not possible to make a freezed class extends another class, freezed or not, right ?

**Comment by rrousselGit** [comment]
Correct, because there's no good syntax for the `super` constructor.
