### ISSUE TITLE
memoized or equivilent

### ISSUE THREAD

**Issue by jimmyff** [rrousselGit/freezed#1130]
I've moved from using built_value to freezed and I love how much more succinct this package makes my models although one feature I really miss is the [memoized annotation](https://pub.dev/documentation/built_value/latest/built_value/memoized-constant.html).

Do you think this is something freezed could get or is there a way of achieving similar that I've missed?

Thanks

**Comment by rrousselGit** [comment]
Dart natively supports that:

```dart
late final myMemoized = <some code>;
```

**Comment by jimmyff** [comment]
Not quite the same thing? This is on a getter on an immutable object so it has the major advantage over your solution that it is lazily executed (which is the main reason for this feature). Other bonus advantage is the class can still have a const constructor as doesn't use `late`.
