### ISSUE TITLE
Upgrading to 0.10.1 suddenly starts warning on all dart files

### ISSUE THREAD

**Issue by mhmdanas** [rrousselGit/freezed#114]
After upgrading to 0.10.1, I get warnings on all files that don't use Freezed. The warnings are like this:
```
[WARNING] freezed:freezed on lib/doesnt_use_freezed.dart:
Missing "part 'doesnt_use_freezed.freezed.dart';".
```
Using version 0.10.0 gives the same warnings, so I suspect it was introduced in 0.10.0.

**Comment by rrousselGit** [comment]
Could you make a small project to reproduce the issue? I do not have it.

**Comment by mhmdanas** [comment]
Here you go: [freezed-missing-part-warning.zip](https://github.com/rrousselGit/freezed/files/4365934/freezed-missing-part-warning.zip)

**Comment by rrousselGit** [comment]
Oh, I can reproduce it. Will fix 👌
