### ISSUE TITLE
Why are we using "const" factory?

### ISSUE THREAD

**Issue by Chojecki** [rrousselGit/freezed#116]
May I ask, why are we using freezed like `const factory ClassName.something() = Something;` ? 

I mean why the `const` is there? Is it just for optymalisation purpose?

**Comment by rrousselGit** [comment]
The const keyword is optional.

You can use it if you want to.

**Comment by Chojecki** [comment]
> The const keyword is optional.
> 
> 
> 
> You can use it if you want to. 

Thanks
