### ISSUE TITLE
Add // ignore: avoid_as

### ISSUE THREAD

**Issue by KlausJokinen** [rrousselGit/freezed#117]
Add `// ignore: avoid_as` into generated files to ignore warning.

**Comment by rrousselGit** [comment]
Consider excluding generated files from your linter instead

**Comment by rubgithub** [comment]
> Consider excluding generated files from your linter instead

@rrousselGit  I've tried to ignore but the warning persist, do you know how to fix this?

https://stackoverflow.com/questions/57114823/how-can-i-ignore-files-with-dartanalyzer
https://github.com/dart-lang/sdk/issues/25551

**Comment by rrousselGit** [comment]
I'd suggest contacting the Dart team/Intelij teams if the warnings persists. This is not in the scope of Freezed
