### ISSUE TITLE
Is there any way to define compareTo()?

### ISSUE THREAD

**Issue by orestesgaolin** [rrousselGit/freezed#119]
I'd like to be able to sort lists of objects that are created with freezed.

Is there any way to extend [Comparable](https://api.dart.dev/stable/2.7.1/dart-core/Comparable-class.html) or provide compareTo() method?

**Comment by rrousselGit** [comment]
Yes, see https://github.com/rrousselGit/freezed#custom-getters-and-methods

```dart
@freezed
abstract class Example<T> with _$Example<T> implements Comparable<T> {
  Example._();
  factory Example(T value) = _$Example<T>;

  @override
  int compareTo(T other) {
    return 0;
  }
}
```

**Comment by rrousselGit** [comment]
Closing this since it's already feasible
