### ISSUE TITLE
Generate "copyAs" methods

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/freezed#12]
Sometimes we have a union with common properties between the different possibilities:

```dart
@immutable
abstract class TodoList with _$TodoList {
  factory TodoList.data(List<Todo> todos) = TodoListData;
  factory TodoList.loading(List<Todo> todos) = TodoListLoading;
  factory TodoList.error(List<Todo> todos, [String message]) = TodoListError;
}
```

In such a situation, it is common to want to convert from one state to another, while preserving the common properties.

Currently, we have to use do it ourselves:

```dart
var todo = TodoList.data([]);
todo = TodoList.loading(todo.todos);
todo = TodoList.error(toto.todos, 'Error');
```

But we could simplify that by having a `copyWith` that converts to a new type:

```dart
var todo = TodoList.data([]);

todo = todo.copyAsLoading();
todo = todo.copyAsError(message: 'Error');
```

**Comment by rrousselGit** [comment]
This should support #59 to make a value not required if it has a default value

**Comment by rrousselGit** [comment]
This should also support changing the generic type arg

**Comment by rrousselGit** [comment]
Instead of `copyAsX`, it should probably be named `toX`.

This is semantically closer to what Dart does (`toList`, ...)

**Comment by samandmoore** [comment]
Been playing around with `freezed` a bunch lately in conjunction with the `flutter_bloc` package and I think this `copyAs` / `toX` functionality would be super useful. Thanks for working on this!

**Comment by rrousselGit** [comment]
Honestly, I'm skeptical on parts of this feature.

I wonder if, instead of duplicating the field between all possibilities of the union, don't we want something like:
"the last valid data"

**Comment by samandmoore** [comment]
hm. i'm not sure what you mean by "the last valid data" can you elaborate?

my use-case is something like this: I have a form for collecting a mailing address. I want to have a state for when i'm populating the form, then the form is being submitted, then when the form has submitted successfully. In order to transition from a `Populating` state to a `Submitting` state, I need to manually copy all the attributes which is super annoying and error prone. I can show some code if it helps.

**Comment by samandmoore** [comment]
@rrousselGit updated the above comment with some real code to make it more concrete

**Comment by samandmoore** [comment]
so basically, I think the valuable part of this feature for me is the ability to change the "type" of the object but retain any shared properties.

**Comment by rrousselGit** [comment]
>  i'm not sure what you mean by "the last valid data" can you elaborate? 

This "copyAs" is a solution to such code:
```dart
@immutable
abstract class TodoList with _$TodoList {
  factory TodoList.data(List<Todo> todos) = TodoListData;
  factory TodoList.loading(List<Todo> todos) = TodoListLoading;
  factory TodoList.error(List<Todo> todos, [String message]) = TodoListError;
}
```

where `todos` is duplicated 3 times, because during loading the UI still needs to show the list of todos.

But another way to look at it is, the problem is the duplication. 
If we find a way to remove the duplication, without losing the feature, then we technically do not need a "copyAs" anymore. 


One thing I had in mind recently is, we could instead write:

```dart
@immutable
abstract class TodoList with _$TodoList {
  factory TodoList.data(List<Todo> todos) = TodoListData;
  const factory TodoList.loading() = TodoListLoading;
  factory TodoList.error([String message]) = TodoListError;
}
```

which becomes easy to manipulate since there is no duplicate field.

And to implement the "the UI continues to show the todos during loading", we would instead have a form of "history" of the state. 
And we would read the "last valid TodoListData" to obtain its todos

**Comment by samandmoore** [comment]
Ah yes. So we're definitely dealing with the same issue. Without freezed, I'd probably end up using inheritance to solve this issue. So each factory method would be a class and they'd each inherit from each other and share a base copyWith method that could be overridden in derived classes.

**Comment by samandmoore** [comment]
I would definitely be interested in a way to avoid the duplication in the declarations.

I'm not sure that I love the history idea, but I'd have to think about it more and maybe see what it could look like.

The other approach I was thinking about was some sort of composition. If maybe we could say that the`TodoListLoading` state has a reference to the `TodoListData` state that came before it. Perhaps that's kinda what you mean by the history approach you mentioned. I'm still not quite sure what the UI consumption of that would look like.

**Comment by rrousselGit** [comment]
Composition + computed property is definitely the way to go.\
I think we should give up on the idea of having a single class for it, and split it into two classes

We'd have our `TodoList` + controller with no duplicate:

```dart
@freezed
abstract class TodoList with _$TodoList {
  factory TodoList.data(List<Todo> todos) = TodoListData;
  const factory TodoList.loading() = TodoListLoading;
  factory TodoList.error([String message]) = TodoListError;
}
```

And then, we have a secondary UI-only class on the top of `TodoList` that tracks a bunch of stuff:

```dart
@freezed
abstract class TodoState with _$TodoState {
  factory TodoState({
    @required TodoList value,
    @required @nullable TodoListData lastValidState,
  }) = _TodoState;
}
```

____


Using `state_notifier`/`provider`, all of this could be managed this way:

```dart
class TodoListController extends StateNotifier<TodoList> {
//  ...
}

void main() {
  runApp(
    MultiProvider(
      providers: [
        StateNotifierProvider<TodoListController, TodoList>(
          create: (_) => TodoListController(),
        ),
        ProxyProvider<TodoList, TodoState>(
          update: (_, list, state) {
            return list.maybeMap(
              data: (data) => TodoState(value: data, lastValidState: data),
              orElse: () => state?.copyWith(value: list) ?? TodoState(value: list),
            );
          },
        ),
      ],
      child: MyApp(),
    ),
  );
}
```


And for your case @samandmoore, instead of a `maybeMap` you would check if the state is valid or not

**Comment by KlausJokinen** [comment]
```dart
@freezed
abstract class LoginState with _$LoginState {
  const factory LoginState(
      User user,
      EmailState emailState,
      List<PasswordState> passwordState,
      LoginProcessState loginProcessState) = _LoginState;
}
```
Small work around to the current issue where you need to preserve properties between states is that I created a separate `LoginProcessState` inside the `LoginState`

Example usage:
```dart
      if (existingUser != null) {
        yield state.copyWith(loginProcessState: LoginProcessState.Success);
        _authenticationBloc.add(const LoggedInEvent());
      } 
```

Of course, it would be nice if I could just change Object type and still preserve the shared properties in Union class and use `copyWith` between the classes

**Comment by rrousselGit** [comment]
The problem is, `copyAsX`/`toX` methods would not be as reliable as you would expect.

Say we have:

```dart
@freezed
abstract class TodoList with _$TodoList {
  factory TodoList.data(List<Todo> todos) = TodoListData;
  factory TodoList.loading(List<Todo> todos) = TodoListLoading;
  factory TodoList.error([String message]) = TodoListError;
}
```

Where both `data` and `loading` have a list of todos, but `error` doesn't

Then we wouldn't be able to do:

```dart
TodoList list = TodoList.data([Todo()]);
list = list.toLoading();
```

and would instead have to write:

```dart
TodoList list = TodoList.data([Todo()]);
list = list.map(
  data: (data) => data.toLoading(),
  loading: (loading) => loading,
  error: (_) => TodoList.loading([]),
)
```

**Comment by RollyPeres** [comment]
@rrousselGit I like your history idea. I believe there should be a store for the last known value of each common prop and whenever a user instantiates a new union case, the store should be checked and all the props that the user doesn't explicitly provide should be copied from the store.
So something like:
```
yield AddressState.populating(
        address1: state.address1,
        address1Error: error.address1Error,
      );
```
becomes:
```
yield AddressState.populating(
        address1Error: error.address1Error,
      );
```
and `address1` is fetched from store.

Also, whenever a union case is instantiated, the store should be updated if this new instance has an explicit value(s) passed for the props available in store.
Or am I missing something ?

**Comment by rrousselGit** [comment]
> I believe there should be a store for the last known value of each common prop 

For that, `copyWith` works.

This is more about "do not duplicate properties between union cases"

**Comment by rrousselGit** [comment]
So, I'll hold off on making this feature for now. As explained before, I think there are different ways of architecture out model that does not involve relying on `copyAs`.

Implementing `copyAs` is fairly complex (even more if we want to support deep copy like with `copyWith`) and I don't immediately need it.

You are free to make a pull request though, I would gladly review/help a bit.

**Comment by rrousselGit** [comment]
I'll close this, as I don't think this is the correct solution as I mentioned previously in this conversation
