### ISSUE TITLE
[Question] Skip == override

### ISSUE THREAD

**Issue by RollyPeres** [rrousselGit/freezed#120]
What's the recommended way of preventing `==` override in a union ? I'd like two unions of same case to be treated as different even if they're value equal.

**Comment by rrousselGit** [comment]
Don't and use a different solution 😜

I do not want people to cheat around ==. It's both usually the wrong solution, very brittle, and would increase the complexity of Freezed

**Comment by RollyPeres** [comment]
I don't think it should be about what you want, it should be about what the real world needs are. What about having a mixin that would just return false on `==` ?

**Comment by rrousselGit** [comment]
It should be about what I want because I'm the one writing the code and maintaining it 😉

I do not want to spend time on something that I do not use and do not want people to use

**Comment by RollyPeres** [comment]
Don't take it personal, I pointed out that you should probably take into consideration real life scenarios also 😉. After all, I'm assuming you've built the package for the community and to be flexible enough that it could be used without too much restrictions.

**Comment by rrousselGit** [comment]
My point is, there are better ways of solving these real world issues.
Many languages don't even have == override

So instead of working on that, I would prefer working on articles or other more useful things

**Comment by RollyPeres** [comment]
This package has a lot of potential when used in conjunction with `flutter_bloc` if not for things like this.
