### ISSUE TITLE
Support for MyClassToJson()?

### ISSUE THREAD

**Issue by pedromassango** [rrousselGit/freezed#124]
Does this package support class sserialization to json? I didn't find anything related in the README I only find `MyClassFromJson(json)` example.

When I try to call `MyClassToJson(this)`  the IDE show me a error. In the generated file there is no code related to `toJson` feature. Does this package support it or it is jus a Bug?

**Comment by rrousselGit** [comment]
It does

See https://github.com/rrousselGit/freezed#fromjsontojson

**Comment by pedromassango** [comment]
I Can't find anything related to this in the link you provided.

Have you tried it? its giving me a error and looks like the toJson code is not being generated.

**Comment by rrousselGit** [comment]
It does.
Here's one of the test of this package which test the toJson part

https://github.com/rrousselGit/freezed/blob/master/packages/freezed/test/json_test.dart

**Comment by lukepighetti** [comment]
We're not seeing `freezed` generate `toJson()`

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:twic/models2/program_type.dart';
import 'package:twic/services/search_service/models/university_search_result.dart';

part 'onboarding_view_model.freezed.dart';
part 'onboarding_view_model.g.dart';

/// The data backing the Onboarding flow
/// [email]: TODO: document these fields
@freezed
abstract class OnboardingViewModel with _$OnboardingViewModel {
  @JsonSerializable()
  factory OnboardingViewModel({
    @required String email,
    @required ProgramType program,
    @required int graduationYear,
    @required String major,
    @required String minor,
    @required String residentialCollege,
    @required String graduateSchool,
    @required List<String> organizations,
    @required UniversitySearchResult university,
  }) = _OnboardingViewModel;

  factory OnboardingViewModel.fromJson(Map<String, dynamic> json) =>
      _$OnboardingViewModelFromJson(json);
  Map<String, dynamic> toJson() => _$OnboardingViewModelToJson(this);
}
```

```
The method '_$OnboardingViewModelToJson' isn't defined for the type 'OnboardingViewModel'.
Try correcting the name to the name of an existing method, or defining a method named '_$OnboardingViewModelToJson'.dart(undefined_method)
```

<img width="1033" alt="Screen Shot 2020-04-29 at 9 41 14 AM" src="https://user-images.githubusercontent.com/666539/80602800-92bfdc80-89fd-11ea-90fe-11a2a45cadc9.png">

**Comment by lukepighetti** [comment]
Generated mixin

```dart
mixin _$OnboardingViewModel {
  String get email;
  ProgramType get program;
  int get graduationYear;
  String get major;
  String get minor;
  String get residentialCollege;
  String get graduateSchool;
  List<String> get organizations;
  UniversitySearchResult get university;

  Map<String, dynamic> toJson();
  $OnboardingViewModelCopyWith<OnboardingViewModel> get copyWith;
}
```

**Comment by rrousselGit** [comment]
Why did you write a toJson? You shouldn't, it's fine for you

**Comment by lukepighetti** [comment]
I see, when we write `fromJson` it generated `toJson` behind the scenes as well. Got it. This is not clear. Thanks for the help.

**Comment by rrousselGit** [comment]
Closing as `toJson` is correctly generated
