### ISSUE TITLE
Ignore TypeHelper types when fromJson is provided

### ISSUE THREAD

**Issue by FilledStacks** [rrousselGit/freezed#125]
When using freezed and a type is not supported the generation fails. This is understandable if there is no conversion supplied for the type. In my case I'm trying to generate a Material color from a string in json like below.

```dart
@freezed
abstract class Decoration with _$Decoration {
  factory Decoration ({
    // specifically this here
    @JsonKey(fromJson: Converters.colorFromString) Color color,
    double borderRadius,
    DropShadow dropShadow,
  }) = _Decoration;
  factory Decoration .fromJson(Map<String, String> json) =>
      _$DecorationFromJson(json);
}
```

To avoid having this converted in code I've provided a static conversion function so my model can have the color on it that I require. This is valid with the json package being used. The above code fails to generate with the following message.

```
Could not generate `toJson` code for `color`.
None of the provided `TypeHelper` instances support the defined type.

final Color color;
```

Is this functionality expected to work or supported?

**Comment by rrousselGit** [comment]
Instead of `@JsonKey(fromJson: something)`, consider making a `JsonConverter`

Here's an example:

```dart
@freezed
abstract class Generic<T> with _$Generic<T> {
  factory Generic(@DataConverter() T a) = _Generic<T>;

  factory Generic.fromJson(Map<String, dynamic> json) =>
      _$GenericFromJson<T>(json);
}

class DataConverter<T> implements JsonConverter<T, Object> {
  const DataConverter();

  @override
  T fromJson(Object json) {
    return json as T;
  }

  @override
  Object toJson(T object) {
    return object;
  }
}
```
