### ISSUE TITLE
Ignore sort_unnamed_constructors_first

### ISSUE THREAD

**Issue by vr19860507** [rrousselGit/freezed#126]
Ignore rule sort_unnamed_constructors_first

Add sort_unnamed_constructors_first to ignore_for_file

**Comment by rrousselGit** [comment]
I would suggest excluding generated files from your linter instead.

**Comment by rrousselGit** [comment]
Closing as this should be per project configuration instead.

You can configure this in a`build.yaml` file as explained here https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file
