### ISSUE TITLE
Error when I use Nested generic freezed type

### ISSUE THREAD

**Issue by kainosk** [rrousselGit/freezed#128]
When I write nested generic `freezed` type, compiler puts errors.

My code is below.

* `Inner` is a `freezed` class which has a generic type `I`.
* `Outer` is also a `freezed` class which contains a `Inner<int>`.

`inner.dart`

```dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'inner.freezed.dart';

@freezed
abstract class Inner<I> with _$Inner<I> {
  const factory Inner({
    I data,
  }) = _Inner<I>;
}

```

and `outer.dart`

```dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:freezed_generics/inner.dart';

part 'outer.freezed.dart';

@freezed
abstract class Outer with _$Outer {
  const factory Outer({
    Inner<int> innerData,
  }) = _Outer;
}

```

The code generation is succeeded. But generated code causes (four) errors.

```text
error: The name 'I' isn't a type so it can't be used as a type argument. (non_type_as_type_argument at [freezed_generics] lib/outer.freezed.dart:36)
error: The name 'I' isn't a type so it can't be used as a type argument. (non_type_as_type_argument at [freezed_generics] lib/outer.freezed.dart:57)
error: The name 'I' isn't a type so it can't be used as a type argument. (non_type_as_type_argument at [freezed_generics] lib/outer.freezed.dart:61)
error: The name 'I' isn't a type so it can't be used as a type argument. (non_type_as_type_argument at [freezed_generics] lib/outer.freezed.dart:74)

```

When I replace above `I` to `int` in generated `outer.freezed.dart` manually, the code seems to work fine. Is this expected behavior? Do I missed some usages? (I'm new to Dart and Flutter :pray: )

I attached a reproduction project (as zip file).

[freezed_generics.zip](https://github.com/rrousselGit/freezed/files/4399287/freezed_generics.zip)

Thanks for great package! :heart: :heart:

**Comment by rrousselGit** [comment]
Thanks for the report!

It looks like a bug. I'll investigate

**Comment by rrousselGit** [comment]
I've pin-pointed the problem and know the fix.
But to make the fix, I need an extra information: the generic parameters passed to the object (`int` for `List<int>`)

Sadly, I don't see any way to obtain this information.

**Comment by rrousselGit** [comment]
Actually I found the solution through luck

**Comment by mohammadne** [comment]
I also have the issue.
```
Could not generate `fromJson` code for `data` because of type `T` (type parameter).
None of the provided `TypeHelper` instances support the defined type.
To support type paramaters (generic types) you can:
1) Use `JsonConverter`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
2) Use `JsonKey` fields `fromJson` and `toJson`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
3) Set `JsonSerializable.genericArgumentFactories` to `true`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/genericArgumentFactories.html
package:melodyo/domain/core/response.freezed.dart:152:11
```

and my freezed class is: 
```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';

part 'response.freezed.dart';
part 'response.g.dart';

@freezed
abstract class Response<T> with _$Response<T> {
  const factory Response({
    T data,
    String message,
    Map<String, dynamic> errors,
    Map<String, dynamic> links,
    Map<String, dynamic> meta,
  }) = _Response<T>;

  factory Response.fromJson(Map<String, dynamic> json) =>
      _$ResponseFromJson(json);
}

```

**Comment by rrousselGit** [comment]
There is no way to deserialize T, because that could be anything.

Either use a Converter (see https://github.com/rrousselGit/freezed#fromjson---classes-with-multiple-constructors), or change how you model your data to not rely on generics.

Maybe change your `Response` to:

```dart
@freezed
abstract class Response<T> with _$Response<T> {
  const factory Response({
    Map<String, Object> data,
    String message,
    Map<String, Object> errors,
    Map<String, Object> links,
    Map<String, Object> meta,
  }) = _Response<T>;

  factory Response.fromJson(Map<String, Object> json) =>
      _$ResponseFromJson(json);
}
```

and deserialize `data` separately.

**Comment by mohammadne** [comment]
Hi @rrousselGit
Ok, the ```data``` could be a Map or a List or anything else.
I will deserialize ```data``` separately but hope you find a way to deserialize generic types.
Thanks.

**Comment by rrousselGit** [comment]
That's simply not feasible

**Comment by RakaAlrian** [comment]
@mohammadne or maybe don't use freezed for that class, you can use json_serializable and equatable instead. But you can still use freezed for the T classes themselves.
This is my BaseResponse class which is similar to your Response class. Hope this help somebody.
```dart
import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';

part 'base_response.g.dart';

@JsonSerializable(genericArgumentFactories: true)
class BaseResponse<T> extends Equatable {
  final String status;
  final T data;
  final String message;

  const BaseResponse({
    this.status,
    this.data,
    this.message,
  });

  factory BaseResponse.fromJson(
    Map<String, dynamic> json,
    T Function(Object json) fromJsonT,
  ) {
    return _$BaseResponseFromJson<T>(json, fromJsonT);
  }

  Map<String, dynamic> toJson(
    Map<String, dynamic> Function(T value) toJsonT,
  ) {
    return _$BaseResponseToJson<T>(this, toJsonT);
  }

  @override
  List<Object> get props => [
        status,
        data,
        message,
      ];
}

**Comment by sooxt98** [comment]
@RakaAlrian it works! But i need to cast the json object back to map inside model like this;

``` dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:flutter/foundation.dart';

part 'user_model.freezed.dart';
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  const factory UserModel({required String name, required int age}) =
      _UserModel;

  factory UserModel.fromJson(Object? json) =>
      _$UserModelFromJson(json as Map<String, dynamic>);
}

```

**Comment by ihorkozar** [comment]
@sooxt98 hi, faced the same problem. Have you found a solution?

**Comment by paul-paliychuk** [comment]
@ron-brosh thank you so much, appreciate the snippet

**Comment by rignaneseleo** [comment]
@rrousselGit shouldn't this compile fine?

```
class PaginatedModel<T extends JsonSerializable> with _$PaginatedModel<T > {
  const factory PaginatedModel({
    required int page,
    required int per_page,
    required int pages,
    required int total_items,
    required List<T > items
  }) = _PaginatedModel<T>;

  factory PaginatedModel.fromJson(Map<String, dynamic> json) =>
      _$PaginatedModelFromJson<T >(json);
}
```

Instead, I get the error `Could not generate `fromJson` code for `items` because of type `T` (type parameter).
`

**Comment by mazenrashed** [comment]
> Combining the answers from above, this snippet worked for me using dio and retrofit.
> 
> ```dart
> part 'v4_request.g.dart';
> 
> @JsonSerializable(genericArgumentFactories: true)
> class V4Request<T> {
>   const V4Request(this.data);
> 
>   factory V4Request.fromJson(Map<String, dynamic> json, T Function(Object? json) fromJsonT) =>
>       _$V4RequestFromJson(json, fromJsonT);
> 
>   Map<String, dynamic> toJson(Map<String, dynamic> Function(T value) toJsonT) {
>     return _$V4RequestToJson<T>(this, toJsonT);
>   }
> 
>   final T data;
> }
> ```

Thanks, it's working well with retrofit.

**Comment by digu3120** [comment]
👉 Try it out now: https://dartfreezed.tech/

 💬 I’d love your feedback and suggestions!

🚀 Introducing dartfreezed.tech – Your AI-Powered Flutter Freezed Model Generator! ⚡

Tired of manually converting complex JSON into Dart models?

 Say hello to dartfreezed.tech – a smart, lightning-fast tool that uses AI to generate Freezed and JsonSerializable Dart models from any JSON response in seconds!

 ✅ Powered by AI for intelligent field detection

 ✅ Clean, reliable Freezed models with built-in null safety

 ✅ Boosts productivity for Flutter developers

 ✅ Handles deeply nested and complex structures with ease

**Comment by rrousselGit** [comment]
@digu3120 stop the spam or I will have to ban you.

This isn't the right place for advertising
