### ISSUE TITLE
Freezed class extending a parent class does not get a generated toString() method

### ISSUE THREAD

**Issue by kaciula** [rrousselGit/freezed#131]
Take the following code.

```
abstract class DataEvent {}

@freezed
abstract class VersionNameRefreshed extends DataEvent
    with _$VersionNameRefreshed {
  factory VersionNameRefreshed(String versionName) = _VersionNameRefreshed;
}
```

The generated class does not have a toString() method. Is it possible to generate the toString() method in this particular case?

**Comment by rrousselGit** [comment]
It looks like a bug. I'll investigate

**Comment by rrousselGit** [comment]
I tested using version 0.14.3 and Freezed is properly generating a toString. So I will close this issue.
