### ISSUE TITLE
Declaration _$identity isn't referenced

### ISSUE THREAD

**Issue by cidothia** [rrousselGit/freezed#134]
I have a simple Union for simple status tracking, and I am getting the informational analysis in the .freezed part of the file below: 

The declaration '_$identity' isn't referenced.
Try removing the declaration of '_$identity'.

The code for this is below:

import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'repository_status.freezed.dart';

@freezed
abstract class RepositoryStatus with _$RepositoryStatus{
  const factory RepositoryStatus.loaded() = _Loaded;
  const factory RepositoryStatus.loading() = _Loading;
  const factory RepositoryStatus.waiting() = _Waiting;
}

Flutter version:
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (7 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

Freezed package information:
freezed:
    dependency: "direct dev"
    description:
      name: freezed
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.4"
  freezed_annotation:
    dependency: "direct main"
    description:
      name: freezed_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.1"

**Comment by rrousselGit** [comment]
This is known, but of little priority

Consider excluding generated files from your linter.

**Comment by bfovez** [comment]
How would you do that? It seems that linter (unlike analyzer) does not support an "exclude" option.

**Comment by mhmdanas** [comment]
@bfovez you could add an `exclude` property in your `analysis_options.yml` like this:
```yml
analyzer:
  exclude: [build/**, lib/**.freezed.dart]
```

**Comment by bfovez** [comment]
@mhmdanas  Thanks, but it won't work. The error message is issued by the linter, not the analyzer, and unfortunately the former has no "exclude" option.

**Comment by rrousselGit** [comment]
Linter and analyzer are the same thing.
The exclude works for both.

**Comment by bfovez** [comment]
@rrousselGit Thanks for resolving the misunderstanding. It is working perfectly.

**Comment by rrousselGit** [comment]
Closing this as I don't plan on supporting every single lint possible.

Instead consider ignoring generated files, as described here: https://dash-overflow.net/articles/getting_started/
