### ISSUE TITLE
Intellij doesnt show params in shortcut dialog in copyWith function 

### ISSUE THREAD

**Issue by apgapg** [rrousselGit/freezed#137]
Hi Remi,
Thanks for the versatile package,

Just an issue with Alt+enter dialog on intellij in copyWith function. I can't see parameter in diaog and i have to manually look into the class and copy the param name

**Comment by mono0926** [comment]
Same here ✋ 

After around v0.10, `copyWith`'s auto complete seems not work.

**Comment by rrousselGit** [comment]
Try inside parenthesis :

something.copyWith()

**Comment by apgapg** [comment]
@rrousselGit  i tried inside them. everytime i need to copy the variable from the model

**Comment by rrousselGit** [comment]
In any case, that's not something I can fix
It's a bug in the dart tooling

**Comment by Peng-Qian** [comment]
if use someThing.copyWith.call(), IntelliJ can properly work, but the syntax is a little bit...

**Comment by Parkar99** [comment]
> if use someThing.copyWith.call(), IntelliJ can properly work, but the syntax is a little bit...

This is a life saver. Thank you

**Comment by tbm98** [comment]
Hi @apgapg  
I'm happy to see it seems to work correctly on flutter 2.2.3
cc @rrousselGit 
<img width="476" alt="Screen Shot 2021-08-17 at 22 49 48" src="https://user-images.githubusercontent.com/52562340/129759264-b2f940bf-63e5-4dcc-a2fd-c3f1455f8477.png">
<img width="786" alt="Screen Shot 2021-08-17 at 22 52 15" src="https://user-images.githubusercontent.com/52562340/129759278-01fe19f5-bf66-47ce-841a-d5ad5a3398b2.png">

**Comment by apgapg** [comment]
Yes it is working.
