### ISSUE TITLE
Custom annotation instead of @immutable?

### ISSUE THREAD

**Issue by winterDroid** [rrousselGit/freezed#14]
Hey!

I was wondering whether it would be better to introduce a custom annotation if one wants to add the generator to an existing project which uses `@immutable` already for the analyzer.

What do you think?

**Comment by rrousselGit** [comment]
Do you mind explaining why? It shouldn't have any impact.

**Comment by winterDroid** [comment]
We are currently using @immutable in many classes. I'd like to be able to explicitly enable Freezed for certain classes and not just everywhere at once.

**Comment by rrousselGit** [comment]
I need a concrete explanation on _why_.

A project already using `@immutable` shouldn't cause any issue. If it does, then it's a bug and I need an example to reproduce it.

**Comment by winterDroid** [comment]
I think it is also not ideal if you run the generator for every class even when you don't want to use it. Maybe I'm also misunderstand the generator.

**Comment by rrousselGit** [comment]
A generator runs on files, not on classes.

The fact that a class is decorated or not changes nothing. The generator still has to iterate through everything to search for what matches.

**Comment by winterDroid** [comment]
Yeah that is correct. But why generating code for everything if it is not required instead of skipping those classes and just generating the code for the once that are required? It is mostly about visibility of the tool and the performance of the generator.

**Comment by rrousselGit** [comment]
>  But why generating code for everything if it is not required instead of skipping those classes and just generating the code for the once that are required?

That's what it does.

**Comment by winterDroid** [comment]
Alright 👍

**Comment by rrousselGit** [comment]
Just to make sure:
Did you create an issue because you found a situation where `freezed` generated unneeded code, or was this just a misunderstanding?

**Comment by winterDroid** [comment]
So far I did not see that issue. In case I'll see it happening I'll create another issue.
