### ISSUE TITLE
Support for implementing abstract class ? 

### ISSUE THREAD

**Issue by DanielCardonaRojas** [rrousselGit/freezed#141]
Currently the freezed class can support methods by replacing the mixin with and implements. But  what if we want to implement the methods of a contract given by another abstract class ? 

Is this possible?

**Comment by rrousselGit** [comment]
I don't understand the question

**Comment by DanielCardonaRojas** [comment]
I guess I was stuck trying to implement a second interface  besides the generated one.

For example: 

```dart
abstract class Greet {
     void sayHello();
}

@freezed
abstract class Person implements _$Person, Greet {
  factory Person(String name, int age) = _Person;

  void sayHello() {
       print('My name is $name');
  }
}

```
With the example above this would cause an error in the generated freezed file.

Is there a workaround for this ?

**Comment by rrousselGit** [comment]
This is explained here: https://github.com/rrousselGit/freezed#custom-getters-and-methods
