### ISSUE TITLE
Build Failure - $InitialCopyWith defined in multiple libraries

### ISSUE THREAD

**Issue by DuncanKelbie** [rrousselGit/freezed#143]
I've separated my UI and domain logic into separate packages. If I create two or more freezed unions in my domain package and export them in a barrel file, then I get an error like this...

> The name '$InitialCopyWith' is defined in the libraries 'package:domain/src/my_first_bloc_state.dart' and 'package:domain/src/my_second_bloc_state.dart'.
> Try removing the export of one of the libraries, or explicitly hiding the name in one of the export directives.dart(ambiguous_export).

### domain.dart
```
library domain;

export 'src/my_first_bloc_state.dart';
export 'src/my_second_bloc_state.dart';
```
### my_first_bloc_state.dart
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'my_first_bloc_state.freezed.dart';

@freezed
abstract class MyFirstBlocState with _$MyFirstBlocState{
  const factory MyFirstBlocState.initial() = Initial;
  const factory MyFirstBlocState.loaded(int data) = Loaded;
}
```
### my_second_bloc_state.dart
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'my_second_bloc_state.freezed.dart';

@freezed
abstract class MySecondBlocState with _$MySecondBlocState{
  const factory MySecondBlocState.initial() = Initial;
  const factory MySecondBlocState.loaded(String data) = Loaded;
}
```

A workaround is to make the generated classes private by adding an underscore like so:
```
@freezed
abstract class MySecondBlocState with _$MySecondBlocState{
  const factory MySecondBlocState.initial() = _Initial;
  const factory MySecondBlocState.loaded(String data) = _Loaded;
}
```

However, sometimes I would like these classes to be available in the presentation layer.

**Comment by rrousselGit** [comment]
Your problem is that you have two classes with the same name ("Initial")
Rename one or both of them to fix the conflict

May I suggest Initial -> MySecondGBlocStateInitial ?

**Comment by DuncanKelbie** [comment]
Amazing! Thanks!!
