### ISSUE TITLE
Update freezed to use freezed

### ISSUE THREAD

**Issue by TimWhiting** [rrousselGit/freezed#145]
I don't know if the title makes sense, but I feel like a lot of code generation libraries could be simplified or at least made less error prone if there was a good library for manipulating / generating dart classes and constructs. 

I know that the analyzer gives a lot of the information about classes for the generator, but there are a lot of 'is' checks 'as' casts and null checks in generator code that I have looked through and written. 

 I think it would be great to create a library that uses extension methods to take Element, ClassElement and other classes given by the dart analyzer and return a freezed class corresponding to the correct type. A lot of times generators want to carry around extra information along with these elements so a dynamic or Object field that can be null would be a good place to add in information with the generator author using element.copyWith(extraInfo: MyExtraInfo()). 

Another feature of this library would be a good way to generate the strings from the object representation, so that author's of generator libraries don't have to worry about issues with string interpolation that can get tricky in some cases (especially dealing with generic types, lists, and maps), and instead build the code programmatically and call a .toDartString() method or something to get the textual dart representation, which might get a little tricky with comments.

I don't think the library would have to be comprehensive to be useful, and could include the raw analyzer class as a property for those who want to get more information out of the elements.

 I'd be interested in contributing to / co-authoring such a library, I just would rather not go at it alone, especially since I have don't have a ton of code generation experience, I've just played with it for a few things.

**Comment by rrousselGit** [comment]
I don't quite understand what this is about

Do you mind making an example?

**Comment by TimWhiting** [comment]
It's not really a feature request or bug for the freezed library. It's more of a request for a library to help in code generation. Sorry if this is the wrong place to bring it up. I don't have time to create an example right now, but will try to do it sometime this week.

**Comment by rrousselGit** [comment]
I still don't understand what this is about

Is this a request to extract the "template" things into a package?

**Comment by rrousselGit** [comment]
I'll close this since for now
