### ISSUE TITLE
Support preserving a value across copies

### ISSUE THREAD

**Issue by DanielCardonaRojas** [rrousselGit/freezed#151]
This is better show cased with an example: 

```dart
@freezed
abstract class TodoItem with _$TodoItem {
  @late
  String get primaryKey => Uuid().v4();

  factory TodoItem({
    @JsonKey(toJson: idToString) String id,
    String title,
    int order,
    bool completed,
  }) = _TodoItem;
```

In this escenario it is desirable to preserve  primaryKey property when performing a `copyWith()`. 

Maybe let `Default` decorator accept functions. Or have another decorator `@keep` which will allow 
a value to be retained when creating new copies.

Or am I missing something to get this working?

**Comment by rrousselGit** [comment]
That's working as intended, as the getter can be built based on other variables, which means it may need to be recomputed on copy.

I would suggest instead making the `id` required, without default values, and move the Uuid creation logic to object that _creates_ the `TodoItem`
