### ISSUE TITLE
DiagnosticsProperty issue

### ISSUE THREAD

**Issue by Fallar** [rrousselGit/freezed#152]
After code being generated i have a lot of errors -
The method 'DiagnosticsProperty' isn't defined for the class '_$_EventDtoResponse'.
Try correcting the name to the name of an existing method, or defining a method named 'DiagnosticsProperty'.
```
part 'event_dto_response.freezed.dart';
part 'event_dto_response.g.dart';

@freezed
abstract class EventDtoResponse with _$EventDtoResponse {
  factory EventDtoResponse({
    @required int id,
    @required List<int> members,
    @required int membersLimit,
    @required Map<String, dynamic> price,
    @required int eventType,
    @required int reminderDuration,
    @required int startDate,
    @required int startTime,
    @required int locationId,
    @required String description,
    @required String title,
    @required String note,
    @required int endDate,
    @required int endTime,
    @required bool isRecurring,
    @required bool recurring,
    @required Map<String, dynamic> recurringPattern,
  }) = _EventDtoResponse;
```

![image](https://user-images.githubusercontent.com/19286226/80067809-d66aa000-853e-11ea-83a2-04377a2c2d6a.png)

**Comment by Fallar** [comment]
Can someone help? Right now i just commentout bunch of code in generated file, but this is not a solution....

**Comment by rrousselGit** [comment]
Either remove the flutter import from your file, or add `import 'package:flutter/foundations.dart'`

**Comment by Fallar** [comment]
It was as simple as that... Man. U saved my life.
