### ISSUE TITLE
Add unused_element on // ignore_for_file for freezed generated files

### ISSUE THREAD

**Issue by scostagabriel** [rrousselGit/freezed#153]
I am using lint rules for my project and the generated .freezed.dart contains the line below which is warned by the analyzer because of an unused import. I checked that there are already some rules ignored in the file .freezed.dart. so it's just adding that also.

`T _$identity<T>(T value) => value;`

**Comment by rrousselGit** [comment]
As stated elsewhere, I don't plan on fixing lint issues as it adds too much complexity

Instead consider ignoring generated files from your linter https://dash-overflow.net/articles/getting_started/#step-5-ignoring-warnings-on-generated-files
