### ISSUE TITLE
Unions factories with no parameters triggers the avoid_single_cascade_in_expression_statements lint rule

### ISSUE THREAD

**Issue by mr-mmmmore** [rrousselGit/freezed#155]
Hi,

Thank you Rémi for this great package!

I have started using stricter linting rules after reading your blog post (great post also !). I am using the dart-lint list with little variations.

I encounter a minor problem with Unions : classes without parameters have a `debugFillProperty` method that look like this:

```dart
  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties..add(DiagnosticsProperty('type', 'Union.loading'));
  }
```
(generated from the `Union` class in the readme.md).

This triggers the `avoid_single_cascade_in_expression_statements` lint rule.

I could disable the rule but I'd rather not if possible. Do you think you can fix it?

_I'm on the stable channel (flutter 1.12.13+hotfix.9 / Dart 2.7.2) with freezed 0.9.2._

**Comment by sdgroot** [comment]
+1 for this one. I'm currently using freezed 0.10.7 and this is the only warning that's repeatedly showing up in the console. Would love to see this rule being ignored in the freezed files.

**Comment by rrousselGit** [comment]
You should instead make the linter ignore freezed files

```yaml
# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
```

**Comment by sdgroot** [comment]
> You should instead make the linter ignore freezed files
> 
> ```yaml
> # analysis_options.yaml
> analyzer:
>   exclude:
>     - "**/*.g.dart"
>     - "**/*.freezed.dart"
> ```

I'm aware of this setting and we've implemented it, but it is currently bugged and still shows the warnings/info's.

See: https://github.com/dart-lang/sdk/issues/25551

**Comment by rrousselGit** [comment]
Yes, but that is not my responsibility that the setting is bugged

**Comment by mr-mmmmore** [comment]
> You should instead make the linter ignore freezed files

Since you add a `ignore_for_file` comment in the generated files, isn't it that you yourself consider that these files should pass the analyzer, except for the rules that you must violate?

The creators of packages that generate files can't anticipate for all the problems their package may produce In such situations if the analyzer is off, the build may succeed while the app's code is actually buggy. Freezed files although not written by me are essential parts of my app, so why should their analysis be skipped?

Also, I think I have faced situations where the analyzer errors in the generated file have helped me to identify  problems in my own code.

**Comment by rrousselGit** [comment]
Source gen expose the necessary options for you to add extra ignore_for_file if you need them

https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file

**Comment by mr-mmmmore** [comment]
Yes but this would disable the rule for any package that uses source_gen... All this because of this double dot that could be written with a single dot.

**Comment by rrousselGit** [comment]
Feel free to make a pull request to update the generste code to use a
single dot

This is not a priority for me.

**Comment by mr-mmmmore** [comment]
No problem, I understand.

I have been away from Flutter for a month, but I'll try to do so as soon as I can.

**Comment by rrousselGit** [comment]
As stated elsewhere, I don't plan on fixing lint issues as it adds too much complexity

Instead consider ignoring generated files from your linter https://dash-overflow.net/articles/getting_started/#step-5-ignoring-warnings-on-generated-files
