### ISSUE TITLE
Add dart version declaration to generated files

### ISSUE THREAD

**Issue by dluksza** [rrousselGit/freezed#158]
As non-nullable support in dart is approaching it is already possible to test it in flutter projects. Unfortunately code generated with freezed is not yet compatible with non-nullables.

Adding simple `// @dart=2.7` to generated files ensures usage of proper dart version, this also allows use other version syntax in rest of the code base. Effectively this allows to use dart 2.8 with non-nullables with current version of freezed.

**Comment by rrousselGit** [comment]
I'll close this, as I would recommend adding this flag yourself using a custom `build.yaml` – since the version you want to use may vary

See https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file

**Comment by eggnstone** [comment]
> I'll close this, as I would recommend adding this flag yourself using a custom `build.yaml` – since the version you want to use may vary
> 
> See https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file

How exactly would the build.yaml file look?
I'm not familiar with these flags and just from your link I cannot infer how to build a proper build.yaml.

**Comment by mariamalbarghouti** [comment]
> 
> 
> I'll close this, as I would recommend adding this flag yourself using a custom `build.yaml` – since the version you want to use may vary
> 
> See https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file

it does not work!
