### ISSUE TITLE
Comment fields

### ISSUE THREAD

**Issue by lukepighetti** [rrousselGit/freezed#161]
Is there any way to comment fields? If not, can we copy three slash `///` lines above default factory parameters to the generated mixin getters to pass these comments to the generated fields?

**Comment by rrousselGit** [comment]
No, and I don't think that's the responsibility of Freezed

It should probably instead be the IDE that have a fallback mechanism for the documentation like "if there's no doc on a property use the doc of the enclosing element"

**Comment by lukepighetti** [comment]
IIRC the documentation mechanism is via the language server, not the IDE.

**Comment by rrousselGit** [comment]
But how would that work for shared properties on a union?

Also, there's no dartdoc for parameters, only dartdoc for constructors. So how would you determine what documentation should go on which property?

**Comment by lukepighetti** [comment]
Not sure what you mean. If I comment a class getter the language server makes that inline documentation available to the IDE and to pub. Not sure where dartdoc fits into that.

**Comment by rrousselGit** [comment]
Comments == dartdoc

What I meant is, you can't do:

```dart
class Class {
  Class(
    /// Documentation for [parameter]
    int parameter,
  );
}
```

That won't be picked-up by the IDE. So what would you expect?

**Comment by lukepighetti** [comment]
That's exactly right. What I'm expecting is the freezed builder to copy those to the generates getters so that we *can* comment getter fields which is currently impossible due to the limitation you described.

**Comment by lukepighetti** [comment]
```dart
@freezed
abstract class TestModel with _$TestModel {
  factory TestModel({
    /// Foo
    @required String id,
  }) = _TestModel;
}
```

```dart
mixin _$TestModel {
  // Foo
  String get id;

  $TestModelCopyWith<TestModel> get copyWith;
}
```

**Comment by lukepighetti** [comment]
To be honest that doesn't even seem to work, not sure why not. I'm trying to find a way to comment the getters so we get IDE documentation.

<img width="578" alt="Screen Shot 2020-04-29 at 8 55 45 AM" src="https://user-images.githubusercontent.com/666539/80598360-378aeb80-89f7-11ea-85dd-afb3adbdc672.png">

**Comment by rrousselGit** [comment]
> That's exactly right. What I'm asking for as a feature is having the freezed builder copy those comments to the generated getters so that we _can_ comment getter fields which is currently impossible due to the limitation you described.

You don't understand
This is not valid dartdoc. The daet analyzer does not pick up comments on parameters. So freezed can't do that

**Comment by lukepighetti** [comment]
So you're saying this doesn't get picked up by dartdoc?

```dart
class Foo {
  /// This is just an example
  String get example => "";
}

**Comment by rrousselGit** [comment]
No doc on constructor parameters

**Comment by lukepighetti** [comment]
Yeah, that part is well known. What I'm saying is it would be nice if we could FORWARD comments on constructor parameters to the generated getters.

**Comment by rrousselGit** [comment]
I know what you want.

What I'm saying is, dart analyser do not pick up comments placed there.
So Freezed can't forward them

**Comment by lukepighetti** [comment]
You can't copy the lines above like you do with capturing method arguments?

**Comment by rrousselGit** [comment]
No, that's not how parameters are captured and i can't just take the previous line

**Comment by lukepighetti** [comment]
Alright, no problem. Thanks for explaining it to me. I'll happily close this.

**Comment by lukepighetti** [comment]
This was resolved in https://github.com/rrousselGit/freezed/issues/236
