### ISSUE TITLE
Array/List support

### ISSUE THREAD

**Issue by bogdannedelcu** [rrousselGit/freezed#165]
Hello, Very good package!

Please can you have support for array/list item replacement? Suppose I have the following freezed class:

abstract class AppState with _$AppState {
  const factory AppState(
      {String appName,
      int version,
      List<PersonState> persons,

}

In some action I would like to do:
state.copyWith.persons[0](name: "John", age: 24).

Regards

**Comment by rrousselGit** [comment]
This is planned, but not a priority

Feel free to make a pull request 😊

**Comment by rrousselGit** [comment]
Closing in favor of #185
