### ISSUE TITLE
Question: How best to handle inheritance  with Freezed

### ISSUE THREAD

**Issue by pratikpparikh** [rrousselGit/freezed#174]
HI @rrousselGit ,

How to best handle inheritance with Freezed.  How can i write the code to avoid copywith error.

Class A:
     `@freezed
abstract class Fruti with _$Fruti {
  Fruti._();

  @JsonSerializable(explicitToJson: true)
  factory Fruti(@JsonKey(name: 'fruti') String id) = _Fruti;

  factory Fruti.fromJson(Map<String, dynamic> json) =>
      _$FrutiFromJson(json); 
}`

Class B:
     `@freezed
abstract class Apple extends Fruti with _$Apple {
  Apple._();

  @JsonSerializable(explicitToJson: true)
  factory Apple(@JsonKey(name: 'apple') String id) = _Apple;

  factory Apple.fromJson(Map<String, dynamic> json) =>
      _$AppleFromJson(json); 
}`

I get a copyWith problem on Apple class 'error: '_$Apple.copyWith' ('$AppleCopyWith<Apple> Function()') isn't a valid override of '_$Fruti.copyWith' ('$FrutiCopyWith<Fruti> Function()'). (invalid_override at [fruti_family] lib\src\apple.dart:5)'

Regards,
Pratik Parikh

**Comment by rrousselGit** [comment]
Freezed classes are sealed. You should not extend them.

**Comment by pratikpparikh** [comment]
@rrousselGit Thank you.
