### ISSUE TITLE
Caching Freezed classes on CI

### ISSUE THREAD

**Issue by sterrenburg** [rrousselGit/freezed#176]
Hello, `v0.10.8` is working great!

Currently I am using Codemagic for Continuous Integration (CI). This works well and code generation takes place on the CI server (using `flutter pub run build_runner build`).

The caveat is that the code generation takes up to 8 minutes on a Mac Mini, for example.
 
I am wondering if it is possible to somehow cache the output of my Freezed classes on the CI server. The generated files are in the same directory as the original files (since they use `part 'my_model.freezed.dart';`). Would it be necessary to save the Freezed classes in a separate directory to allow for easy caching?

Since other stuff like dependency injection is also code generated, the timing also isn't fully the "fault" of Freezed. Perhaps this question is outside the scope of the `freezed` package, so if you reckon it is, I will take the question elsewhere.

**Comment by rrousselGit** [comment]
As you said, it's not really in the scope of Freezed.

Maybe ask on the source_gen or build repository

**Comment by sterrenburg** [comment]
Thank you for your quick reply and suggestion. I will look there!
