### ISSUE TITLE
Using member getters instead of constructor arguments for code generation?

### ISSUE THREAD

**Issue by hpoul** [rrousselGit/freezed#181]
Hi,
I was wondering if it would be possible to add support for defining properties of freezed objects via member getters (similar to built_value) instead of constructors. It would obviously only be a either or for each class, but I kind of prefer defining members so most autocompletion and documentation, etc. works even without running the code generator..
Just wondering if this would be technically feasible to support that in addition to the current constructor arguments or a no-go.

I prefer how freezed generates copyWith, integrates with json_serializable, etc. compared with built_values' builders and serializable.. but for simple use cases (ie. no need for enum-like types) it feels simpler to write member getters :)

**Comment by rrousselGit** [comment]
That's not as cool as it sounds.

In the end, you'd still have to write the constructor, because there is not way to add constructor to a class from outside, so Freezed can't generate the constructor for you.

**Comment by hpoul** [comment]
good point.. that's probably the reason for the builders, so the constructor don't change for each property. maybe we simply need built-in data classes 😅️

**Comment by rrousselGit** [comment]
Closing this since it's not feasible right now
