### ISSUE TITLE
Class with 2 Generics

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/freezed#183]
@rrousselGit 
Hi Remi,

using the class below will result in type errors in map/when.
Am i doing something wrong?

freezed: 0.10.9
freezed_annotation: 0.7.1
build_runner: 1.10.0

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.freezed.dart';

@freezed
abstract class Test<Result, Params> with _$Test<Result, Params> {
  factory Test.result(Result result, Params params) = _Result<Result, Params>;
  factory Test.loading() = _Loading<Result, Params>;
  factory Test.error(dynamic error) = _Error<Result, Params>;
}

```

**Comment by rrousselGit** [comment]
What is your error?

**Comment by smiLLe** [comment]
![image](https://user-images.githubusercontent.com/655296/82728110-a73a8080-9cee-11ea-9128-9e5c4f12aae3.png)

**Comment by rrousselGit** [comment]
Oh, the constructor name and the variable name is the same

**Comment by rrousselGit** [comment]
Wait that's not the problem. 
Not sure what happens here?

**Comment by rrousselGit** [comment]
Ah I know.
The it's the generic argument shadowing the class

**Comment by smiLLe** [comment]
I was also thinking about the naming as  a problem. But this code won't work as well.
```dart
@freezed
abstract class Test<Result, Params> with _$Test<Result, Params> {
  factory Test.r(Result res, Params params) = _Re<Result, Params>;
  factory Test.loading() = _Loading<Result, Params>;
  factory Test.error(dynamic error) = _Error<Result, Params>;
}


```

**Comment by rrousselGit** [comment]
The conflict is on the map/when definiton.
They are defined as:

```dart
Result when<Result extends Object>(...)
```

**Comment by smiLLe** [comment]
Yes, but i don't know if i can fix this in my code :(

**Comment by rrousselGit** [comment]
Change the name of the generic parameter

**Comment by smiLLe** [comment]
Oops. Had some kind of tunnel vision. Of couse, i must change my generic ...
thanks
