### ISSUE TITLE
Make generating fromJson/toJson() optional

### ISSUE THREAD

**Issue by alfinbi** [rrousselGit/freezed#190]
I think `toJson()` implmentation shouldn't be force autogenerated, but user should has the option to write it manually like `@Freezed(generateToJson: false)`.

For instance, my app is written in flutter and angulardart, and the backend use firebase functions (also written in dart). I use firestore to store database. Firestore timestamp implementation is different in web, flutter, and backend, so do many others database have their implementation of DateTime. So my data model implement `toJson(TimestampConverter converter)` and `factory Model.fromJson(Map<String,dynamic> json, TimestampConverter converter)` and I can use single data model either in angulardart, flutter or backend by providing each timestamp converter. Currently using freeezed, I use method `toJsonWithConverter(TimestampConverter converter)`.

**Comment by rrousselGit** [comment]
For information, when using `{}` on a `fromJson`, Freezed to not generate anything. So you can make custom constructor:

```dart
@freezed
abstract class Example with _$Example {
  factory Example({ int a }) = _Example;

  factory Example.fromJson(Whatever json) {
    return Example(...};
  }
}
```

**Comment by rrousselGit** [comment]
Done

**Comment by RCSandberg** [comment]
@rrousselGit Hi! Done in what way? To use an empty constructor, or to use something like `generateToJson: false` ?
