### ISSUE TITLE
Specify default value when incoming json is null

### ISSUE THREAD

**Issue by RollyPeres** [rrousselGit/freezed#192]
@rrousselGit is there a way of adding the default value when the incoming json is null ? 
At this time it seems that you must make it `@nullable` and if null comes it won't attach the default value.

```
@freezed
abstract class Model with _$Model {
  const factory Model({
    @Default(0) int count,
  }) = _Model;

  factory Model.fromJson(Map<String, dynamic> json) =>
      _$ModelFromJson(json);

  static const Model defaultValue = Model();
}

@freezed
abstract class OtherModel with _$OtherModel{
  const factory OtherModel({
    @nullable @Default(Model.defaultValue) @JsonKey() Model prop1,
    @nullable @Default(Model.defaultValue) @JsonKey() Model prop2,
  }) = _OtherModel;

  factory OtherModel.fromJson(Map<String, dynamic> json) =>
      _$OtherModelFromJson(json);

  static const OtherModel defaultValue = OtherModel();
}
```
Am I missing something with this approach ?

**Comment by rrousselGit** [comment]
Freezed is unrelated to that.

I dont remember which one, but there's likely an option on JsonKey for it.
In any case, I can't do anything.

**Comment by RollyPeres** [comment]
`json_serializable` will complain that `Model.defaultValue` is not a literal no matter what.
This could be solved with a custom converter like:
```
class _OtherModelConverter
    implements JsonConverter<OtherModel, Map<String, dynamic>> {
  const _LikertReviewStatsModelConverter._();
  @override
  OtherModel fromJson(Map<String, dynamic> json) {
    if (json == null) {
      return OtherModel.defaultValue;
    }
    return OtherModel.fromJson(json);
  }

  @override
  Map<String, dynamic> toJson(OtherModel object) => object.toJson();
}
```

Which can be used in some other class/es that has `OtherModel` props.
The downside is you'd have to explicitly create the default value and specify all the nested ones too.
```
static const SomeOtherModel defaultValue = SomeOtherModel(
  prop1: OtherModel.defaultValue,
  prop2: OtherModel.defaultValue,
);
```
Would be cool if this could be generated by freezed in case `@Default(SomeValueNotCoolWithJsonSerializable)` contains a default value not cool with `json_serializable` along with the proper converter.
