### ISSUE TITLE
problem with multiple part freezed for a single file

### ISSUE THREAD

**Issue by mohammadne** [rrousselGit/freezed#193]
Hi
I am using bloc library and I want to define my events and states in freezed classes but the code generator not works correctly means the freezed classes are not generated.

EVENT:
```
part of 'auth_form_detailed_bloc.dart';

@freezed
abstract class AuthFormDetailedEvent with _$AuthFormDetailedEvent {
  const factory AuthFormDetailedEvent.changedTextField() = _ChangeTextField;
  const factory AuthFormDetailedEvent.submit() = _Submit;
}
```

STATE:
```
part of 'auth_form_detailed_bloc.dart';

@freezed
abstract class AuthFormDetailedState with _$AuthFormDetailedState {
  const factory AuthFormDetailedState.waiting() = WaitingState;
  const factory AuthFormDetailedState.disable() = DisableState;
  const factory AuthFormDetailedState.enable() = EnableState;
  const factory AuthFormDetailedState.error(String title, String subtitle) = ErrorState;
}
```

BLOC:
```
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'auth_form_detailed_event.freezed.dart';
part 'auth_form_detailed_event.dart';

part 'auth_form_detailed_state.freezed.dart';
part 'auth_form_detailed_state.dart';

class AuthFormDetailedBloc
    extends Bloc<AuthFormDetailedEvent, AuthFormDetailedState> {

  @override
  AuthFormDetailedState get initialState => DisableState();

  @override
  Stream<AuthFormDetailedState> mapEventToState(
      AuthFormDetailedEvent event) async* {}
}
```

**Comment by rrousselGit** [comment]
What do you mean by the generator doesn't work?

**Comment by mohammadne** [comment]
Hi @rrousselGit Remi

what I mean is that freezed classes are not generated by running :
flutter pub pub run build_runner watch --delete-conflicting-outputs

if I use a normal single file and include : 
part '*.freezed.dart';
then it works perfectly.

but if I use multiple part in a file like a situation I described like bloc,then it fails and freezed classes are not auto generated.

**Comment by RollyPeres** [comment]
@mohammadne Your bloc needs to contain:

```
part 'auth_form_detailed_event.dart';
part 'auth_form_detailed_statet.dart';
part 'auth_form_detailed_bloc.freezed.dart';
```

**Comment by mohammadne** [comment]
> @mohammadne Your bloc needs to contain:
> 
> ```
> part 'auth_form_detailed_event.dart';
> part 'auth_form_detailed_state.dart';
> part 'auth_form_detailed_bloc.freezed.dart';
> ```

@RollyPeres 
yes , I did it , but the problem has not been resolved.

**Comment by mohammadne** [comment]
> @mohammadne Your bloc needs to contain:
> 
> ```
> part 'auth_form_detailed_event.dart';
> part 'auth_form_detailed_state.dart';
> part 'auth_form_detailed_bloc.freezed.dart';
> ```

Thanks.
my problem was because my bloc contained:
```
part 'auth_form_detailed_event.dart';
part 'auth_form_detailed_event.freezed.dart';
part 'auth_form_detailed_state.dart';
part 'auth_form_detailed_state.freezed.dart';
```
