### ISSUE TITLE
Add methods and getters

### ISSUE THREAD

**Issue by hashemp206** [rrousselGit/freezed#194]
when I add custom getter to the class, following the readMe example:
```
@freezed
abstract class Person with _$Person {
  const factory Person(String name, {int age}) = _Person;

  void method() {
    print('hello world');
  }
}
```
I see this error:
what am I missing?
freezed: ^0.10.9
```
Missing concrete implementation of 'Person.method'.
Try implementing the missing method, or make the class abstract.
```
<img width="742" alt="Screen Shot 2020-06-11 at 11 27 23 PM" src="https://user-images.githubusercontent.com/3206748/84427915-de8bb580-ac3a-11ea-87b1-0095ca8ac8a3.png">

I added an extension to Person class to fix it. please update the readme.

**Comment by rrousselGit** [comment]
See https://github.com/rrousselGit/freezed#custom-getters-and-methods for how to support methods

**Comment by hashemp206** [comment]
I added private constructor, but still not working, to solution is to use extensions to add methods.

**Comment by tbm98** [comment]
@hashemp206 replace with by implements and add private constructor and it work.
like this
```
abstract class MyState implements _$MyState {
  const MyState._();
  const factory MyState(int a, int b, int c, int d, {String name}) = _MyState;
  String get sumWithname {
    return '$name has ${a + b + c + d}';
  }
}
```
