### ISSUE TITLE
How to add custom method inside a class in sealed class?

### ISSUE THREAD

**Issue by QAQyzk** [rrousselGit/freezed#209]
For example:
```@freezed
abstract class CartState with _$CartState {
  const factory CartState.loadSuccess(List<Item> items) = _LoadSuccess;
}
```
I want to add a get total price method inside the `_LoadSuccess` class, how can it be achieved?

**Comment by rrousselGit** [comment]
Hi! 

This is documented in the Readme: https://github.com/rrousselGit/freezed#custom-getters-and-methods

**Comment by QAQyzk** [comment]
@rrousselGit Hi, 
Thank you for your response, I have followed the instructrion, but can't figure out how to access the getter.
```
abstract class CartState implements _$CartState {
  const CartState._();
  const factory CartState.loadSuccess(List<Item> items) = _LoadSuccess;

  num get totalPrice => maybeWhen(
        loadSuccess: (items) =>
            items.fold(0, (sum, item) => sum + item.price),
        orElse: () => -1,
      );
}
```
if I use `CartState.loadSuccess().totalPrice;` I need to provide the items argument, is there any other way to access the getter?

**Comment by rrousselGit** [comment]
What do you mean by you can't access the getter?

**Comment by QAQyzk** [comment]
If I want to access the total price of the cart state, I need to do the following:
```
state.maybeWhen(
          loadSuccess: (items) {
            final price = CartState.loadSuccess(items).totalPrice;
          },
          orElse: null,
        );
```
which requires manually provide the `items` argument. Is this the correct way to access the getter or there is way to access it like `final price = CartState.loadSuccess.totalPrice`?

**Comment by rrousselGit** [comment]
Use `map`instead:

```dart
state.maybeWhen(
          loadSuccess: (state) {
            final price = state.totalPrice;
          },
          orElse: null,
        );
```

**Comment by QAQyzk** [comment]
Thanks! That solves it.
