### ISSUE TITLE
Add assert(field != null) functionality

### ISSUE THREAD

**Issue by carlowenig** [rrousselGit/freezed#21]
Hi there,
first of all: Great package!

The only thing I am missing at this point is the possibility to ensure fields to be non null.
Normally I would use `assert(field != null)` in the constructor to make a field non-nullable.
It would be really useful to have this feature on freezed classes to make nullability errors easier to prevent.

Thanks!

**Comment by rrousselGit** [comment]
I didn't add it because I can't think of any good enough syntax for it.
`@required` cannot be used here, because we can have required nullable parameters.

Unless you have a proposal (that doesn't rely on a custom annotation), then I'd prefer to wait for non-nullable types to land.
Non-nullable types should remove the need for such an assertion.

**Comment by carlowenig** [comment]
Would it be possible to check if the package "non_null" is installed and if so use its `@nonNull` annotation?

**Comment by passsy** [comment]
I'd love to have this. This way I could replace all my "data classes" with freezed classes.
I'd add a `@nonNull` annotation to this project.

**Comment by rrousselGit** [comment]
Now that `freezed` will have an annotation package, it should be fine.

**Comment by rrousselGit** [comment]
If we're going with custom annotations, I would go with a `@nullable` annotation instead:

```dart
@freezed
abstract class MyClass with _$MyClass {
  factory MyClass({
    @required String notNullable,
    @required @nullable String nullable,
  }) = _MyClass;
}
```


Thought?

**Comment by carlowenig** [comment]
I like it! Will only `@required` properties be checked for null or all properties which are not annoted with `@nullable`?

**Comment by rrousselGit** [comment]
All properties unless:
- they are annoted with `@nullable`
- they are named parameters without a `@required`

**Comment by rrousselGit** [comment]
This will also be applied to `copyWith` and the future `copyAs` by the way.

**Comment by rrousselGit** [comment]
I'll try to also generate a `@JsonKey(nullable: true)` when no `@JsonKey` are passed and the field is nullable?
