### ISSUE TITLE
Performing a type change in factory constructor

### ISSUE THREAD

**Issue by giiyms** [rrousselGit/freezed#210]
Hello,

Is it possible to run a function on a property of a factory constructor?

I am looking to reformat a date from a string to a yyyy-mm-dd string as soon as the factory has been created.

I was thinking of something like this. Is this functionality in freezed?

```
@freezed
abstract class Example implements _$Example {
  const Example._();

  const factory Example({
    @required
    @JsonKey(name: 'start_date', fromJson: _convertDate, toJson: _convertDate)
        String startDate,
  }) = _Example;

  static String _convertDate(String date) {
    return DateFormat("yyyy-mm-dd").format(DateTime.parse(date));
  }

  factory Example.fromJson(Map<String, dynamic> json) =>
      _$ExampleFromJson(json);
}
```

**Comment by rrousselGit** [comment]
There's currently no way to do such thing

**Comment by rrousselGit** [comment]
I'll close this. I don't think this is feasible.

If you have an idea on how to implement such thing, feel free to make a PR or create an issue explaining how this would work.
