### ISSUE TITLE
Support "non-nullable" experiment for NNBD technical preview

### ISSUE THREAD

**Issue by roman-petrov** [rrousselGit/freezed#211]
I successfully migrated my early stage project to NNBD tech preview and now trying to use `freezed`. When I start latest `build_runner` with `flutter pub run build_runner build --delete-conflicting-outputs --enable-experiment=non-nullable` I see errors like:
![image](https://user-images.githubusercontent.com/18419515/85353910-ff44ec80-b511-11ea-8f19-db81b25fafd6.png)

As I suppose, the minimal change required to support NNBD is to use a new [experiments library](https://pub.dev/documentation/build/latest/experiments/experiments-library.html) in `build` package somehow.

Can NNBD be supported in `freezed` in some near future?..

**Comment by rrousselGit** [comment]
Support for nnbd will not be added until it is officially the time to start migrating (so beta).

**Comment by roman-petrov** [comment]
thanks, I will look for updates!

**Comment by roman-petrov** [comment]
Might be related to [Add dart version declaration to generated files](https://github.com/rrousselGit/freezed/issues/158)

**Comment by rrousselGit** [comment]
That can be added by yourself using a build.yaml file

https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file

**Comment by roman-petrov** [comment]
@rrousselGit , thank you! I will try this approach.

**Comment by britannio** [comment]
I'm getting the same issue, any fix?
```
Bad state: Unexpected diagnostics:
/Users/britannio/development/flutter/bin/cache/pkg/sky_engine/lib/ui/channel_buffers.dart:119:41 - This requires the 'non-nullable' language feature to be enabled.
...
```

**Comment by rrousselGit** [comment]
The code generator does not support NNBD. You should not pass `--enable-experiment=non-nullable` to `build_runner`. Instead insert https://github.com/rrousselGit/freezed/issues/158 at the top of the generated files, with https://github.com/dart-lang/source_gen#configuring-combining_builder-ignore_for_file

**Comment by nguyenduckhai** [comment]
Hi, 
I've created the custom build.yaml file but it's not working! Here is the code 
```
targets:
  $default:
    builders:
      freezed:
        options:
          non-nullable: true
```

**Comment by QAQyzk** [comment]
> I'm getting the same issue, any fix?

Hi,
I found a solution in this issue [flutter#56779](https://github.com/flutter/flutter/issues/56779#issuecomment-663926681)
by adding this to pubspec.yaml
```
dependency_overrides:
  analyzer: '0.39.14'
```

**Comment by iobytex** [comment]
Updating my analyzer did the trick.
`analyzer: '0.39.14' -> analyzer: '0.39.16'
`

**Comment by nerder** [comment]
As of today works for me with:

```
dependency_overrides:
  analyzer: '0.39.14'
```

By the way this is in beta right now 😕

**Comment by rrousselGit** [comment]
Nnbd isn't in beta but in preview

Beta is a separate step where packages can officially start migrating

**Comment by nerder** [comment]
I see. My bad, i thought you was talking about `flutter channel beta` 😄

**Comment by Skycoder42** [comment]
As seen in the changelog of https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md#2120, NNBD has been enabled by default in the beta - this might be the time to start integrating it into freezed.

**Comment by Hexer10** [comment]
I guess this is blocked by the several packages that are not yet migrated to nnbd which are:
```
analyzer*
build
build_runner
build_config
build_test
json_serializable
json_annotation
source_gen
source_gen_test
```

I've stared migrating the package here: https://github.com/Hexer10/freezed if someone wants to have a look

**Comment by comigor** [comment]
It seems json_serializable already has a proper [null_safety branch](https://github.com/google/json_serializable.dart/tree/null_safety) but it was not merged yet: https://github.com/google/json_serializable.dart/pull/740.
(Also OMG how many changes)

**Comment by renatoathaydes** [comment]
As you're probably already aware, NNBD is [officially in beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730) now, and most core packages , as well as several community packages, have already been migrated.

I am doing my part and migrating my small packages (done a couple so far, very smooth experience) :) but for big libraries like this one, it's hard because you must wait until all your dependencies have been migrated.

I've just run a test of this package's non-dev dependencies and the result looks disappointing:

```
Package Name  Current         Upgradable      Resolvable      Latest          

direct dependencies:
analyzer      ✗0.41.0         ✗0.40.6         ✗0.40.6         ✗0.41.0         
build         -               ✗1.5.1          ✗1.5.1          ✗1.5.1          
build_config  -               ✗0.4.3          ✗0.4.3          ✗0.4.3          
source_gen    -               ✗0.9.8          ✗0.9.8          ✗0.9.8      
```

I guess it'll be some time until we can get this package migrated?! I was going to offer to help but given how all dependencies are still not migrated, I think it's still not time to do it? Anyway, let us know how we can help.

**Comment by felix-barz-brickmakers** [comment]
See https://github.com/dart-lang/sdk/issues/44290 and https://github.com/dart-lang/build/issues/2920

As it seems as of now, these two will take a while to be migrated. However, as stated in the second issue, Generators can already generate sound null safe code, it's just the generator itself the cannot be sound. AFAIK the code generated by freezed does not depend on anything not supporting null safety. Mabey it would be a good idea to support This early for generated code via a special build config variable. For me personally, freezed not supporting null safety is reason enough to look for a different package (which would be a shame, loving freezed so far ❄️ )

**Comment by zs-dima** [comment]
> Support for nnbd will not be added until it is officially the time to start migrating (so beta).

**Comment by roman-petrov** [comment]
I am closing this since null-safety support in `freezed` was shipped in v.0.14.0.
