### ISSUE TITLE
how should bloc to bloc updates be handled?

### ISSUE THREAD

**Issue by QAQyzk** [rrousselGit/freezed#215]
I want to update BlocA's state from BlocB. BlocB can have many different events and when the output state of the event is LoadSuccess, it should call update function to update state in BlocA.
One way I can think of is add the update function at end of every event in BlocB, is there any better way I can handle this?

**Comment by rrousselGit** [comment]
Hello!

I would suggest asking this on Bloc's github. Freezed is unrelated to Bloc and I am not qualified to answer questions about it.

**Comment by QAQyzk** [comment]
Oh! Sorry, seems like I posted to wrong repo by accident.
