### ISSUE TITLE
Add "isFoo" and "asFoo" getters

### ISSUE THREAD

**Issue by carlowenig** [rrousselGit/freezed#22]
It would be very useful, especially if Union classes are declared privately, to have getter generated which checks if the class is of a certain type. Additionally a getter to cast an object to a nested union type would be useful.

Example:
```dart
@immutable
abstract class AuthState with _$AuthState {
    const factory AuthState.authorized(User user) = _AuthStateAuthorized;
    const factory AuthState.unauthorized() = _AuthStateUnauthorized;
}

// Some logic which needs user to be authorized
if (!authState.isAuthorized) return;

final authorizedState = authState.asAuthorized; // Returns authState as _AuthStateAuthorized
```

**Comment by rrousselGit** [comment]
A isFoo wouldn't work with type promotion, and a asFoo would be unsafe

You should use `maybeMap` or `maybeWhen` instead

**Comment by carlowenig** [comment]
As an alternative I personally would make `() => null` the default/fallback value of orElse in maybeMap/maybeWhen, so the following would be easier to read and would contain less boilerplate:

Example 1:
```dart
// Current implementation
authState.maybeWhen(
  authorized: (user) {
    // Some logic for authorized users
  },
  orElse: () {},
);

// Shorter with default orElse
authState.maybeWhen(authorized: (user) {
  // Some logic for authorized users
});
```

Example 2:
```dart
// Current implementation
final name = authState.maybeWhen(
  authorized: (user) => user.name,
  orElse: () => null,
);

// Shorter with default orElse
final name = authState.maybeWhen(
  authorized: (user) => user.name,
);
```

Not that much of a change, but I think it's more concise and not an unexpected behavior since the "maybe" keyword implicates something nullable in my opinion.

**Comment by rrousselGit** [comment]
That is incompatible with non-nullable types.\
It would work _now_, but would break soon.

**Comment by rrousselGit** [comment]
I've opened an issue on dart-lang about such `orElse` with NNBD:

https://github.com/dart-lang/language/issues/836

For now, I would refrain on making such change, as it would cause a breaking change
