### ISSUE TITLE
DiagnosticableTreeMixin related code still generated when foundation.dart is not imported

### ISSUE THREAD

**Issue by skybur** [rrousselGit/freezed#220]
I have this freezed class which uses `TimeOfDay` from `material` library.

```dart
import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'time_slot.freezed.dart';

@freezed
abstract class TimeSlot with _$TimeSlot {
  factory TimeSlot({
    TimeOfDay start,
    TimeOfDay end,
  }) = _TimeSlot;
}
```

The generated class still contains `DiagnosticableTreeMixin` even though I didn't add import for `flutter/foundation.dart`, thus making a compile error.

Freezed version is `0.10.9`

**Comment by rrousselGit** [comment]
Probably an issue with the logic that determines if "foundations" is imported.

Fancy making a PR? Shouldn't be too difficult, but I have other things to do.

**Comment by skybur** [comment]
I have no experience dealing with code generation but I'll see what I can do.

**Comment by DFelten** [comment]
Same issue here. I had to manual import foundation within the freezed class.
