### ISSUE TITLE
Overridden toString() is not called when flutter/foundation.dart imported

### ISSUE THREAD

**Issue by skybur** [rrousselGit/freezed#221]
I have this freezed class

```dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'time_slot.freezed.dart';

@freezed
abstract class TimeSlot implements _$TimeSlot {
  const TimeSlot._();

  factory TimeSlot({
    String start,
    String end,
  }) = _TimeSlot;

  @override
  String toString() {
    return start + end;
  }
}
```

When I call `toString()` for `TimeSlot` object, the result is from `DiagnosticableTreeMixin` instead of the overridden `toString()`.
The result is
```
_$_TimeSlot#9c939(type: TimeSlot, start: TimeOfDay(10:00), end: TimeOfDay(12:00))
```
instead of
```
TimeOfDay(10:00)TimeOfDay(12:00)
```

Freezed version is `0.10.9`

**Comment by Maatteogekko** [comment]
Is there any progress on this issue?
I think there is a problem even when not overriding the `toString()` generated method.
This is the `toString()` method that is generated  when importing `flutter/foundation.dart` inside the file that defines the freezed class:
```dart
@override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
    return 'User(id: $id, name: $name, registration: $registration, status: $status, email: $email, emailVerification: $emailVerification, prefs: $prefs)';
  }
```
If in a widget I use the `toString` I get the something like `_$_User#d1936(type: User, id: ...etc)`, not `User(id: $id, name: $name, registration: $registration, status: $status, email: $email, emailVerification: $emailVerification, prefs: $prefs)`, as the overriden `toString()` method defines.
I'm no expert, but t seems that the override is not working for some reason.

**Comment by mateusfccp** [comment]
I am still having this, and this makes impossible to override `toString` in a file that you define a `ChangeNotifier`.
