### ISSUE TITLE
Hard to use.

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/freezed#222]
Why don't you generate code based on an existing class like `json_serializable` do, instead of creating an abstract class?

I just want to build it based on an existing class with the benefit of the `copyWith` method, so I can control my class more flexibly.

**Comment by rrousselGit** [comment]
The way copyWith works requires a factory constructor, for the null support.

The syntax is also shorted (no duplicate between properties and the constructor). 

And it support union types. 

If you don't like it, you can use built_value

**Comment by tbm98** [comment]
I think there is a simpler way to solve the null case. that is to use setters.
like this:
`state = state.copyWith(name: 'guest', avatar: 'empty').setToken(null);`

**Comment by rrousselGit** [comment]
The classes are immutable.
They don't have setters.

**Comment by tbm98** [comment]
I think I should wait until the dart can distinguish between passing a null parameter and a non-passed parameter.😕

**Comment by tbm98** [comment]
@rrousselGit What do you think if I wrap parameters with Value?
like this
```
state = state.copyWith(token: Value(null));
```

**Comment by rrousselGit** [comment]
`state.copyWith(token: null)` already works with the current syntax.

I don't see a reason to do a downgrade on that aspect

**Comment by tbm98** [comment]
but current. It requires a abstract class to generate code and reduced flexibility

**Comment by rrousselGit** [comment]
Freezed is not made to be flexible but to have a concise syntax.

**Comment by tbm98** [comment]
Yes. Thanks !
