### ISSUE TITLE
Instance of 'UnrecognizedKeysException' - runtimeType

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/freezed#226]
Hi!

Having the `json_serializable` configuration `disallow_unrecognized_keys` set to true throws an error in a class with multiple types as `json_serializable` doesn't know about the field `runtimeType` that is added in each type:

```dart
return _$_$TextModuleToJson(this)..['runtimeType'] = 'textModule';
```

Is there any way to prevent this?

**Comment by hacker1024** [comment]
@rrousselGit

The fix added breaks my code.
The API I'm using has a few types of media.

```dart
enum MediaType {
  @JsonValue('station') station,
  @JsonValue('playlist') playlist,
  @JsonValue('track') track,
}
```

Various objects are related to media types, such as media objects that can be played and media objects that contain metadata.

```dart
abstract class MediaObject {
  MediaType get mediaType;
}

@Freezed(unionKey: 'type')
class PlayableMedia with _$PlayableMedia implements MediaObject {
  @FreezedUnionValue('track')
  const factory PlayableMedia.track({
    @JsonKey(name: 'type') required MediaType mediaType,
    // ...
  });
}

@Freezed(unionKey: 'type')
class MediaDescription with _$MediaDescription implements MediaObject {
  @FreezedUnionValue('track')
  const factory MediaDescription.track({
    @JsonKey(name: 'type') required MediaType mediaType,
    // ...
  });
}
```

It's true that each union type will only ever have its corresponding `mediaType` value, so parsing it from the JSON is a little redundant. That being said, I don't know of any other solution to achieve the same behaviour. As of the latest update, even this method does not work.

**Comment by hacker1024** [comment]
@rrousselGit Gentle bump. Can this change be disable with a configuration option, perhaps?

**Comment by hacker1024** [comment]
@rrousselGit

**Comment by rrousselGit** [comment]
Extracting the JSON key was never officially supported, so no.

If you want this, this probably should be a separate feature request.

Le jeu. 28 avr. 2022 à 09:28, hacker1024 ***@***.***> a
écrit :
