### ISSUE TITLE
Custom equality decorator

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/freezed#227]
hi,

Is there a way to specify a custom equality in order to handle lists more appropriately based off the data.

For example I'm coming from `functional_data` which allowed to have a decorator to specify an equality from dart's `collection` lib to be used in comparisons instead of the standard `==`.

```dart
@CustomEquality(DeepCollectionEquality())
final List<String> answers;

@CustomEquality(DeepCollectionEquality.unordered())
final List<int> answerIndices;

@CustomEquality(DeepCollectionEquality.unordered())
final List<QuestionCategory> categories;
```

If this is already supported, sorry for the trouble.

**Comment by rrousselGit** [comment]
There is no built-in way to do this.
I would instead recommend using a custom List implementation with the correct == override

KtList may help you with that

**Comment by Nolence** [comment]
I think the DeepCollectionEquality freezed uses is enough for me currently. Feel free to close or leave open as possible feature request.

Thanks

**Comment by rrousselGit** [comment]
:+1: I'll close it then
