### ISSUE TITLE
Conflicting factory and parameter name

### ISSUE THREAD

**Issue by winterDroid** [rrousselGit/freezed#23]
Hey,

I currently get a build error due to an error that the argument type can't be assigned to the parameter type:
```
@immutable
abstract class Example with _$Example {
  factory Example.something() = Something;
  factory Example.error(Error error) = SomeError;
}
```

This happens in the generated `when` and `maybeWhen` in `_$SomeError` when the passed `error` function will be called with the field `error`. All parameters should be references with e.g. `this.error` instead.

**Comment by rrousselGit** [comment]
\<sarcasm> stop reporting bugs! I need to sleep 😛 \</sarcasm> 


Thanks for these reports! They are really helpful

**Comment by winterDroid** [comment]
Thanks for fixing the issue that fast. One question: why did you not just always use `this.<parametername>`?

**Comment by rrousselGit** [comment]
This would cause lint errors.
