### ISSUE TITLE
Add annotation for generate docs

### ISSUE THREAD

**Issue by CurrySenpai** [rrousselGit/freezed#236]
I would like an annotation so that the generated getters have documentation

```dart
@freezed
abstract class TestModel with _$TestModel {
  factory TestModel({
    @docs('Foo') @required  String id,
  }) = _TestModel;
}
```

```dart
mixin _$TestModel {
  /// Foo
  String get id;

  $TestModelCopyWith<TestModelget copyWith;
}
```

**Comment by rrousselGit** [comment]
That's an interesting idea.

**Comment by Maistho** [comment]
Would it be possible to copy regular dartdoc comments? I miss having documentation on properties.

```dart
@freezed
abstract class TestModel with _$TestModel {
  factory TestModel({
    /// Foo
    @required String id,
  }) = _TestModel;
}
```
```dart
mixin _$TestModel {
  /// Foo
  String get id;

  $TestModelCopyWith<TestModelget copyWith;
}
```

**Comment by rrousselGit** [comment]
No, the analyzer doesn't pick up comments on parameters

**Comment by bwilkerson** [comment]
The class `NormalFormalParameter` does have a `documentationComment` getter. I'm guessing that that isn't being populated, even though it seems like it ought to be. Is there an issue filed for that?

As a work-around, you could potentially use `parameter.beginToken.precedingComments` to access the comment tokens. You'd have to do some extra work that ought to have been done for you, but you'd be able to get the information (if you want to).

**Comment by rrousselGit** [comment]
Thanks @bwilkerson!

Am I right to assume that from a `ParameterElement`, we can obtain its precedingComments with:

```dart
ParameterElement parameter;

final parameterComments = parameter.session
    .getParsedLibraryByElement(parameter.library)
    ?.getElementDeclaration(parameter)
    ?.node
    ?.beginToken
    ?.precedingComments;
```

and then iterating over `CommentToken.next` ?

I managed to parse the documentation of a parameter this way, but I do not know if there's any edge-case.

**Comment by eggnstone** [comment]
Is this fixed? How?
When I have a /// comment in the factory it does not show up in the API doc:
https://github.com/eggnstone/dart_format/blob/master/lib/src/Data/Config.dart
https://pub.dev/documentation/dart_format/1.1.16/dart_format/Config/addNewLineAfterClosingBrace.html
