### ISSUE TITLE
Customize Equality fields

### ISSUE THREAD

**Issue by RaviKavaiya** [rrousselGit/freezed#237]
Hello @rrousselGit 👋 

The generated freezed class' equality works as expected.
However, can we customize it? I mean, can we choose fields that will be used for equality comparison.

I used Equatable before. That allowed me to select which fields will be used in comparison. That was very much useful for me in some cases where I wanted to mark an object unique based on specific fields only.

Your thoughts?

**Comment by RaviKavaiya** [comment]
@rrousselGit any help in this regard would be appreciated...

**Comment by rrousselGit** [comment]
There is no way to do such thing.
My recommendation is to clone the model class, with only the properties you need

**Comment by RaviKavaiya** [comment]
Okay, closing.
