### ISSUE TITLE
Not clear how to apply custom json serializable converter

### ISSUE THREAD

**Issue by SandroMaglione** [rrousselGit/freezed#240]
I am trying to apply my custom json converter. The README states that it is possible to add a custom json serializable converter to a model created with freezed, but it does not seem to provide an example on how to actually apply it to a model.

I tried different strategies, but all seem unsuccessful.
``` dart
// 1. Outside the model

@freezed
@ModelConverter()
abstract class Model with _$Model {
  const factory Model({
    String name,
    String surname,
  }) = _Model;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```
``` dart
// 2. On the factory constructor

@freezed
abstract class Model with _$Model {
  @ModelConverter()
  const factory Model({
    String name,
    String surname,
  }) = _Model;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```
``` dart
// 3. On the factory fromJson method

@freezed
abstract class Model with _$Model {
  const factory Model({
    String name,
    String surname,
  }) = _Model;

  @ModelConverter()
  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```
As stated, none of this solutions seem to work.

How can I apply my custom converter such that `toJson` and `fromJson` generated with json_serializable utilize my custom converter?

**Comment by rrousselGit** [comment]
The decorator isn't placed on the `Model` class, but the places where `Model` is used:

```dart
@freezed
abstract class Another with _$Another {
  const factory Another({
    @ ModelConverter Model model,
  }) = _Another;

  factory Anotherl.fromJson(Map<String, dynamic> json) => _$AnotherFromJson(json);
}
```

**Comment by SandroMaglione** [comment]
I see, now it works. Thanks.

I was having doubts because the `Model` inside `Another` class was contained in a `List`, so I thought it would not work.
``` dart
@freezed
abstract class Another with _$Another {
  const factory Another({
    // Adding the decorator with a list works as well!
    @ModelConverter List<Model> modelList,
  }) = _Another;

  factory Another.fromJson(Map<String, dynamic> json) => _$AnotherFromJson(json);
}
```

Do you think it would be useful to add this example to the docs (both for the plain `Model` and `List` examples)? Should I open a PR?

**Comment by rrousselGit** [comment]
Sure, feel free to make a PR
