### ISSUE TITLE
generate only the code needed

### ISSUE THREAD

**Issue by sangron** [rrousselGit/freezed#244]
Hello, Is there a way to generate only the code we need, in the ValueObject I only need the tostring, == op and hash, but in the AuthValueFailure I need it all. this is to avoid implementing copyWith in the EmailAddress class if I remove it the compiler ask me to implement it.

thanks

```Dart
import 'package:dartz/dartz.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'value_objects.freezed.dart';

//default to everything, @freezed(data), @freezed(data, clonable), @freezed(data, json) or @freezed(union, fromJson)
@freezed  //@freezed(data) just to have ==/toString generated
abstract class ValueObject<T> with _$ValueObject {
  const factory ValueObject(Either<ValueFailure<T>, T> value) = _ValueObject;
}

class ValueFailure<T> {}

class EmailAddress extends ValueObject<String> {
  factory EmailAddress(String input) {
    return ValueObject(validateEmailAddress(input));
  }
  @override
  $ValueObjectCopyWith<String, ValueObject> get copyWith =>
      throw UnimplementedError();

  @override
  Either<ValueFailure, String> get value => throw UnimplementedError();
}

Either<AuthValueFailure<String>, String> validateEmailAddress(String input) {
  assert(input != null);
  const emailRegex =
      r"""^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+""";
  if (RegExp(emailRegex).hasMatch(input)) {
    return right(input);
  } else {
    return left(AuthValueFailure.invalidEmail(failedValue: input));
  }
}

@freezed // defaults to everything
abstract class AuthValueFailure<T> extends ValueFailure<T>
    with _$AuthValueFailure<T> {
  const factory AuthValueFailure.invalidEmail({
    @required String failedValue,
  }) = InvalidEmail<T>;
  const factory AuthValueFailure.shortPassword({
    @required String failedValue,
  }) = ShortPassword<T>;
}

```

**Comment by rrousselGit** [comment]
You probably don't want to use Freezed for ValueObject/EmailAdress.

**Comment by willlockwood** [comment]
I was thinking of opening another issue with the same general idea, but saw this, and thought I'd just tack on my brief thoughts here. While I think the example above isn't very compelling, I think this could be a significant improvement.

I'm experiencing a use case of `freezed`, where for 60% of my `freezed` classes (I have a lot of them), I'm only  
using it to safely generate `copyWith`, and for another 20%, I'm only using it for `copyWith` and `fromJson`/`toJson`, and for another 20%, for `when/maybeWhen`.

Specifically, I'm thinking that it could be nice to be able to specify (as OP suggested, probably in the freezed annotation?), that I only need `copyWith` for a certain freezed class, or only `copyWith` and `fromJson`, etc.

The main benefit I'm imagining, is mainly the time it takes to generate `freezed` files. This is quickly rising through the ranks of significant pain points for my team's rapidly growing codebase.

@rrousselGit I'm not quite able to follow how `freezed` works internally—would this be a huge lift, and if not, then could this represent as much of a `build_runner` performance upgrade as I'm imagining?

**Comment by rrousselGit** [comment]
Reducing the generated code isn't not really got to change much 

What is slow is the analysis

**Comment by rrousselGit** [comment]
It doesn't seem that this would have a clear benefit besides making the implementation of Freezed more complex.

I'd be happy to continue the discussion, but for now I'll close this as I don't plan on working on this
