### ISSUE TITLE
Improve examples in docs - Mixins and Interfaces

### ISSUE THREAD

**Issue by giovannilondero** [rrousselGit/freezed#255]
Hi,

would it be possible to extend the [Mixins and Interfaces for individual classes for union types](https://pub.dev/packages/freezed#mixins-and-interfaces-for-individual-classes-for-union-types) section? For example adding GeographicArea and House classes which the moment are used with `@Implements(...)` and `@With(...)`; it would be clearer imo to see how they're defined, if for example they're simple classes or freezed ones.

Instead of having just
```
@freezed
abstract class Example with _$Example {
  const factory Example.person(String name, int age) = Person;

  @Implements(GeographicArea)
  const factory Example.city(String name, int population) = City;
}
```
I think it would be better to have something like 
```
@freezed
abstract class GeographicArea with _$GeographicArea {
  const factory GeographicArea({
    double latitude,
    double longitude,
  }) = _Person;
}

@freezed
abstract class Example with _$Example {
  const factory Example.person(String name, int age) = Person;

  @Implements(GeographicArea)
  const factory Example.city(String name, int population) = City;
}
```

Since I might be missing something, I want to leave a reference to my issue too: https://stackoverflow.com/questions/63779359/flutter-freezed-package-how-to-properly-compose-classes

Thank you

**Comment by rrousselGit** [comment]
I've added some documentation about that part and answered your SO question. Hopefully, that should fix the misunderstanding

**Comment by giovannilondero** [comment]
Thank you Remi, it helped to clear things in my mind.
