### ISSUE TITLE
dart Compilation failed

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/freezed#258]
I am not sure if this is a freezed or dart problem.
The following code will generate code as expected, however, as soon as i compile the code, i will receive an error in the generated freezed file

```dart
typedef Test = void Function(void Function<T extends Object>(T event));

@freezed
abstract class SomeClass with _$SomeClass {
  factory SomeClass({Test test}) = _SomeClass;
}
```

will result in 
```
lib/main.freezed.dart:51:11: Error: The argument type 'void Function(void Function(Object))' can't be assigned to the parameter type 'void Function(void Function<T extends Object>(T))'.
 - 'Object' is from 'dart:core'.
          ? _value.action
          ^
lib/main.freezed.dart:79:11: Error: The argument type 'void Function(void Function(Object))' can't be assigned to the parameter type 'void Function(void Function<T extends Object>(T))'.
 - 'Object' is from 'dart:core'.
          ? _value.action
          ^
```

 The generated code in my .freezed file looks like this:
```dart
@override
  $Res call({
    Object test = freezed,
  }) {
    return _then(_value.copyWith(
      test: test == freezed
          ? _value.test
          : test as void Function(void Function<T extends Object>(T)),

/// NOTE TO @rrousselGit 
/// the line above
/// :  test as void Function(void Function<T extends Object>(T)), 
/// replaced by
/// : test 
/// will fix the problem
/// 
    ));
  }
}
```

**Comment by rrousselGit** [comment]
> /// NOTE TO @rrousselGit 
/// the line above
/// :  test as void Function(void Function<T extends Object>(T)), 
/// replaced by
/// : test 
/// will fix the problem


That works only if you did not disable `implicit-cast`. And `implicit-cast` will be disabled by default with NNBD


I'm not exactly sure what happens here tbh. Freezed is clearly casting using the correct type definition.

**Comment by rrousselGit** [comment]
It appears to be a bug in Dart, not Freezed.
 https://github.com/dart-lang/sdk/issues/43759

**Comment by rrousselGit** [comment]
Closing since this is a Dart bug
