### ISSUE TITLE
Add @nodoc on $* classes

### ISSUE THREAD

**Issue by aloisdeniel** [rrousselGit/freezed#259]
It would be great to have more control on what is generated with dartdoc.

For example I would love to ignore `$<X>CopyWith` generated mixins.

![image](https://user-images.githubusercontent.com/7687231/93591512-d74e1380-f9b0-11ea-8ca1-5083a2aeb5b7.png)

**Comment by rrousselGit** [comment]
Freezed cannot do anything. You'll have to play with settings on dartdoc, potentially ignoring `.freezed.dart` files

**Comment by aloisdeniel** [comment]
Any pointer on helping with that ? 

dartdoc seems to allow library exclusion, but not at a class or method level until there's a `/// @nodoc` comment above the element.

**Comment by rrousselGit** [comment]
Maybe look into the `dartdoc_options.yaml` as explained here https://github.com/dart-lang/dartdoc

I would suggest transferring this issue to the dartdoc repository instead https://github.com/dart-lang/dartdoc. There's nothing Freezed can do here.

**Comment by aloisdeniel** [comment]
Already read all the available options, and I'm pretty sure the only available option is adding `/// @nodoc` comment before each class which is only possible from freezed generators.

I'll create an issue, see what they say and keep this issue updated! Thanks

**Comment by rrousselGit** [comment]
In the end, I've added the `/// @nodoc`
