### ISSUE TITLE
Generate optics for every mutable property

### ISSUE THREAD

**Issue by sroddy** [rrousselGit/freezed#266]
**Is your feature request related to a problem? Please describe.**
Lenses are very useful when it comes to deal with immutable types. The generated CopyWith classes are very powerful for direct mutations but they are not flexible enough if you want to use them to abstract logic.

**Describe the solution you'd like**
I think it would be extremely useful to have a generated lens for every mutable property of a freezed object so that I could write:

```dart
final foo$ = AppState$.subState.foo;

print(foo$.get(appState));
final updatedAppState = foo$.update(appState, newFoo);

final fooCopyWith = foo$.of(appState); // the already existing $FooCopyWith<AppState>
final updatedAppState = fooCopyWith(bar: newBar);
```

**Describe alternatives you've considered**
Lenses can be generated for every mutable property (not only freezed values) and also for Lists and Maps (to access/modify an item at a given index/key).

It's important to include inside the freezed_annotation package a protocol for the lens (Lens<S, T>) so that it would be possible to use them in a generic way inside functions/libraries and also easily compose them 

The already existing generated $ClassName could be used for the purpose but it's important to consider the naming of the generated properties in order to avoid collisions.

**Comment by sroddy** [comment]
for reference:
https://arrow-kt.io/docs/optics

Ideally it would be amazing to have Lenses generated for single class freezed and Prisms for Union/Sealed classes, along with Optionals for nullable properties

**Comment by rrousselGit** [comment]
I don't plan on working on this, so I'll close this.
