### ISSUE TITLE
Freezed model throws error on code generation   

### ISSUE THREAD

**Issue by vedantrathore** [rrousselGit/freezed#268]
**Describe the bug**
Unable to generate freezed classes for models.

**To Reproduce**

I have this model file named `activity.dart`. I've highlighted the errors I'm getting from VSCode in the comments. 

```dart

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'activity.freezed.dart'; // Expected this library to be part of 'package:habitwave/app/model/Activity.dart', not 'package:habitwave/app/model/activity.dart'. Try including a different part, or changing the name of the library in the part's part-of directive
part 'activity.g.dart'; // Expected this library to be part of 'package:habitwave/app/model/Activity.dart', not 'package:habitwave/app/model/activity.dart'. Try including a different part, or changing the name of the library in the part's part-of directive

enum ActivityType {
  AcceptAddToSquadRequest,
  RemovedFromSquad,
  AddToSquadRequest,
  Reaction,
  Nudge,
}

toNull(_) => null;

@freezed
abstract class ActivityObject with _$ActivityObject {
  const factory ActivityObject({
    String sentByName,
    String requestId,
    int sentOn,
    String id,
    ActivityType activityType,
    String sentById,
    bool unread,
    String reactionType,
    int reactionCount,
    String habitName,
    String text,
    String sentByPhotoURL,
  }) = _ActivityObject; // The redirected constructor '_ActivityObject Function({ActivityType activityType, String habitName, String id, int reactionCount, String reactionType, String requestId, String sentById, String sentByName, int sentOn, String text, bool unread})' has incompatible parameters with 'ActivityObject Function({ActivityType activityType, String habitName, String id, int reactionCount, String reactionType, String requestId, String sentById, String sentByName, String sentByPhotoURL, int sentOn, String text, bool unread})'. Try redirecting to a different constructor

  factory ActivityObject.fromJson(Map<String, dynamic> json) => _$ActivityObjectFromJson(json);
}

@freezed
abstract class Activity implements _$Activity {
  const Activity._();
  const factory Activity({
    List<ActivityObject> data,
    dynamic metadata,
  }) = _Activity;

  Activity add(Activity other) {
    return Activity(metadata: other.metadata, data: this.data + other.data);
  }

  factory Activity.fromJson(Map<String, dynamic> json) => _$ActivityFromJson(json);
}

```

It's a simple freezed class. To circumvent the first `dart part_of_different_library` issue, I've to rename the file to `Activity.dart` after running `flutter pub run build_runner build --delete-conflicting-outputs`

Haven't found a solution to the second constructor issue. Do let me know if I'm missing something here. I have similar 7-8 model classes and they all seem to be working fine. 

**Expected behavior**
Freezed and JSONSerializable should generate 2 files without error. `activity.g.dart` and `activity.freezed.dart`

**Comment by vedantrathore** [comment]
Update: I seem to have solved the second issue by deleting the 2 generated files and running the build runner again.  

Error: `The redirected constructor '_ActivityObject Function({ActivityType activityType, String habitName, String id, int reactionCount, String reactionType, String requestId, String sentById, String sentByName, int sentOn, String text, bool unread})' has incompatible parameters with 'ActivityObject Function({ActivityType activityType, String habitName, String id, int reactionCount, String reactionType, String requestId, String sentById, String sentByName, String sentByPhotoURL, int sentOn, String text, bool unread})'. Try redirecting to a different constructor`

**Comment by vedantrathore** [comment]
As we can see I'm getting this error in the main model file 
<img width="1106" alt="Screen Shot 2020-09-22 at 8 41 25 PM" src="https://user-images.githubusercontent.com/14354315/93901360-12837600-fd14-11ea-94fe-41198d6079fb.png">

but the part files in the generated files seem to be correct 
<img width="723" alt="Screen Shot 2020-09-22 at 8 43 33 PM" src="https://user-images.githubusercontent.com/14354315/93901573-4c547c80-fd14-11ea-8438-a115355ede53.png">

<img width="475" alt="Screen Shot 2020-09-22 at 8 43 51 PM" src="https://user-images.githubusercontent.com/14354315/93901607-570f1180-fd14-11ea-87bb-a146d62123a2.png">

**Comment by joanofdart** [comment]
I'm having these issues constantly too and the only solution is to close-reopen vscode.

**Comment by rrousselGit** [comment]
Do you have an error in the terminal, or is it just the IDE?
If so, you may want to raise an issue to vscode as that's unrelated to Freezed

If that's what I'm thinking about, the way I go around this is using cmd + hovering the "part"

**Comment by KlausJokinen** [comment]
This might be related https://github.com/dart-lang/sdk/issues/43166

**Comment by vedantrathore** [comment]
@rrousselGit I think it was just IDE but due the error I was unable to compile the app. This might've been the weirdest bug I've encountered. To bypass this I eventually had to change the name of the file from `activity.dart` to `activityFeed.dart` and the error vanished. Super weird. I think you can close this issue for now given that it might not be an issue with the package itself.

**Comment by al-mohad** [comment]
The class 'x' doesn't have a constructor named '_'.

**Comment by digu3120** [comment]
👉 Try it out now: https://dartfreezed.tech/

 💬 I’d love your feedback and suggestions!

🚀 Introducing dartfreezed.tech – Your AI-Powered Flutter Freezed Model Generator! ⚡

Tired of manually converting complex JSON into Dart models?

 Say hello to dartfreezed.tech – a smart, lightning-fast tool that uses AI to generate Freezed and JsonSerializable Dart models from any JSON response in seconds!

 ✅ Powered by AI for intelligent field detection

 ✅ Clean, reliable Freezed models with built-in null safety

 ✅ Boosts productivity for Flutter developers

 ✅ Handles deeply nested and complex structures with ease
