### ISSUE TITLE
Confusing types with the same name

### ISSUE THREAD

**Issue by fdietze** [rrousselGit/freezed#278]
**Describe the bug**
When having two types in different packages, which have the same name, freezed generates code, as if these types would be the same.

**To Reproduce**

```dart
@freezed
abstract class AuthState with _$AuthState {
  const factory AuthState.SignedIn(FirebaseAuth.User authUser, User dbUser) = SignedIn;
}
```

The generated code contains only the base types:
```dart
...
SignedIn(User authUser, User dbUser)
...
```

**Expected behavior**
The generated code should use the correct types.

**Comment by rrousselGit** [comment]
Duplocate of #70
