### ISSUE TITLE
Prefer mixin lint rule

### ISSUE THREAD

**Issue by petrnymsa** [rrousselGit/freezed#28]
Generated _$Union is abstract class. With lint rule 'prefer_mixin' [link](https://dart-lang.github.io/linter/lints/prefer_mixin.html) enabled there is warning. 

Is there a special reason to have it as an abstract class? 
Of course, this issue does not have any negative impact, just <pedantic>reason</pedantic>

**Comment by rrousselGit** [comment]
It is semantically not a mixin: It doesn't have methods/properties/...
It's only an interface.

In theory, we should use `implements` instead of `with`.

But that's a fair request. I'll change it to be a mixin instead.
