### ISSUE TITLE
How to get actual `runtimeType` of my Freezed Class by overriding `toString()` 

### ISSUE THREAD

**Issue by aytunch** [rrousselGit/freezed#287]
Right now, I have this:

```
@Freezed(unionKey:'type')   //I am not sure about this but read in the issues so gave it a try
abstract class CellState with _$CellState {
  const CellState._();   //this is for overriding toString()

factory CellState.initial() => CellState(.........

@override
  String toString() {
    return "${this.runtimeType}";   //prints _$_CellState
  }
```
However console gives me `_$_CellState` instead of `CellState`. Also I would like to print which specific factory constructor is being used like `CellState.initial()`. Is there a clean way to do this?

**Comment by rrousselGit** [comment]
What you want is the default behavior of the toString.

**Comment by aytunch** [comment]
Yes, But I will change the text. The arguments are too many and make it very hard to read in the console. After I can nicely print them, I will pick which members to `toString()`. So unlike the above example, I will not be just printing runtimeType

**Comment by mohitkyadav** [comment]
Can anyone help me with the same issue, I'm trying to write tests and I get `_$_BaseClass` as runtimeType. How do I get `BaseClass`?

**Comment by rrousselGit** [comment]
The runtime type **is** `_$_BaseClass`

**Comment by mohitkyadav** [comment]
I know that @rrousselGit , how do I write a year for comparing the type.

**Comment by rrousselGit** [comment]
The toString no-longer points to _$ classes but instead `MyClass.named` so I think this can be closed
