### ISSUE TITLE
Annoying json_serializable bug

### ISSUE THREAD

**Issue by jhionan** [rrousselGit/freezed#29]
On my production project freezed is not generating g.dart file, the problem is that I could not reproduce this bug on a test project. 

Creating a test project everything works fine, copying the working fine class of test to production and the .g.dart is not generated.

I tried do add all pubspec dependencies of production project at test project, and test still working.
json_serializable classes is working well when not generated by freezed.

I dont know what to do to find this bug, any idea?

**Comment by rrousselGit** [comment]
Without having some code to reproduce the error I cannot help you

A quick check though:
Freezed doesn't generate `.g.dart` but `.freezed.dart`.
Did you use the right part?

**Comment by jhionan** [comment]
This is the annoying part, freezed.dart is being generated, and it have the
expected @JsonSerializable() annotations.

I try to dig deeper, but i couldn't reproduce it into a new project
(because it works).

**Comment by rrousselGit** [comment]
It may have something to do with the package versions.

build_runner didn't support having a generator outputting dart code for another generator until last week.

**Comment by jhionan** [comment]
tried to force a version on build_runner, is not that.  build_runner dont send any error feedback when generating stuffs.

`dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^3.0.1
  build_runner: ^1.7.4
  mockito: 4.1.1
  mobx_codegen: ^1.0.1
  json_serializable: ^3.2.5
  freezed: ^0.2.4`

I just used your example:
`import 'package:flutter/foundation.dart';
import 'package:json_annotation/json_annotation.dart';

part 'aaa.freezed.dart';
part 'aaa.g.dart';

@immutable
abstract class Model with _$Model {
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}`

and still not generating .g.dart.

**Comment by rrousselGit** [comment]
I see that you're using mobx_codegen. What happens if you remove it?

**Comment by rrousselGit** [comment]
Also, could you try adding the following file at the root of your project?



```dart
# build.yaml
targets:
  $default:
    builders:
      freezed|freezed:
        enabled: false


builders:
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: ["freezed"]
    build_extensions: { ".dart": [".freezed.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before:
      - json_serializable|json_serializable
      - source_gen|combining_builder
```

**Comment by jhionan** [comment]
after this build yaml  .freezed.dart stopped get generated too.  but this can be a clue because I have a build.yaml for json_serializable.
I `ll try  a consistent way to reproduce.

**Comment by nonoyona** [comment]
> On my production project freezed is not generating g.dart file, the problem is that I could not reproduce this bug on a test project.
> 
> Creating a test project everything works fine, copying the working fine class of test to production and the .g.dart is not generated.
> 
> I tried do add all pubspec dependencies of production project at test project, and test still working.
> json_serializable classes is working well when not generated by freezed.
> 
> I dont know what to do to find this bug, any idea?

I am having the same issue

**Comment by jhionan** [comment]
Already tried to comment all dependences that could generate stuffs..

So far no good =/

Next test: comment ALL dependences of project and see if it will generate.

**Comment by rrousselGit** [comment]
Sadly I can't do much to help here.

Consider uploading your `pubspec.lock` and potentially use `dependency_overrides` to ensure that the version of build_runner+co is the right one

**Comment by jhionan** [comment]
> Sadly I can't do much to help here.
> 
> Consider uploading your `pubspec.lock` and potentially use `dependency_overrides` to ensure that the version of build_runner+co is the right one

It worked!!!

Just deleted pubspec.lock, I guess build_runner was with an old version, even forcing it on pubspec.

Tks so much!
