### ISSUE TITLE
Question, How copyWith support null?

### ISSUE THREAD

**Issue by sm2017** [rrousselGit/freezed#291]
@rrousselGit I know here is not for question, But if you have free time please help me

Can you show me a minimal example represent how you implement a copyWith support null values?

**Comment by rrousselGit** [comment]
I'd suggest looking at the generated code

But TL;DR, that's achieved through default values. 
Freezed adds a custom default value to each parameter of the copyWith, and check whether the passed value is equal to that default value or not.
