### ISSUE TITLE
Share common attributes between different freezed models

### ISSUE THREAD

**Issue by SandroMaglione** [rrousselGit/freezed#296]
**Is your feature request related to a problem? Please describe.**
I am trying to **share some common attributes between different freezed models**. I use freezed extensively and the feature I am missing is the possibility to reduce code copies by sharing some attributes between models.

**Describe the solution you'd like**
I was thinking about a new annotation that allows you to inject some attributes in a freezed model from another class, for example:
```dart
class CommonUser {
   String email;
   String password;
}

@freezed
abstract class MasterUser with _$MasterUser {
  @From(CommonUser)
  const factory MasterUser({
    String address,
  }) = _MasterUser;
}

@freezed
abstract class NormalUser with _$NormalUser {
  @From(CommonUser)
  const factory NormalUser({
    String name,
    String surname,
  }) = _NormalUser;
}
```
In this case, `MasterUser` and `NormalUser` would have two additional attributes, `email` and `password`, inherited from the `CommonUser` class.

**Describe alternatives you've considered**
What I am currently doing is duplicating common attributes in multiple models. This makes the code error-prone in case of changes that must occur in both models since it is easy to forget to update one of the two models.

**Comment by rrousselGit** [comment]
How would you initialize the values when calling the constructor? As the constructor doesn't have the parameter

**Comment by SandroMaglione** [comment]
The idea would be that the code of the example:
```dart
class CommonUser {
   String email;
   String password;
}

@freezed
abstract class MasterUser with _$MasterUser {
  @From(CommonUser)
  const factory MasterUser({
    String address,
  }) = _MasterUser;
}

@freezed
abstract class NormalUser with _$NormalUser {
  @From(CommonUser)
  const factory NormalUser({
    String name,
    String surname,
  }) = _NormalUser;
}
```
would be equivalent to this code:
```dart
@freezed
abstract class MasterUser with _$MasterUser {
  const factory MasterUser({
    String address,
    String email,
    String password.
  }) = _MasterUser;
}

@freezed
abstract class NormalUser with _$NormalUser {
  const factory NormalUser({
    String name,
    String surname,
    String email,
    String password.
  }) = _NormalUser;
}
```
The advantage is that with `@From()` the `email` and `password` parameters are shared and can be changed in only one place instead of two, thus reducing code duplication and errors.

**Comment by SandroMaglione** [comment]
The freezed model could also inherit the definition from the `CommonUser` class, for example:
```dart
class CommonUser {
   final String email;
   final String password;
   
   CommonUser({
    @required this.email,
    @required this.password,
   });
}
```
would be equivalent to:
```dart
@freezed
abstract class MasterUser with _$MasterUser {
  const factory MasterUser({
    String address,
    @required String email,
    @required String password.
  }) = _MasterUser;
}

@freezed
abstract class NormalUser with _$NormalUser {
  const factory NormalUser({
    String name,
    String surname,
    @required String email,
    @required String password.
  }) = _NormalUser;
}
```

**Comment by rrousselGit** [comment]
That is not what I meant.

What I meant is, how do you instantiate Master User and specify an email?

**Comment by SandroMaglione** [comment]
Since `MasterUser` with `@From()` would be equivalent to:
```dart
@freezed
abstract class MasterUser with _$MasterUser {
  const factory MasterUser({
    String address,
    String email,
    String password.
  }) = _MasterUser;
}
```
you could simply write:
```dart
MasterUser master = MasterUser(
   address: 'Address',
   email: 'Email',
   password: 'Password',
);
```

**Comment by rrousselGit** [comment]
You can't. In your `@From` example, MasterUser does not have a email parameter in its constructor.

**Comment by SandroMaglione** [comment]
Sorry, I think I have not clear how code generation works.

In my mind it would work like this, please correct me if I am wrong (probably I am):
When I annotate the `MasterUser` with `@From(CommonUser)`, you have access to the attributes of `CommonUser` when you write the code generation (i.e. `email` and `password`). From here you would be able to add these two new parameters internally to the constructor of `MasterUser` during code generation.

What am I missing?

**Comment by rrousselGit** [comment]
Code generation does not edit existing code. It only adds new code

Le ven. 6 nov. 2020 à 13:38, Sandro Maglione <notifications@github.com> a
écrit :

**Comment by SandroMaglione** [comment]
Ah, I see.

Do you think there could be a way to shared attributes between freezed models? Or at least enforce the implementation of common getters?

**Comment by rrousselGit** [comment]
You can enforce the implementation of common properties with interfaces:

```dart
abstract class Interface {
  int get a;
}

@freezed
abstract class Example with _$Example implements Interface {
  factory Example({int a}) = _Example;
}
```
