### ISSUE TITLE
12.2 doesn't generate a .g.dart part file for enums

### ISSUE THREAD

**Issue by theweiweiway** [rrousselGit/freezed#299]
Describe the bug
Thanks for fixing the last issue I made here #280. However, now the .g.dart file does not generate.

```
import 'package:freezed_annotation/freezed_annotation.dart';
part 'enums.freezed.dart';
part 'enums.g.dart'; // target of URI hasn't been generated

@freezed
abstract class MessageTypeEnum implements _$MessageTypeEnum {
  const MessageTypeEnum._();
  const factory MessageTypeEnum(String label) = _MessageTypeEnum;
  static const notification = MessageTypeEnum("notification");
  static const message = MessageTypeEnum("message");
  static const file = MessageTypeEnum("file");

  factory MessageTypeEnum.fromJson(String val) {
    return MessageTypeEnum(val);
  }

  @override
  String toString() => this.label;

  static MessageTypeEnum stringToEnum(String val) {
    if (val == notification.toString()) return notification;
    if (val == message.toString()) return message;
    if (val == file.toString()) return file;
    return null;
  }
}
```

To Reproduce
Try to run `flutter pub run build_runner watch --delete-conflicting-outputs` with the code block above and it won't generate the json serializable part file

Expected behavior
It should generate the file. If i revert back to version 11.6, everything works great. 

Thanks Remi!

**Comment by rrousselGit** [comment]
Sorry for the late reply

I can't reproduce it in 0.12.7. Could you double check that you still have the issue?

**Comment by theweiweiway** [comment]
No worries Remi,

My `enums.g.dart` file still doesn't generate - I copy and pasted the code above exactly as is into my project with freezed 0.12.7 but no luck

**Comment by rrousselGit** [comment]
Do you think you could create a minimal project to reproduce this issue?

As I too copy-pasted this code, but it works for me.

**Comment by theweiweiway** [comment]
no problem! here it is: https://github.com/theweiweiway/test_app

and my Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
```

**Comment by rrousselGit** [comment]
Oh sorry, this is the expected behaviour

The syntax for `fromJson` isn't `fromJson(json) {}` but `fromJson(json) => `

If you use `{}`, freezed will not ask `json_serializable` to generate anything and consider it as if you implemented `fromJson` manually
