### ISSUE TITLE
Sound null safety support

### ISSUE THREAD

**Issue by Cilestal** [rrousselGit/freezed#300]
Does freezed support dart Sound null safety?
https://dart.dev/null-safety

**Comment by rrousselGit** [comment]
No, not yet

**Comment by Skycoder42** [comment]
See #211

**Comment by pratikpparikh** [comment]
@rrousselGit it would be nice to have freezed with null-safety.  It is blocking any development with 2.12 sdk.  Can you please consider updating freezed. I understand this become more complex for you as other frameworks that you provide do depend on it and might endup creating web of changes.  Thank you for considering.

**Comment by rrousselGit** [comment]
This is planed, but that's a big change

**Comment by pratikpparikh** [comment]
@rrousselGit Thank you, I understand

**Comment by rrousselGit** [comment]
I've opened a WIP pull-request for null safety https://github.com/rrousselGit/freezed/pull/350

Feel free to try it out using git dependency. I'd be happy to fix any bug

**Comment by rrousselGit** [comment]
I've release a 0.13.0-nullsafety.0 :smile:

**Comment by haashem** [comment]
Please mention this null safe version and how to upgrade in Github page. I was struggling for 2 hours to fix my issue! I thought the problem is with build_runner!

**Comment by rrousselGit** [comment]
Could you explain your problem?

**Comment by haashem** [comment]
I have adopted null safety to my project and have created a union class for bloc event cases.
I was using `freezed: ^0.12.7` but build_runner code generator couldn't generate null safe freezed class.
I thought it was issue of build_runner not supporting null safety yet. but later I fount its issue of Freezed package, which I have to use a null safe version of it. it's was not mentioned from home page a beta null safe is available. so please update the read me file beta null safe version is available. `freezed: ^0.13.0-nullsafety.2`
