### ISSUE TITLE
Getter for class attributes

### ISSUE THREAD

**Issue by phijma** [rrousselGit/freezed#301]
Would it be possible to get all attributes of a `@freezed` class. So the ones you define in the constructor?

Right now I use a custom getter, like so:

```
@freezed
abstract class Foo with _$Foo {
  factory Foo({
    String some_string,
    String some_other_string,
  }) = _Foo;

  const Foo._();

  List<String> get props => [
    some_string,
    some_other_string,
  ];
}
```

But this doesn't feel very DRY.

**Comment by rrousselGit** [comment]
I would recommend making a separate code generator for this, possibly based on extension methods

**Comment by phijma** [comment]
Thanks!
