### ISSUE TITLE
Remove identity not used warning from freezed abstract classes

### ISSUE THREAD

**Issue by Hari-07** [rrousselGit/freezed#305]
**Is your feature request related to a problem? Please describe.**
All the freezed abstract classes return a warning "The declaration '_$identity' isn't referenced"

**Describe the solution you'd like**
This warning to not exist. Add 'unused_element' to the the ignore for file options in generated .freezed file

**Comment by rrousselGit** [comment]
Closing as the suggestion is to disable lints on generated files
