### ISSUE TITLE
Make json generation option as an argument in @freezed annotation

### ISSUE THREAD

**Issue by Gintasz** [rrousselGit/freezed#311]
This is a very minor idea for a modification. Instead of requiring to write `part "file.g.dart"` and `factory ClassName.fromJson(Map<String, dynamic> json) => _$ClassNameFromJson(json);` to trigger json code generation, this library could have an option in the annotation, so that json generation could be enabled by e.g. `@freezed(json: true)`. Json generated methods would also be in `.freezed.dart` file, instead of a separate additional `.g.dart` file. This would make the class code contain less boilerplate (true, by only 1 line). Less of `.g.dart` files would make a file explorer in IDE cleaner for those who choose not to hide generated files.

**Comment by rrousselGit** [comment]
Freezed is making that _.g.dart_ file.
It is generated by json_serializable

Freezed is unable to fuse the .g.dart and the .freezed.dart.

**Comment by rrousselGit** [comment]
Closing as there's nothing I can do
