### ISSUE TITLE
Class level decorators/annotations that are used as Types

### ISSUE THREAD

**Issue by xzhorikx** [rrousselGit/freezed#314]
Related issues: #49, #50 

I have a very specific case that requires types (`Type` ) to be passed to a class/annotation, and I'd like to use freezed library to achieve class creation. I believe it will be easier to demonstrate the case using a small example:
 * I'm using [floor database package](https://pub.dev/packages/floor) that requires its database to be initialized in the following manner:
```
@Database(entities: [      Table    ])
abstract class AppDatabase extends FloorDatabase { ... }
```
* As you can see it requires `List<Type> entities` field to be passed within the `@Database` annotation. I'd like to generate `Table` class using freezed library.

**The issue**
`Table` must be annotated with `@Entity` annotation and `Table` must be a concrete class (non-abstract). Currently, `Entity` is being created using following approach:
```
@freezed
abstract class MyTable with _$MyTable {
    factory MyTable(String id) = Table
}
```

I cannot reference `MyTable ` and `Table` in `entities` field within `@Database(entities: [      Table    ])` because they are both abstract.  Neither can I reference `_$Table` because it is of its visibility. The only way of doing it is to create a separate "wrapper" class for the sole purpose of having `@Entity` annotation
```
@Entity( ... )
class EntityWrapper extends _$Table {
    EntityWrapper(String id) : super(id)
}
```
and then pass the said class to the `Database` object:
```
@Database(entities: [      EntityWrapper    ])
abstract class AppDatabase extends FloorDatabase { ... }
```

As you can see this becomes hard to maintain because each field change requires it to be updated in 3 separate places and I'm would not prefer to extend generated classes.

Maybe there is an easier solution to achieve it?

**Comment by rrousselGit** [comment]
You could do:

```dart
@freezed
abstract class MyTable with _$MyTable {
  @Entity()
  factory MyTable(String id) = Table
}

@Database(entities: [      Table    ])
abstract class AppDatabase extends FloorDatabase { ... }
```

**Comment by rrousselGit** [comment]
Did that proposed solution work for you? If so, can we close this?

**Comment by xzhorikx** [comment]
Thank you for the suggestion, this has indeed worked out pretty well.

Sorry for the late reply, this issue might be closed.

**Comment by codingwiththiago** [comment]
@xzhorikx Could you please explain some more how it worked? 
I'm trying to achieve the same result, but `Table` is an abstract class aswell.

**Comment by knvpk** [comment]
@xzhorikx did you fixed it, how?

**Comment by knvpk** [comment]
Hi @rrousselGit , 

> You could do:
> 
> ```dart
> @freezed
> abstract class MyTable with _$MyTable {
>   @Entity()
>   factory MyTable(String id) = Table
> }
> 
> @Database(entities: [      Table    ])
> abstract class AppDatabase extends FloorDatabase { ... }
> ```

This still not able to work, any other suggestions.

**Comment by knvpk** [comment]
@codingwiththiago , did you find out any other solution
