### ISSUE TITLE
Can't use outside flutter?

### ISSUE THREAD

**Issue by Gintasz** [rrousselGit/freezed#315]
I'm trying to reuse the business logic files inside a server app. It looks like freezed is generating code that depends on some flutter's dependencies in `toString` and `debugFillProperties` because my IDE shows:
```The method 'DiagnosticsProperty' isn't defined for the type```

Looking at the source, it looks like `hasDiagnosticable` property might control this behavior. Any way to control it? Also, why not make it this either flutter-dependant or flutter-independant?

**Comment by rrousselGit** [comment]
If you imported flutter, you need to also import `flutter/foundation.dart`

**Comment by rrousselGit** [comment]
Freezed is Flutter independent

What happens is, it detected that you are using Flutter and therefore requires an extra import, to make your objects print nicely in the devool

**Comment by Gintasz** [comment]
Alright, looks like I just had to re-run `build_runner` to regenerate freezed files after I removed flutter dependency from pubspec.yaml during refactoring. No errors now. Great!
