### ISSUE TITLE
Hash the content of every class using freezed to prevent unnecessary rebuilds/file recreations

### ISSUE THREAD

**Issue by marcopapula-dev** [rrousselGit/freezed#316]
**Is your feature request related to a problem? Please describe.**
Currently the builder recreates every .freezed.dart file every time. This leads to a long waiting time in bigger projects.

**Describe the solution you'd like**
The package could hash the content of the class annotated and only recreate the ones that actually have a changed hash.

**Describe alternatives you've considered**
Not using freezed because it interrupts the workflow :S.

**Additional context**
The hash could be included as a comment in the generated file.

**Comment by rrousselGit** [comment]
This is not the responsibility of Freezed, but `build`/`build_runner`

As much as I would like to improve the speed, the slowness is not something I have control over. It is these packages that decide to re-execute the code-generator, not Freezed
