### ISSUE TITLE
Not generating other factories when fromJson present 

### ISSUE THREAD

**Issue by gullucktheapp** [rrousselGit/freezed#323]
import 'package:freezed_annotation/freezed_annotation.dart';

part 'income_dto.freezed.dart';

part 'income_dto.g.dart';

@freezed
abstract class IncomeDto with _$IncomeDto {
  const factory IncomeDto({
    @required String id,
    @required num amount,
  }) = _IncomeDto;
  
  factory IncomeDto.fromJson(Map<String, dynamic> json) =>
      _$IncomeDtoFromJson(json);

  factory IncomeDto.unknown(num amount) => IncomeDto(
        id: '',
        amount: amount,
      );
}

Its giving this error

Could not generate `fromJson` code for `copyWith`.
To support the type `_$IncomeDtoCopyWith` you can:
* Use `JsonConverter`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
* Use `JsonKey` fields `fromJson` and `toJson`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
package:Code_Generation/models/income_dto.freezed.dart:175:39
    ╷
175 │   _$IncomeDtoCopyWith<_IncomeDto> get copyWith =>
    │                                       ^^^^^^^^

**Comment by pratikpparikh** [comment]
@rrousselGit this is only a problem with 0.12.5.  @gullucktheapp you might want to use 0.12.4 or lesser version

**Comment by gullucktheapp** [comment]
> @rrousselGit this is only a problem with 0.12.5. @gullucktheapp you might want to use 0.12.4 or lesser version

Its still not working. I am using latest dart and flutter stable.

**Comment by rrousselGit** [comment]
This was fixed as part of 0.12.6
