### ISSUE TITLE
some errors in *.freezed.dart files after upgrade from v0.12.4 to v0.12.5

### ISSUE THREAD

**Issue by ndinhbang** [rrousselGit/freezed#324]
**Describe the bug**
I got some errors in *.freezed.dart files after upgrade from v0.12.4 to v0.12.5
[
![image](https://user-images.githubusercontent.com/47777358/102056148-7eaadd00-3e1e-11eb-9744-a48ac3e6edbd.png)
](url)

**To Reproduce**
I followed tutorials on resocoder.com website. So to reproduce the problem, you can clone the repo here: 
https://github.com/ResoCoder/flutter-ddd-firebase-course.git
and then update the version of **freezed** to **^0.12.5**

p/s: sorry for my bad english.

**Comment by 2shrestha22** [comment]
yes same problem after updating to latest version. I reverted to old version but still when generating does not generates properly and bloc states are missing.

**Comment by gullucktheapp** [comment]
> yes same problem after updating to latest version. I reverted to old version but still when generating does not generates properly and bloc states are missing.

Same problem.

**Comment by gullucktheapp** [comment]
I already created the issue.

**Comment by ndinhbang** [comment]
@2shrestha22 you may fix the version to 0.12.4. note that you need to remove the **^**

**Comment by rrousselGit** [comment]
This was fixed as part of 0.12.6
