### ISSUE TITLE
Error using `@implement` on Freezed Class

### ISSUE THREAD

**Issue by iapicca** [rrousselGit/freezed#327]
I'm not sure this a bug or failure of my understanding, I'll try to explain my situation:

in a nutshell I'd like to be able to do something like 

`Foo.success('') is Success` in my tests (and not only)

## first attempt

<details>
<summary>code sample</summary>

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'foo.freezed.dart';

@freezed
abstract class Foo<T> with _$Foo {
  const factory Foo.success(T result) = Success;
}
```

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'baz.freezed.dart';

@freezed
abstract class Baz<T> with _$Baz {
  const factory Baz.success(T result) = Success;
  const factory Baz.loading() = Loading;
}
```

</details>

when I try to export as below 

```dart
export 'src/baz.dart';
export 'src/foo.dart';
```
I get the error

> The name '$SomethingCopyWith' is defined in the libraries 'package:freezed_test/src/baz.dart' and 'package:freezed_test/src/foo.dart'. Try removing the export of one of the libraries, or explicitly hiding the name in one of the export directives.

## second attempt
I tried to use `@Implements` but with a `freezed class` as below

<details>
<summary>code sample w/ @implement</summary>

```dart 
import 'package:freezed_annotation/freezed_annotation.dart';
part 'success.freezed.dart';

@freezed
abstract class Success<T> with _$Success {
  const factory Success(T result) = _Success;
}
```

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'success.dart';
part 'baz.freezed.dart';

@freezed
abstract class Baz<T> with _$Baz {
  @Implements(Success)
  const factory Baz.success(T result) = _BazSuccess;
}

```

you can guess how `Foo` looks like

</details>

I get the error 

> '_BazSuccess.copyWith' ('_$BazSuccessCopyWith<T, _BazSuccess<T>> Function()') isn't a valid override of '_$Success.copyWith' ('$SuccessCopyWith<dynamic, Success<dynamic>> Function()').

## alternative
 tried to extend the derive `Baz` from `Foo` [with little success](https://stackoverflow.com/questions/65309793/how-to-extend-freezed-abstact-classes)
 
 
 ##
 I do not know if it is a bug or, most likely, a mistake from my side or even a possible hint for a feature request
 thanks for the attention

**Comment by rrousselGit** [comment]
As the resume says, you cannot implement/extend freezed classes

Use a normal interface instead:

```dart
abstract class Success<T> {
  T get result;
}

@freezed
abstract class Baz<T> with _$Baz {
  @Implements('Success<T>')
  const factory Baz.success(T result) = _BazSuccess;
}
```

**Comment by iapicca** [comment]
> As the resume says, you cannot implement/extend freezed classes
> 
> Use a normal interface instead:
> 
> ```dart
> abstract class Success<T> {
>   T get result;
> }
> 
> @freezed
> abstract class Baz<T> with _$Baz {
>   @Implements('Success<T>')
>   const factory Baz.success(T result) = _BazSuccess;
> }
> ```

thank you for the answer, with the approach you suggest 
I don't think I can achieve my goal

> in a nutshell I'd like to be able to do something like
> 
> `Foo.success('') is Success` in my tests (and not only)

`Foo.success('') is Success` will always be false

maybe I'm approaching the problem from the wrong direction
is there a better way to do that?

**Comment by rrousselGit** [comment]
> Foo.success('') is Success will always be false

What do you mean?

In the code I gave, `Bar<int>() is Success<int>` is true

**Comment by iapicca** [comment]
> > Foo.success('') is Success will always be false
> 
> What do you mean?
> 
> In the code I gave, `Bar<int>.success() is Success<int>` is true

sorry... my bad :/

**Comment by iapicca** [comment]
> Use a normal interface instead:
> 
> ```dart
> abstract class Success<T> {
>   T get result;
> }
> 
> @freezed
> abstract class Baz<T> with _$Baz {
>   @Implements('Success<T>')
>   const factory Baz.success(T result) = _BazSuccess;
> }
> ```

@rrousselGit 
I get an error if I try to pass T in @implements 
I don't want to clog your issues, I updated my [stack question](https://stackoverflow.com/questions/65309793/how-to-extend-freezed-abstact-classes)

**Comment by rrousselGit** [comment]
@iapicca make sure to use a "string" instead of a "type"

My snippet was wrong, do:

```dart
@Implements.fromString('Success<T>')
```
