### ISSUE TITLE
Custom toString methods for data classes

### ISSUE THREAD

**Issue by passsy** [rrousselGit/freezed#33]
I'd love to be able to define custom `toString` methods for data classes.

```dart
@immutable
abstract class ClubId with _$ClubId {
  const factory ClubId(String value) = _ClubIdDataClass;

  @override
  String toString() {
    return 'ClubId#$value';
  }
}
```

It should skip generation of `toString` in `_$_ClubIdDataClass` and rely on the implementation in `ClubId`.

Should be only possible for `@immutable` annotated classes with one factory constructor. Alternatively with a custom `@freezedDataClass` annotation which only allows one factory constructor

**Comment by rrousselGit** [comment]
That's hardly feasible. 
The class user-defined is _implemented_ not _extended_.


The closest we can get is:

```dart
@immutable
abstract class ClubId with _$ClubId {
  const factory ClubId(String value) = _ClubIdDataClass;

  @override
  String toString() {
    return 'ClubId#$value';
  }
}
@immutable
abstract class ClubId with _$ClubId {
  const factory ClubId(String value) = _ClubIdDataClass;

  @override
  String toString() {
    return 'ClubId#$value';
  }
}@immutable
abstract class ClubId with _$ClubId {
  const factory ClubId(String value) = _ClubIdDataClass;

  @override
  String toString() {
    return 'ClubId#$value';
  }
}@immutable
abstract class ClubId with _$ClubId {
  const ClubId._();
  const factory ClubId(String value) = _ClubIdDataClass;

  @override
  String toString() {
    return 'ClubId#$value';
  }
}
```

**Comment by z-dmitri** [comment]
> That's hardly feasible.
> The class user-defined is _implemented_ not _extended_.
> 
> The closest we can get is:
> 
> ```dart
> @immutable
> abstract class ClubId with _$ClubId {
>   const ClubId._();
> ***
> ```

It looks ugly with additional 'const ClubId._();' line

What if about freezedNoToString attribute for example:

```dart
@freezedNoToString
abstract class ClubId with _$ClubId {
  const factory ClubId(String value) = _ClubIdDataClass;

  @override
  String toString() {
    return 'ClubId#$value';
  }
}
```

**Comment by rrousselGit** [comment]
That's still not feasible.

As I said, the class is implemented not extended. This doesn't allow user defined methods.

**Comment by z-dmitri** [comment]
> 
> As I said, the class is implemented not extended. This doesn't allow user defined methods.

And what about use different attribute for the different generation to extend this class as I told about?

toString methods became unreadable with lists and complex objects..

**Comment by rrousselGit** [comment]
I would very much prefer working on the readability instead.

The toString could be made to be multi-line instead

**Comment by z-dmitri** [comment]
> The toString could be made to be multi-line instead

How it could be readable with hundred items List<Item> for example?

**Comment by rrousselGit** [comment]
It can be shown last in the toString

**Comment by z-dmitri** [comment]
`list: [0, 1,..., N]` is a bit better then print big lists, however it could be big objects where could be nice toString just Id or some short info

**Comment by rrousselGit** [comment]
Closing in favor of #83
