### ISSUE TITLE
Create Utilities for Intellij

### ISSUE THREAD

**Issue by Tinhorn** [rrousselGit/freezed#332]
**Describe what scenario you think is uncovered by the existing examples/articles**
I added live templates for IntelliJ so you can create boilerplate code faster
https://github.com/Tinhorn/freezed_intellij_live_templates

**Describe why existing examples/articles do not cover this case**
The utility section contains a utility for VSCode, not IntelliJ

**Additional context**
I have a repo with instructions here:
https://github.com/Tinhorn/freezed_intellij_live_templates
Let me know what I can do to make it better.
Thanks for the package.
It has been a great help.

Merry Christmas

**Comment by rrousselGit** [comment]
Hello! Sorry for the delay.

Feel free to open a pull-request to add your template to the readme
