### ISSUE TITLE
extending an abstract class documentation ambiguity

### ISSUE THREAD

**Issue by aytunch** [rrousselGit/freezed#336]
The `extends` keyword is nowhere to be found in the code snippet. Is it missing or is the documentation misleading? I am trying to write a Freezed class which extends an abstract class if possible.

> This is because by default, Freezed has no way of "extending" the class and instead "implements" it.
> 
> To fix it, we need to give Freezed a way to use that extends keyword.
> To do so, we have to define a single private constructor as such:
> 

```
@freezed
abstract class Person implements _$Person { // uses implements instead of with
  const Person._(); // Added constructor
  const factory Person(String name, {int age}) = _Person;

  void method() {
    print('hello world');
  }
}
```

**Comment by noobloser** [comment]
I agree that it can be viewed as a little misleading, as the case specifically describes the extending in the sense of functionality and not class extention.
Adding an example for a case with "with" and "implements" together might help:

```
@freezed
abstract class Tester with AC implements _$Tester { // with would work with abstract classes and mixins
  factory Tester(int value) = TesterT;
}

abstract class AC {
  int value;
}
```
