### ISSUE TITLE
Add riverpod's StateNotifier `change` method code generation (like `copyWith`)

### ISSUE THREAD

**Issue by rodion-m** [rrousselGit/freezed#339]
I'm using `freezed` + `riverpod`. At the moment freezed is used only in state model, but I also want to use it in `StateNotifier` for easier update state field(s).
So, I suggest to add an additional code generator for `StateNotifier`, it'll be very useful to laconic state changing.
Here is a short example:
Model:
```dart
@freezed
abstract class Model with _$Model {
  factory Model({String name, String caption}) = _Model;
}
```
StateNotifier:
```dart
class Notifier extends StateNotifier<Model> {
  Notifier() : super(_initialValue);
  static final Model _initialValue = Model(name: 'Sample', caption: 'Example');

  void change({String? name, String? caption}) {
    state = Model(name ?? state.name, caption ?? state.caption);
  }
}
```
So, now we can change state from widget simply like this:
```dart
context.read(provider).change(caption: 'New caption')
```

**Comment by rrousselGit** [comment]
Hello!

I'm not quite sure what this is about.
Maybe you want a setter instead?

```dart
notifier.state = notifier.state.copyWith(
  name: 'John',
);
```

**Comment by rodion-m** [comment]
> Hello!
> 
> I'm not quite sure what this is about.
> Maybe you want a setter instead?
> 
> ```dart
> notifier.state = notifier.state.copyWith(
>   name: 'John',
> );
> ```
Hi! Yes, something like that , but by a more convenient way, using one inline method: `notifier.change(name: 'John')`.  It's a suggestion to implement, I think it should be useful.

**Comment by smiLLe** [comment]
@rodion-m 
What about this?
```dart
class Notifier extends StateNotifier<Model> {
  Notifier() : super(_initialValue);
  static final Model _initialValue = Model(name: 'Sample', caption: 'Example');

  void reduce(Model cb(Model model) {
     state = cb(state);
  }
}
```

**Comment by rodion-m** [comment]
@smiLLe Hi! And call it like this? `context.read(provider).change((update) => update.copyWith(name: "Jane"))`

Yes, actually it's a good workaround. Thank you!

**Comment by rrousselGit** [comment]
It seems that this was answered, so I'll close this
