### ISSUE TITLE
Add let function like in Kotlin to map models

### ISSUE THREAD

**Issue by Maksimka101** [rrousselGit/freezed#341]
**Is your feature request related to a problem? Please describe.**
It is very cool that I can map freezed union classes but I also want to do this with freezed classes. As I think this is common situation when you need map your model. Or map if not null otherwise return the default value. 

Example of situation when `let` function would be useful:
```dart
@freezed
abstract class Person with _$Person {
  const factory Person({
    String name,
    PersonInfo info,
  }) = _Person;
}

@freezed
abstract class PersonInfo with _$PersonInfo {
  const factory PersonInfo({
      DateTime date,
      int age,
  }) = _PersonInfo;
}

void workWithString(String s) { ... }
String dateToString(DateTime date) { ... }

/// I want to map person's date to string with [dateToString] and directly pass it as argument to [workWithString] function
workWithString(person?.info?.date != null ? dateToString(person.info.date) : 'defaultStr');
``` 

**Describe the solution you'd like**
How can I do the same thing but with `let` function:

```dart 
workWithString(person?.info?.date?.let((date) => dateToString(date)) ?? 'defaultStr');
```

Also I can do some very complex things. For example:
```dart
/// load person with [getPerson] and then map complex person's info to string
workWithString(getPerson()?.let((person) => person.info?.let((info) => "age is ${info.age}. date is ${info.date}. ") ?? 'no info' + person.name?.let((name) => "name is $name") ?? 'no name') ?? 'person is null');
```

**Describe alternatives you've considered**
As alternative of `let` method I can write extension on Object.
```dart
extension Let on Object {
  T let<T, K>(T Function(K it) map) => map(this as K);
}
```
But I ran into a few problems with this variant:
 - I can't use auto import with extension methods
 - I must specify T and K to have idea's suggestions

**Comment by nexron171** [comment]
why 'let' and not 'map'?

**Comment by grino-studio** [comment]
Because map is for union classes and collections but here we deal with a mapping of single object

**Comment by Maksimka101** [comment]
Because map is used for union types an collections. Also let is well known function

**Comment by rrousselGit** [comment]
This is definitely a use-case for extensions instead.

This isn't something Freezed can do.

**Comment by rrousselGit** [comment]
Closing as there is nothing Freezed can do
