### ISSUE TITLE
Non-creatable and non-updatable propery

### ISSUE THREAD

**Issue by aabccd021** [rrousselGit/freezed#343]
**Is your feature request related to a problem? Please describe.**
One of my usage for data class is non-creatable and non-updatable property.
Following is example for `Tweet` data class in `tweet.dart`.
```dart
class Tweet {
  final String id;
  final DateTime time;
  final String text;

  Tweet({
    this.id,
    this.text,
  }) : time = null;

  Tweet.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        text = json['text'],
        time = json['time'];

  Tweet._({
    this.id,
    this.time,
    this.text,
  });

  Tweet copyWith({String text}) {
    return Tweet._(
      id: this.id,
      time: this.time,
      text: text ?? this.text,
    );
  }
}
```
With above implementation, outside of file `tweet.dart`, we can't assign property `time` when it's created through public constructor, and we can't update (copy) property `id`. In my project, such property `time` is categorized as non-creatable property, and `id` is categorized as non-updatable property.
I think we can't achieve this kind of behaviour using current version of freezed.

**Describe the solution you'd like**
Best solution I can think right now is using annotation.
```dart
@freezed
abstract class Tweet with _$Tweet {
  const factory Tweet({
    @Nonupdatable String id,
    @Noncreatable DateTime time,
    String text,
  }) = _Tweet;
}
```
Can we implement this, technically speaking?

**Comment by rrousselGit** [comment]
This is not supported at the moment by Freezed

Is that really useful? After all, you could simply not use the parameter
