### ISSUE TITLE
Ability to change .freezed.dart file name.

### ISSUE THREAD

**Issue by ravish-tech** [rrousselGit/freezed#349]
I think `.freezed.dart` `part` file name is distinctive for sure but not something I prefer as generated file name. Specially when mixing with other packages that generate file and we now we have 3 files. Main, `.freezed.dart` and `.g.dart`. 

Most of the generators generate `.g.dart` file and I have file nesting configurations on my IDEs to nest these for better dev experience.

Firstly it would be great to know from the author why he choose to create it this way. Was there any reason?
Secondly if we can please have it as configurable? Say from pubspec.yaml file?

Thanks.

**Comment by rrousselGit** [comment]
Freezed isn't using `.freezed.dart` instead of `.g.dart` for distinction, but because it is necessary for Freezed to work.

It is not possible to use `.g.dart` _and_ have Freezed work with `json_serializable`.
