### ISSUE TITLE
Nice project name…

### ISSUE THREAD

**Issue by freezed** [rrousselGit/freezed#35]
… but I hope that I will not be notified everyday as today :wink:

**Comment by smiLLe** [comment]
bad luck brian here. hahaha

**Comment by rrousselGit** [comment]
Next step: Make a project named `smiLLe` 😄

**Comment by smiLLe** [comment]
ughhh. please don't let it be some kind of state management lib :(

**Comment by freezed** [comment]
Have fun people :wink:
