### ISSUE TITLE
Ignore generating special factory 

### ISSUE THREAD

**Issue by II11II** [rrousselGit/freezed#359]
**Is your feature request related to a problem? Please describe.**
I would like to implement my fromJson and toJson methods and implementing there my own logic
**Describe the solution you'd like**
It would be great if we had @ignore annotation to ignore  creation class  for this type

**Comment by rrousselGit** [comment]
You don't need anything. Freezed will not generate a fromJson/toJson if you're writing your own.

**Comment by II11II** [comment]
Hi @rrousselGit ,
Thank you for attention,
It gives me error when i write fromJson and toJson
![image](https://user-images.githubusercontent.com/45257709/107257640-b3bd5f80-6a5c-11eb-8d18-030d09d64caa.png)

**Comment by II11II** [comment]
![Uploading image.png…]()

**Comment by II11II** [comment]
![image](https://user-images.githubusercontent.com/45257709/107257759-d94a6900-6a5c-11eb-9b5c-de6014d4f6d6.png)

**Comment by rrousselGit** [comment]
You need to have an empty `MyClass._();` constructor
