### ISSUE TITLE
Ability to declare union key value for factory constructor

### ISSUE THREAD

**Issue by KieranLafferty** [rrousselGit/freezed#360]
Not sure if this already exists or not but from my experience the unionKey value for a union class constructor is determined by the part that comes after the base class name  (i.e. `SomeClass.fooBar(...)` would produce a union key value of `"fooBar"`. 

Is it possible to override the value for the union key? I've done this in the past by naming the constructor to match what I need it to output as i.e. `SomeClass.foo_bar(...)` to produce `foo_bar` but kind of a hack and doesn't allow for special characters. 

Essentially what I'm looking for is some annotation that would allow me to declare what the unionKey is for each factory constructor explicitly

Thank you for all of the effort you put into this awesome package don't know what I'd do without it!

**Comment by rrousselGit** [comment]
There's nothing like that at the moment. But that sounds like a useful feature.

**Comment by ookami-kb** [comment]
Hi @rrousselGit, we need this feature as well.

I can take the issue, if you're not planning to work on it in the near future.

**Comment by rrousselGit** [comment]
Sure go ahead :smile:

**Comment by KieranLafferty** [comment]
Thanks @ookami-kb!
