### ISSUE TITLE
difference between $default and orElse: in maybeWhen?

### ISSUE THREAD

**Issue by tiloc** [rrousselGit/freezed#362]
**Describe what scenario you think is uncovered by the existing examples/articles**
I do not understand the difference between the mandatory $default parameter and the optional orElse: in maybeWhen? I try to use the new null-safe freezed 0.13.0-nullsafety and I can no longer specify null for the $default which is being used in all the example code. What should I specify instead? Will it become a nullable parameter again?

**Describe why existing examples/articles do not cover this case**
I was unable to locate any related articles through Google search.

**Additional context**
n.a.

**Comment by rrousselGit** [comment]
What mandatory "$default" are you talking about? There is no such parameter

**Comment by tiloc** [comment]
I am using this code to create a sealed union to act as a state in my Bloc/Cubit:
```
@freezed
abstract class CouplingState with _$CouplingState {
  const factory CouplingState() = Uncoupled;

  const factory CouplingState.capturing() = Capturing;

  const factory CouplingState.captureFailure(String message) = CaptureFailure;

  const factory CouplingState.coupling() = Coupling;

  const factory CouplingState.coupled() = Coupled;

  const factory CouplingState.failure(String message) = Failure;
}

```

This is resulting in the following code being generated by freezed:
```
  @optionalTypeArgs
  TResult maybeWhen<TResult extends Object?>(
    TResult Function()? $default, {
    TResult Function()? capturing,
    TResult Function(String message)? captureFailure,
    TResult Function()? coupling,
    TResult Function()? coupled,
    TResult Function(String message)? failure,
    required TResult orElse(),
  });

```

The $default parameter is a mandatory, nullable positional parameter and the orElse is a required named parameter.

Up to now (pre-null-safety) I have simply set the $default to `null` and only specified the orElse. But now with null-safety I have to cast the `null` to a very lengthy definition and I never fully understood the difference between the two, I started out with a tutorial which suggested this pattern.
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(child:
          BlocBuilder<CouplingCubit, CouplingState>(builder: (context, state) {
        return state.maybeWhen(
          null as Widget Function(),
          coupled: () => _buildMainScreen(context),
          orElse: () => _buildQrCodeCapture(),
        );
      })),
    );
  }
```

**Comment by rrousselGit** [comment]
$default represents the default constructor (which has no name, so freezed uses a positional "$default" arg)
