### ISSUE TITLE
@required not recognized?

### ISSUE THREAD

**Issue by tiloc** [rrousselGit/freezed#363]
**Describe the bug**
I am running the code as listed below through build_runner. A parameter which has @required is rejected as not being required nor having a default.

**To Reproduce**
I am processing the following code with `flutter pub run build_runner build --delete-conflicting-outputs`
My freezed_annotation is at 0.13.0-nullsafety.0

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'synched_resource.freezed.dart';
part 'synched_resource.g.dart';

enum SynchStatus {
  ClientUnconfirmed, // resource exists only in client app and user needs to confirm its validity
  ClientDiscarded, // resource has been discarded by user
  ClientOnly, // resource only exists on client app
  ServerOnly, // resource only exists on server
  ClientServer, // resource is successfully synched between client and server
  Uploading, // Resource is currently in process of being uploaded to server
  Downloading, // Resource is currently in process of being downloaded from server
  Failed, // Exchange with server failed
  FailedPermanently, // Exchange with server failed and no re-attempts will be tried
}

@freezed
abstract class SynchedResource with _$SynchedResource {
  static final noUploadAttempt = DateTime.fromMicrosecondsSinceEpoch(0);

  const factory SynchedResource(
      { // Do not move the lines below
      @required lastUploadAttempt,
      @required countUploadAttempts,
      @required code,
      @required resource,
      @required hash,
      @required effectiveDate,
      @required synchStatus,
      @required resourceType}) = _SynchedResource;

  factory SynchedResource.fromJson(Map<String, dynamic> json) =>
      _$SynchedResourceFromJson(json);
}
```

I am getting the following output:
[WARNING] freezed:freezed on lib/modules/observations/database/synched_resource.dart:
Error The parameter `lastUploadAttempt` of `SynchedResource` is non-nullable but is neither required nor marked with @Default
package:flutter_healthcare/modules/observations/database/synched_resource.dart:24:17
   ╷
24 │       @required lastUploadAttempt,
   │                 ^^^^^^^^^^^^^^^^^
   ╵
[WARNING] freezed:freezed on lib/modules/observations/database/synched_resource.dart:
#0      FreezedGenerator._assertValidUsage (package:freezed/src/freezed_generator.dart:122:13)
#1      FreezedGenerator.parseElement (package:freezed/src/freezed_generator.dart:51:5)
#2      ParserGenerator.generate (package:freezed/src/parse_generator.dart:38:28)
<asynchronous suspension>
#3      _generate (package:source_gen/src/builder.dart:338:23)
<asynchronous suspension>
#4      Stream.toList.<anonymous closure> (dart:async/stream.dart)
<asynchronous suspension>

[SEVERE] freezed:freezed on lib/modules/observations/database/synched_resource.dart:

The parameter `lastUploadAttempt` of `SynchedResource` is non-nullable but is neither required nor marked with @Default
package:flutter_healthcare/modules/observations/database/synched_resource.dart:24:17
   ╷
24 │       @required lastUploadAttempt,
   │                 ^^^^^^^^^^^^^^^^^
   ╵

**Expected behavior**
I am expecting this to run successfully and to generate a required parameter. I was not sure about null-safety, therefore I also tried `required` instead of `@required`. But that is leading to duplicate output of `required` into the generated source.

**Comment by rrousselGit** [comment]
You're using the null-safety version.

With null-safety, you shouldn't use `@required` anymore. Instead use the `required` keyword:

```dart
factory MyClass({
  required name,
}) = _MyClass;
```

**Comment by tiloc** [comment]
I will try that again. It resulted in faulty code output when I first tried that. It would output "required required variablename" into the generated code.

**Comment by tiloc** [comment]
@rrousselGit I think it was ultimately that I had forgotten the data type. If I go with "required name", it will generate
 code that will read "required required name". I am now doing "required String name" and it works flawlessly.
BTW: Is there a before/after comparison for null-safety? For which things do I still have to use special freezed annotations and where can I simply use plain Dart? Is `@nullable` obsolete now and replaced by plain`?`.
