### ISSUE TITLE
freezed generator not working 

### ISSUE THREAD

**Issue by WahdanZ** [rrousselGit/freezed#365]
**Describe the bug**
freezed generator not working 

`
@freezed
abstract class LoginState with _$LoginState {
  const factory LoginState(int value) = Data;
  const factory LoginState.loading() = Loading;
  const factory LoginState.error([String message]) = ErrorDetails;
}

`
**To Reproduce**
I got this error after I run  Flutter pub run build_runner build
`
Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../flutter/.pub-cache/hosted/pub.dartlang.org/freezed-0.12.7/lib/src/freezed_generator.dart:532:36: Error: The getter 'late' isn't defined for the class 'FieldElement'. - 'FieldElement' is from 'package:analyzer/dart/element/element.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.40.6/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'late'.    return TypeChecker.fromRuntime(late.runtimeType).hasAnnotationOf(                                   ^^^^../../../flutter/.pub-cache/hosted/pub.dartlang.org/freezed-0.12.7/lib/src/templates/concrete_template.dart:361:36: Error: The getter 'nullable' isn't defined for the class 'Element'. - 'Element' is from 'package:analyzer/dart/element/element.dart' ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.40.6/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'nullable'.    return TypeChecker.fromRuntime(nullable.runtimeType)                                   ^^^^^^^^
pub finished with exit code 78
`

**Comment by hayashi-ay** [comment]
Perhaps it would because of the mismatch of version of freezed and freezed_annotation. If you use the null-safety version of freezed_annotation, you need to use null-safety version of freezed as well.

**Comment by WahdanZ** [comment]
yes, thanks
