### ISSUE TITLE
@Default() should override the defaultValue or custom @JsonKey annotations

### ISSUE THREAD

**Issue by nvshah** [rrousselGit/freezed#367]
### **_Describe the bug_**

Assume that **field**/**param** of freezed class is provided with annotation combinations of ```@Default()``` &  ```@JsonKey()```
i.e
  
> ```...```
> 
> ```@Default(v)```
  ```@JsonKey(name:'n') ```(i.e *without ```defaultValue``` argument*)
  ```String fieldName,```
>
> ```...```

➤ Aforementioned scenario is resulting with an exception when _json-key_ with name 'n' is missing in json object.
 
NOTE: 
It has been observed that if ```@JsonKey()``` is omitted while defining in above case, then ```@JsonKey()``` annotation is implicitly created with ```defaultValue``` for corresponding property in generated class (*as mentioned in [doc](https://pub.dev/packages/freezed#default-values)*) 

i.e In generated class (when @JsonKey() is omitted while defining)
> ```...```
>
> ```@override```
  ```@JsonKey(defaultValue: v)```
  ```String get fieldName;```
>
> ```...```

### **_To Reproduce_**

NOTE : (below snippets are partial-content files but include relevant LOC pertaining to understand)

1] anime.dart

```dart

//...

@freezed
abstract class Anime with _$Anime {
  const factory Anime({
    @JsonKey(name: 'ninja') @Default('naruto') String name,
  }) = _Anime;

  factory Anime.fromJson(Map<String, dynamic> json) => _$AnimeFromJson(json);
}

//...

```

2] anime.freezed.dart (*_generated_) 
  
```dart
//...

abstract class _Anime implements Anime {
  const factory _Anime({@JsonKey(name: 'ninja') String name}) = _$_Anime;

  factory _Anime.fromJson(Map<String, dynamic> json) = _$_Anime.fromJson;

  @override
  @JsonKey(name: 'ninja')
  String get name;
  @override
  @JsonKey(ignore: true)
  _$AnimeCopyWith<_Anime> get copyWith;
}

//...

class _$_Anime implements _Anime {
  const _$_Anime({@JsonKey(name: 'ninja') this.name = 'naruto'})
      : assert(name != null);

   //... neglecting rest part
}

//...
```
> NOTE : Although ```@Default('naruto')``` was declared in _anime.dart_, ```@JsonKey(name: 'ninja')``` misses ```defaultValue``` parameter having ```"naruto"``` as value, 

3] anime.g.dart (*_generated_) 

  
```dart
//...

_$_Anime _$_$_AnimeFromJson(Map<String, dynamic> json) {
  return _$_Anime(
    name: json['ninja'] as String,
  );
}

//...
```
> NOTE : null check (i.e ??) is absent during evaluating ```name``` field.

➤ If in json object, ```'ninja'``` key is unavailable, then ```name``` will hold ```null``` which contradicts with assertion. i.e ```assert(name!=null)```

### **_Expected behavior_**

> if ```@Default()``` annotation is defined for a field
> & at same time
> if ```@JsonKey()``` annotation is defined too but without ```defaultValue``` for the same field,
> then -> generated @JsonKey() might consider value of @Default() as a source for it's ```defaultValue``` argument  

So expected alteration in behaviour in same eg would be :-

in generated ```<fname>.freezed.dart``` file's ```_DataClass``` 
```dart 
@JsonKey(defaultValue: 'naruto', name: 'ninja',)
@override
String get name;
```
i.e

2] anime.freezed.dart (expected after generation*) 
  
```dart
//...

abstract class _Anime implements Anime {
  const factory _Anime({@JsonKey(name: 'ninja') String name}) = _$_Anime;

  factory _Anime.fromJson(Map<String, dynamic> json) = _$_Anime.fromJson;

  @override
  @JsonKey(defaultValue: 'naruto', name: 'ninja',)
  String get name;
  @override
  @JsonKey(ignore: true)
  _$AnimeCopyWith<_Anime> get copyWith;
}

//...
```

NOTE :

✔️  If ```@JsonKey()``` annotation is provided with ```defaultValue``` then that defaultValue's __value__ will be accounted.

but if ```@JsonKey()``` annotation is provided without defaultValue, and at same time if ```@Default()``` annotation also exist then whether ```@JsonKey()```  should accounts ```@Default()```'s value ⁉️

**Comment by rrousselGit** [comment]
This is the expected behavior.

If you pass a `@JsonKey`, this annotation takes over the default annotation.

As such do `@Default(value) @JsonKey(whatever, defaultValue: value)`

**Comment by nvshah** [comment]
Aye I see,

Thanks for the update.

Actually I was musing that if it can be enhanced/modified (since there is probability of exception) :- 

-> i.e Intercept the property before finalizing it.

```dart 
//PSEUDO CODE

if (defaultValue_exists){
   if(Annotation_JsonKey_not_exists){
      //create new @JsonKey() which is currently adopted.
   }
  else {
     if(Argument_defaultValue_not_exists_in_JsonKey){
        //TODO: add ( defaultValue: value ) argument pair in JsonKey
     }
  }
```
    

If  ```@JsonKey``` takes over default annotation, it can be intercepted & check if defaultValue misses, in which case ```defaultValue: value```  pair can be added by taking into account ```@Default```'s value.

**Comment by nvshah** [comment]
Just attempted one approach for aforementioned enhancement :
[commit reference](https://github.com/nvshah/freezed/commit/85756b151448476a23898256d810931ff507755f)

> gist :
> If defaultValue misses in ```@JsonKey``` annotation then look-up for ```@Default``` annotation
