### ISSUE TITLE
Upgrade analyzer version to 1.1.0 

### ISSUE THREAD

**Issue by theweiweiway** [rrousselGit/freezed#368]
Hi @rrousselGit,

I'm using freezed ^0.13.0-nullsafety.2 in conjunction with the `injectable` package (version 1.2.0-nullsafety) which depends on analyzer 1.1.0

Just wondering what kind of timeline you were thinking of for upgrading analyzer

Thanks Remi!

**Comment by FogNature** [comment]
I have same issue using freezed ^0.14.0-nullsafety.0
