### ISSUE TITLE
Template Union not forwarding Types to methods

### ISSUE THREAD

**Issue by TylerR909** [rrousselGit/freezed#373]
**Describe the bug**

If I create a template Union type, such as `Loadable<T>`, subsequent calls to `.when`, `.map`, etc are not forwarded `T`.

**To Reproduce**

```dart
class User {}

abstract class Loadable<T> with _$Loadable {
  const factory Loadable.loaded(T loaded) = _Loaded;
  const factory Loadable.loading({T initial}) = _Loading;
  const factory Loadable.error() = _Error;
}

Loadable<User>.loading(
  initial: User(), // {User initial}
).when(
  loaded: (dynamic loaded) {}, // Expected: {Function(User) loaded}
  loading: (dynamic initial) {}, // Expected: {Function(User) loading}
  error: () {}, // {Function() error}
)
```

**Expected behavior**
In the above case, if I create a `Loadable<User>` then I should see the `User` type in subsequent calls like this: `loadable.when(loaded: (User loaded) {}, …);`

<details><summary>Use Case</summary>

I'm creating some custom streams for development ahead of Backend integration. Everything seemed to work until a Provider reached up and couldn't find my class, because it was obfuscated under `dynamic`.

```dart
    return StreamBuilder<Loadable<Collection>>(
      stream: collectionService.watchOneCollection(selectedCollection),
      initialData: Loadable.loading(initial: selectedCollection),
      builder: (context, snapshot) {
        // snapshot.data is Loadable<Collection>
        return snapshot.data.when(
            loaded: (collection) => Provider.value(
                  value: collection, // <-- dynamic, not Collection
                  child: _CollectionScreen(),
                ),
            loading: (initial) => LoadingScaffold(
                  title: initial.name as String,
                ),
            error: () { /* handle errors, pop stack */ });
      },
```

In order for this to work for downstream consumers, I have to cast: `value: collection as Collection`. I also need to cast `initial.name` to String for it to work. 

</details>

**Comment by rrousselGit** [comment]
The correct syntax is:

```dart
abstract class Loadable<T> with _$Loadable {
  const factory Loadable.loaded(T loaded) = _Loaded<T>;
  const factory Loadable.loading({T initial}) = _Loading<T>;
  const factory Loadable.error() = _Error<T>;
}
```

**Comment by TylerR909** [comment]
That didn't work but it did put me on the right track.

```dart
abstract class Loadable<T> with _$Loadable<T> {
  const factory Loadable.loaded(T loaded) = _Loaded;
  const factory Loadable.loading({T initial}) = _Loading;
  const factory Loadable.error() = _Error;
}
```

Now when I call `.map`, `.when`, etc, the `loaded` and `initial` parameters are properly typed. Is there a reason I'd need `_Loaded<T>` even though it's working now? If it wasn't private, would I want `T` forwarded?

If you had to chalk my error up to one issue, what would it be? Fundamental misunderstanding of Dart? Failure to understand Freezed? Problem understanding Factory Redirects?
