### ISSUE TITLE
Are there known issues with analyser 1.0.0?

### ISSUE THREAD

**Issue by tiloc** [rrousselGit/freezed#374]
**Describe the bug**
I am using freezed and another generator in the same app. freezed requires analyzer <1.0.0. The other package wants analyzer 1.0.0. I have entered a dependency_override to use analyzer 1.1.0, and freezed seems to be fine, but is there something why I should not do that?

**To Reproduce**
see above. Put freezed and another package which requires analyzer 1.0.0 into pubspec.yaml.

**Expected behavior**
freezed can work with analyzer ^1.1.0.

**Comment by arsamme** [comment]
Please merge this pull request, The issue is annoying
