### ISSUE TITLE
Escaped single quotes lead to errors

### ISSUE THREAD

**Issue by tfvtti** [rrousselGit/freezed#379]
**Describe the bug**
Single quoted strings containing escaped single quotes causes build_runner to fail. When escaping a single quote with a back slash the back slash does not get preserved in the generated freezed file. This issue, however, is intermittent and only occurs reliably when building "many" freezed files at a time. This is highly unexpected. If I run build_runner with only one or two files which need to be regenerated then I usually do not see the error, however, if I delete all 42 freezed files ( in my case ) and run build_runner then I hit the following error: 

```
[SEVERE] freezed:freezed on lib/common/models/workzone/single_quote.dart:
An error `FormatterException` occurred while formatting the generated source for
  `package:workzone_builder_flutter/common/models/workzone/single_quote.dart`
which was output to
  `lib/common/models/workzone/single_quote.freezed.dart`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 104, column 87: Unterminated string literal.
    ╷
104 │   const _$CdSingle([ this.d = '32" tall, 24" thick and 10' long.']): assert(d != null);
    │                                                                                       ^
    ╵
line 18, column 1: Expected to find ']'.
   ╷
18 │ }
   │ ^
```

**To Reproduce**

Create the following file. Note that two default initializers are used where one value is double quoted and the other is single quoted. If I run `flutter pub run build_runner build --delete-conflicting-outputs`  the following 

```
@freezed
abstract class ChanDevType with _$ChanDevType {
  const factory ChanDevType.cdSingle([@Default("32\" tall and 10' long.") String d]) = CdSingle;
  const factory ChanDevType.cdDouble([@Default('32" tall and 10\' long.') String d]) = CdDouble;
}

const cdSingle = ChanDevType.cdSingle();
const cdDouble = ChanDevType.cdDouble();
```

**Expected behavior**
Upon further testing there are multiple different ways to cause the build_runner to fail. I can provide more examples if desired.

**Comment by iamim** [comment]
I had the same issue after upgrading to the latest version. Updating SDK constraint to `>=2.12.0 <3.0.0` (enables null-safety) resolved the issue.

**Comment by rrousselGit** [comment]
I cannot reproduce on 0.14.0

As @iamim mentioned, make sure to enable null-safety on your project (sdk >= 0.12.0)
