### ISSUE TITLE
json_serializable warnings

### ISSUE THREAD

**Issue by pblinux** [rrousselGit/freezed#38]
Hi.

First, I'm really having fun with this package, will be very useful.

Working with json_serializable, a couple of warnings appear in the g.dart, related to the linter.

```Name non-constant identifiers using lowerCamelCase.``` for FromJson and ToJson method.

This is my freezed class:

```
@freezed
abstract class Station with _$Station {
  factory Station({String description, String image, String name, String url}) =
      _Station;

  factory Station.fromJson(Map<String, dynamic> json) =>
      _$StationFromJson(json);
}
```

And the g.dart file have this:

```
_$_Station _$_$_StationFromJson(Map<String, dynamic> json) {
  return _$_Station(
    description: json['description'] as String,
    image: json['image'] as String,
    name: json['name'] as String,
    url: json['url'] as String,
  );
}

Map<String, dynamic> _$_$_StationToJson(_$_Station instance) =>
    <String, dynamic>{
      'description': instance.description,
      'image': instance.image,
      'name': instance.name,
      'url': instance.url,
    };
```
I think is adding an extra '_$'. :thinking:

**Comment by rrousselGit** [comment]
I can't do anything about it.

Consider:
- ignoring them
- asking `json_serializable` to add an `ignore_for_file` for this (and `prefer_const_constructors ` too)
- ask dart-lang/lint to fix these false positive

**Comment by pblinux** [comment]
Ok @rrousselGit, thank you.

**Comment by julienlebren** [comment]
I was looking for a solution for this because I hate to see 'Problems' in my IDE 🙄

Here is a fix (an ignore, in fact):

1) Add this to your `pubspec.yaml`
```yaml
dev_dependencies:
  lints: ^1.0.1
```

2) Create a file named `analysis_options.yaml` at the root of your project (same folder as `pubspec.yaml`) and add this:
```yaml
include: package:lints/recommended.yaml

linter:
  rules:
    non_constant_identifier_names: false
```

The error `Name non-constant identifiers using lowerCamelCase.`  won't be shown anymore.

Also, to go further, when using Freezed, you can also add `
    avoid_single_cascade_in_expression_statements: false` in your linter rules.

**Comment by SunlightBro** [comment]
@julienlebren 
Instead of weakening your static analysis by disabling rules, consider just excluding generated files:
[ignore-lint-warnings-on-generated-files](https://pub.dev/packages/freezed#ignore-lint-warnings-on-generated-files)

**Comment by derpda** [comment]
For those wondering, the link that @SunlightBro posted no longer fully works, and the current version of the freezed `README.md` seems to longer container the relevant information.
Here is [a working link](https://pub.dev/packages/freezed/versions/0.14.4#ignore-lint-warnings-on-generated-files). The solution is to add
```
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
```
to `analysis_options.yaml`
