### ISSUE TITLE
Add an annotation to select what I want to build

### ISSUE THREAD

**Issue by gabrielvictorjs** [rrousselGit/freezed#389]
Sometimes I don't want my sealed classes to have the copyWith method.

I think there could be an annotation to select which methods I want for my class.

**Comment by rrousselGit** [comment]
What is the issue with `copyWith` being generated? Why wouldn't you want it, even if you're not using it?

**Comment by gabrielvictorjs** [comment]
> What is the issue with `copyWith` being generated? Why wouldn't you want it, even if you're not using it?

I usually use sealed classes for error mapping and sometimes I wouldn't like to generate copy with for example. I think that the code generated would be clearer. But it's not a problem, just a suggestion! :)

**Comment by rrousselGit** [comment]
That adds quite a bit of complexity to the generator for little

Unless there's a clear reason to not generate those functions, I don't think that's a good idea.
