### ISSUE TITLE
@DefaultValue should not generate assert.

### ISSUE THREAD

**Issue by vadrian89** [rrousselGit/freezed#394]
**Describe the bug**
Hello.
Assert is generated where fields have @DefaultValue which is counter productive as it throws exceptions in debug mode for no reason. The point of having a default value is to have a value when none (null) are provided.

A small example
```
factory ProductModel({
    @Default(0.00) double buyPrice,
    @Default(0.00) double salePrice,
 }) = _ProductModel;
```

This generates: 
```
class _$_ProductModel extends _ProductModel with DiagnosticableTreeMixin {
  _$_ProductModel({
      this.buyPrice = 0.0,
      this.salePrice = 0.0,
      }): assert(buyPrice != null),
        assert(salePrice != null),
        super._();
// -------------------------------
}
```
**Expected behavior**
assert should be generated only for those fields which are marked required or with Assert annotation.

**Comment by rrousselGit** [comment]
This is expected

Do:

```dart
factory ProductModel({
  @Default(.0) @nullable double buyPrice,
}) = _ProductModel;
```
