### ISSUE TITLE
Unable to default a field value to anything

### ISSUE THREAD

**Issue by danallen88** [rrousselGit/freezed#395]
Apologies if this is a misuse of the library.  I'm not able to default a value to a non-null value because the `@Default` annotation is currently broken with this library.

I tried to workaround it as follows: If I have a getter with the same name as one of the fields of the freezed class, my custom getter logic is never invoked when accessing the property.  If I use a name that does not appear as a field name, the custom logic is invoked [as outlined here](https://pub.dev/packages/freezed#custom-getters-and-methods).

```bash
Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (11 days ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

```yaml
dependencies:
    freezed_annotation: ^0.12.0
```

**To Reproduce**

```dart
part 'test.freezed.dart';

@freezed
abstract class Test with _$Test {

  Test._();

  factory Test({
    @nullable String name,
  }) = _Test;

  String get name => name ?? '';
}
```

**Expected behavior**
```dart
test('null name returns empty string', () {
    var test = Test();
    expect(test.name, '');
});
```
This test fails because `test.name` is null.

If I instead try:
```dart
part 'test.freezed.dart';

@freezed
abstract class Test with _$Test {

  Test._();

  factory Test({
    @nullable @Default('') String name,
  }) = _Test;
}
```

This test also fails.

**Comment by rrousselGit** [comment]
> If I instead try:
> 
> ```dart
> part 'test.freezed.dart';
> 
> @freezed
> abstract class Test with _$Test {
> 
>   Test._();
> 
>   factory Test({
>     @nullable @Default('') String name,
>   }) = _Test;
> }
> ```
> 
> This test also fails.

Why does this fail?

**Comment by danallen88** [comment]
> Why does this fail?

If I change my freezed class to use those annotations instead, as I assume they're intended to be used, the unit test I referenced above fails.  It claims that `name` is null and not the empty string.

**Comment by rrousselGit** [comment]
The test is passing for me, using 0.14.0

**Comment by danallen88** [comment]
Thanks for the reply, Remi.  I'm not able to upgrade right now because of other project dependencies, but as soon as I get the chance I'll verify.  Sounds like perhaps this is just an issue with the version of freezed I have (0.12.0)

**Comment by danallen88** [comment]
Hi @rrousselGit, just wanted to say we were able to migrate to null-safety (and therefore upgrade to 0.14.2) and I am no longer experiencing this issue.  Closing this issue.
