### ISSUE TITLE
Unable to add @required for a field

### ISSUE THREAD

**Issue by hramnathnayak** [rrousselGit/freezed#396]
**Describe the bug**
I am unable to add the @required annotation to a field. Is this the right way to do it with freezed ?

```
@freezed
class LoginRequest with _$LoginRequest {
  const factory LoginRequest({@required String username,@required String password}) = _LoginRequest;
  factory LoginRequest.fromJson(Map<String, dynamic> json) =>_$LoginRequestFromJson(json);
}
```

I get below error with build runner that says the field is neither marked required nor marked @Default, but i do have it marked @required as you see above. what am i missing?
I am using freezed: ^0.14.1, json_serializable: ^4.0.2, build_runner: ^1.10.11

```
The parameter `username` of `LoginRequest` is non-nullable but is neither required nor marked with @Default
package:freezed_required_demo/login_request.dart:22:22
   ╷
22 │     @required String username,
   │                      ^^^^^^^^
   ╵
```

**Comment by SunlightBro** [comment]
> I am using freezed: ^0.14.1, json_serializable: ^4.0.2, build_runner: ^1.10.11

I assume you want to use Dart 2.12 with null-safety, check out the documentation of [dart](https://dart.dev/null-safety/faq#how-does-required-compare-to-the-new-required-keyword).
As of Dart 2.12, the `required` keyword replaces the `@required` meta annotation.

```dart
@freezed
class LoginRequest with _$LoginRequest {
  const factory LoginRequest({required String username, required String password}) = _LoginRequest;
  factory LoginRequest.fromJson(Map<String, dynamic> json) =>_$LoginRequestFromJson(json);
}
```
If you don't want to migrate yet, use `freezed: 0.12.7`

**Comment by hramnathnayak** [comment]
Ah.. thats what i was missing with the 2.12. Thank you !
