### ISSUE TITLE
Upgrade to latest pkg:build

### ISSUE THREAD

**Issue by 2shrestha22** [rrousselGit/freezed#397]
With `json_serializable 4.0.3` and `freezed 0.14.1`, `flutter pub get` gives error.

```
Because json_serializable >=4.0.3 depends on build ^2.0.0 and freezed 0.14.1 depends on build ^1.6.0, json_serializable >=4.0.3 is incompatible with freezed 0.14.1.
And because no versions of freezed match >0.14.1 <0.15.0, json_serializable >=4.0.3 is incompatible with freezed ^0.14.1.
So, because voiceofblessings depends on both freezed ^0.14.1 and json_serializable ^4.0.3, version solving failed
```

`source_gen` have upgraded 10 hrs ago, - https://github.com/dart-lang/source_gen/pull/517

**Comment by 2shrestha22** [comment]
Duplicate of #391

**Comment by kim-mini6** [comment]
I have the same problem.

Is there a solution?

**Comment by rrousselGit** [comment]
use a version of json_serializable lower than `4.0.3`

I will upgrade the dependency later this week.

**Comment by rrousselGit** [comment]
More specifically, use `^4.0.0` as version constraints instead of `^4.0.3`

That should allow pub to use a compatible json_serializable version.
