### ISSUE TITLE
Union case mapper based on type only

### ISSUE THREAD

**Issue by aloisdeniel** [rrousselGit/freezed#400]
## Is your feature request related to a problem? Please describe.

I would like to optimize rebuilds regarding the current union case.

An example when mapping a state to a widget :

```dart
 @override
  Widget build(BuildContext context) {
    return StoreConnector<RootState, ChildState>(
      converter: (store) => store.state.child,
      builder: (context, assignDevice) => assignDevice.map(
        error: (error) => ErrorView(),
        result: (result) => ResultView(),
      ),
    );
  }
```

The issue is that this widget is rebuilt even when the `result` value changes but the only needed rebuilds are when the union case changes.

## Describe the solution you'd like

I don't really know an ideal solution, maybe a `Case` generated class that would only rely on the case and not on its value : 

```dart
 @override
  Widget build(BuildContext context) {
    return StoreConnector<RootState, ChildStateCase>(
      converter: (store) => store.state.child.case,
      builder: (context, assignDevice) => assignDevice.map(
        error: () => ErrorView(),
        result: () => ResultView(),
      ),
    );
  }
```

## Describe alternatives you've considered

To solve the issue I had to write an wrapper class that compares the runtime types instead of their actual values :

```dart
class TypeComparisonMapper<T> {
  const TypeComparisonMapper(this.value);

  final T value;

  @override
  bool operator ==(dynamic other) {
    return other is TypeComparisonMapper<T> &&
        value?.runtimeType == other.value?.runtimeType;
  }

  @override
  int get hashCode => value?.runtimeType.hashCode ?? 0;
}
```

And use it this way :

```dart
 @override
  Widget build(BuildContext context) {
    return StoreConnector<RootState, TypeComparisonMapper<ChildState>>(
      converter: (store) => TypeComparisonMapper(store.state.child),
      builder: (context, assignDevice) => assignDevice.value.map(
        error: (error) => ErrorView(),
        result: (result) => ResultView(),
      ),
    );
  }
```

**Comment by rrousselGit** [comment]
I'd recommend having a secondary Freezed class that contains only what your builder cares about instead, and convert the original Freezed class to the more specific one.

**Comment by rrousselGit** [comment]
I don't plan on working on this. Ultimately Dart will support this more naturally (records/tuple). So it's only a matter of time
