### ISSUE TITLE
Package is not available.

### ISSUE THREAD

**Issue by kim-mini6** [rrousselGit/freezed#401]
Because no versions of build_runner match >1.12.2 <2.0.0 and build_runner 1.12.2 depends on build >=2.0.0 <2.1.0, build_runner ^1.12.2 requires build >=2.0.0 <2.1.0.

And because freezed >=0.13.0-nullsafety.0 depends on build ^1.6.0, build_runner ^1.12.2 is incompatible with freezed >=0.13.0-nullsafety.0.

So, because dolink_app depends on both freezed ^0.14.1 and build_runner ^1.12.2, version solving failed.
pub get failed (1; So, because dolink_app depends on both freezed ^0.14.1 and build_runner ^1.12.2, version solving failed.)

Is there a solution?

**Comment by 2shrestha22** [comment]
This is due to the issue #397, build runner is using build version 2.0.0 while freezed is using build version 1.6.0. You can use old version of build_runner to solve this.

**Comment by kim-mini6** [comment]
Thank you, but it has a conflict with other packages and cannot be resolved.

**Comment by 2shrestha22** [comment]
Well, then wait for the update. New version may be available this weekend.
