### ISSUE TITLE
Null safety version generating error when use @required annotation

### ISSUE THREAD

**Issue by ShelMax** [rrousselGit/freezed#402]
**Describe the bug**

When I use @required annotation and run build runner, I receive the error message:
`The parameter 'id' of 'CategoryDto' is non-nullable but is neither required nor marked with @Default`

If I add `@Default('')` to `@required String id,` I receive the error message:
`@Default cannot be used on non-optional parameters`

If delete @Default and @required all work fine.

**To Reproduce**

**Run command:** flutter pub run build_runner watch --delete-conflicting-outputs

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'language.freezed.dart';

@freezed
class Language with _$Language {
  const factory Language({
    @required String id,
    @required String name,
  }) = _Language;
}
```

**Expected behavior**
The success of run build_runner

```
dependencies:
  freezed_annotation: ^0.14.1
  freezed: 0.14.1
dev_dependencies:
  build_runner: ^1.11.5
```
Environment:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.2 20D80 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)
```

**Comment by SunlightBro** [comment]
duplicate:
https://github.com/rrousselGit/freezed/issues/396#issuecomment-800050203

**Comment by rrousselGit** [comment]
Closing as this is expected. use `required` instead of `@required`

**Comment by ShelMax** [comment]
Thanks for the answer guys!
