### ISSUE TITLE
Pull doc comments from extends, implements or Mixins

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/freezed#403]
Hello! Is it feasible to generate comments on a `freezed` model fields if whatever the model extends/implements or mixins already has a doc comment for that field?

For example, if we had this

```dart
abstract class BaseUser {
  /// User doc...
  String get name;

  /// Email doc...
  String get email;
}

@freezed
class User with _$User, BaseUser {
  factory User({
    required String name,
    required String email,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
```

Could we get this?

```dart
mixin _$User {
   /// User doc...
  String get name => throw _privateConstructorUsedError;
  /// Email doc...
  String get email => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $UserCopyWith<User> get copyWith => throw _privateConstructorUsedError;
}
```

Could an analyzer node get that kind of information (such as from [`tryGetAstNodeForElement`](https://github.com/rrousselGit/freezed/blob/cd29a64c3369bff6ccbe794c323b995adf15ac6a/packages/freezed/lib/src/utils.dart#L26)) or would you first have to parse the `BaserUser`s fields and then store that information then cross reference that later when compiling the docs to see which to use?

**Comment by rrousselGit** [comment]
The IDE should already take care of that

**Comment by Nolence** [comment]
Good to know.

Closing
