### ISSUE TITLE
Private class with optional arguments generate warning

### ISSUE THREAD

**Issue by derolf** [rrousselGit/freezed#406]
Private class with optional arguments:

```Dart
@freezed
class _Foo with _$_Foo {
  factory _Foo({
    List<int>? ints,
  }) = __Foo;
}
```

Generates:

```
A value for optional parameter 'ints' isn't ever given.
Try removing the unused parameter.
```

**Comment by rrousselGit** [comment]
And the parameter is not unused?

**Comment by derolf** [comment]
When initializing the StateNotifier, the field defaults to null, but later I am using copyWith.

So, the parameter in the constructor is unused, but the actual field is used.

**Comment by rrousselGit** [comment]
Then add an `// ignore:`

**Comment by derolf** [comment]
> Then add an `// ignore:`

That’s what I did... thought there might be something better...
