### ISSUE TITLE
Invalid syntax generated

### ISSUE THREAD

**Issue by PieterHartzer** [rrousselGit/freezed#411]
**Describe the bug**
When running `flutter pub run build_runner build --delete-conflicting-outputs` the generated `.freezed.dart` files contain errors.  This started after I upgraded flutter.  All packages in pubspec.yaml is up to date.

**To Reproduce**
On the latest flutter, create a new app using VS Code.  Add a new cubit with the following code.

_test_cubit.dart_
```
import 'package:bloc/bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test_state.dart';
part 'test_cubit.freezed.dart';

class TestCubit extends Cubit<TestState> {
  TestCubit() : super(TestState.initial());
}
```

_test_state.dart_
```
part of 'test_cubit.dart';

@freezed
class TestState with _$TestState {
  const factory TestState.initial() = _Initial;
  const factory TestState.loaded(String someValue) = _Loaded;
}
```

Run `flutter pub run build_runner build --delete-conflicting-outputs`

Result contains errors, eg. 
```
_Loaded loaded( String* someValue) {
  return  _Loaded(someValue,);
}
```
![image](https://user-images.githubusercontent.com/1129284/112362243-88bd6100-8cd4-11eb-94f1-05600cdcccd8.png)

Manually deleting the * resolves the errors until the file is generated again.

**Expected behavior**
The `.freezed.dart` file should contain valid Dart code that can be built.

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.3 at /usr/local/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/pieter/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /usr/local/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /usr/local/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

**Comment by nazrinharris** [comment]
Facing the same problem. 
Both in the stable and dev channel

**Comment by rrousselGit** [comment]
It is likely that you are using the version 0.14.x, but your application is not migrated to null-safety.

Migrating your app to null-safety should fix the issue.

**Comment by PieterHartzer** [comment]
That might very well be the case.  
```
$ dart pub upgrade --null-safety
null-safety compatible versions do not exist for:
 - build_runner
 ```
 
 The freezed instructions state to run `flutter pub run build_runner build` but build runner doesn't appear to have a null safety version.  When I try it without upgrading it I get

```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:build_runner_core
 - package:build_runner
 - package:build_config
 - package:build_daemon
 - package:code_builder
```
When running with the flag `--no-sound-null-safety` it fails where the code isn't null safe.

What would be the process to generate freezed files without a null safe build_runner?

**Comment by PieterHartzer** [comment]
After changing my `pubspec.yaml` to have **>=2.12.0-0**  it appears to work!

```
environment:
  sdk: ">=2.12.0-0 <3.0.0"
```

Not sure why that's not replaced as part of the upgrade, or for new projects, but at least I found the issue.
Thanks for pointing me in the right direction @rrousselGit
