### ISSUE TITLE
Redirecting constructors

### ISSUE THREAD

**Issue by hacker1024** [rrousselGit/freezed#414]
**Is your feature request related to a problem? Please describe.**

For state structures like the following (commonly used with Redux), an `initial` constructor is often used:

```dart
@freezed
class AppState with _$AppState {
  const factory AppState({
    required ApiState apiState,
    required SessionState sessionState,
  }) = _AppState;

  const AppState.initial()
      : this(
          apiState: const ApiState.initial(),
          sessionState: const SessionState.initial(),
        );
}
```

This, however, does not generate, instead printing this error:

```
Classes decorated with @freezed can only have a single non-factory, without parameters, and named MyClass._()
```

**Describe the solution you'd like**

The example shown above isn't valid Dart code, but it'd be great if there was an alternative way to create const constructors (or const factories) that redirect to other constructors/factories.

**Describe alternatives you've considered**

Factories can be used, but they cannot be `const`.

```dart
factory AppState.initial() => const AppState(
      apiState: ApiState.initial(),
      sessionState: SessionState.initial(),
    );
```

Alternatively, a static value can be used, but it doesn't seem appropriate for this use case.

```dart
static const initial = AppState(
  apiState: ApiState.initial(),
  sessionState: SessionState.initial(),
);
```

**Additional context**

**Comment by rrousselGit** [comment]
The `: this(...)` syntax is not possible to support because Freezed relies on factory constructors.

The `static const` syntax sounds the most appropriate and already works.
Are you expected Freezed to do something else?

**Comment by rrousselGit** [comment]
Closing since this is not possible to support.

**Comment by hacker1024** [comment]
The problem with the `static const` syntax is that is doesn't support type arguments.
For example, how can I define an initial value with an empty list?

```dart
@freezed
class TypedClass<T> with _$TypedClass<T> {
  const factory TypedClass(List<T> list) = _TypedClass;
}
```

**Comment by rrousselGit** [comment]
```dart
@freezed
class TypedClass<T> with _$TypedClass<T> {
  const factory TypedClass([@Default(const []) List<T> list]) = _TypedClass;
}
