### ISSUE TITLE
Cant use the library even with the basic example on documentation

### ISSUE THREAD

**Issue by smunozp** [rrousselGit/freezed#415]
Hi

Im having this error following the documentation example when running 
flutter pub run build_runner build --delete-conflicting-outputs

The parameter `name` of `Person` is non-nullable but is neither required nor marked with @Default
package:product_flutter/domain/models/person.dart:9:27
  ╷
9 │   factory Person({ String name, int age }) = _Person;
  │                           ^^^^
  ╵
[INFO] Running build completed, took 1.5s

the class code is following 

`import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'person.freezed.dart';

@freezed
class Person with _$Person {
  factory Person({ String name, int age }) = _Person;
}
`

and this is my pubspect.yaml

`version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_platform: ^0.1.3
  emojis: ^0.9.3
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  flutter_riverpod: ^0.13.0
  hasura_connect: ^3.0.0+1
  freezed_annotation: ^0.14.1
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  material_design_icons_flutter: ^4.0.5345

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
  freezed: ^0.14.1+1
  build_runner: ^1.11.5`

**Comment by SunlightBro** [comment]
please follow the [README](https://github.com/rrousselGit/freezed#0140-and-null-safety),
As long as your still using `sdk: ">=2.7.0 <3.0.0"` you should use
```YAML
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
```

**Comment by rrousselGit** [comment]
The examples in the README were outdated, fixed

**Comment by smunozp** [comment]
thanks!

a good hint to newcomers to dart is to specify that environment SDK should be
  sdk: ">=2.12.0 <3.0.0" in the project, took me a bit to realize that null safety was not activated as default on sdk 2.7.0
