### ISSUE TITLE
Using custom getters and methods causes Freezed objects to have two of each property

### ISSUE THREAD

**Issue by BenjaminFarquhar** [rrousselGit/freezed#416]
version:   
```
freezed: ^0.14.1+2
freezed_annotation: ^0.14.1
build_runner: ^1.12.2
```

**Describe the bug**
Copying the official docs to add custom methods or getters to the freezed class, creates all properties on the object twice.

**To Reproduce**

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'person.freezed.dart';

@freezed
class Person with _$Person {
  const factory Person(String name, {int? age}) = _Person;

  void method() {
    print('hello world');
  }
}
```
In another file:

```
final p = Person('John');
inspect(p);
```

output:

```
inspected variable>
age:null
name:"John"
age:null
copyWith:__$PersonCopyWithImpl (Instance of '__$PersonCopyWithImpl<_Person>')
hashCode:491549727
name:"John"
runtimeType:Type (_$_Person)
```

**Expected behavior**
The fields should appear on the object only once.

**Comment by rrousselGit** [comment]
> In another file:
> 
> ```
> final p = Person('John');
> inspect(p);
> ```

What is this `inspect`?

**Comment by BenjaminFarquhar** [comment]
@rrousselGit The `inspect` is from `import 'dart:developer';`

Which prints the value specified in the issue to the debug console (which has two of each field - `name` and `age`:

```
inspected variable>
age:null
name:"John"
age:null
copyWith:__$PersonCopyWithImpl (Instance of '__$PersonCopyWithImpl<_Person>')
hashCode:491549727
name:"John"
runtimeType:Type (_$_Person)
```
