### ISSUE TITLE
Change "operator ==(dynamic)" parameter to "Object"

### ISSUE THREAD

**Issue by rich-j** [rrousselGit/freezed#417]
Working on mocking our code with Mockito and encountered https://github.com/dart-lang/mockito/issues/354. This bug suggests that the correct equality override is `bool operator ==(Object other) {` When scanning our code for `bool operator ==(dynamic other) {` we found instances in our generated `freezed` classes. These currently aren't causing us problems but would like to see `freezed` follow best practices.

**Comment by rrousselGit** [comment]
Closing since it shouldn't have any impact besides style
