### ISSUE TITLE
Unable to genearate JSON Could not resolve annotation for `_$CycleEventDtoCopyWith<_CycleEventDto> get copyWith

### ISSUE THREAD

**Issue by cadaniel** [rrousselGit/freezed#419]
**Describe the bug**

So I have a freezed object 

    part 'cycle_event_dto.freezed.dart';
    part 'cycle_event_dto.g.dart';
    
    @freezed
    class CycleEventDto with _$CycleEventDto {
      factory CycleEventDto(CycleEventType cycleEventType, DateTime eventDate,
          DateTime lastUpdated, bool deleted) = _CycleEventDto;
      factory CycleEventDto.fromJson(Map<String, dynamic> json) =>
          _$CycleEventDtoFromJson(json);
      factory CycleEventDto.fromCycleEvent(CycleEvent event) => CycleEventDto(
          event.cycleEventType,
          event.eventDate,
          event.lastUpdated ?? DateTime.now(),
          event.delete);
    }
    
    extension CycleEventDtoExtension on CycleEventDto {
      CycleEventTableCompanion toEvent(int? existingId) {
        if (existingId != null) {
          return CycleEventTableCompanion.insert(
              id: Value(existingId),
              cycleEventType: this.cycleEventType,
              eventDate: this.eventDate,
              lastUpdated: Value(this.lastUpdated),
              delete: Value(this.deleted));
        }
        return CycleEventTableCompanion.insert(
            cycleEventType: this.cycleEventType,
            eventDate: this.eventDate,
            lastUpdated: Value(this.lastUpdated),
            delete: Value(this.deleted));
      }
    } 

I'm getting the following error: 
[cycle_event_dto.freezed.dart.txt](https://github.com/rrousselGit/freezed/files/6280581/cycle_event_dto.freezed.dart.txt)

[SEVERE] json_serializable:json_serializable on lib/src/data/dto/cycle_event_dto.dart:

line 1, column 6724 of /normative/lib/src/data/dto/cycle_event_dto.freezed.dart: Could not resolve annotation for `_$CycleEventDtoCopyWith<_CycleEventDto> get copyWith`.
  ╷
1 │ @JsonKey(ignore: true)
  │ ^^^^^^^^^^^^^^^^^^^^^^
  ╵

I've attached the output freezer file since that's a monster.

**To Reproduce**

I'm not sure the minimum needed to reproduce. 

**Expected behavior**
Generates valid code

**Comment by cadaniel** [comment]
Found the problem, and It's not actually freezed. 

I'm using moor data types as well in the class, and moor has a similar named annotation, so it's name space confustion

**Comment by nhingo-312** [comment]
> Found the problem, and It's not actually freezed.
> 
> I'm using moor data types as well in the class, and moor has a similar named annotation, so it's name space confustion

Since you're using moor, do you happen to know how to with a freezed model that extends a moor table? I'm got stuck with the issue: ```'copyWith' is inherited as a getter (from '_$MindsetResponse') and also a method (from 'Mindset')```,  and ```'_$MindsetResponse.toJson' ('Map<String, dynamic> Function()') isn't a valid override of 'Mindset.toJson' ('Map<String, dynamic> Function({ValueSerializer? serializer})')```,
where `_$MindsetResponse'` is my freezed model and `Mindset` is the moor  table. Tks so much!
