### ISSUE TITLE
Generic lists are failing in compilation time

### ISSUE THREAD

**Issue by AndresR173** [rrousselGit/freezed#421]
**Describe the bug**
I'm using a generic class for my API responses

```dart
@freezed
class BaseResponseList<T> with _$BaseResponseList {
  const factory BaseResponseList({
    String? message,
    @DataConverter() required List<T> info,
  }) = BaseResponseFromList<T>;

  factory BaseResponseList.fromJson(Map<String, dynamic> json) =>
      _$BaseResponseListFromJson(json);
}
```

```yaml
freezed_annotation: ^0.14.1
freezed: ^0.14.1+2
```

When I try to build the project, the following error appears:

`response.freezed.dart:252:18: Error: The argument type 'BaseResponseList<dynamic>' can't be assigned to the parameter type 'BaseResponseList<T>'.
     - 'BaseResponseList' is from`

**Expected behavior**
`_value.copyWith` should return `BaseResponseList<T>` instead of `BaseResponseList<dynamic>`
![Screen Shot 2021-04-10 at 1 17 32 PM](https://user-images.githubusercontent.com/5528401/114280489-1d2b0180-99ff-11eb-81dd-a186620d82d9.png)

as a temporary fix, I'm adding `as BaseResponseList<T>`

```dart
@override
  $Res call({
    Object? message = freezed,
    Object? info = freezed,
  }) {
    return _then(
      _value.copyWith(
        message: message == freezed
            ? _value.message
            : message // ignore: cast_nullable_to_non_nullable
                as String?,
        info: info == freezed
            ? _value.info
            : info // ignore: cast_nullable_to_non_nullable
                as List<T>,
      ) as BaseResponseList<T>,
    );
  }
```

**Comment by rrousselGit** [comment]
Try doing:

```dart
with _$BaseResponseList<T> {...}
```

**Comment by AndresR173** [comment]
Hey @rrousselGit you are right, that worked for me. Thank you very much!
