### ISSUE TITLE
Inheritable JSON annotations

### ISSUE THREAD

**Issue by hacker1024** [rrousselGit/freezed#423]
**Is your feature request related to a problem? Please describe.**
I'm building an API wrapper, and I'm dealing with two JSON object that have numerous shared keys and only a few specific ones. I have an interface like this to implement this:

```dart
abstract class MyBaseType {
  @JsonKey(name: 'property_key')
  final String property;
}
```

And a couple of freezed classes like this:

```dart
@freezed
class MySpecializedType extends MyBaseType with _$MySpecializedType {
  const MySpecializedType._();

  const factory MySpecializedType({
    required String property,
    @JsonKey(name: 'another_propery_key') required String anotherProperty,
  }) = _MySpecializedType
}
```

Normally, when using `json_serializable`, the `JsonKey` annotation in the base class will be used in subclasses. This is not happening when using `freezed`.

**Describe the solution you'd like**
I'd like `JsonKey` annotations used in superclasses to be used in freezed subclasses as well.

**Describe alternatives you've considered**
The only alternative is writing the same annotation everywhere it's needed.

**Additional context**

**Comment by rrousselGit** [comment]
This is not up to Freezed but json_serializable

It is likely that the current logic which searches for the annotation does not currently find the subclass.

**Comment by hacker1024** [comment]
That's plausible, considering the complexity of the generates class hierarchy.
I'll look into it more, and file an issue there. Should this issue stay open?

**Comment by rrousselGit** [comment]
I'll close this for now. Feel free to open a new issue if the conclusion changes and there's indeed a problem with Freezed.
