### ISSUE TITLE
fromJson missing

### ISSUE THREAD

**Issue by mohanasundaramn** [rrousselGit/freezed#43]
Hi,

I am using freezed for serialisation. But getting the following error ```Try correcting the name to the name of an existing method, or defining a method named 'fromJson'```, I also defined factory constructor in the model class.
 ```dart   
   factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
```

Here is reproducible [example](https://github.com/mohanasundaramn/flutter_freezed_example)

Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (3 weeks ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0

Operating System: Windows10(64bit)

**Comment by rrousselGit** [comment]
The repository you linked does include the fromJson

Maybe it's just your IDE that didn't refresh?

**Comment by mohanasundaramn** [comment]
I am using Android Studio for my project, for reproducible example, I used vscode as an ide.

**Comment by smiLLe** [comment]
we no longer have to import json package?

**Comment by rrousselGit** [comment]
> we no longer have to import json package?

Yes. The annotation package re-export json_annotations

**Comment by mohanasundaramn** [comment]
I did restart my pc still, the issue persists.
![Annotation 2020-02-14 194041](https://user-images.githubusercontent.com/24430497/74538510-66e69c00-4f62-11ea-9541-e8c1ade520b9.png)
![Annotation 2020-02-14 194159](https://user-images.githubusercontent.com/24430497/74538624-9f867580-4f62-11ea-8f78-20e523280947.png)

**Comment by mohanasundaramn** [comment]
> > we no longer have to import json package?
> 
> Yes. The annotation package re-export json_annotations

Still, we need to add ```json_serializable``` dependency right?

**Comment by rrousselGit** [comment]
> Still, we need to add json_serializable dependency right?

Yes

**Comment by SHRJamal** [comment]
@mohanasundaramn  from your screenshot, it looks like you are trying to invoke fromJson on `verifyOtp` instance. it must be on Class: `VerifyOtp.fromJson()`

**Comment by mohanasundaramn** [comment]
Oops! my bad, ``` VerifyOtp.fromJson``` is a named factory constructor. Thank you @SHRJamal 
@rrousselGit Thank you for your contribution to the community(Flutter+Provider= ❤️)
