### ISSUE TITLE
Make freezed compatible with latest buildrunner

### ISSUE THREAD

**Issue by remonh87** [rrousselGit/freezed#433]
**Is your feature request related to a problem? Please describe.**
When upgrading to buildrunner v2.01. I get the following error: 

```
Because no versions of freezed match >0.14.1+2 <0.15.0 and freezed 0.14.1+2 depends on build_config ^0.4.2, freezed ^0.14.1+2 requires build_config ^0.4.2.
And because build_runner >=2.0.0 depends on build_config >=1.0.0 <1.1.0, freezed ^0.14.1+2 is incompatible with build_runner >=2.0.0.
```

**Describe the solution you'd like**
Update dependencies on freezed so I can run it using latest stable build_runner version.

**Describe alternatives you've considered**
Technically I could try dependency overrides but would like to avoid this when possible.

**Comment by jhlabs** [comment]
I am having the same issue. Is there a current workaround with dependency overrides?
