### ISSUE TITLE
Ability to get all values for union/sealed classes

### ISSUE THREAD

**Issue by proninyaroslav** [rrousselGit/freezed#434]
**Is your feature request related to a problem? Please describe.**

If I need to get all the members of the union/sealed class, then I would like to do the following:
```Dart
final values = [
  Union.one(),
  Union.two(),
  ...
];
```
but this is not without its drawbacks - if a new member is added, then I will have to find for this place in the code, since the analyzer will not work in this case (as if i used `when`/`map`), this creates potential bugs. The appearance of `values` shifts the responsibility of filling the list from the developer to the generator.

**Describe the solution you'd like**

A method/member similar to enum's `values` is needed:
```Dart
final values = Union.values;
```
It may be worth making it optional, so as not to break the API, as is done with `fromJson()`:
```Dart
@freezed
class Union with _$Union {
  const factory Union.one() = UnionOne;
  const factory Union.two() = UnionTwo;
  const factory Union.three() = UnionThree;

  static const values = _$UnionValues;

  factory Union.fromJson(Map<String, dynamic> json) => _$UnionFromJson(json);
}
```

**Additional context**

Yes, it looks like https://github.com/rrousselGit/freezed/issues/74, but the idea is not to create full-fledged enum analogue, but to add `values` analogue, which is very useful in the case of a union/sealed class.

**Comment by rbdog** [comment]
# Problem
I think it becomes hard to implement them when they include properties.

```union.dart
@freezed
class Union with _$Union {
  const factory Union.one( int a ) = UnionOne;
  const factory Union.two( String b ) = UnionTwo;
  const factory Union.three( MyClass c ) = UnionThree;
}
```

# Alternative Solutions

```union.dart
List<Type> derivedClasses = [
  UnionOne, 
  UnionTwo, 
  UnionThree,
];

List<UnionEnum> enumValues = [
  UnionEnum.one,
  UnionEnum.two,
  UnionEnum.three,
];

List<String> names = [
  'one',
  'two',
  'three',
]; 
```

# Other Naming Ideas

- members
- patterns
- subTypes

**Comment by rrousselGit** [comment]
I have no plan to support this. You probably should be using a plain `enum` in this scenario.

Enums can now defined constructors or have methods.
