### ISSUE TITLE
InconsistentAnalysisException

### ISSUE THREAD

**Issue by vadrian89** [rrousselGit/freezed#435]
**Describe the bug**

Build runner crashes on random classes, cleaning doesn't seem to work.
Tried different versions of analyzer and of build_runner, as much as I am able, since I cannot upgrade to sound null because of dependencies.

Full terminal log:
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 478ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 13.5s

[INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.2s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 19 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 6ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 4.1s elapsed, 0/16 actions completed.
[INFO] Generating SDK summary completed, took 4.1s

[INFO] 5.2s elapsed, 31/47 actions completed.
[INFO] 6.3s elapsed, 38/54 actions completed.
[INFO] 7.3s elapsed, 38/54 actions completed.
[INFO] 8.4s elapsed, 38/54 actions completed.
[INFO] 9.7s elapsed, 38/54 actions completed.
[INFO] 10.7s elapsed, 40/54 actions completed.
[WARNING] freezed:freezed on lib/domain/core/operation_result.dart:
Error InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

[WARNING] freezed:freezed on lib/domain/core/operation_result.dart:
#0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:146:7)
#1      AnalysisSessionImpl.getParsedLibraryByElement (package:analyzer/src/dart/analysis/session.dart:93:5)
#2      documentationOfParameter (package:freezed/src/utils.dart:8:12)
#3      new Property.fromParameter (package:freezed/src/templates/concrete_template.dart:399:12)
#4      FreezedGenerator._parseConstructorsNeedsGeneration (package:freezed/src/freezed_generator.dart:473:24)
#5      FreezedGenerator.parseElement (package:freezed/src/freezed_generator.dart:239:9)
#6      ParserGenerator.generate (package:freezed/src/parse_generator.dart:29:22)
#7      _generate (package:source_gen/src/builder.dart:338:33)
<asynchronous suspension>
#8      Stream.toList.<anonymous closure> (dart:async/stream.dart)
<asynchronous suspension>

[SEVERE] freezed:freezed on lib/domain/core/operation_result.dart:

InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

[INFO] 18.3s elapsed, 89/101 actions completed.
[INFO] 19.4s elapsed, 90/101 actions completed.
[INFO] 22.0s elapsed, 94/101 actions completed.
[INFO] 23.1s elapsed, 156/171 actions completed.
[INFO] 24.2s elapsed, 202/217 actions completed.
[INFO] 25.2s elapsed, 310/314 actions completed.
[INFO] Running build completed, took 25.3s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 129ms

[SEVERE] Failed after 25.5s
pub finished with exit code 1
```

This is the class in question: 

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'operation_result.freezed.dart';

@freezed
abstract class OperationResult with _$OperationResult {
  const factory OperationResult.failure(String message) = _Failure;
  const factory OperationResult.success() = _Success;
}
```

This is a previous class which didn't wanted to build:

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'app_updater_model.freezed.dart';
part 'app_updater_model.g.dart';

@freezed
abstract class AppUpdaterModel with _$AppUpdaterModel {
  const AppUpdaterModel._();

  String get versionString => "$majorVersion.$minorVersion.$devVersion";

  const factory AppUpdaterModel({
    int majorVersion,
    int minorVersion,
    int devVersion,
    int buildVersion,
    String updateNotes,
  }) = _UpdaterModel;

  factory AppUpdaterModel.fromJson(Map<String, dynamic> data) => _$AppUpdaterModelFromJson(data);
}

```

Dev dependencies:
build_runner: ^1.10.1
freezed: ^0.12.1
json_serializable: ^3.5.1

Flutter version 2.0.5

**Comment by rrousselGit** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> Build runner crashes on random classes, cleaning doesn't seem to work.
> Tried different versions of analyzer and of build_runner, as much as I am able, since I cannot upgrade to sound null because of dependencies.
> 
> Full terminal log:
> 
> ```
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 478ms
> 
> [INFO] Creating build script snapshot......
> [INFO] Creating build script snapshot... completed, took 13.5s
> 
> [INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).
> 
> [INFO] Initializing inputs
> [INFO] Building new asset graph...
> [INFO] Building new asset graph completed, took 1.2s
> 
> [INFO] Checking for unexpected pre-existing outputs....
> [INFO] Deleting 19 declared outputs which already existed on disk.
> [INFO] Checking for unexpected pre-existing outputs. completed, took 6ms
> 
> [INFO] Running build...
> [INFO] Generating SDK summary...
> [INFO] 4.1s elapsed, 0/16 actions completed.
> [INFO] Generating SDK summary completed, took 4.1s
> 
> [INFO] 5.2s elapsed, 31/47 actions completed.
> [INFO] 6.3s elapsed, 38/54 actions completed.
> [INFO] 7.3s elapsed, 38/54 actions completed.
> [INFO] 8.4s elapsed, 38/54 actions completed.
> [INFO] 9.7s elapsed, 38/54 actions completed.
> [INFO] 10.7s elapsed, 40/54 actions completed.
> [WARNING] freezed:freezed on lib/domain/core/operation_result.dart:
> Error InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
> 
> [WARNING] freezed:freezed on lib/domain/core/operation_result.dart:
> #0      AnalysisSessionImpl._checkConsistency (package:analyzer/src/dart/analysis/session.dart:146:7)
> #1      AnalysisSessionImpl.getParsedLibraryByElement (package:analyzer/src/dart/analysis/session.dart:93:5)
> #2      documentationOfParameter (package:freezed/src/utils.dart:8:12)
> #3      new Property.fromParameter (package:freezed/src/templates/concrete_template.dart:399:12)
> #4      FreezedGenerator._parseConstructorsNeedsGeneration (package:freezed/src/freezed_generator.dart:473:24)
> #5      FreezedGenerator.parseElement (package:freezed/src/freezed_generator.dart:239:9)
> #6      ParserGenerator.generate (package:freezed/src/parse_generator.dart:29:22)
> #7      _generate (package:source_gen/src/builder.dart:338:33)
> <asynchronous suspension>
> #8      Stream.toList.<anonymous closure> (dart:async/stream.dart)
> <asynchronous suspension>
> 
> [SEVERE] freezed:freezed on lib/domain/core/operation_result.dart:
> 
> InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
> 
> [INFO] 18.3s elapsed, 89/101 actions completed.
> [INFO] 19.4s elapsed, 90/101 actions completed.
> [INFO] 22.0s elapsed, 94/101 actions completed.
> [INFO] 23.1s elapsed, 156/171 actions completed.
> [INFO] 24.2s elapsed, 202/217 actions completed.
> [INFO] 25.2s elapsed, 310/314 actions completed.
> [INFO] Running build completed, took 25.3s
> 
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 129ms
> 
> [SEVERE] Failed after 25.5s
> pub finished with exit code 1
> ```
> 
> This is the class in question:
> 
> ```
> import 'package:freezed_annotation/freezed_annotation.dart';
> 
> part 'operation_result.freezed.dart';
> 
> @freezed
> abstract class OperationResult with _$OperationResult {
>   const factory OperationResult.failure(String message) = _Failure;
>   const factory OperationResult.success() = _Success;
> }
> ```
> 
> This is a previous class which didn't wanted to build:
> 
> ```
> import 'package:freezed_annotation/freezed_annotation.dart';
> 
> part 'app_updater_model.freezed.dart';
> part 'app_updater_model.g.dart';
> 
> @freezed
> abstract class AppUpdaterModel with _$AppUpdaterModel {
>   const AppUpdaterModel._();
> 
>   String get versionString => "$majorVersion.$minorVersion.$devVersion";
> 
>   const factory AppUpdaterModel({
>     int majorVersion,
>     int minorVersion,
>     int devVersion,
>     int buildVersion,
>     String updateNotes,
>   }) = _UpdaterModel;
> 
>   factory AppUpdaterModel.fromJson(Map<String, dynamic> data) => _$AppUpdaterModelFromJson(data);
> }
> ```
> 
> Dev dependencies:
> build_runner: ^1.10.1
> freezed: ^0.12.1
> json_serializable: ^3.5.1
> 
> Flutter version 2.0.5

That's some pretty old versions and most likely the issue.

There's nothing I can do besides recommending you to upgrade your dependencies.

**Comment by vadrian89** [comment]
Managed to try and match between versions and it seems freezed: ^0.12.7 worked.

Can't upgrade dependencies as there are other dependencies which are not upgraded yet to sound null.
So I am a bit stuck.

Thank you.
