### ISSUE TITLE
[Feature request] getting property name variables

### ISSUE THREAD

**Issue by shinriyo** [rrousselGit/freezed#437]
**Is your feature request related to a problem? Please describe.**
I want to get a name string variable option like `User.field.name` and so on.
It is used for the map key.

**Describe the solution you'd like**

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'user.freezed.dart';
part 'user.g.dart';

@freezed
abstract class User with _$User {
  const factory User({
    required final String name,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
```

And if we use map value, It is `{'name': 'Mike'}`.

but if we use like this,
```
`{`User.field.name`: 'Mike'}`
```

even if `name` was changed, we can find it is changed for the error log.

**Describe alternatives you've considered**

Add before fire the `build_runner` command, we just put it like the field.

```
@freezed
abstract class User with _$User {
  static final field = _$UserField();
```

and auto-generate like below

```
class _$UserField {
  String get name => 'name';
}
```

**Additional context**
N/A

**Comment by rrousselGit** [comment]
> but if we use like this,
> 
> ```
> `{`User.field.name`: 'Mike'}`
> ```


Maybe you want `toString` instead? 

For your example, `toString` would be:

```
User(name: 'Mike')
```

**Comment by rrousselGit** [comment]
Closing in favour of #254
