### ISSUE TITLE
Model.toJson() should not include fields that have the default value

### ISSUE THREAD

**Issue by locohost** [rrousselGit/freezed#441]
Freezed model.toJson() creates a Json structure that includes every field even when it has a blank default value. This breaks Firestore's SetOptions(merge: true). Since the Json returned by model.toJson() has every field set with default values, the Firestore **merge** literally wipes every field in the doc when saving.  

The Freezed model.toJson() returned Json object **should not include** fields that have value that matches the default.

Only option to fix this is to not use Freezed and go back to building my own models.

**Comment by locohost** [comment]
Ok well, maybe a flag in .toJson() to do this. As a default behavior it won't work.

**Comment by dossiman** [comment]
I think the to/fromJson() are generated by json_serializable and not by freezed, @Default(xxx) are converted to @JsonKey(defaultValue: xxx) and then json_serializable will generate the .g.dart file from that.
So it's probably something that should be requested to the devs of json_serializable instead, something like @JsonSerializable(ignoreDefaults: true) would be nice.
