### ISSUE TITLE
late keyword section in readme

### ISSUE THREAD

**Issue by nt4f04uNd** [rrousselGit/freezed#446]
**Describe what scenario you think is uncovered by the existing examples/articles**
The section in readme is unclear

**Describe why existing examples/articles do not cover this case**
In readme, this section
https://pub.dev/packages/freezed#late

What is this supposed to mean? That the library supports late keywords? Providing the same sample code twice is unclear to me

![image](https://user-images.githubusercontent.com/39104740/118129516-f3516a00-b404-11eb-9da2-b124b8f149a9.png)

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rrousselGit** [comment]
Haha, that's some outdated doc that was weirdly migrated after null-safety. I will remove it.

**Comment by rrousselGit** [comment]
Fixed, I removed the section entirely.
