### ISSUE TITLE
Deep Copy no longer works as intended with nullable objects.

### ISSUE THREAD

**Issue by Jonan2813** [rrousselGit/freezed#447]
Documentation says that we can replicate this:
```dart
@freezed
class Company with _$Company {
  factory Company({String? name, Director? director}) = _Company;
}

@freezed
class Director with _$Director {
  factory Director({String? name, Assistant? assistant}) = _Director;
}

@freezed
class Assistant with _$Assistant {
  factory Assistant({String? name, int? age}) = _Assistant;
}
```
and be able to deep copy the assistant even though when director is null using the `?.` operator
```dart
final company = Company(name: 'Google', director: null);
final newCompany = company.copyWith.director?.assistant(name: 'John');
```

However, this doesn't work since `assistant` can also be nullabe in `Director` class and `The function can't be unconditionally invoked because it can be 'null'`.

Therefore, deep copy no longer works and is needed to make regular copy:
```dart
final newCompany = company.copyWith(
  director: company.director?.copyWith(
    assistant: company.director?.assistant?.copyWith(name: 'John'),
  ),
);
```
Or either make a null-check in the last value to use `!` operator without throwing an error at runtime when calling the function to copy.

In fact, all of these examples from documentation no longer works because of the same problem:
```dart
company = company.copyWith.director(name: 'Larry', assistant: Assistant(...));
company = company.copyWith.director.assistant(name: 'John', age: 42);
```
We cannot call the function in `director` and `assistant` because both can be null.

I know the way null-safety works makes this happens, therefore if deep-copy will not change to support these cases, then documentation needs to be changed.

Edit: I already see the `call` method that works for these situations. Then just the documentation need to be changed to specified this method.

Edit 2: However now, adding `?.call` in `company = company.copyWith.director?.call(name: 'Larry', assistant: Assistant(...));` makes the returning type nullable.

**Comment by rrousselGit** [comment]
Adding `?.call` is correct

Maybe you want to do something like `.assistant?.call(name: 'John') ?? company`?

**Comment by rrousselGit** [comment]
In the lack of an answer, I will close this. Have a nice day!
