### ISSUE TITLE
Could not generate `fromJson` code for `unit8List`. To support the type `Uint8List` you can:

### ISSUE THREAD

**Issue by Patrick386** [rrousselGit/freezed#457]
@nullable Uint8List unit8List, << failed
Uint8List unit8List, << failed
Uint8List? unit8List, << failed

**What method can be used?**

![스크린샷 2021-05-28 오후 10 35 54](https://user-images.githubusercontent.com/49754877/119992036-11be8480-c005-11eb-8014-98e6fdfcd6b5.png)

```
@freezed
class PageWidgetModel with _$PageWidgetModel {
  @JsonSerializable(
      includeIfNull: true,
      explicitToJson: true,
      checked: true,
      createToJson: true)

  factory PageWidgetModel({

    //@nullable Uint8List unit8List,
    @required Uint8List? unit8List,  //<<< Error

    @Default(1) int type, 
    @Default(900) double width,
    @Default(0.0) double height,
    @Default(12.0) double fontSize,
    @Default('') String text,
    @Default('') String imageUrl, 
  }) = _PageWidgetModel;

  const PageWidgetModel._();

  factory PageWidgetModel.fromJson(Map<String, dynamic> json) =>
      _$PageWidgetModelFromJson(json);
}
```

**Comment by Patrick386** [comment]
thank you. I need to upload the files obtained with the image picker or several other files to the cloud server. I use putBlob(blobFile) for consistency. How can I create a JsonConverter for a blob in the same way?

**Comment by rrousselGit** [comment]
Closing as this was answered
