### ISSUE TITLE
Adding Methods to Union Classes

### ISSUE THREAD

**Issue by chenyair** [rrousselGit/freezed#458]
**Is your feature request related to a problem? Please describe.**
Currently when union classes are being generated you can't really control the code that's inside these onions.
Lets say im creating a state object and I want the state object to expose a complex computation that I don't want the UI to know how its done, I can't write this method on the union class.

**Describe the solution you'd like**
I would love for an option to generate the code for the union classes as well in order to make it possible to add logic to the union classes as well as the main class that's controlling them.

**Describe alternatives you've considered**
I considered creating a class that takes the state and expose the required methods but it feels like a lot of extra code just to add some functionality to a data class.

**Comment by rrousselGit** [comment]
I am not sure what this is about.

You can add methods to your unions:

```dart
@freezed
class Example with _$Example {
  const Example._();

  factory Example.first() = _First;
  factory Example.second() = _Second;

  void method() {
    when(
      first: () => print('first'),
      second: () => print('second'),
    );
  }
}
```

Is that not what you want?

**Comment by chenyair** [comment]
> I am not sure what this is about.
> 
> You can add methods to your unions:
> 
> ```dart
> @freezed
> class Example with _$Example {
>   const Example._();
> 
>   factory Example.first() = _First;
>   factory Example.second() = _Second;
> 
>   void method() {
>     when(
>       first: () => print('first'),
>       second: () => print('second'),
>     );
>   }
> }
> ```
> 
> Is that not what you want?

It's not exactly what I need. I want to be able to add a method only to one of the union classes. Lets say for example I have an abstract class with 3 unions of it's possible states. I want to be able to generate method for only one of the unions because I want to expose some extra functionality for that state.

**Comment by rrousselGit** [comment]
You can do that with extension methods:

```dart
@freezed
class Example with _$Example {
  const Example._();

  factory Example.first() = _First;
  factory Example.second() = _Second;
}

extension _FirstMethods on _First {
  void method() {

  }
}
```

**Comment by derolf** [comment]
Is it possible to add a mixin that implements the custom methods instead of an extension?

**Comment by rrousselGit** [comment]
Sure

```
@freezed
class Example with _$Example {
  const Example._();

  @With<Foo>()
  factory Example.first() = _First;
  factory Example.second() = _Second;
}

mixin Foo {
  void method() {}
}
```

**Comment by derolf** [comment]
Cool, but how can `Foo` access fields of `_First`?

**Comment by rrousselGit** [comment]
Define an abstract field on the mixin

**Comment by clragon** [comment]
extension methods only work for normal members;
static ones cannot be added. 

My usecase for that is e.g.

Credentials 
- TokenCredentials 
- BasicAuthCredentials
  - parse (<-- target)

but it seems that this cannot be expressed right now.

I would move BasicAuthCredentials into its own class that implements Credentials and use a redirecting factory constructor, but since both TokenCredentials and BasicAuthCredentials have the member username, the _$Credentials mixin will create a copyWith class member that cannot be implemented by BasicAuthCredentials.
