### ISSUE TITLE
annotating @nullable can generate JsonKey(nullable:true)

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/freezed#46]
As title says, wouldn't this make sense?
it would only generate the JsonKey if there is  a .fromJson method and no JsonKey annotation is used for the property.

**Comment by rrousselGit** [comment]
What's the purpose?

**Comment by smiLLe** [comment]
it felt wrong using @nullable without JsonKey(nullable:true)

**Comment by smiLLe** [comment]
json will be created but the moedl will fail to create

**Comment by rrousselGit** [comment]
Could you give an example of where you think not doing so leads to a weird behavior?
