### ISSUE TITLE
Support null "unionKey" when a fallback is provided

### ISSUE THREAD

**Issue by ken-ng-esotec** [rrousselGit/freezed#467]
How can we instruct freezed to type `json['type'] as String` to `json['type'] as String?` for this freezed configuration?

The left hand side file is `interaction.freezed.dart` while right-hand side is `interaction.dart` (freezed).

On line 38 on the right hand side, you can see that SectionType can be null. But I have to manually change `json['type'] as String` to `json['type']` or `json['type'] as String?` each time I rerun build-runner.

![image](https://user-images.githubusercontent.com/57630713/122669887-e12bce00-d1f1-11eb-9be3-122b9fe9c5d3.png)

Thank you in advance!

**Comment by rrousselGit** [comment]
There is no such thing at the moment. 

But I'd be happy to review a PR
