### ISSUE TITLE
How do I implement JsonConverter to override fromJson

### ISSUE THREAD

**Issue by Cyberavater** [rrousselGit/freezed#473]
**Describe what scenario you think is uncovered by the existing examples/articles**
Hi, first of all, thanks for this awesome tool. I'm relatively new in this field so forgive my naive questions/mistakes.
So, what I'm trying to do is to convert this bit of code freezed-based from here,
https://bloclibrary.dev/#/flutterweathertutorial?id=location-model-1

```dart
import 'package:json_annotation/json_annotation.dart';

part 'location.g.dart';

enum LocationType {
  @JsonValue('City')
  city,
  @JsonValue('Region')
  region,
  @JsonValue('State')
  state,
  @JsonValue('Province')
  province,
  @JsonValue('Country')
  country,
  @JsonValue('Continent')
  continent
}

@JsonSerializable()
class Location {
  const Location({
    required this.title,
    required this.locationType,
    required this.latLng,
    required this.woeid,
  });

  factory Location.fromJson(Map<String, dynamic> json) =>
      _$LocationFromJson(json);

  final String title;
  final LocationType locationType;
  @JsonKey(name: 'latt_long')
  @LatLngConverter()
  final LatLng latLng;
  final int woeid;
}

class LatLng {
  const LatLng({required this.latitude, required this.longitude});

  final double latitude;
  final double longitude;
}

class LatLngConverter implements JsonConverter<LatLng, String> {
  const LatLngConverter();

  @override
  String toJson(LatLng latLng) {
    return '${latLng.latitude},${latLng.longitude}';
  }

  @override
  LatLng fromJson(String jsonString) {
    final parts = jsonString.split(',');
    return LatLng(
      latitude: double.tryParse(parts[0]) ?? 0,
      longitude: double.tryParse(parts[1]) ?? 0,
    );
  }
}

```

But it seems I can't find it in docs to how to override fromJson.

**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

It'd be nice to add an example such as this provided one to tackle this kind of situation (including enum with @JsonValue). 

**Additional context**
Add any other context or screenshots about the documentation request here.
Thanks for your time! <3

**Comment by SunlightBro** [comment]
You can simply replace your `@JsonSerializable()`class with a `@freezed`class.
Freezed will simply pass your Converter, JsonyKey and JsonValues through to `json_serializable `

Checkout the readme [FromJson/ToJson](https://pub.dev/packages/freezed#fromjsontojson)

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:flutter/foundation.dart';

part 'location.freezed.dart';
part 'location.g.dart';

@freezed
class Location with _$Location {
  factory Location({
    required String title,
    required LocationType locationType,
    @LatLngConverter() @JsonKey(name: 'latt_long') required LatLng latLng,
    required int woeid,
  }) = _Location;

  factory Location.fromJson(Map<String, dynamic> json) => _$LocationFromJson(json);
}

/// ... the enum, latlng and converter can all stay the same
```

**Comment by Cyberavater** [comment]
Thanks for the explanation, everything seems to be working as expected. <3
Now, if you think that the doc is already sufficient then go ahead and close this issue, I have no complaints since my issue is solved. But I'm leaving it open for your decision, thanks!
