### ISSUE TITLE
Support for json_serializable 5.0.0

### ISSUE THREAD

**Issue by abibiano** [rrousselGit/freezed#474]
With the publication of json_serializable 5.0.0 yesterday, is it planned to update freezed to use this release?

json_serializable >=5.0.0 depends on analyzer ^2.0.0 and freezed 0.14.2 depends on analyzer ^1.5.0, json_serializable >=5.0.0 is incompatible with freezed 0.14.2

**Comment by SunlightBro** [comment]
with updated:
```
analyzer: ^2.0.0
json_serializable: ^5.0.0
json_annotation: ^4.1.0
```
test are failing because **json_serializable** generates faulty `*.g.dart` files
For example /freezed/test/integration/export.dart

<details>
  <summary>export.g.dart</summary>
  
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'export.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Export _$$_ExportFromJson(Map<String, dynamic> json) => _$_Export(
      json['a'] as int,
    );

Map<String, dynamic> _$$_ExportToJson(_$_Export instance) => <String, dynamic>{
      'a': instance.a,
    };

```
</details>

The function name _$$_ExportFromJson should be _$_$_ExportFromJson (same for _$$_ExportToJson).

I'm not sure if this is an issue with **json_serializable** or **analyzer**. This needs more investigation.
But I think for now an upgrade to 5.0.0 is not viable.

**Comment by hpoul** [comment]
@SunlightBro I don't think this is a faulty behavior, since the changelog contains:

> Improve names of private classes generated for toJson and fromJson.

this seems to be intentional: https://github.com/google/json_serializable.dart/commit/c72dd11eaafa448272e38c6b3b98d362c21ffc64

although I don't quite understand the reason for that change, since it was somehow related to `freezed`? 🤔️ https://github.com/google/json_serializable.dart/issues/619

**Comment by SunlightBro** [comment]
Ok I created a PR,
but I'm running into the issue that json_annotation 4.1.0 added `@Target()` annotations to minimize incorrect usage [#912](https://github.com/google/json_serializable.dart/commit/b0a0e519c7f1103c05b31a9e5302a5da73cddd2f).

So `@JsonKey` should only be used on **fields** and **getters** but in freezed you annotate the **parameters**.
So `@JsonSerializable` should only be used on **classes** but in freezed you annotate the **constructors**.

Don't see a better way then just to add some
```dart
//ignore: invalid_annotation_target
```
And I don't really like that.

**Comment by hpoul** [comment]
@SunlightBro maybe I'm wrong, but there is no real reason to use JsonKey from json_annotion to begin with.. freezed could provide it's own (Freezed)JsonKey (maybe subclass/implements the original?). If i understand it correctly, json_serializable always ignored the annotations on parameters, and only detected the ones in the code which freezed generates? So users would use freezed annotations and freezed generates the correct JsonKey annotations. 🤔

**Comment by SunlightBro** [comment]
Yes but currently it's implemented using the annotations from json_annotation.
And I think your your suggestion would introduce a breaking change, because that new
> (Freezed)JsonKey
cannot be named the same.

**Comment by rrousselGit** [comment]
I will discuss with the meta team to see if the lint can be disabled when an annotation is applied on a Freezed constructor.

**Comment by rrousselGit** [comment]
https://github.com/dart-lang/linter/issues/2778

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit any ideas for an interim solution?

**Comment by Hari-07** [comment]
Is this resolved yet?

> The function name `_$$_ExportFromJson` should be `_$_$_ExportFromJson` (same for `_$$_ExportToJson`).
>

**Comment by rrousselGit** [comment]
Closing since json_serializable 5.0.0 is supported

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit so the proposed solution is including ignores everywhere?

So let's put it like this: if we upgrade to `json_serializable` right now, our CI will break and we have to fix all of the warnings.

**Comment by hpoul** [comment]
@creativecreatorormaybenot i guess technically your build breaks due to the json_serializable update, which is a major version change and hence breaks compatibility by definition 🤔

**Comment by rrousselGit** [comment]
> @rrousselGit so the proposed solution is including ignores everywhere?
> 
> So let's put it like this: if we upgrade to `json_serializable` right now, our CI will break and we have to fix all of the warnings.

This issue was about supporting the version 5.0.0, which is now done.

The warnings needs to be tackled separately.

**Comment by rrousselGit** [comment]
But for now, I would suggest disabling the `invalid_annotation_target` warning inside your analysis_options.yaml

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit sounds good 👍 Is there an issue for tracking the warnings here? Or just https://github.com/dart-lang/linter/issues/2778?

**Comment by rrousselGit** [comment]
There is https://github.com/rrousselGit/freezed/issues/488

But do note that considering the amount of work necessary to fix the warning, I probably won't work on it.
Disabling the warning is a good solution for now imo

**Comment by proninyaroslav** [comment]
@rrousselGit 
I'm still getting this bug in version 0.14.5:
> The function name _$$_ExportFromJson should be _$_$_ExportFromJson (same for _$$_ExportToJson).

**Comment by proninyaroslav** [comment]
@rrousselGit 
UPD: very strange if i use json_serializable 4.1.3. then the bug with the name appears in the generated `freezed.dart` file, and not in the `g.dart` file)

**Comment by proninyaroslav** [comment]
@rrousselGit 
After several attempts to rebuild the project and return all dependencies, everything returned to normal. But this is very strange.

**Comment by rrousselGit** [comment]
Sounds like you used either upgraded freezed without upgrading json_serializable, or did the opposite.

**Comment by proninyaroslav** [comment]
@rrousselGit 
Initially, I upgraded both dependencies, and then this bug appeared. I tried to clean the project, lower the versions of both dependencies, but the problem disappeared is also strange as it appeared.
