### ISSUE TITLE
default for empty class

### ISSUE THREAD

**Issue by callmejm** [rrousselGit/freezed#476]
@freezed
      class ABCModel with _$ABCModel {
        factory ABCModel({
          @JsonKey(name: "id") @Default('') String id,
          @JsonKey(name: "name") @Default('') String name,
        }) = _ABCModel;

        factory ABCModel.fromJson(Map<String, dynamic> json) => _$ABCModelFromJson(json);
      }

      @freezed
      class EFGModel with _$EFGModel {
        factory EFGModel({
          @JsonKey(name: "abc") @Default(ABCModel()) ABCModel abc, //empty ABCModel
        }) = _EFGModel;

        factory EFGModel.fromJson(Map<String, dynamic> json) => _$EFGModelFromJson(json);
      }

If EFGModel get an empty or null abc json value, what is the suitable value to put on `@Default()` freezed annotation, `@Default(ABCModel())` is not correct

**Comment by rrousselGit** [comment]
Define your `ADBModel` constructor as:

```dart
const factory ABDModel({...}) = _ABDModel;
```

Then you should be able to write `@Default(ABCModel())`

**Comment by callmejm** [comment]
> Define your `ADBModel` constructor as:
> 
> ```dart
> const factory ABDModel({...}) = _ABDModel;
> ```
> 
> Then you should be able to write `@Default(ABCModel())`

I getting Error with `@JsonKey` on `abc`. `defaultValue` is `_$_ABCModel`, it must be a literal.

**Comment by rrousselGit** [comment]
Oh right, this won't work with json_serializable

**Comment by callmejm** [comment]
> Oh right, this won't work with json_serializable

the error is if I didn't put `@JsonKey` just `@Default(ABCModel()) ABCModel abc`

**Comment by rrousselGit** [comment]
`@Default` adds an implicit `@JsonKey(default: ABCModel())`

**Comment by rrousselGit** [comment]
Maybe try `@JsonKey() @Default(ABCModel())`

**Comment by callmejm** [comment]
> Maybe try `@JsonKey() @Default(ABCModel())`

with jsonkey is working fine
