### ISSUE TITLE
"Parameters can't override default values" warning in generated toString method

### ISSUE THREAD

**Issue by carlowenig** [rrousselGit/freezed#48]
Hi there,
great progress so far on the project, I like the new additions!

I get a warning in all generated freezed files which says:

> Parameters can't override default values, this method overrides 'DiagnosticableMixin.toString' where 'minLevel' has a different value.

It refers to the `minLevel` parameter of the `toString` method in the `_$_Model` class.

Nothing too serious for now, but it would be nice to get rid of this warning.
Thanks!

**Comment by rrousselGit** [comment]
The default value has changed recently, and Freezed is using the latest version.

You're likely using "stable" channel which has yet to receive the change

**Comment by carlowenig** [comment]
I've tested with flutter beta, dev and master channel and I still get the warning. I am writing an app for production use so I'd like to stay on the stable or beta channel. Would it be possible to generate `// ignore_for_file: invalid_override_different_default_values_named` until the flutter change is in the stable release? That would be really helpful for me.

**Comment by rrousselGit** [comment]
I've added such ignore
