### ISSUE TITLE
Name non-constant identifiers using lowerCamelCase.

### ISSUE THREAD

**Issue by callmejm** [rrousselGit/freezed#481]
part 'country_list_response.freezed.dart';
    part 'country_list_response.g.dart';

    @Freezed(unionKey: "Status")
    class CountryListResponse with _$CountryListResponse {
      factory CountryListResponse.success({
        @JsonKey(name: "Status") @Default('') String status,
        @JsonKey(name: "List", defaultValue: []) @Default([]) List<CountryItem> list,
      }) = _CountryListResponseData;
      const factory CountryListResponse.failed(
        @JsonKey(name: "Status") String status,
        @JsonKey(name: "Errors") @ErrorMessageConverter() String errors,
      ) = _CountryListResponseError;

      factory CountryListResponse.fromJson(Map<String, dynamic> json) => _$CountryListResponseFromJson(json);
    }
    
 My vscode have a lot of info showing at PROBLEMS section, saying `Name non-constant identifiers using lowerCamelCase.` How to avoid this info showing up, because it almost 200

**Comment by rrousselGit** [comment]
See https://github.com/rrousselGit/freezed#disabling-invalid_annotation_target-warning-and-warning-in-generates-files on how to disable lints on generated files

**Comment by HasanAlqaisi** [comment]
You can disable lints on generated files by excluding generated files in analysis_options.yaml:

```
analyzer:
  exclude:
    - "**/*.g.dart"
```

**Comment by Gustl22** [comment]
@rrousselGit can we reopen or change the docs? 
Using the option `invalid_annotation_target` only removes the warning for `The annotation 'JsonKey' can only be used on fields or getters.`

But this it is not applied to the generated `.g.dart` files in contrast to what is mentioned in the README: `Name non-constant identifiers using lowerCamelCase.` like methods which start with `_$$_`.

Using:
- flutter: 3.3.9
- freezed: ^2.3.0
- freezed_annotation: ^2.2.0
- json_serializable: ^6.5.4

If you agree, I do a PR.

**Comment by LeoAndo** [comment]
> You can disable lints on generated files by excluding generated files in analysis_options.yaml:
> 
> ```
> analyzer:
>   exclude:
>     - "**/*.g.dart"
> ```

@HasanAlqaisi 

I solved my problem too! thank you!
