### ISSUE TITLE
Cannot run build runner due to missing pubspec.yaml from libraries

### ISSUE THREAD

**Issue by ken-ng-esotec** [rrousselGit/freezed#484]
This affects multiple libraries initially failed with map_launcher but seems it's not an isolated issue.

$ /Users/keng/flutter/bin/flutter packages pub run build_runner build --delete-conflicting-outputs

Could not find a file named "pubspec.yaml" in "/Users/keng/flutter/.pub-cache/hosted/pub.dartlang.org/amplify_analytics_plugin_interface-0.2.0".
pub finished with exit code 66
build_runner Error! Exit with code: 66

**Comment by rrousselGit** [comment]
Freezed it not responsible for this. Consider raising an issue on pub/build_runner repositories instead
