### ISSUE TITLE
Constructor paramaters warnings when building with @Default annotation.

### ISSUE THREAD

**Issue by vadrian89** [rrousselGit/freezed#503]
**Describe the bug**
Hello,
Recently, after upgrading freezed & json_serializable packages strange warnings  have appeared,  when running build, for calss constructors paramaters with @Default annotations:

The constructor parameter for `stockAvailable` has a default value `false`, but the `JsonKey.defaultValue` value `false` will be used for missing or `null` values in JSON decoding.

JsonKey isn't used for the parameter in question. And this happens on multiple projects with freezed classes.

The parameter:
`@Default(false) bool stockAvailable,`

**To Reproduce**
Use @Default annotation in freezed class.

**Expected behavior**
The default value from @Default annotation should be used without any warning.

**Comment by sobimor** [comment]
@rrousselGit  How can we ignore this warning?

I get below warning for all data model classes which use freezed annotation.

```
[WARNING] json_serializable:json_serializable on .../events_response.dart:
The constructor parameter for `results` has a default value `const []`, but the `JsonKey.defaultValue` value `[]` will be used for missing or `null` values in JSON decoding.
```

**Comment by rrousselGit** [comment]
As I mentioned before, it looks to be a bug in json_serializable. Consider raising an issue on its repository

**Comment by micimize** [comment]
I think this warning is meant more to indicate that as of version [5.0.0](https://github.com/google/json_serializable.dart/blob/master/json_serializable/CHANGELOG.md#500) the annotation is unneeded:

> Use the default value for optional constructor parameters if `JsonKey.defaultValue` is not provided.

The error is confusing so I filed https://github.com/google/json_serializable.dart/issues/1018 regardless

**Comment by micimize** [comment]
> Nevermind, for some reason I saw this error after upgrading but it was a result of build_runner failing due to `json_annotation:` in my `pubspec.yaml`. This warning no longer shows up

Upgrading to `json_serializable: ^6.0.1 ; json_annotation: ^4.3.0` has resolved this issue for me.

**Comment by danallen88** [comment]
> As I mentioned before, it looks to be a bug in json_serializable. Consider raising an issue on its repository

@rrousselGit Opening an issue with json_serializable got immediately closed as you can see in https://github.com/google/json_serializable.dart/issues/1023.  I don't have enough insight into the inner-workings of freezed and json_serializable to really know how to continue the conversation.  If you have time, it would be great to have your input on that thread if there is something that can be done from the Google team.

**Comment by rrousselGit** [comment]
This warning should come-up anymore since json_serializable got updated
