### ISSUE TITLE
Exception with json_serializable on `String? override` (FieldElementImpl)

### ISSUE THREAD

**Issue by chunghha** [rrousselGit/freezed#507]
**Describe the bug**
Following build_runner command is throwing an exception so generation of 'risk_factor.model.g.dart' gets failed.

**dart run build_runner build --delete-conflicting-outputs --verbose**

> **InconsistentAnalysisException**: Requested result might be inconsistent with previously returned results
> 
> package:analyzer/src/dart/analysis/session.dart 197:7      AnalysisSessionImpl._checkConsistency
> package:analyzer/src/dart/analysis/session.dart 107:5      AnalysisSessionImpl.getParsedLibraryByElement
> package:source_gen/src/type_checker.dart 305:16            UnresolvedAnnotationException._findSpan
> package:source_gen/src/type_checker.dart 344:24            new UnresolvedAnnotationException._from
> package:source_gen/src/type_checker.dart 114:43            TypeChecker._computeConstantValue
> package:source_gen/src/type_checker.dart 139:21            TypeChecker._annotationsWhere
> dart:core                                                  Iterable.isEmpty
> package:source_gen/src/type_checker.dart 73:20             TypeChecker.firstAnnotationOf
> package:json_serializable/src/utils.dart 17:21             _jsonKeyAnnotation
> package:json_serializable/src/utils.dart 27:5              hasJsonKeyAnnotation
> dart:collection                                            ListMixin.firstWhere
> package:json_serializable/src/field_helpers.dart 30:16     new _FieldSet
> package:json_serializable/src/field_helpers.dart 102:19    createSortedFieldSet.<fn>
> dart:core                                                  Iterable.toList
> package:json_serializable/src/field_helpers.dart 103:8     createSortedFieldSet
> package:json_serializable/src/generator_helper.dart 54:26  GeneratorHelper.generate
> 
> [SEVERE] json_serializable:json_serializable on lib/src/clpapi/**risk_factor.model.dart**:
> 
> Could not resolve annotation for `String? type`.
> package:source_gen/src/type_checker.dart 114:7             TypeChecker._computeConstantValue
> package:source_gen/src/type_checker.dart 139:21            TypeChecker._annotationsWhere
> dart:core                                                  Iterable.isEmpty
> package:source_gen/src/type_checker.dart 73:20             TypeChecker.firstAnnotationOf
> package:json_serializable/src/utils.dart 17:21             _jsonKeyAnnotation
> package:json_serializable/src/utils.dart 27:5              hasJsonKeyAnnotation
> dart:collection                                            ListMixin.firstWhere
> package:json_serializable/src/field_helpers.dart 30:16     new _FieldSet
> package:json_serializable/src/field_helpers.dart 102:19    createSortedFieldSet.<fn>
> dart:core                                                  Iterable.toList
> package:json_serializable/src/field_helpers.dart 103:8     createSortedFieldSet
> package:json_serializable/src/generator_helper.dart 54:26  GeneratorHelper.generate

**To Reproduce**

This is the '**risk_factor.model.dart**' 
Strange thing is that I have **String? type,** in other model classes but only this particular class gets the exception on build.

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'risk_factor.model.freezed.dart';
part 'risk_factor.model.g.dart';

@freezed
class RiskFactorModel with _$RiskFactorModel {
  factory RiskFactorModel({
    String? type,
    String? value,
    String? override,
  }) = _RiskFactorModel;

  factory RiskFactorModel.fromJson(Map<String, Object?> json) =>
      _$RiskFactorModelFromJson(json);
}
```

Flutter version:
> [✓] Flutter (Channel master, 2.6.0-1.0.pre.142, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
>     • Flutter version 2.6.0-1.0.pre.142 at <snip>
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision cf806f7d5f (3 hours ago), 2021-08-31 11:11:04 -0700
>     • Engine revision fe89463f14
>     • Dart version 2.15.0 (build 2.15.0-66.0.dev)
> 

Package versions in the lock:

> analyzer: version: "2.1.0"
> build_runner: version: "2.1.1"
> source_gen: version: "1.1.0"
> 

**Expected behavior**
Just building of this particular class is fine as the other model classes with freezed. I am not sure the exception caused by freezed or something else like as dart's bug but I would like to start with insights from @rrousselGit

**Comment by SunlightBro** [comment]
Your issue is with **json_serializable** not with **freezed**.

> [SEVERE] json_serializable:json_serializable on lib/src/clpapi/risk_factor.model.dart:

Also the issue is comes from the dot in your file name `risk_factor.model.dart` and not because your parameter is called **type**.

**Comment by chunghha** [comment]
In case, double post here as posted in the dart-lang/source-gen.

As I commented out the override property in the RiskFactorModel, the build gets fine. So now I think that "String? override" (which is also unique in the classes) is culprit instead of "String? type". 

Here is a diff of freezed.dart files without/with the override property for someone to take a look deeper.

diff -urN risk_factor.model.freezed.dart risk_factor.model.freezed-1.dart

```
--- risk_factor.model.freezed.dart      2021-09-01 10:35:41.000000000 -0500
+++ risk_factor.model.freezed-1.dart    2021-09-01 10:35:20.000000000 -0500
@@ -21,10 +21,11 @@
 class _$RiskFactorModelTearOff {
   const _$RiskFactorModelTearOff();
 
-  _RiskFactorModel call({String? type, String? value}) {
+  _RiskFactorModel call({String? type, String? value, String? override}) {
     return _RiskFactorModel(
       type: type,
       value: value,
+      override: override,
     );
   }
 
@@ -40,6 +41,7 @@
 mixin _$RiskFactorModel {
   String? get type => throw _privateConstructorUsedError;
   String? get value => throw _privateConstructorUsedError;
+  String? get override => throw _privateConstructorUsedError;
 
   Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
   @JsonKey(ignore: true)
@@ -52,7 +54,7 @@
   factory $RiskFactorModelCopyWith(
           RiskFactorModel value, $Res Function(RiskFactorModel) then) =
       _$RiskFactorModelCopyWithImpl<$Res>;
-  $Res call({String? type, String? value});
+  $Res call({String? type, String? value, String? override});
 }
 
 /// @nodoc
@@ -68,6 +70,7 @@
   $Res call({
     Object? type = freezed,
     Object? value = freezed,
+    Object? override = freezed,
   }) {
     return _then(_value.copyWith(
       type: type == freezed
@@ -78,6 +81,10 @@
           ? _value.value
           : value // ignore: cast_nullable_to_non_nullable
               as String?,
+      override: override == freezed
+          ? _value.override
+          : override // ignore: cast_nullable_to_non_nullable
+              as String?,
     ));
   }
 }
@@ -89,7 +96,7 @@
           _RiskFactorModel value, $Res Function(_RiskFactorModel) then) =
       __$RiskFactorModelCopyWithImpl<$Res>;
   @override
-  $Res call({String? type, String? value});
+  $Res call({String? type, String? value, String? override});
 }
 
 /// @nodoc
@@ -107,6 +114,7 @@
   $Res call({
     Object? type = freezed,
     Object? value = freezed,
+    Object? override = freezed,
   }) {
     return _then(_RiskFactorModel(
       type: type == freezed
@@ -117,6 +125,10 @@
           ? _value.value
           : value // ignore: cast_nullable_to_non_nullable
               as String?,
+      override: override == freezed
+          ? _value.override
+          : override // ignore: cast_nullable_to_non_nullable
+              as String?,
     ));
   }
 }
@@ -124,7 +136,7 @@
 /// @nodoc
 @JsonSerializable()
 class _$_RiskFactorModel implements _RiskFactorModel {
-  _$_RiskFactorModel({this.type, this.value});
+  _$_RiskFactorModel({this.type, this.value, this.override});
 
   factory _$_RiskFactorModel.fromJson(Map<String, dynamic> json) =>
       _$$_RiskFactorModelFromJson(json);
@@ -133,10 +145,12 @@
   final String? type;
   @override
   final String? value;
+  @override
+  final String? override;
 
   @override
   String toString() {
-    return 'RiskFactorModel(type: $type, value: $value)';
+    return 'RiskFactorModel(type: $type, value: $value, override: $override)';
   }
 
   @override
@@ -146,14 +160,18 @@
             (identical(other.type, type) ||
                 const DeepCollectionEquality().equals(other.type, type)) &&
             (identical(other.value, value) ||
-                const DeepCollectionEquality().equals(other.value, value)));
+                const DeepCollectionEquality().equals(other.value, value)) &&
+            (identical(other.override, override) ||
+                const DeepCollectionEquality()
+                    .equals(other.override, override)));
   }
 
   @override
   int get hashCode =>
       runtimeType.hashCode ^
       const DeepCollectionEquality().hash(type) ^
-      const DeepCollectionEquality().hash(value);
+      const DeepCollectionEquality().hash(value) ^
+      const DeepCollectionEquality().hash(override);
 
   @JsonKey(ignore: true)
   @override
@@ -167,7 +185,8 @@
 }
 
 abstract class _RiskFactorModel implements RiskFactorModel {
-  factory _RiskFactorModel({String? type, String? value}) = _$_RiskFactorModel;
+  factory _RiskFactorModel({String? type, String? value, String? override}) =
+      _$_RiskFactorModel;
 
   factory _RiskFactorModel.fromJson(Map<String, dynamic> json) =
       _$_RiskFactorModel.fromJson;
@@ -177,6 +196,8 @@
   @override
   String? get value => throw _privateConstructorUsedError;
   @override
+  String? get override => throw _privateConstructorUsedError;
+  @override
   @JsonKey(ignore: true)
   _$RiskFactorModelCopyWith<_RiskFactorModel> get copyWith =>
       throw _privateConstructorUsedError;
```

**Comment by SunlightBro** [comment]
Yes you can't use override as a parameter/variable name. The reason is that in the context of this generated class
```dart
@JsonSerializable()
class _$_RiskFactorModel implements _RiskFactorModel {...}
```
`override` will exist as an instance variable (field). 
So any/every `@override` in there will ref the instance variable, instead of the `const Object override = _Override();` from dart:core.

😑 sry I overlooked that in your first post ...

**Comment by chunghha** [comment]
@SunlightBro  thanks for taking a look. 
Yes, I did put same workaround,  https://github.com/dart-lang/source_gen/issues/555#issuecomment-910465300

I am closing this one, but leave the other one open in dart-lang/source_gen.

**Comment by chunghha** [comment]
@rrousselGit  would you see if there is any solution by freezed per this comment, https://github.com/dart-lang/source_gen/issues/555#issuecomment-910477985 ?

**Comment by rrousselGit** [comment]
I have hardly anything to say. As jake suggested, you should consider renaming your field to something else. At best, I could update Freezed to throw an error if naming a variable "override"

As for the warning, see the README. It is recommended to update your lints to ignore it.

**Comment by chunghha** [comment]
@rrousselGit  thanks for taking a look. 

I am using the model classes as data class to interface with backend services I can't update so the JsonKey workaround is just good enough.
