### ISSUE TITLE
How to generate positioned arguments in .when method.

### ISSUE THREAD

**Issue by FaKenKoala** [rrousselGit/freezed#508]
Is there an annotation to make the generated class's **when** method to generate positioned parameters instead of named parameters?

```
@freezed
class Animal with _$Animal {
  factory Animal.dog({required Color color, required int age}) = Dog;
  factory Animal.wolf({required int type}) = Wolf;
}

void animalAction(Animal animal) {
  animal.when(dog: dogBark, wolf: wolfHowl);
}
/// named parameters not fit
void dogBark({required Color color, required int age}) {}

/// positioned parameters fit
void wolfHowl(int type) {}
```

Like above, the dogBar method with positioned parameters is not fit with **when** method.

**Comment by rrousselGit** [comment]
There is no such thing at the moment.

It was judge to be far too verbose to use, and `map` instead of `when is a good alternative.
