### ISSUE TITLE
Generation issue on newer versions > 0.14.2

### ISSUE THREAD

**Issue by atoka93** [rrousselGit/freezed#514]
`freezed` not generated correctly after version `0.14.2` for the following example:

```
@freezed
class GameBoardViewModel with _$GameBoardViewModel {
  const factory GameBoardViewModel({
    required final Size2D boardSize,
    required final GameStatus gameStatus,
    required final ValueSetter<Direction> onDirectionChanged,
    required final VoidCallback onSpacePressed,
  }) = _GameBoardViewModel;
}
```

using `0.14.2` everything is generated as expected. 
on newer versions the following error is thrown:

```
[FINE] freezed:freezed on lib/ui/main/game_board.dart:Running FreezedGenerator
[SEVERE] freezed:freezed on lib/ui/main/game_board.dart:

Null check operator used on a null value
package:freezed/src/tools/type.dart 15:23                    resolveFullTypeStringFrom.<fn>
package:collection/src/iterable_extensions.dart 246:15       IterableExtension.firstWhereOrNull
package:freezed/src/tools/type.dart 13:40                    resolveFullTypeStringFrom
package:freezed/src/templates/concrete_template.dart 407:10  parseTypeSource
package:freezed/src/templates/properties.dart 44:13          Property.fromParameter
package:freezed/src/freezed_generator.dart 250:15            FreezedGenerator._parseConstructorsNeedsGeneration
package:freezed/src/freezed_generator.dart 55:41             FreezedGenerator.parseElement
package:freezed/src/parse_generator.dart 34:20               ParserGenerator.generate
package:source_gen/src/builder.dart 328:23                   _generate

```

**Comment by rrousselGit** [comment]
Hello!
Could you share an example that I can execute? I do not have access to the objects used in your snippet.

**Comment by iulian0512** [comment]
i had this exact issue with the following stacktrace 
["freezed:freezed on lib/logic/blocs/current_location_fld_cubit.dart",["","Null check operator used on a null value","#0     
 resolveFullTypeStringFrom.<anonymous closure> (package:freezed/src/tools/type.dart:15:23)
#1      IterableExtension.firstWhereOrNull (package:collection/src/iterable_extensions.dart:246:15)
#2      resolveFullTypeStringFrom (package:freezed/src/tools/type.dart:13:40)
#3      parseTypeSource (package:freezed/src/templates/concrete_template.dart:407:10)
#4      Property.fromParameter (package:freezed/src/templates/properties.dart:44:13)
<asynchronous suspension>
#5      FreezedGenerator._parseConstructorsNeedsGeneration (package:freezed/src/freezed_generator.dart:250:15)
<asynchronous suspension>
#6      FreezedGenerator.parseElement (package:freezed/src/freezed_generator.dart:55:41)
<asynchronous suspension>
#7      ParserGenerator.generate (package:freezed/src/parse_generator.dart:34:20)
<asynchronous suspension>
#8      _generate (package:source_gen/src/builder.dart:326:23)
<asynchronous suspension>
#9      Stream.toList.<anonymous closure> (dart:async/stream.dart)
<asynchronous suspension>
"]]


this is my freezed class

typedef GetLocalizedMsgCallback = String Function(BuildContext ctx);

@freezed
class CurrentLocationFldState with _$CurrentLocationFldState {
  const factory CurrentLocationFldState.noValue() = _Initial;
  const factory CurrentLocationFldState.hasValue(LatLonAcc llacc) = _HasValue;
  const factory CurrentLocationFldState.waitingForLocation() = _WaitLocation;
  const factory CurrentLocationFldState.noLocationAvailable(
      GetLocalizedMsgCallback getLocalizedMsgFunc) = _NoLocAvailable; -----crashed when having this .ctor, worked with it uncommended----
  const factory CurrentLocationFldState.error(dynamic e) = _Error;
}

it crashed when generating this class having this function as a parameter but after cleaning up the unused imports it works fine with this function parameter.

**Comment by atoka93** [comment]
Sorry @rrousselGit, totally spaced out on the objects the example was depending on. 😅 

Here you go:
```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'example.freezed.dart';

@freezed
class GameBoardViewModel with _$GameBoardViewModel {
  const factory GameBoardViewModel({
    required final Size2D boardSize,
    required final GameStatus gameStatus,
    required final ValueSetter<Direction> onDirectionChanged,
    required final VoidCallback onSpacePressed,
  }) = _GameBoardViewModel;
}

@freezed
class Size2D with _$Size2D {
  const factory Size2D({
    required final int width,
    required final int height,
  }) = _Size2D;
}

enum GameStatus { lobby, playing, paused, won, lost }

enum Direction { left, right, up, down }
```

Generated using:
```
freezed_annotation: 0.14.3
build_runner: 2.0.6
freezed: 0.14.5
```

**Comment by givip** [comment]
@atoka93 I have the similar problem, but your example does work as expected.

**Comment by noinskit** [comment]
I'm getting the same problem, with this stacktrace:
```
Null check operator used on a null value
package:freezed/src/tools/type.dart 15:23                    resolveFullTypeStringFrom.<fn>
package:collection/src/iterable_extensions.dart 246:15       IterableExtension.firstWhereOrNull
package:freezed/src/tools/type.dart 13:40                    resolveFullTypeStringFrom
package:freezed/src/templates/concrete_template.dart 407:10  parseTypeSource
package:freezed/src/templates/properties.dart 44:13          Property.fromParameter
package:freezed/src/freezed_generator.dart 250:15            FreezedGenerator._parseConstructorsNeedsGeneration
package:freezed/src/freezed_generator.dart 55:41             FreezedGenerator.parseElement
package:freezed/src/parse_generator.dart 34:20               ParserGenerator.generate
package:source_gen/src/builder.dart 325:23                   _generate
```

it's in this line in type.dart:
```
      if (type.element!.library!.isInSdk) return false;
```
...and in my case, `type` is `void Function()` and `type.element` is null.

I tried a minimal repro with a simple class with one field of type `void Function()`, but it didn't trigger this, so it must be more subtle.

**Comment by iulian0512** [comment]
i did
flutter clean
flutter pub get
flutter pub run build_runner build --delete-conflicting-outputs  
no more issues for me.

**Comment by rrousselGit** [comment]
Any way that you could share a way to reproduce the issue? Possibly a complete project with a pubspec.yaml and the lock file too.

**Comment by rrousselGit** [comment]
Also try changing the Flutter channel too. It may be related

**Comment by noinskit** [comment]
It's still broken, at least for me. Could you please try running the MCVE I pasted above? The error now moved to:
```dart
Element _getElementForType(DartType type) {
  if (type.element != null) {
    return type.element!;
  }
  return type.alias!.element; // <-- HERE
}
```

**Comment by smiLLe** [comment]
@rrousselGit having the same issue in 1.1.1 at the exact same place @noinskit  mentioned above.
This happens because of an aliased import like others mentioned above.
