### ISSUE TITLE
Default with constant issue

### ISSUE THREAD

**Issue by MoonyDevs** [rrousselGit/freezed#518]
Hello All,

First, thank you for the package.

Maybe I have misunderstood the documentation, I would like to use sealed class with default value as following code but it generate errors like bellow, does anyone can help me? 

Error: Getter not found: 'maleId'.
  Male male({int? id = maleId}) {
Error: Getter not found: 'maleId'.
  const _$Male({this.id = maleId});  
  

`/// Gender enum
part 'gender.freezed.dart';

@freezed
/// Gender object
class Gender with _$Gender {
  /// Man
  const factory Gender.male({@Default(maleId) int? id}) = Male;

  /// Woman
  const factory Gender.female({@Default(femaleId) int? id}) = Female;

  /// Undefined
  const factory Gender.other({@Default(otherId) int? id}) = Other;

  /// Get Gender from id
  static Gender fromId({required int id}) {
    switch(id) {
      case maleId: return const Male();
      case femaleId: return const Female();
      case otherId: return const Other();
      default: return const Other();
    }
  }
  static const int maleId = 0;
  static const int femaleId = 1;
  static const int otherId = 2;

  static const int defaultId = otherId;
}`

**Comment by rrousselGit** [comment]
The syntax is:

```dart
@Default(Gender.maleId)
```

**Comment by MoonyDevs** [comment]
Yes mybad, thank you, it works now !
