### ISSUE TITLE
When using freezed classes with rxdart's .distinct() collection equality doesn't seem to work.

### ISSUE THREAD

**Issue by timcreatedit** [rrousselGit/freezed#522]
I have a simple freezed class called LearnPlan that I use along with json_serializable and cloud firestore.
The class contains a list of seven bools to represent which days of the week are selected. In my data model, the LearnPlan object is contained within another freezed class called UserData. 

```dart
// learn_plan.dart (excerpt)
@freezed
class LearnPlan with _$LearnPlan {
  const LearnPlan._();

  const factory LearnPlan({
    required bool isRecommendation,
    required int minNewWordsPerDay,
    required List<bool> weekdays,
  }) = _LearnPlan;

  factory LearnPlan.fromJson(Map<String, dynamic> json) =>
      _$LearnPlanFromJson(json);
}
```

```dart
// user_data.dart (excerpt)
@freezed
class UserData with _$UserData {
  const factory UserData({
    required String? userId,
    required LearnPlan? learnPlan,
    @Default(false) bool isPro,
  }) = _UserData;

  factory UserData.fromJson(Map<String, dynamic> json) =>
      _$UserDataFromJson(json);
}
```

Now if I do this:
```dart
  Stream<LearnPlan?> get learnPlan$ => _userDataRepository.userData$
      .map((d) => d?.learnPlan)
      .where((p) => p != null)
      .distinct();
```
(where ``learnPlan$`` is just the Stream of UserData objects obtained directly from firestore)
Changes in the ``weekday`` list only get picked up every second time.
When overriding the equality check on the ``.distinct()`` and printing out the two LearnPlan objects that it receives, the weekday lists on both are identical every second time, which explains why they don't come through.

If I do this weird thing instead:
```dart
  Stream<LearnPlan?> get learnPlan$ => _userDataRepository.userData$
      .map((d) => d?.learnPlan)
      .where((p) => p != null)
      // TODO Why is this needed?
      .map((plan) => LearnPlan.fromJson(plan!.toJson()))
      .distinct();
```
everything works as intended.

I have no idea why this makes a difference, but it seems like some call by reference issue to me?

**Comment by rrousselGit** [comment]
Hello!

It could be anything. Could you share a better way to reproduce the problem? Ideally not dependent on your codebase

**Comment by timcreatedit** [comment]
Hi, thanks for your quick answer!
Sorry, but I don't have time to set up a minimal example right now, so I'll just have to live with this weird workaround.
I just thought that maybe you'd have an idea for what it could be.
Feel free to close the issue of course, maybe if I have time in the future, I'll get back to you with more info.
Thank you for your time!

**Comment by rrousselGit** [comment]
No problem. Good luck!
