### ISSUE TITLE
Support for generic annotations

### ISSUE THREAD

**Issue by nikitadol** [rrousselGit/freezed#524]
Dart now supports generic annotations
https://github.com/dart-lang/language/issues/1297
https://dart.dev/guides/language/evolution#dart-214

Can we use them instead?
https://github.com/rrousselGit/freezed/blob/b6e930e31eeb15b5fe66f72d329d10e29697301c/packages/freezed_annotation/lib/freezed_annotation.dart#L270

**Comment by nikitadol** [comment]
If it works out of the box, then it might be worth removing the extra constructor

**Comment by rrousselGit** [comment]
Yes, this is planned

**Comment by rockyoung** [comment]
how do we get the generic type from `annotation` which now is provided as a `ConstantReader` of pkg: source_gen
