### ISSUE TITLE
Factories should return specific types

### ISSUE THREAD

**Issue by fdietze** [rrousselGit/freezed#525]
**Is your feature request related to a problem? Please describe.**

I find it a bit annoying that factories return the supertype of a union instead of the specific type. For example, AFAIK I cannot write this without a cast, `map` or `maybeMap`:

```dart
@freezed
class Union with _$Union {
  const factory Union.data(int value) = Data;
  const factory Union.loading() = Loading;
}

int processData(Data data) { data.value + 7 }

processData(Union.Data(5)) // Does not type check, because Union.Data(...) is of type Union and not Union.Data
```

**Describe the solution you'd like**
Factories should return their specific types, in this case `Union.Data(...)` should have a return type of `Union.Data`

**Describe alternatives you've considered**
`maybeMap()` gives me the specific type, but then I have to handle the dead `orElse` case:

```dart
Union.Data(5).maybeMap(
    data: (data) => processData(data),
    orElse: () => 0
)
```

**Additional context**
I guess this is a dart language limitation, but maybe there's a practical workaround?

Thank you!

**Comment by rrousselGit** [comment]
That's not really how Dart works though, so this isn't doable.

**Comment by fdietze** [comment]
I see. Your solution without the prefix is good enough. Thank you!
