### ISSUE TITLE
Inheritance question

### ISSUE THREAD

**Issue by sdebruyn** [rrousselGit/freezed#53]
Do you have an example of how I can implement inheritance? E.g. type animal has a name and type cat has a name and a color...

**Comment by rrousselGit** [comment]
You don't.
Freezed classes are sealed. You cannot and should not try to extend them.

Use composition instead

**Comment by sdebruyn** [comment]
And the other way around? I create an abstract class and I want my freezed classes to implement them?

**Comment by rrousselGit** [comment]
The implements keyword works as usual. Methods are not supported though

**Comment by sdebruyn** [comment]
Alright, thanks for clearing that up!
