### ISSUE TITLE
Way to cast generic type variables

### ISSUE THREAD

**Issue by micimize** [rrousselGit/freezed#532]
**Is your feature request related to a problem? Please describe.**
When working with generic freezed classes there is not currently a straightforward way to change the generic type variable when it changes.

**Describe the solution you'd like**
* Somehow allowing attribute type overrides with `copyWith` would be the ideal API, but may be infeasible 
* A non-getter alternate API to `copyWith` may make sense (i.e. `castWith<T>()({T genericValue});`
* maybe a `.cast`-like attribute on `$FreezedCopyWith` would be more general than the above for deep copy

**Describe alternatives you've considered**
A dedicated `.cast` method directly on the freezed class would enable downcasting as in `List`, but would require an intermediate step in some cases (e.g. `C(value: "foo").cast<Object>().copyWith(value:1).cast<int>()`.

**Additional context**
I'm guessing this has been considered thoroughly already and is very difficult to pull off, especially given the deep copy API. Or maybe there's a syntax trick I missed here 😅

**Comment by rrousselGit** [comment]
This API would be fairly unsafe. I have therefore no plan to implement such a thing.
