### ISSUE TITLE
Why is freezed expanding typedefs?

### ISSUE THREAD

**Issue by Norbert515** [rrousselGit/freezed#533]
I'm sorry if this has been talked about before, but I wasn't able to find any documentation on this in the docs or in any issues.

What's the reason for typedefs being expanded instead of being included as the actual typedef?

I'm talking about this:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'f.freezed.dart';

typedef MyTypedef = Function(String it);

@freezed
class Demo with _$Demo {

  factory Demo.test(MyTypedef myTypedef) = DemoTest;

}
```

Resulting in this generated code:

```dart
abstract class DemoTest implements Demo {
  factory DemoTest(dynamic Function(String) myTypedef) = _$DemoTest;

  @override
  dynamic Function(String) get myTypedef;
  @override
  @JsonKey(ignore: true)
  $DemoTestCopyWith<DemoTest> get copyWith =>
      throw _privateConstructorUsedError;
}
```

What's the reason this couldn't be:

```dart
abstract class DemoTest implements Demo {
  factory DemoTest(MyTypedef myTypedef) = _$DemoTest;

  @override
  MyTypedef get myTypedef;
  @override
  @JsonKey(ignore: true)
  $DemoTestCopyWith<DemoTest> get copyWith =>
      throw _privateConstructorUsedError;
}
```

The downside with the typedef expansion is that the freezed class now has to import all the parameter types of the typedef (which in turn could possibly be not exposed if the typedef is in a package).

**Comment by rrousselGit** [comment]
Freezed isn't expanding typedefs per say. The analyzer is. That's what Freezed receives

With newer analyzer versions, it seems that it is possible to _explicitly_ use the typedef instead of the expanded expression, although this requires extra work and I haven't bothered.

Feel free to make a PR :)
