### ISSUE TITLE
freezed 1.5.1+1 Code generation error with @Implements<Interface<Type>> annotation

### ISSUE THREAD

**Issue by lvsecoto** [rrousselGit/freezed#535]
**freezed 1.5.1+1 Code generation error with @Implements annotation**

If interface has `<Type>`，the generated code is incorrect.

Here is an example.

```
 abstract class SearchResultWord {
   String get title;
 
   String get definition;
 
   String get phonetic;
 }
 
 abstract class SearchResultDictWord<T extends TranslationResult>
     extends SearchResultWord {
   T get translation;
 }
 
 @freezed
 class SearchResultItem with _$SearchResultItem {
 
   @Implements<SearchResultDictWord<TranslationResultOffline>>()
   factory SearchResultItem.offlineDictWord({
     required String title,
     required String definition, 
     required String phonetic, 
     required TranslationResultOffline translation, 
   }) = SearchResultOfflineDictWord; 
}
```
Generated code:
```
abstract class SearchResultOfflineDictWord
    implements SearchResultItem, SearchResultDictWord<dynamic> {
  factory SearchResultOfflineDictWord(
          {required String title,
          required String definition,
          required String phonetic,
          required TranslationResultOffline translation}) =
      _$SearchResultOfflineDictWord;

  String get title;
  String get definition;
  String get phonetic;
  TranslationResultOffline get translation;
  @JsonKey(ignore: true)
  $SearchResultOfflineDictWordCopyWith<SearchResultOfflineDictWord>
      get copyWith => throw _privateConstructorUsedError;
}

```

`implements SearchResultItem, SearchResultDictWord<dynamic>` should be 
`implements SearchResultItem, SearchResultDictWord<TranslationResultOffline>`

**Comment by rrousselGit** [comment]
Looking back at this, the problem stems from the fact that you are doing `@With<UnionCase>()`

In general I'd discourage against using the redirected class (`factory MyClass(..) = <<this>>`) as input of another class.
The analyzer will be unable to know that the generated class exist, so the code-generator will receive `dynamic`. That makes everything hellish to handle

**Comment by rrousselGit** [comment]
Closing this as supporting this would be too difficult, and metaprogramming should fix such problem naturally.
