### ISSUE TITLE
Allow fallbackUnion fallback to its value.  

### ISSUE THREAD

**Issue by HJ29** [rrousselGit/freezed#538]
**Is your feature request related to a problem? Please describe.**
When using fallbackUnion,
``` dart
// union.dart
...
@Freezed(unionKey: 'key', fallbackUnion: 'default')
class BaseUnion with _$BaseUnion {
  const factory BaseUnion(
      {required String key}) = Fallback;

  @FreezedUnionValue('special')
  const factory BaseUnion.special(
      {required String key}) = Special;

  factory BaseUnion.fromJson(Map<String, dynamic> json) =>
      _$BaseUnionFromJson(json);
}
...
```
freeze auto generate `toJson` like this, overwrite key to 'default',
``` dart
// union.freezed.dart
...
 @override
  Map<String, dynamic> toJson() {
    return _$_$FallbackToJson(this)..['key'] = 'default';
  }
...
```

``` dart
final result = BaseUnion.fromJson({'key': 'random'});
// result.key is 'random'
final json = result.toJson();
// json['key'] is 'default'
```
I thought `json['key']` will be same as `result.key`, but they aren't.
Are there a way to make it fallback to `'random'` instead of `'default'`?

**Describe the solution you'd like**
Maybe an extra parameter for `@Freezed(unionKey: 'key', fallbackUnion: 'default', fallbackOverwrite: false)`,
then `toJson` will become something like below
``` dart
// union.freezed.dart
...
 @override
  Map<String, dynamic> toJson() {
    return _$_$FallbackToJson(this)';
  }
...
```
I don't actually understand why fallbackUnion behaves like this,
so I am not sure if this solution make sense to you.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by rrousselGit** [comment]
This is indeed unexpected. I'll think about what can be done to change this. I'd be happy to review a PR though :)
