### ISSUE TITLE
Coverage bug on flutter beta

### ISSUE THREAD

**Issue by Kiruel** [rrousselGit/freezed#541]
**Describe the bug**
When I `flutter test --coverage` on the channel beta (2.6.0-5.2.pre) the state file is taken to the coverage. But when I'm on the flutter stable (2.5.3) he doesn't. I suspect the beta change something on the coverage and now the state file is taken during the coverage.

**To Reproduce**

Use `flutter test --coverage` inside a project that use freezed when you are on the beta channel of flutter.

**Expected behavior**
Should not take the state file during the coverage test.

On the stable version of Flutter:
![Screenshot 2021-10-19 at 14 40 08](https://user-images.githubusercontent.com/8250175/137911034-bcbd049c-6cf8-484c-b359-b111f807d58f.png)

On the beta version of Flutter:
![Screenshot 2021-10-19 at 14 40 42](https://user-images.githubusercontent.com/8250175/137911142-06756576-dcda-4074-bb77-dd3b615c49c7.png)

**Comment by rrousselGit** [comment]
Hello!

Was this filed on the wrong repository? Freezed is not responsible for coverage reports.

**Comment by Kiruel** [comment]
Thanks, was fixed on https://github.com/flutter/flutter/issues/95008#issuecomment-995275929 :)
