### ISSUE TITLE
Implementing interface within a freezed class

### ISSUE THREAD

**Issue by victorblaess** [rrousselGit/freezed#543]
Hey guys,

I have followed they documentation for the following case but it seems to be outdated.

```dart
abstract class GeographicArea {
  int get population;
  String get name;
}

@freezed
class Example with _$Example {
  const factory Example.person(String name, int age) = Person;

  @Implements<GeographicArea>()
  const factory Example.city(String name, int population) = City;
}
```

I actually cant set the type at @implements in <> anymore. I'll give them as parameter.

**Comment by rrousselGit** [comment]
This isn't an error, the document is up-to-date.

Chances are your Dart SDK version is too old. You will need to upgrade your Dart version for it to work.
