### ISSUE TITLE
Support `json_serializable` 6.0.1

### ISSUE THREAD

**Issue by SunlightBro** [rrousselGit/freezed#545]
**Upgrade the json_serializable and json_annotation dependencies**
- [ ] Added support for JsonSerializable.constructor to allow specifying an alternative constructor to invoke when creating a fromJson helper.
- [x] Support the new @JsonEnum annotation in package:json_annotation.
- [x] Support JsonKey.nullForUndefinedEnumValue as a value for JsonKey.unknownEnumValue when you want to use null as the unknown value.
- [ ] Use the new $enumDecodeNullable and $enumDecode in `json_annotation' instead of generating these for each library. NOTE: This is a potential breaking change if any user code relies on the previously generated private functions.
- [x] The builder now checks to make sure there is a correctly constrained dependency on package:json_annotation.
- [x] Require Dart SDK >=2.14.0.
- [x] Require json_annotation '>=4.3.0 <4.4.0'.

**Comment by rrousselGit** [comment]
Thanks for the help!
