### ISSUE TITLE
`FreezedClass<FreezedUnionClass> variable` generates invalid/dynamic nested copyWith getter

### ISSUE THREAD

**Issue by micimize** [rrousselGit/freezed#548]
Env: `Dart 2.15.0 (build 2.15.0-178.1.beta)`, `freezed: 0.15.0+1`, freezed_annotation: 0.15.0`

I'm seeing a strange code generation issue in the following case:
1. My top-level `@freezed` union `Top` has an also-freezed variable `v`
2. `v`'s type is `Var<Option>`, where `Option` is an option within a `@freezed` union `Union`
3. The generated nested `copyWith.v`is then generated with the signature `$VCopyWith<dynamic, $Res> get v`

If `Option` is changed to `Union` there is no issue. I also haven't tested if this is the case when `Top` is not a union.

 Code:
```dart
@freezed
abstract class GoalProgress with _$GoalProgress {
  GoalProgress._();
  factory GoalProgress.task({
    /// another file contains `const factory MetricValue.number(num value) = NumberValue`
    required Target<NumberValue> target,
  }) = TaskProgress;

  factory GoalProgress.metric() = MetricProgress;
}

/* generated */

/// @nodoc
class _$TaskProgressCopyWithImpl<$Res> extends _$GoalProgressCopyWithImpl<$Res>
    implements $TaskProgressCopyWith<$Res> {
  // other correct generated code ....

  @override
  $TargetCopyWith<dynamic, $Res> get target {
    return $TargetCopyWith<dynamic, $Res>(_value.target, (value) {
      return _then(_value.copyWith(target: value));
    });
  }
}
```

**Comment by Aqluse** [comment]
I have this issue too

**Comment by volskaya** [comment]
Same here, on v1.1.1.


Maybe a simple toggle in `build.yaml` would suffice, just to unblock people who don't use nested copyWith in their code?

**Comment by rrousselGit** [comment]
> * `v`'s type is `Var<Option>`, where `Option` is an option within a `@freezed` union `Union`

That's the core of the issue


I would discourage from relying of the option's type The problem is that this class doesn't exist when the code-generator runs

As such, the Analyzer says that the type is dynamic, and Freezed uses that. 

Supporting those cases is really difficult. And metaprogramming should fix most of those cases. So I don't plan on working on this

**Comment by fzyzcjy** [comment]
Hi, is it possible to add a toggle to avoid generating nested copyWith, such that the error will not happen? Thanks!

**Comment by fzyzcjy** [comment]
It seems possible to remove generation of *deep nested* copyWith and only remain shallow copywith: https://github.com/fzyzcjy/freezed/commit/3a7165fb85440ce40ff240dff649cbfa7eee6dbe

If you like, I can make a PR adding a option to `Freezed`
