### ISSUE TITLE
Replacing @Implements with @With results in an error

### ISSUE THREAD

**Issue by matthewfx** [rrousselGit/freezed#560]
**Describe the bug**
I've replaced @Implements with @With but VS code is showing the Extra Positional Arguments error. Too many positional arguments: 0 expected, but 1 found.

**To Reproduce**
Everything was working fine in 0.14.3 when I updated it a few weeks ago to 0.15 the above error was displayed. I gave up. Today I tried updating to 1.0.0 but the same issue happened. Is there anything else I should do in order for it to work (apart from replacing the old annotation with the new one)

Nevertheless. Thank you very much for your great packages. Hats off to you!

**Comment by rrousselGit** [comment]
Do you have some code to reproduce the issue? It isn't clear with this description how you got this error.

**Comment by matthewfx** [comment]
So the below code works perfectly with @Implements and Freezed 0.14.5 but when Freezed is upgraded and @Implements replaced with @With than the build runner successfully generates code but there are errors in both the original file and the generated .freezed.dart file 

'
import 'package:freezed_annotation/freezed_annotation.dart';

part 'freezed_classes.g.dart';
part 'freezed_classes.freezed.dart';

enum TargetCriteria { EXACTLY, ATLEAST, ATMOST }
enum DayOfWeek { SUN, MON, TUE, WED, THU, FRI, SAT }

abstract class AggregatedDailyGoalValueBase {
  String? get systemCode;
  TargetCriteria? get criteria;
  String? get criteriaValue;
  String? get aggregatedValue;
  bool? get met;
  String? get date;
  DayOfWeek? get dayOfWeek;
}

abstract class AggregatedWeeklyGoalValueBase {
  List<AggregatedDailyGoalValueBase>? get days;
  TargetCriteria? get daysCriteria;
  int? get daysCriteraValue;
  int? get daysMet;
  bool? get met;
  String? get date;
}

@Freezed(unionKey: '__typename', unionValueCase: FreezedUnionCase.pascal)
class AggregatedGoalValue with _$AggregatedGoalValue {
  @With(AggregatedDailyGoalValueBase)
  @FreezedUnionValue('AggregatedDailyGoalValue')
  const factory AggregatedGoalValue.daily(
      {String? systemCode,
      TargetCriteria? criteria,
      String? criteriaValue,
      String? aggregatedValue,
      bool? met,
      String? date,
      DayOfWeek? dayOfWeek}) = AggregatedDailyGoalValue;

  @With(AggregatedWeeklyGoalValueBase)
  @FreezedUnionValue('AggregatedWeeklyGoalValue')
  const factory AggregatedGoalValue.weekly(
      {List<AggregatedDailyGoalValue>? days,
      TargetCriteria? daysCriteria,
      int? daysCriteraValue,
      int? daysMet,
      bool? met,
      String? date}) = AggregatedWeeklyGoalValue;
  factory AggregatedGoalValue.fromJson(Map<String, dynamic> json) =>
      _$AggregatedGoalValueFromJson(json);
}
'
