### ISSUE TITLE
Equality of non-dart:core lists broken (ie: Uint8List)

### ISSUE THREAD

**Issue by CelticMajora** [rrousselGit/freezed#561]
**Describe the bug**
As of https://github.com/rrousselGit/freezed/pull/529, the generated `==` operator does not use `DeepCollectionEquality()` for non-dart:core lists since they don't fall under the category of `isPossiblyDartCollection`. I ran into this issue upgrading from version `^0.14.2` to `0.15.1+1` on a freezed class that uses a `Uint8List` as a property and some equality tests began failing.

Happy to help dig in on this as well! Let me know if there is any additional information I can provide.

**To Reproduce**
```dart
import 'dart:typed_data';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:test/test.dart';

part 'example.freezed.dart';

@freezed
class ExampleWithUint8List with _$ExampleWithUint8List {
  factory ExampleWithUint8List({
    required Uint8List typedDataList,
    required List<int> dartCoreList,
  }) = _ExampleWithUint8List;
}

void main() {
  test('equality', () {
    final first = ExampleWithUint8List(
      typedDataList: Uint8List.fromList([0, 1]),
      dartCoreList: [0, 1],
    );
    final second = ExampleWithUint8List(
      typedDataList: Uint8List.fromList([0, 1]),
      dartCoreList: [0, 1],
    );

    // This expectation should succeed, but fails. Note the dartCoreList will be equal in this example
    expect(first, second);
  });
}
```

**Expected behavior**
The expected behavior would be that non-dart:core lists would also cause the generator to use `DeepCollectionEquality()` rather than `==` when generating the `==` operator for the enclosing freezed object.

**Comment by rrousselGit** [comment]
Fixed as pat of 1.0.2
