### ISSUE TITLE
Deactivate maybeMap generation

### ISSUE THREAD

**Issue by aloisdeniel** [rrousselGit/freezed#562]
# Is your feature request related to a problem? Please describe

The `maybeMap` method from generated unions introduced a lot of issues in my recent projects. Union cases were added later on during development and were not processed in many places where `maybeMap` is used.

# Describe the solution you'd like

I would like to deactivate the `maybeMap` method generation (*with a `build.yaml` options?*) to enforce all developers to process every state each time a new state is introduced in a union type.

# Describe alternatives you've considered

We have considered adding a lint rule at the dev/CI level.

**Comment by realshovanshah** [comment]
Can we do the same for the `copyWith` method? @Lyokone would your help be possible in this too? I'll try to see if I can create a PR first.

**Comment by Lyokone** [comment]
Hey, the PR should be pretty similar to #565. Happy to help if needed. Not sure what would be the use case tho?

**Comment by realshovanshah** [comment]
I have filled an issue describing the my problem here: #587.
#576 also seemed to have a use case for this.
