### ISSUE TITLE
Allow custom annotations to mark only said properties to be considered for equality checks.

### ISSUE THREAD

**Issue by srikanth-vm** [rrousselGit/freezed#563]
**Is your feature request related to a problem? Please describe.**
Currently I am not sure if there is any way where we can override the equality checks being run against all properties.

**Describe the solution you'd like**
Consider proving an annotation which includes only the annotated properties for equality checks. 

**Describe alternatives you've considered**
Nothing as classes generated with freezes cannot be extended.

**Additional context**
Consider below class 

```
class Foo with _$Foo {
  const factory Foo({required String id, required String name, required String email}) = _Foo;
}
```

Now all of the properties are considered when comparing two objects in the overridden `==` method.
How can I exclude some properties ?

**Comment by rrousselGit** [comment]
There is no such thing.

But you can manually implement `==` to behave as you want to.
