### ISSUE TITLE
Different behaviour when fromJson factory uses the arrow notation rather instead of a block

### ISSUE THREAD

**Issue by vmorilla** [rrousselGit/freezed#567]
**Describe the bug**
Freezed produces different code when a fromJson factory is defined using the arrow notation. It seems it tries to generate json_serializable methods producing a compilation error.

**To Reproduce**
The following snippet reproduces the problem. The code is a simple class with two custom methods (fromJson and toJson). However, it produces an error: *Telephone.toJson' ('String Function()') isn't a valid override of '_$Telephone.toJson' ('Map<String, dynamic> Function()')*.

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'telephone.freezed.dart';

@freezed
class Telephone with _$Telephone {
  const factory Telephone(int country, int number) = _Telephone;

  const Telephone._();

  static final _regexp = RegExp(r"\+(\d+)\w+(\d+)");

  factory Telephone.fromJson(String json) => Telephone(
      int.parse(_regexp.matchAsPrefix(json)!.group(1)!),
      int.parse(_regexp.matchAsPrefix(json)!.group(2)!));

  String toJson() => "+$country $number";
}
```

**Expected behavior**
However, the following snippet (just replacing the arrow notation for block notation in the fromJson factory) produces the expected result: no json_serialize code, just two custom methods.

```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'telephone.freezed.dart';

@freezed
class Telephone with _$Telephone {
  const factory Telephone(int country, int number) = _Telephone;

  const Telephone._();

  static final _regexp = RegExp(r"\+(\d+)\w+(\d+)");

  factory Telephone.fromJson(String json) {
    final match = _regexp.matchAsPrefix(json)!;
    return Telephone(int.parse(match.group(1)!), int.parse(match.group(2)!));
  }

  String toJson() => "+$country $number";
}
```

**Comment by rrousselGit** [comment]
This is the expected behavior.

If you don't want json_serializable to generate from/toJson, use a block for your fromJson. Otherwise use an arrow
