### ISSUE TITLE
@Default annotation, json_serializable warning

### ISSUE THREAD

**Issue by laurensdewaele** [rrousselGit/freezed#568]
**Describe the bug**
When using the `@Default()` annotation, json_serializable spits out a warning message:

> [INFO] json_serializable:json_serializable on model.dart:The default value `0` for `id` is defined twice in the constructor and in the `JsonKey.defaultValue`.

**To Reproduce**
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'document.freezed.dart';
part 'document.g.dart';

@freezed
class Document with _$Document {
  factory Document({
    @Default(0) int id,
  }) = _Document;

  factory Document.fromJson(Map<String, dynamic> json) =>
      _$DocumentFromJson(json);
}
```

With the following dependencies:
```
build_runner: ^2.0.6
freezed: ^1.0.0
freezed_annotation: ^1.0.0
json_annotation: ^4.4.0
json_serializable: ^6.0.1
```

**Expected behavior**
No warning messages by json_serializable.

**Comment by SunlightBro** [comment]
This not a Warning just an Info and it's working the intened way, have a look at this https://github.com/google/json_serializable.dart/issues/1023

**Comment by laurensdewaele** [comment]
Thanks for the reply SunlightBro,

The generated is something like this:
```
/// @nodoc
@JsonSerializable()
class _$_Document implements _Document {
  _$_Document({this.id = 0});

  factory _$_Document.fromJson(Map<String, dynamic> json) =>
      _$$_DocumentFromJson(json);

  @JsonKey(defaultValue: 0)
  @override
  final int id;
 ....
}
```

Here we in fact do see a default value in the constructor, and a @JsonKey defaultValue annotation as well.
json_serializable is telling us one is redundant and can be removed.

Is the issue than not with Freezed, for generating redundant code?
