### ISSUE TITLE
(With PR) Add `avoid_equals_and_hash_code_on_mutable_classes` to suppress linter warnings

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/freezed#574]
Hi thanks for the wonderful lib! Since I use a bit stricter linter rules, I would appreciate it if `avoid_equals_and_hash_code_on_mutable_classes` could be added to suppress linter warnings.

I do not use the ignores in analysis_options, since I still want the analyzer to work on those generated files to give me, for example, quick jumps.

**Comment by rrousselGit** [comment]
Closing as 1.1.1 should fix that
