### ISSUE TITLE
build error regarding analyzer "getParsedLibraryByElement2"

### ISSUE THREAD

**Issue by maestrolsj** [rrousselGit/freezed#575]
**Describe the bug**

-   freezed_annotation: ^0.14.2
-   freezed: ^0.14.5
-   analyzer: ^3.0.0
- 
There is an build error

` ../../development/flutter/.pub-cache/hosted/pub.dartlang.org/freezed-0.14.5/lib/src/utils.dart:33:38: Error: The method 'getParsedLibraryByElement2' isn't defined for the class 'AnalysisSession'.
 - 'AnalysisSession' is from 'package:analyzer/dart/analysis/session.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-3.0.0/lib/dart/analysis/session.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getParsedLibraryByElement2'.
      final result = library.session.getParsedLibraryByElement2(library)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 981ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.`

**To Reproduce**

flutter packages pub run build_runner build --delete-conflicting-outputs

**Comment by SunlightBro** [comment]
@maestrolsj 
Version ^0.14.5 of `freezed` did depend on `analyzer` ^2.0.0.
[2.1.0](https://pub.dev/packages/analyzer/changelog#210) of analyzer changed and deprecated those functions:
- Deprecated and renamed AnalysisSession.getXyz2() into getXyz().

[3.0.0](https://pub.dev/packages/analyzer/changelog#300) then completely removed these old methods:
- Removed deprecated methods from AnalysisSession.

Your best action would be to upgrade to the newest version of freezed (and all it's transitive dependencies).
If thats not possible consider to add a `dependency_overrides:`  to force analyzer 2.0.0.

**Comment by rrousselGit** [comment]
You're using an old version of freezer ( 0.14.5 as per your error message)

Upgrade that version to the latest available and the error should go away
