### ISSUE TITLE
Default collection values

### ISSUE THREAD

**Issue by victor-tinoco** [rrousselGit/freezed#578]
Consider this minimal freezed object:
```dart
@freezed
class FreezedCollectionTestClass with _$FreezedCollectionTestClass {
  factory FreezedCollectionTestClass({
    @Default(<String>[]) List<String> myList,
    @Default(<String>{}) Set<String> mySet,
  }) = _FreezedCollectionTestClass;
}
```
The resulting code is as this:
```dart
/// @nodoc
class _$FreezedCollectionTestClassTearOff {
  const _$FreezedCollectionTestClassTearOff();
  _FreezedCollectionTestClass call(
      {List<String> myList = const <String>[],
      Set<String> mySet = const <String>{}}) {
    return _FreezedCollectionTestClass(
      myList: myList,
      mySet: mySet,
    );
  }
}
```
Note that, even if the `@Default` value is non-constant, the generated code is a `const` collection.

This leads to inconsistent behavior. If I don't pass any list to the constructor, I won't be able to modify the internal list with collection methods like `.add`, while if I pass a collection as argument, unless I explicitly pass a `const` collection, I will be able.

The fact that we have different behavior if we pass or not an argument is not ideal and easily results in bugs, as happened in my job's project

**Comment by mateusfccp** [comment]
The default collection you are providing is not non-constant. `@Default` is constant, as all annotations are, and thus all the arguments you pass to it are constant. This is why the generated code uses also constant collections.

**Comment by victor-tinoco** [comment]
I understand the cause, the problem is this non-obvious behaviour according to pass or not arguments. Wouldn't be better to cast all collections to an unmodifiable one?

**Comment by rrousselGit** [comment]
> I understand the cause, the problem is this non-obvious behaviour according to pass or not arguments. Wouldn't be better to cast all collections to an unmodifiable one?

I'm not sure what this means.

What would "casting all collections to an unmodifiable one" entail?

**Comment by victor-tinoco** [comment]
In order to make all collections behave equally, there is a way to convert all collections to an unmodifiable one?

**Comment by rrousselGit** [comment]
Dart does not have a type for immutable lists. You're free to rely on a third-party package for that.


We could have Freezed convert `List` instances into a custom third-party immutable list implementation, but I don't think that is desirable.

**Comment by scopendo** [comment]
Dart has `UnmodifiableListView` in dart:collection.  Wouldn't that be suitable?

**Comment by rrousselGit** [comment]
I've been considering it for a while


Although it isn't truly perfect:
- UnmodifiableListView does not override == and it breaks the identity
- it is not compile-safe, meaning it's still possible to write code that invoke `add`
- it's a breaking change, and one that is fairly hard to detect on top of that

**Comment by rrousselGit** [comment]
Closing this as this behavior is expected.

Defaults values must be constant. If you want non-constant initializers, there is an issue for this: https://github.com/rrousselGit/freezed/issues/64
