### ISSUE TITLE
Too much code is generated

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/freezed#580]
Hi thanks for the wonderful lib, and congratulations that this becomes "flutter favorite"!

However, I see a very simple usage generates thousands of lines of code. This makes, for example,

* bigger app size
* slower compile speed

and so on. So I wonder whether it can be reduced.

**Comment by rrousselGit** [comment]
> bigger app size

Dart only ships what you use, so it doesn't matter

> So I wonder whether it can be reduced.

What exactly do you want to be reduced?

**Comment by fzyzcjy** [comment]
@rrousselGit Thanks for the reply!

> Dart only ships what you use, so it doesn't matter

You are right. But IMHO the compile speed is slower b/c Dart needs to consider a lot of code.

> What exactly do you want to be reduced?

Code size

**Comment by rrousselGit** [comment]
> Code size

That's too broad. What exactly do you think can be removed?

It's not clear to me that we can remove code without losing features.

**Comment by fzyzcjy** [comment]
@rrousselGit Well my main concern is the compile speed and code linter speed etc. But after re-reading those code I agree it is hard to remove code without losing features... Anyway thanks for the reply
