### ISSUE TITLE
Async equivalents for `map` and `when`

### ISSUE THREAD

**Issue by mensch272** [rrousselGit/freezed#582]
**Is your feature request related to a problem? Please describe.**
While sync is useful inside widget build methods, async equivalents would be more useful when using the generated classes in logical components.

Let's say I have a class named `ProcessState<T>`

```
@freezed
class ProcessState<T> with _$ProcessState<T> {
  const factory ProcessState.input() = ProcessStateInput;
  const factory ProcessState.data(T data) = ProcessStateData;
  const factory ProcessState.terminated(String reason) = ProcessStateTerminated;
}
```

If I use `when` inside an async business logic component like shown below

```
option.when(
  input: () {},
  data: (value) async {
    // calculations
  },
  terminated: () {},
)
```

It hangs, to fix it I need to have it so that I can await the `when` method.

**Describe the solution you'd like**
I would like to have async equivalents for `map` and `when`, which can potentially be named `mapAsync` and `whenAsync` respectively.

**Describe alternatives you've considered**
There are no alternatives I know of.

**Comment by rrousselGit** [comment]
I do not understand what an async when/map would do. Do you have an example of how this would look like and how this would be implemented?

I also do not understand why you believe when/map don't properly allow async logic. I

**Comment by mensch272** [comment]
I tried to use when inside an async method, the above-mentioned syntax and it hanged the whole flutter app. So I made a custom method for the class:

```
Future<R> whenAsync<R>({
  required Future<R> Function() inout,
  required Future<R> Function(T value) data,
  required Future<R> Function(String reason) terminated,
}) async {
  ...
}
```

Which allowed me to use it as below

```
await option.whenAsync(
  input: () {},
  data: (value) async {
    // calculations
  },
  terminated: () {},
)
```

And this fixed the situation.

Maybe I'm misreading this, I encountered this in a somewhat complicated project. Might be worth making a minimal project to check.

**Comment by rrousselGit** [comment]
> Might be worth making a minimal project to check.

Definitely. I don't see why the method you created would change anything to your issue.

To begin with, the problem is most likely with your callbacks.

**Comment by mensch272** [comment]
I tested a couple more scenarios and was able to get it to work as-is.

**Comment by garysm** [comment]
Is there a reason why `map` and `when` cannot be marked as async? For example, if I use `when` inside of an async function, it throws the error **Asynchronous error cant serialize such type**

Example: 
```dart
message.whenOrNull(
  create: (String name) async {
    // Perform async operations
  },
  join: () {
  },
);
```

Would the alternative be to use a callback?

**Comment by rrousselGit** [comment]
Try adding generic parameters on `whenOrNull`. That could be the problem

**Comment by garysm** [comment]
> Is there a reason why `map` and `when` cannot be marked as async? For example, if I use `when` inside of an async function, it throws the error **Asynchronous error cant serialize such type**
> 
> Example:
> 
> ```dart
> message.whenOrNull(
>   create: (String name) async {
>     // Perform async operations
>   },
>   join: () {
>   },
> );
> ```
> 
> Would the alternative be to use a callback?

This can be disregarded.  I've determined the issue is not coming from Freezed.
