### ISSUE TITLE
Inheritance must be restricted no prevented

### ISSUE THREAD

**Issue by MohammedElotol** [rrousselGit/freezed#585]
After looking at the meaning of sealed class in **JAVA** and **KOTLIN**
I figured out that sealed classes **restrict** and **doesn't prevent** Inheritance 

> All direct subclasses of a sealed class are known at compile time

### Java example:
`public abstract sealed class Vehicle permits Car, Truck {}
`
`public non-sealed class Car extends Vehicle {}`

In Java you have to use `final class` to prevent inheritance, but `sealed class` has another purpose.

**Freezed should allow us to determine what classes must extend a sealed class therefore these subclasses can add further implementation.**

### References:
[Java](https://www.baeldung.com/java-sealed-classes-interfaces)
[Kotlin](https://kotlinlang.org/docs/sealed-classes.html)

**Comment by rrousselGit** [comment]
Inheritance isn't restricted, it's not supported.

There is no way to specify support constructors at the moment because Freezed is relying on `factory` to work. This is a technical limitation
