### ISSUE TITLE
Separate between Data Class and Sealed Class

### ISSUE THREAD

**Issue by realshovanshah** [rrousselGit/freezed#587]
Reopening #576

As the title say, a condition to generate only Data Class or Sealed Class would be really helpful for those looking for only one of the use case. 

Now, to get to the actual issue that I was facing:

<img width="694" alt="Screen Shot 2022-01-21 at 16 37 49" src="https://user-images.githubusercontent.com/53654505/150514884-273e3c15-3262-48cc-aa11-42ebb62c452d.png">

This was the precise message that the compiler was showing: _Try adjusting the supertypes of this class to remove the inconsistency.dart(inconsistent_inheritance_getter_and_method)_

The class the I am extending from, let's call it class Parent, already has a `copyWith` method. (As classes often do.) The external Parent class is not in my control, so I cannot remove or shadow the `copyWith` method from it. But the freezed class is something that I have control over so I argue for separation between data & sealed class. Or maybe make it optional in the same way `maybeWhen` and `maybeMap` are.

I did try some other workaround but didn't find any way to shadow the `copyWith` method. 
To be precise, I tried make it protected with the @protected annotation but was of no help. And I don't think there's any way of choosing which method to use when using inheritance.

I am currently at a roadblock so if anyone has previously solved parent classes that expose a method with a same name.

**Comment by rrousselGit** [comment]
Inheriting Freezed classes is not supported.
For the simple reason that when using factory constructors, we cannot specify "super"

**Comment by realshovanshah** [comment]
Do you mean that I am not able to extend my freezed data classes with any other class? 
Because, when I do so, the compiler doesn't complain and the build runner works just fine too.

**Comment by rrousselGit** [comment]
Even without the need for "super", it's still not supported to subclass freezed classed

As you've seen, you'll get a clash on various properties like copyWith and possibly the when/map functions

**Comment by realshovanshah** [comment]
It actually compiles fine if there are no name collisions. Am I missing something here?
<img width="649" alt="Screen Shot 2022-01-21 at 22 48 30" src="https://user-images.githubusercontent.com/53654505/150569074-c9922949-0912-40a1-a6c9-349649125675.png">

In the previous screenshot, it's not compiling because the generated freezed mixin has a `copyWith` method. So, what do you think about #576 ? This would be really helpful for avoiding name collisions.

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/freezed/issues/636
