### ISSUE TITLE
Dart expects a different library than what is created with part '....freezed.dart' after renaming folder

### ISSUE THREAD

**Issue by Wizzel1** [rrousselGit/freezed#588]
**Describe the bug**
I want to create a Class named "PlatformAccount". 

Its located under ../models/platform_account/platform_account.dart 

It looks like this: 
```dart 
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'platform_account.freezed.dart';

@freezed
class PlatformAccount with _$PlatformAccount {
  const factory PlatformAccount({
    required String accountId,
    required String platformType,
    required String accountName,
    required String updateStatus,
    String? errorCode,
  }) = _PlatformAccount;

  factory PlatformAccount.fromJson(Map<String, dynamic> json) => _$PlatformAccountFromJson(json);
}
```

After I run `flutter pub run build_runner build --delete-conflicting-outputs` a file named `platform_account.freezed.dart` is created - as expected. However I am getting an error 
```
Expected this library to be part of 'package:podsuite/models/platform_account/platform_Account.dart', not 'package:podsuite/models/platform_account/platform_account.dart'.
Try including a different part, or changing the name of the library in the part's part-of directive.dartpart_of_different_library
```

I have renamed the folder from platform_Account to platform_account. So why is it still expecting the wrong library ?

I  tried flutter clean but that didn't work

**Comment by rrousselGit** [comment]
Try clearly your cache and restarting the command

In any case this error isn't cause by Freezed. It is likely coming from build_runner/source_gen. So not much I can do here

**Comment by Wizzel1** [comment]
Okay thanks for your quick response 👍
