### ISSUE TITLE
Custom json converter without a wrapper class

### ISSUE THREAD

**Issue by Kounex** [rrousselGit/freezed#592]
**Goal:** applying / using a custom `JsonConverter` on a freezed class with multiple constructors without the need of a wrapper class.

**Reasoning:** the wrapper class is adding another layer of abstraction which is not needed in general (in this case has to be created only to make the `JsonConverter` work). Especially since the wrapper class does not have any other benefit / purpose and it feels like it should be possible to do that without using it.

# Use case

We have a simple `User` class / model with different union types (`UserLoggedIn`, `UserGeneral`, `UserError`):

```dart
@freezed
class User with _$User {
  const factory User(String id, String email, String displayName) =
      UserLoggedIn;
  const factory User.general(String email, String displayName) = UserGeneral;
  const factory User.error(String message) = UserError;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
```

Since I'm using multiple constructors and don't want my API to include the `runtimeType` key as suggested by the documentation, I make use of a [converter](https://pub.dev/packages/freezed#fromjson---classes-with-multiple-constructors):

```dart
class UserConverter implements JsonConverter<User, Map<String, dynamic>> {
  const UserConverter();

  @override
  User fromJson(Map<String, dynamic> json) {
    if (json['id'] != null) {
      return UserLoggedIn.fromJson(json);
    } else if (json['error'] != null) {
      return UserError.fromJson(json);
    } else {
      return UserGeneral.fromJson(json);
    }
  }

  @override
  Map<String, dynamic> toJson(User data) => data.toJson();
}
```

The documentation now references another class (a wrapper class) which would now use this converter via annotation, in this case something like this:

```dart
@freezed
class UserModel with _$UserModel {
  const factory UserModel(@UserConverter() User user) = UserModelData;

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);
}
```

As described initially and what can be seen at the wrapper class, is that the `UserModel` wrapper ha sno other purpose than working with the converter. We additionally need to access it later on by always referencing `userModel.user` everywhere in the code instead of accessing the `User` directly.

**Idea:** maybe it's possible to apply the `JsonConverter` annotation also to the `fromJson` function form the `User` class like this:

```dart
@UserConverter
factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
```

which indicates to use the converter during the code generation process instead of the usually generated function which looks up the `runtimeType` property.

**Comment by shilangyu** [comment]
You can already just implement your own `fromJson` and `toJson` directly in the freezed class. You just need to remember to remove the expression body on `fromJson` to prevent freezed from generating `fromJson`/`toJson` for you.

**Comment by rrousselGit** [comment]
I don't think that this is a Freezed issue

My understanding is that you want to globally apply a JsonConverter for all User types. It sounds like something json_serializable should take care of

**Comment by ash0080** [comment]
> I don't think that this is a Freezed issue
> 
> My understanding is that you want to globally apply a JsonConverter for all User types. It sounds like something json_serializable should take care of

The problem is, the JsonConverter example in the current documentation is wrong and doesn't compile at all, in fact I tried once a couple of weeks ago, and today I tried again to write a working case, which I haven't been able to succeed so far, before that I could only get it to work by using @jsonKey, but that meant I had to manually mapping almost all the json key name, which is painful, and then after searching for issues, I think there are a ton of issues with jsonConverter, and I wonder if you can consider optimizing it

**Comment by rrousselGit** [comment]
This issue can be solved by writing:

```dart
@Freezed(toJson: true)
class User with _$User {
  const factory User(String id, String email, String displayName) =
      UserLoggedIn;
  const factory User.general(String email, String displayName) = UserGeneral;
  const factory User.error(String message) = UserError;

  factory User.fromJson(Map<String, dynamic> json) {
    if (json['id'] != null) {
      return UserLoggedIn.fromJson(json);
    } else if (json['error'] != null) {
      return UserError.fromJson(json);
    } else {
      return UserGeneral.fromJson(json);
    }
  }
}
```


This will generate a `toJson` while letting you manually define the fromJson.

**Comment by 0ttik** [comment]
> `@Freezed(toJson: true)`

Should be `@Freezed(fromJson: true)`.

**Comment by clragon** [comment]
I have just run into this issue, and I would suggest it would be useful to clarify the documentation to make very clear that a custom converter is only useful in cases where a class needs to be de/serialized that isnt controlled by the developer.

For resolving which union of a model we wrote ourselves should be used, writing a custom fromJson is far easier, but that didnt seem obvious from the readme.
