### ISSUE TITLE
add require_trailing_commas to ignore_for_file

### ISSUE THREAD

**Issue by axeis** [rrousselGit/freezed#594]
**Is your feature request related to a problem? Please describe.**
I went through all my freezed files and added ignore_trailing_commas to them just to clean up my problems view. committed, pushed, the runner kicked in at some point and it is all marked as modified. 

**Describe the solution you'd like**
Ignore one more warning automatically 

**Additional context**
I am not sure if that is in the scope of freezed or in the runner itself?

**Comment by rrousselGit** [comment]
Freezed is already disabling lints in generated files. Either your SDK is too low to support the syntax for disabling lints or there's a bug in the sdk/IDE

**Comment by axeis** [comment]
Do you mean the third line from this?
`// coverage:ignore-file`
`// GENERATED CODE - DO NOT MODIFY BY HAND`
`// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target
`

**Comment by rrousselGit** [comment]
Closing since Freezed includes `// ignore_for_file: type=lint` which disables all lints
