### ISSUE TITLE
Using Function types parameter in factory makes Freezed crashing

### ISSUE THREAD

**Issue by sperochon** [rrousselGit/freezed#597]
Hello,

Including a function type parameter in the factory makes Freezed crashing

I tried both styles :
`void foo()?,`
and
`void Function()? foo,`

Result is :
```
[SEVERE] freezed:freezed on lib/_web/features/datatable_wrapper_widget/column_wrapper.dart:

Null check operator used on a null value
```

**To Reproduce**
```
@freezed
class Bar with _$Bar {
  factory Bar({
    void Function()? foo,
  }) = _ Bar;
}
```

**Expected behavior**
No crash

Thanks

**Comment by SunlightBro** [comment]
1. Probably a typo but   `}) = _ Bar;` => `}) = _Bar;`
2. This doesn't look like a freezed issue but something in **column_wrapper.dart**
as generating Function parameters works directly and via typedef
```dart
typedef Bar = void Function();

@freezed
class Foo with _$Foo {
  factory Foo({
    void Function()? bar1,
    Bar? bar2,
  }) = _Foo;
}
```

If non of those 2, then please provide a full error log.

**Comment by sperochon** [comment]
@SunlightBro Thanks for your answer and sorry for wasting your time... I don't know what happened...I did try with typedef too and got same error... I just retried now both with your example, and in my code, and both are working fine. 

Thanks again 👍
