### ISSUE TITLE
Disable constructor tear-off since Dart 2.8 has built-in support

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/freezed#605]
Hi thanks for the lib! I guess we can have an option to *globally* disable generating the constructor tear-off code, since dart 2.8 has built-in support so we can save a bit of space.

**Comment by fzyzcjy** [comment]
👀  Seems that I cannot find a global flag to disable it

**Comment by rrousselGit** [comment]
I straight up removed the feature

**Comment by fzyzcjy** [comment]
Aha I see it. Thanks

**Comment by fzyzcjy** [comment]
https://github.com/rrousselGit/freezed#constructor-tear-off Maybe we can remove this

**Comment by rrousselGit** [comment]
Yeah the doc needs to be updated

I'll try doing that today
