### ISSUE TITLE
Unable to generate json when using curly braces on fromJson

### ISSUE THREAD

**Issue by crtl** [rrousselGit/freezed#608]
**Is your feature request related to a problem? Please describe.**
When changing the method signature recommended in the docs to generate json to a diffrent format or argument type the json code wont be generated:

```dart
// model.dart

// This works
factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);

// This does not, model.g.dart is not generated
factory Model.fromJson(Map<String, dynamic> json) {
  return _$ModelFromJson(json);
}

// This is what I want to archieve
factory Model.fromJson(dynamic json) {
  final map = json is List ? parseListToMap(json) : json;

  return _$ModelFromJson(map);
}

```

The `model.g.dart` file wont be generated. The same applies when using a diffrent type for json like `dynamic`.

**Describe the solution you'd like**
I would like to generate json factories/helpers even when the method signature differs.

**Describe alternatives you've considered**
You can use the recommended method signature to generate the fromJson code and then change it back and use the generated function. Problem is that it will break every time the builder will run again.

**Additional context**
I am using firestore on the backend which is a NoSQL database and our model for the documents changed.
Now I want to parse a `List<Map<String, dynamic>>` as a `Map<String, dynamic>` but still have to maintain backwards compatibility to update documents on the fly and support the old model. For this I want to check if `json` is a list in `fromJson` and convert it into a `Map<String. dynamic>` before passing it to the generated `_$ModelFromJson` function.

Before I used `@JsonKey` annotation with `fromJson` and `toJson` but now refactored the code to use a freezed instance instead of directly using the Map type.

**Comment by rrousselGit** [comment]
This is expected. Using curly braces means you're manually implementing from/toJson

Consider doing:

```
factory fromJson(json) => _someFunction(json);
```

**Comment by crtl** [comment]
@rrousselGit I want to generate the fromJson but then wrap it with custom logic.

Ive managed to find the following workaround:

```dart

Map<String, dynamic> _transformJson(dynamic json) {
  /* ... */
}

factory Model.fromJson(dynamic json) => _$ModelFromJson(_transformJson(json));

```

**Comment by rrousselGit** [comment]
> ```dart
> Map<String, dynamic> _transformJson(dynamic json) {
>   /* ... */
> }
> 
> factory Model.fromJson(dynamic json) => _$ModelFromJson(_transformJson(json));
> ```

Like I said, you can directly do:

```dart
Model _transformJson(dynamic json) {
  return _$ModelFromJson(...);
}

factory Model.fromJson(dynamic json) => _$ModelFromJson(json);

```

**Comment by crtl** [comment]
@rrousselGit This doesnt solve the problem because I would have to call `_transformJson` instead of `Model.fromJson`.

**Comment by rrousselGit** [comment]
Why?

**Comment by crtl** [comment]
Because `Model` is part of `OtherModel` and `OtherModel`s `fromJson` will call `Model.fromJson` for the property `Model model` which in turn wont call `_transformJson`.

**Comment by rrousselGit** [comment]
> Because Model is part of OtherModel 

Well you never mentioned that you're trying to share your `_tranformJson` between two classes

But in any case you know how to make a custom fromJson now, so you should be able to do what you want :)
