### ISSUE TITLE
'generic-metadata' language feature to be enabled when running build_runner

### ISSUE THREAD

**Issue by freppps** [rrousselGit/freezed#611]
**First of all - thanks for this amazing library! It has saved me a lot of time and sped up development!**

**Describe the bug**
Freezed throws “This requires the 'generic-metadata' language feature to be enabled.” when running the build_runner.

flutter version:
```
flutter --version
Flutter 2.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 097d3313d8 (11 days ago) • 2022-02-18 19:33:08 -0600
Engine • revision a83ed0e5e3
Tools • Dart 2.16.1 • DevTools 2.9.2
```

Output when running build_runner:

```
flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 588ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 91ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 886ms

[INFO] Running build...
[INFO] Running build completed, took 199ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 145ms

[SEVERE] freezed:freezed on lib/models/example.dart (cached):
An error `FormatterException` occurred while formatting the generated source for
  `package:flutter_application_1/models/example.dart`
which was output to
  `lib/models/example.freezed.dart`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 218, column 6 of .: This requires the 'generic-metadata' language feature to be enabled.
    ╷
218 │ @With<AdministrativeArea<House>>()
    │      ^
    ╵
line 323, column 12 of .: This requires the 'generic-metadata' language feature to be enabled.
    ╷
323 │ @Implements<Shop>()
    │            ^
    ╵
line 324, column 12 of .: This requires the 'generic-metadata' language feature to be enabled.
    ╷
324 │ @Implements<GeographicArea>()
    │            ^
    ╵
line 322, column 6 of .: This requires the 'generic-metadata' language feature to be enabled.
    ╷
322 │ @With<House>()
    │      ^
    ╵
[SEVERE] Failed after 394ms
pub finished with exit code 1
```

**To Reproduce**

1. Create a new flutter project
2. Add Freezed to pubspec
3. Add a file "example.dart" containing the below code and run build_runner
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'example.freezed.dart';

abstract class GeographicArea {}
abstract class House {}
abstract class Shop {}
abstract class AdministrativeArea<T> {}

@freezed
class Example with _$Example {
  const factory Example.person(String name, int age) = Person;

  @With<AdministrativeArea<House>>()
  const factory Example.street(String name) = Street;

  @With<House>()
  @Implements<Shop>()
  @Implements<GeographicArea>()
  const factory Example.city(String name, int population) = City;
}
```

**Expected behavior**
build_runner should not throw this error

**Comment by freppps** [comment]
Looking at the generated code and it actually looks like it was able to generate all the code.

**Comment by rrousselGit** [comment]
You need to update your Dart SDK. Generic annotations is a fairly recent feature.

**Comment by NielsSchneider** [comment]
Hello @rrousselGit,

I'm experiencing the same problem. Generic annotations should be in Dart 2.16.1, right? I'm using the latest version of the Flutter stable channel just like @freppps is.

Can you please help?

Kind regards,

Niels

**Comment by NielsSchneider** [comment]
I've `sdk: ">=2.16.1 <3.0.0"` in there.

**Comment by rrousselGit** [comment]
Could you create a minimal reproducible example github repository, with all the dependencies up-to-date?

**Comment by rrousselGit** [comment]
Actually I've seen the error.

There seems to be something different going on. The feature shouldn't require an experiment flag. It's there since Dart 2.14, when stable is using 2.16

I'll investigate

**Comment by freppps** [comment]
The actions are also failing with the same error message.
https://github.com/rrousselGit/freezed/actions

**Comment by freppps** [comment]
Would love to help but my knowledge in code generation is very limited. Let me know if you need any help testing!

**Comment by rrousselGit** [comment]
There seems to be a problem with the analyzer version 3.3.0


Adding:

```dart
analyzer: ">=3.0.0 <3.3.0"
```

seems to fix the issue.

I don't think it's Freezed's fault. I'll raise an issue

**Comment by NielsSchneider** [comment]
Your workaround works for me. 

Thank you for your help and giving the community this beautiful package.

**Comment by freppps** [comment]
The workaround works for me also.
Thanks for the help!

**Comment by foxanna** [comment]
Faced the same issue. Wanted to follow Remi's advice to add 

```yaml
  analyzer: ">=3.0.0 <3.3.0"
```
but my `pubspec.yaml` already contained 
```yaml
dependency_overrides:
  analyzer: 3.3.1
```
The solution for me was to run `pub upgrade`. Leaving it here in case it helps someone.
