### ISSUE TITLE
Improper generic visibility scope with generated decorators

### ISSUE THREAD

**Issue by Aqluse** [rrousselGit/freezed#614]
**Describe the bug**
**To Reproduce**
I got freezed class with a generic, which type used with `@Implements` decorator
```
@freezed
class BugTest<T extends String> with _$BugTest<T> {
  @Implements<BugTestInterface<T>>()
  const factory BugTest() = _BugTest<T>;
}

abstract class BugTestInterface<T> {}
```
Generated output gives me an error that there's no '`T`' in the scope.
```
@Implements<BugTestInterface<T>>()
class _$_BugTest<T extends String> implements _BugTest<T> {
  const _$_BugTest();

  <...>
}
```

**Expected behavior**
I see it can be fixed by moving it right to the constructor to get the correct generic value from the scope.

**Version**
1.1.1

**Comment by nightscape** [comment]
I just ran into the same problems
@Aqluse how exactly would the fixed code look like?
@rrousselGit could this be fixed / worked around by reintroducing `fromString` as mentioned in https://github.com/rrousselGit/freezed/pull/556?
Is the `@Implements` annotation on the generated class required at all?

**Comment by Aqluse** [comment]
@nightscape It could be fixed manually only by now, so it disables a generated file from auto-regeneration.

**Comment by rrousselGit** [comment]
I've "fixed" (because it was useless to add the `@With` annotations in the generated code). But your problem isn't going to disappear. The annotation itself won't compile, and that's more of a Dart thing.
