### ISSUE TITLE
Custom toString methods for Unions

### ISSUE THREAD

**Issue by z-dmitri** [rrousselGit/freezed#62]
It could be nice to have toString overloads, specially for the lists and complex objects to limit BLOC log for example.

We could use **freezedToString** attribute for example:

```dart
@freezed
abstract class Union with _$Union {
  const factory Union.loaded(@freezedToString((i) => i.length) List<Item> items) = Loading;
  const factory Union.loading() = Loading;
}
```

and for the data classes it could be **freezedNoToString** attribute for example:

```dart
@freezedNoToString
abstract class ClubId with _$ClubId {
  const factory ClubId(String value) = _ClubIdDataClass;

  @override
  String toString() {
    return 'ClubId#$value';
  }
}
```

**Comment by rrousselGit** [comment]
`@freezedToString((i) => i.length)`

This is not a valid dart syntax. `() => something` is not allowed inside decorators

**Comment by z-dmitri** [comment]
> This is not a valid dart syntax.

Good point, however it is nice syntax to use, maybe I will create dart issue then

**Comment by rrousselGit** [comment]
Closing in favor of #83

**Comment by z-dmitri** [comment]
#83 Will not help with Unions!

**Comment by rrousselGit** [comment]
It will.

ToString can use `when` & co, so you can do a different implementation for each value

**Comment by z-dmitri** [comment]
Looks it do not work with freezed up to 0.9.2
Could I kindly ask you sample for this case:
```dart
@freezed
abstract class Union with _$Union {
  Union._();

  const factory Union.loaded(List<Item> items) = Loaded;
  const factory Union.loading() = Loading;

  @override
  String toString() {
    return 'text';
  }
}
```

**Comment by rrousselGit** [comment]
Thats why we have #83

It's an aggregation of the issues.

**Comment by z-dmitri** [comment]
Ah, clear, it had not been solved yet
Thanks a lot for details and looking into
