### ISSUE TITLE
List for public Union types have missing type in generated `copyWith` code

### ISSUE THREAD

**Issue by Chralu** [rrousselGit/freezed#620]
Given a model class which has a list of a "**public** union subtype" :

> Notice that `data` generic type is `MyItemPublicUnionType` and not `MyItem`.

```dart
@freezed
class MyState with _$MyState {
  const MyState._();
  
  const factory MyState.factoryWithError({
    required PaginatedList<MyItemPublicUnionType> data,
  }) = _WithIssue;

  
  const factory MyState.okFactory({
    required PaginatedList<MyItem> data,
  }) = _Ok;
}
```

where the union is : 

```dart
@freezed
class PaginatedList<T> with _$PaginatedList<T> {
  const PaginatedList._();
  const factory PaginatedList({
    required List<T> items,
  }) = _PaginatedList<T>;
}
```

and the list item is :

```dart
@freezed
class MyItem with _$MyItem {
  const MyItem._();
  const factory MyItem.withPublicUnionType() = MyItemPublicUnionType;
}
```

the type for the list `MyState.factoryWithError.data`,in the generated code is `dynamic` instead of the actual type:

```dart
/// @nodoc
abstract class _$WithIssueCopyWith<$Res> {
  factory _$WithIssueCopyWith(
          _WithIssue value, $Res Function(_WithIssue) then) =
      __$WithIssueCopyWithImpl<$Res>;
  $Res call({PaginatedList<MyItemPublicUnionType> data});

  $PaginatedListCopyWith<dynamic, $Res> get data;
}
```

In that generated code I expected `$PaginatedListCopyWith get data` getter to be `$PaginatedListCopyWith<MyItemPublicUnionType, $Res> get data`.

On the other hand, it works fine when using `PaginatedList<MyItem>` instead of `PaginatedList<MyItemPublicUnionType>`.

Here is [a repo with the full demo code](https://github.com/Chralu/freezed_copywith_type_issue_demo)

**Comment by rrousselGit** [comment]
You should avoid relying on `MyItemPublicUnionType`. Instead use `MyItem`

While I get the appeal, supporting those is extremely difficult because these classes are not generated yet and therefore the analyzer doesn't understand where they are coming from.

Metaprogramming should solve this naturally, so I don't plan on working on this and would recommend finding another solution instead.
