### ISSUE TITLE
'@With' attribule generate 'implements' instead of 'with'

### ISSUE THREAD

**Issue by zs-dima** [rrousselGit/freezed#621]
```dart
mixin House {
* * *
}

@freezed
class Example with _$Example {
  const factory Example.person(String name, int age) = Person;

  @With<House>()
  const factory Example.city(String name, int population) = City;
}
```

generates 

```dart
abstract class City implements Example, House {
```
instead of

```dart
abstract class City implements Example with House {
```

**Comment by rrousselGit** [comment]
That's normal. `City` isn't a concrete class, only an interface

What matters is the separate `_$City` class:

```dart
class _$City implements City with House {
```

**Comment by zs-dima** [comment]
> That's normal. `City` isn't a concrete class, only an interface

@rrousselGit sorry, I fixed example above

**Comment by rrousselGit** [comment]
My answer is still the same. What's the issue exactly?

**Comment by zs-dima** [comment]
@rrousselGit thanks for looking into.
For example we want to override some operator or add methods:
```dart
mixin UniqueState {
  @override
  bool operator ==(Object o) => false;
}
```

**Comment by zs-dima** [comment]
freezed will generate

`abstract class State2 implements Example, UniqueState {`

instead of

`abstract class State2 implements Example with UniqueState {`

**Comment by zs-dima** [comment]
moreover looks @With has no sense currently as result the same as for the @Implements

**Comment by rrousselGit** [comment]
Like I said, you're looking at the wrong class. This class is an interface. It's another class that do `with Mixin`

**Comment by zs-dima** [comment]
@rrousselGit I see it is the other class generated as well, thanks a lot for details.
