### ISSUE TITLE
Null support for key when using custom converter

### ISSUE THREAD

**Issue by kanari3** [rrousselGit/freezed#623]
Example of defining your own custom converter

```dart
class FooConverter implements JsonConverter<Foo?, String?> {
  const FooConverter();

  @override
  Foo? fromJson()

  @override
  String? toJson()
}


@JsonKey(name: 'foo') @FooConverter() Foo? foo,
```

code of auto-generated foo.g.dart will look like this!

```dart
foo: const FooConverter().fromJson(json['foo'] as String?),
```
Specifically, the following cast scares me
```dart
json['foo'] as String?
```

In this case, a cast error occurs if foo is not found.

Shouldn't it be as follows?

```dart
foo: json['foo'] == null
  ? null
  : const FooConverter().fromJson(json['foo'] as String?),
```

Please let me know if there is a workaround.

**Comment by rrousselGit** [comment]
Freezed isn't dealing with those, it's json_serializable

I'd suggest raising an issue there instead

**Comment by kanari3** [comment]
Thanks for the reply.

By the way, you can get around this by writing
```dart
@JsonKey(name: 'foo') @Default(null) @FooConverter() Foo? foo,
```

The generated code is as follows
```dart
foo: json['foo'] == null
    ? null // null-safety
    : const FooConverter().fromJson(json['foo'] as String?),
```

**Comment by ash0080** [comment]
> Thanks for the reply.
> 
> By the way, you can get around this by writing
> 
> ![Save to Pieces](chrome-extension://igbgibhbfonhmjlechmeefimncpekepm/save_button.svg)
> @JsonKey(name: 'foo') @Default(null) @FooConverter() Foo? foo,
> The generated code is as follows
> 
> ![Save to Pieces](chrome-extension://igbgibhbfonhmjlechmeefimncpekepm/save_button.svg)
> foo: json['foo'] == null
>     ? null // null-safety
>     : const FooConverter().fromJson(json['foo'] as String?),

@rrousselGit 
This syntax not works with Freezed

now only works from me, but ugly and too many typing
```
@JsonKey(name: 'primColor', fromJson: xxx, toJson: xxx)
```
