### ISSUE TITLE
Freezed doesn't work well with `comment_references` lint

### ISSUE THREAD

**Issue by bartekpacia** [rrousselGit/freezed#624]
**Describe the bug** 

Freezed doesn't work well with the [comment_references](https://dart-lang.github.io/linter/lints/comment_references.html) lint.

I haven't found any issue that references this so I created one.

**To Reproduce**

1. You have to enable the `comment_references` lint in your
   `analysis_options.yaml`.

2. Create following `lib/main.dart`

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'main.freezed.dart';

class NormalGuy {
  const NormalGuy(this.name);

  final String name;
}

@freezed
class FreezedGuy with _$FreezedGuy {
  const factory FreezedGuy(String name) = _FreezedGuy;
}

/// Returns [NormalGuy.name].
String func1(NormalGuy guy) => guy.name;

/// Returns [FreezedGuy.name].
String func2(FreezedGuy guy) => guy.name;

void main() {
  func1(const NormalGuy('normal'));
  func2(const FreezedGuy('freezed'));
}
```

3. Execute:

```
$ flutter analyze
```

4. See warning

```
info • Only reference in scope identifiers in doc comments • lib/main.dart:21:14 • comment_references
```

While the dartdoc comment of `func1` is considered to be correct, the dartdoc of
`func2` is not.

I think that the the following line from the description of the lint hints at
the root cause of the problem

"code references within square brackets can consist of:

- ...
- two identifiers separated by a period where the first identifier is the name
  of a class that is in scope and the second is the name of a member declared in
  the class
- ...

`FreezedGuy.name` is not found, because it's not a field of `FreezedGuy`, but of
the generated mixin `_$FreezedGuy`.

**Expected behavior**

I would expect Dart analyzer to correctly detect the field of the freezed class
in dartdoc comment the same way it happens with the normal class.

**Comment by rrousselGit** [comment]
There's not much I can do here.
The field exist, it's just dartdoc that doesn't find it.

Maybe you could request an update of the comment_reference lint to look at superclasses too.

**Comment by bartekpacia** [comment]
@rrousselGit Thanks for your fast response!

That's what I thought – that not much can be done by freezed. I'll create an issue [dart-lang/linter](https://github.com/dart-lang/linter).

**Comment by bartekpacia** [comment]
@rrousselGit Finally after almost 2 months I got myself together and raised an issue for this. See https://github.com/dart-lang/sdk/issues/49069 :)
