### ISSUE TITLE
How to set a default value for an `UnmodifiableListView` ?

### ISSUE THREAD

**Issue by Haidar0096** [rrousselGit/freezed#625]
I have this class ```@freezed
class Editor with _$Editor {
  const factory Editor(
      {@Default(UnmodifiableListView<Element>([])) UnmodifiableListView<Element> elements}) = _Editor;
}```

but the compiler is complaining that I should use a constant value as the `@Default` parameter, but I don't think `UnmodifiableListView` has one, so how can I provide a default value in this case (I don't want to be forced to use union types just for this simple case, is there another way?) ?

**Comment by rrousselGit** [comment]
That's the thing: Since it doesn't have a const constructor, you can't.

Maybe make your value nullable instead, or type the variable as `List`, or use one of the various custom list packages out there.

In any case, this isn't a bug, so I'll close this
