### ISSUE TITLE
Set field to a constant value through constructor

### ISSUE THREAD

**Issue by cadast** [rrousselGit/freezed#627]
**Is your feature request related to a problem? Please describe.**
```dart
@freezed
class Pet with _$Pet {
  const factory Pet.dog({
    required String name,
  }) = _Dog;

  const factory Pet.cat({
    required String name,
  }) = _Cat;
}
```

Let's assume I have the structure above and want to send an instance of a Pet to my backend. For that I need to specify, the type of pet, which would be either `'dog'` or `'cat'`.

**Describe the solution you'd like**
I would like to have an annotation (maybe `@Static(dynamic value)`) to set a field to a constant value, like this:

```dart
@freezed
class Pet with _$Pet {
  const factory Pet.dog({
    required String name,
    @Static('cat') String type,
  }) = _Dog;

  const factory Pet.cat({
    required String name,
    @Static('cat') String type,
  }) = _Cat;
}
```

It could work the same as the `@Default` annotation, but to avoid mistakes, you could not override the value, by supplying it to the constructor.

**Describe alternatives you've considered**
There are several alternatives that would achieve the same thing:

1. Use the `@Default` annotation. This would certainly be the easiest, however the developer could still override the default by accident or on purpose. You could maybe add a `@deprecated` and a comment to not do that. However I am a fan of making making discouraged behavior actually impossible, because developers tend to be creative with repurposing things.
2. Add a custom getter. This would achieve the desired effect of not being able to override the default, but this would add some clutter to the class and is also not very elegant IMO.
```dart
@freezed
class Pet with _$Pet {
  const Pet._();

  const factory Pet.dog({
    required String name,
  }) = _Dog;

  const factory Pet.cat({
    required String name,
  }) = _Cat;

  String get type => map(
    dog: (_) => 'dog',
    cat: (_) => 'cat',
  );
}
```

**Comment by rrousselGit** [comment]
Is it that you're trying to add a getter specific to a union case?

If so, you can use extensions:

```dart
extension on _Cat {
  String get type => 'cat';
}
```

**Comment by cadast** [comment]
Thank you for the fast reply!

Yes, this is more or less what I want and I have not considered extensions, but they are similar to the second alternative above and I think in more complicated cases, this adds some clutter, which freezed is otherwise so good at avoiding.

My proposition is to have this class

```dart
@freezed
class Pet with _$Pet {
  const factory Pet.dog({
    required String name,
    @Static('dog') String type,
  }) = _Dog;
}
```
generate the following implementation:

```dart
class _$_Dog implements _Dog {
  const _$_Dog({required this.name, String? type})
      : assert(type == null,
            'Parameters with @Static() cannot be set in the constructor.'),
        this.type = 'dog';

  @override
  final String name;
  @JsonKey()
  @override
  final String type;

  // ...
}

abstract class _Dog implements Pet {
  const factory _Dog({required String name, String type}) = _$_Dog;

  @override
  String get name;
  @override
  String get type;

  // ...
}
```

**Comment by rrousselGit** [comment]
I don't think this is something desirable when we can use extensions

I can see the appeal of a slightly reduced boilerplate, but I don't like the idea of a constructor parameter that should not be used.
So I don't think the gain is worth the trouble
