### ISSUE TITLE
what the strange issue "this platform are not supported"?

### ISSUE THREAD

**Issue by ValeriusGC** [rrousselGit/freezed#629]
![Screenshot from 2022-04-04 19-15-20](https://user-images.githubusercontent.com/3320861/161563650-fed06950-4bab-4d97-8d5f-53867266e3ea.png)

This is strange decision, because freezed works on pure dart layer and does not require some specific platform dependencies, doesn't?

**Comment by rrousselGit** [comment]
Pub doesn't recognize code-generators

As a code-generator, Freezed only runs in your terminal – as it's relying on analyzing your Dart files, which a Flutter application cannot do.  
\The generated code, however, works on all platforms. But pub doesn't know that

The score ultimately doesn't matter as long as Freezed is working.

**Comment by ValeriusGC** [comment]
> The score ultimately doesn't matter as long as Freezed is working.

Absolutely agreed.

**Comment by rrousselGit** [comment]
I'll close this then

I don't think it's really important
