### ISSUE TITLE
Unions inheritance

### ISSUE THREAD

**Issue by z-dmitri** [rrousselGit/freezed#63]
It could be nice to use Unions for the BLOC states
But states usually have inheritance:

```dart
abstract class AppState {}
abstract class AppNavigationState {}
class AppNavigateToAState extends AppState with AppNavigationState {}
class AppNavigateToBState extends AppState with AppNavigationState {}
class AppSomeOtherState extends AppState {}
```

so we could filter states after:
```dart
.appBloc.whereType<AppNavigationState>()
```

so it could befreezed **freezedWith** attribute for example:

```dart
abstract class AppNavigationState {}

@freezed
abstract class AppState with _$Union {
  @freezedWith(AppNavigationState)
  const factory AppState.navigateToA() = NavigateToA;
  @freezedWith(AppNavigationState)
  const factory AppState.navigateToB() = NavigateToB;
}
```

**Comment by rrousselGit** [comment]
And how do you plan on implementing the interface?

**Comment by z-dmitri** [comment]
> 
> 
> And how do you plan on implementing the interface?

In the example just AppNavigationState inheritance, to filter out BLOC states by whereType<AppNavigationState>() later

**Comment by rrousselGit** [comment]
That's not what I meant..
If the interface has properties and methods, how will you implement these?

**Comment by z-dmitri** [comment]
> If the interface has properties and methods

properties and methods are not usually used for BLOC for the case I described

**Comment by rrousselGit** [comment]
Added as part of 0.11.0

**Comment by fernando-s97** [comment]
Is it possible to use something like:
```dart
abstract class GenericFailure {}

@freezedWith(GenericFailure)
abstract class SpecificFailure with _$SpecificFailure {
  const factory SpecificFailure.A() = A;
  const factory SpecificFailure.B() = B;
}
```

**Comment by rrousselGit** [comment]
No, it is not possible

**Comment by fernando-s97** [comment]
Thanks!

**Comment by petrnymsa** [comment]
Hi, sorry to "reopen" old issue, but how exactly mentioned version 0.11.0 solves this?
