### ISSUE TITLE
[FR] Generated selectors

### ISSUE THREAD

**Issue by purplenoodlesoop** [rrousselGit/freezed#639]
Hello, Remi! 

Thanks for the amazing package – it is truly one of the most useful Dart packages for me and a crazy timesaver. For the time I was using it – from its start, I've had one feature that I think could benefit everyone that uses this package with basically anything widget-related – `Provider` or `Riverpod`, and that is – automatically generated selectors.

**Is your feature request related to a problem? Please describe.**
Data classes are very often used as a state in StateNotifiers/BLoCs/Cubits/ValueNotifiers. Consequentially, since they have many fields, Widgets that consume them select parts of the state through selector functions to optimize rebuilds. 

And those selector functions tend to be very repetitive – if we take a look at an anonymous variant – `(state) => state.field`, word `state` is repeated two times, and there are four symbols and two spaces. Overall, from 22 symbols, only 11 have a meaning, that is – `state.field`.

Since those selectors tend to be used more than one time per field, I usually create a big abstract class with static methods that select fields from the state. Here, things get even worse in terms of repeated code – `static Field selectField(State state) => state.field;`  – again, only 11 symbols have meaning from whopping 54 symbols.

**Describe the solution you'd like**
I think a great solution for this would be to generate those selectors for data classes automatically. It would lessen the amount of repeated code and let the developers focus on writing actual logic – which as I see it aligns with the whole concept of the package.

**Describe alternatives you've considered**
As stated previously, there are two possible solutions – inlining those selectors through anonymous functions and declaring them as top-level/static functions. The first one wins if the selector is used once, the second one if it is used multiple times, but they all lose to the automatically generated alternative.

**Additional context**

To access nested fields, a reverse composition helper extension can be used, eg `WholeState.part.dot(PartState.smallerPart)`.

Naming and their form are totally up to you, but I think an abstract class/mixin named something like `<NameOfTheClass>Selectors` with static methods would work.

On a side note – I fully understand if this feature is out of bounds of this package, as it focuses on data classes – and not the means of consuming them, and my request steps in the gray area. So no hard feelings if you decide to close the issue, and thanks again for the package :)

**Comment by rrousselGit** [comment]
Hello!

I do plan on generating selectors at some point, but not inside Freezed.
I'll do so in Riverpod, once we have metaprogramming.

As in:

```dart
@provider
Model myProvider(ModelRef ref) {
  return Model(count: 0);
}


Model model = ref.watch(ModelProvider);
Model model = ref.watch(ModelProvider.count);
```

**Comment by purplenoodlesoop** [comment]
That's amazing to hear! If not inside Freezed – I think the issue can be closed now. Thanks!
