### ISSUE TITLE
Trailing comma in toJson 

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [rrousselGit/freezed#644]
Can you make toJson function configurable so that it generates without trailing comma. As I know Java(I don't know if in another languages also exist) doesn't allow trailing comma in Json files.

Or can you suggest workaround for this situation?

**Comment by rrousselGit** [comment]
Hello!

This is unrelated to toJson

Freezed returns a Map. There's no trailing comma in it. The comma you're talking about refers is not caused by `toJson`, it's caused by how you encode the `Map` object into a String.
