### ISSUE TITLE
Support methods

### ISSUE THREAD

**Issue by ResoDev** [rrousselGit/freezed#65]
As mentioned in #56, it's useful to have custom methods inside a freezed class. I would argue that those methods should be able to be written manually, not just generated. Something like #11 but with methods.

I agree that copy-pasting the implementation is not the nicest solution. For now, though, I have to resort to extensions.

**Comment by rrousselGit** [comment]
The problem with copy-pasting is, it breaks breakpoints.

**Comment by huang12zheng** [comment]
Is there a way to ignore some methods to implement? Directly using the parent class

**Comment by JillyTaboga** [comment]
I am using extensions to create methods in the freezed classes.

**Comment by rrousselGit** [comment]
Closing in favor of #83
