### ISSUE TITLE
Performance regression related to lists, `copyWith` and `==` in V2.0

### ISSUE THREAD

**Issue by SecondFlight** [rrousselGit/freezed#653]
Hi, thanks for the library! I have greatly appreciated using it.

After updating `freezed` to 2.0, my Flutter app has seen a significant performance regression that worsens over time.

I have not been able to find this reported anywhere else, though I apologize if I've missed something. I believe this differs from #626 as that report is talking in general about the performance of `DeepCollectionEquality` and doesn't mention deteriorating performance over time.

## Reproduction

I believe I've isolated a minimal reproduction case. Here's a code sample:

### `myModel.dart`:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'my_model.freezed.dart';

@freezed
class ModelWithList with _$ModelWithList {
  factory ModelWithList({
    @Default([]) List<int> someList,
    @Default(0) int counter,
  }) = _ModelWithList;
}
```

### `main.dart`:

```dart
import 'my_model.dart';

void main(List<String> arguments) {
  var model = ModelWithList(someList: List.filled(1000000, 0));

  final stopwatch = Stopwatch()..start();

  var elapsed = 0;

  for (var i = 0; i < 10000; i++) {
    final oldModel = model;
    model = model.copyWith(counter: model.counter + 1);

    if (oldModel == model) {
      throw Exception("New model should not equal old model.");
    }

    final elapsedThisIteration = stopwatch.elapsedMicroseconds;

    if (i % 10 == 0) {
      print("Delta: ${(elapsedThisIteration - elapsed) / 1000000} seconds");
    }

    elapsed = elapsedThisIteration;
  }
}
```

## Expected behavior

I expect the `print` statement to display a relatively constant time throughout the duration of the loop, no matter how slow or fast.

## Actual behavior

When using `freezed: ^1.1.0`, I get an output like this:

```
Delta: 0.000178 seconds
Delta: 0.000236 seconds
Delta: 0.000192 seconds
Delta: 0.000197 seconds
Delta: 0.000221 seconds
Delta: 0.000182 seconds
...
```

The average duration does not appear to change significantly over time.

When running with `freezed: ^2.0.2`, I get an output like this:

```
Delta: 0.034594 seconds
Delta: 0.117922 seconds
Delta: 0.319261 seconds
Delta: 0.423841 seconds
Delta: 0.520171 seconds
Delta: 0.635811 seconds
Delta: 0.791081 seconds
...
```

The delta continues to increase over time. Most of the time here seems to be spent in the `oldModel == model` equality check. Commenting it out results in this output (using `^2.0.2`):

```
Delta: 0.000236 seconds
Delta: 0.000345 seconds
Delta: 0.000275 seconds
Delta: 0.000284 seconds
Delta: 0.000229 seconds
Delta: 0.000222 seconds
...
```

**Comment by rrousselGit** [comment]
Hello!

Tha ms for the detailed report.
My immediate guess is that it could be related to immutable collections.

I'm not sure if I'll be able to check that today, so try disabling it and see if the issue disappears 😊

**Comment by SecondFlight** [comment]
Thanks for the quick reply and the suggestion! Adding `makeCollectionsUnmodifiable: false` to the `@Freezed` annotation does seem to fix the issue, so I'm using it as a workaround for now.

```dart
// Workaround for https://github.com/rrousselGit/freezed/issues/653
@Freezed(makeCollectionsUnmodifiable: false)
class MyModel with _$MyModel {
  // ...
```

**Comment by rrousselGit** [comment]
Thinking about this issue, I think it may be worth disabling this feature in release mode

As in, before making a release build, do:

```dart
dart run build_runner build --release
```

which would generate the Freezed files again, but with `makeCollectionsUnmodifiable` disabled.

**Comment by rrousselGit** [comment]
For reference, you can do this `--release` thing today:

```dart
targets:
  $default:
    builders:
      freezed:
        release_options:
          make_collections_unmodifiable: false
```

**Comment by hacker1024** [comment]
What about in packages? I maintain a client package for a HTTP API with a lot of Freezed models exposed in the package API.

Ideally, I'd like collections to be unmodifiable to users of the package. There's no easy way for them to rebuild the package files in release mode, though.

**Comment by rrousselGit** [comment]
Yes, there is an issue about it.

I just don't care too much about it, as Freezed will have to be rewritten soon with metaprogramming.

**Comment by knaeckeKami** [comment]
sorry, yeah I did not mean to comment on this closed issue, i copied it in the open issue
