### ISSUE TITLE
problem with nested  class json conceersion to/from

### ISSUE THREAD

**Issue by becbelk** [rrousselGit/freezed#657]
** when a class contain another class such that 
spose we have
@freezed
class A{
...
List [class B] x;
...
}
and we have
@freezed class B{
....
}
 both are annotated with freezed
a runtime error happen with A.toJson A.fromJson methods
theydont automaticly recognize that B must seriailizes/deserialized
**the solution in the *.g.dart file
 by adding the following method to the nested freezed class  B atribute key of the _$$_BtoJson
'listB': instance.listB.map((b_element) => b_element.toJson()) .toList()**

**Comment by rrousselGit** [comment]
You need to enable json_serializable's explicit_to_json, as the documentation suggests
