### ISSUE TITLE
Freezed 2.0 bug

### ISSUE THREAD

**Issue by Patrick386** [rrousselGit/freezed#658]
There is a problem with version 2.0.
Some of the issues we're having right now...

Back to 1.0. It works fine.

```
    freezed_annotation: ^1.0.0
    freezed: ^1.1.1

```

https://user-images.githubusercontent.com/49754877/166108963-e2ffd31f-52c3-4f13-8a06-4974e3b9b383.mov

**Comment by AlexVegner** [comment]
+1, downgrade to freezed: ^1.1.1

**Comment by rrousselGit** [comment]
Please provide a way to reproduce the issue, otherwise there's no way for me to fix this.

**Comment by AlexVegner** [comment]
@rrousselGit @Patrick386 

I have updated a prokect with latest dependencies 
https://github.com/AlexVegner/freezed2_sample/blob/main/pubspec.yaml
It works for me with (Flutter 3.0, Dart 2.17)
I have created sample project 
https://github.com/AlexVegner/freezed2_sample

**Comment by rrousselGit** [comment]
See #652

**Comment by SalahAdDin** [comment]
> There is a problem with version 2.0. Some of the issues we're having right now...
> 
> Back to 1.0. It works fine.
> 
> ```
>     freezed_annotation: ^1.0.0
>     freezed: ^1.1.1
> ```
> 
> freezed2.0v.mov

How did you record this video?

**Comment by Patrick386** [comment]
> > There is a problem with version 2.0. Some of the issues we're having right now...
> > Back to 1.0. It works fine.
> > ```
> >     freezed_annotation: ^1.0.0
> >     freezed: ^1.1.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > freezed2.0v.mov
> 
> How did you record this video?

Mac keyboard: shift + command + 5 key

I tested the freezed version 2.0.3 now and confirmed that it works without problems.
thank you..
