### ISSUE TITLE
Generic constructor for union types.

### ISSUE THREAD

**Issue by dancamdev** [rrousselGit/freezed#662]
[Michele Benedetti](https://github.com/Michele-x98) and I have been looking for a way of generalizing a widget displaying a list of freezed union. Reading the list is really straight forward, adding elements to it, on the other hand, required us to know the exact type we were trying to add.

Therefore the need for us to have a constructor that given the type `T extends BaseClass` could provide us the correct constructor.

**We expected Freezed union to implement something like this out of the box**, but we couldn't find a solution that fit our needs. 

We developed our own and we're wondering if it's something worth integrating within freezed.

``` Dart
final classTypeMap = <Type, BaseClass Function(String id)>{
  FirstClass: (id) => BaseClass.first(id: id),
  SecondClass: (id) => BaseClass.second(id: id),
};

@freezed
class BaseClass with _$BaseClass {

  /// Used for returning the correct constructor given the generic [Type]
  static T generic<T extends BaseClass>({required String id}) =>
      classTypeMap[T]!(id) as T;

  const factory BaseClass.first({
    required String id,
    @Default('') String name,
  }) = FirstClass;

  const factory BaseClass.second({
    required String id,
    @Default('') String name,
    @Default(5) int age,
  }) = SecondClass;
}
```

The solution above is based on a Map that maps the union type to its constructor. While the generic static method allows for quickly accessing the map, making it possible to write something like this:

``` Dart
void add<T extends BaseClass>() {
    classList.add(BaseClass.generic<T>(id: 'id'));
}
```

**Comment by dancamdev** [comment]
Our goal is about being able to pass `<T extends BaseClass>` to the BaseClass constructor and obtain the correct union object of type T.

Here's an example based on the model code above:

Let's say that we have an _Item widget that looks like this:

``` Dart
class _Item<T extends BaseClass> extends StatelessWidget {
  const _Item({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final elements = classList.whereType<T>().toList();

    return ListView.builder(...);
  }
}
```

It can take and display anything that extends `BaseClass`, by filtering a global `List<BaseClass>`. I'm using this because I want one _Item to display all of the `FirstClass` and another to display all the `SecondClass`.

The problem arises when we need to add a new object to the list, which it's going to be either FirstClass or SecondClass based on the generic. This solution we found, helps exactly with this, as per the following snippet.

``` Dart
class _MyHomePageState extends State<MyHomePage> {
  
  void onAdded<T extends BaseClass>() {
    setState(() {
      classList.add(BaseClass.generic<T>(id: 'id'));
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: [
          const _Item<FirstClass>(),
          const _Item<SecondClass>(),
          ElevatedButton(
            onPressed: onAdded<FirstClass>,
            child: const Text("Add FirstClass item"),
          ),
          ElevatedButton(
            onPressed: onAdded<SecondClass>,
            child: const Text("Add SecondClass item"),
          ),
        ],
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
Closing as I don't think there's a way to generate code for what you're asking. If you have a clear proposal in mind, I'd be happy to review it in a different issue though
