### ISSUE TITLE
Failed to generate the value is non-nullable

### ISSUE THREAD

**Issue by patricktslee** [rrousselGit/freezed#664]
**Describe the bug**
I am failed to generate the code for these method.

factory Model.add([int value]) = _Add;

**To Reproduce**

Here is the source code

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';

@freezed
abstract class Model implements _$Model {
  Model._();
  factory Model.add([int value]) = _Add;
  factory Model.remove([Counter counter]) = _Remove;
}
```

Here is the error message

> flutter pub run build_runner build
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 504ms
> 
> [INFO] Initializing inputs
> [INFO] Reading cached asset graph...
> [INFO] Reading cached asset graph completed, took 101ms
> 
> [INFO] Checking for updates since last build...
> [INFO] Checking for updates since last build completed, took 849ms
> 
> [INFO] Running build...
> [INFO] 1.6s elapsed, 0/1 actions completed.
> [WARNING] freezed:freezed on lib/models/model.dart:
> The class Model was declared as abstract, but it is not need anymore.
> Read here: https://github.com/rrousselGit/freezed/tree/master/packages/freezed#the-abstract-keyword
> 
> [SEVERE] freezed:freezed on lib/models/model.dart:
> 
> The parameter `value` of `Model.add` is non-nullable but is neither required nor marked with @Default
> package:multi_timer/models/model.dart:8:26
>   ╷
> 8 │   factory Model.add([int value]) = _Add;
>   │                          ^^^^^
>   ╵
> [INFO] Running build completed, took 1.9s
> 
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 54ms
> 
> [SEVERE] Failed after 2.0s
> pub finished with exit code 1

**Expected behavior**
Generate the code without error.

This is working fine if the method is on below.
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';

@freezed
abstract class Model implements _$Model {
  Model._();
//  factory Model.add([int value]) = _Add;
//  factory Model.remove([Counter counter]) = _Remove;
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;
}
```

> flutter pub run build_runner build
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 537ms
> 
> [INFO] Initializing inputs
> [INFO] Reading cached asset graph...
> [INFO] Reading cached asset graph completed, took 85ms
> 
> [INFO] Checking for updates since last build...
> [INFO] Checking for updates since last build completed, took 871ms
> 
> [INFO] Running build...
> [INFO] 1.8s elapsed, 0/1 actions completed.
> [WARNING] freezed:freezed on lib/models/model.dart:
> The class Model was declared as abstract, but it is not need anymore.
> Read here: https://github.com/rrousselGit/freezed/tree/master/packages/freezed#the-abstract-keyword
> 
> [INFO] Running build completed, took 2.4s
> 
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 100ms
> 
> [INFO] Succeeded after 2.5s with 1 outputs (1 actions)
> 

Thanks

Patrick Lee

**Comment by SunlightBro** [comment]
You are misusing optional positional parameters, have a look into darts documentation for [parameters](https://dart.dev/guides/language/language-tour#parameters).
> Wrapping a set of function parameters in `[]` marks them as **optional positional parameters**

**optional positional parameters** must either be given a default value or have to be nullable
```
  factory Model.add([@Default(0) int value]) = _Add; // default value
  factory Model.remove([Counter? counter]) = _Remove; // nullable
  factory Model.foo([required int foo]) = _Foo; // Can't have modifier 'required' here.
  // remove [] to make them positional parameters instead.
  factory Model.bar(int bar) = _Bar;
```

For the other warning check the [changelog](https://github.com/rrousselGit/freezed/blob/master/packages/freezed/CHANGELOG.md#0140-nullsafety0)

**Comment by patricktslee** [comment]
Thanks all good.
