### ISSUE TITLE
Big performance penalty and code size penalty?

### ISSUE THREAD

**Issue by fzyzcjy** [rrousselGit/freezed#667]
Hi thanks for this wonderful library! However, I am worried whether the performance will have a big penalty. Suppose I have a `Apple` immutable class.

Originally, if defined the naive way, it is a normal class with a few fields and methods, so everything is good and Dart should be able to optimize its generated assembly code heavily.

However, with freezed, it now becomes:

1. a non-abstract class (`Apple`), with an abstract subclass (`abstract class _Apple implements Apple`), and even one more subclass (`class _$_Apple implements _Apple`). Now it has three classes! Let alone the getters: `String get name => throw _privateConstructorUsedError;` etc. I am very worried whether the Dart compiler is smart enough to understand this case. If no, it will have to go through the inheritance tree and find out the correct method/field, etc, which I guess can be lot lot heavier.
2. Method become getters. For example, the `copyWith` which is very useful (especially great at handling null values!). The compiler understands well what is a "method call", especially for a normal class without subclasses, and should readily optimize it. However, now the compiler only sees "a getter returns an object (or a closure in #642)" and "a closure is invoked". Let alone all these happens with class inheritance, so the compiler will get more confused. In other words, I guess this can be lot lot slower.

The performance may be much worse IMHO. In addition, code size may also grow much bigger, because "one single field using one line of code" now becomes dozens of lines of code which is critical and cannot be optimized out by compiler.

(example: e.g. look at this generated code https://github.com/rrousselGit/freezed/blob/d24ed8bbfee72d49229793a4c979e97e5a1ee15f/packages/freezed/lib/src/models.freezed.dart#L40)

**Comment by rrousselGit** [comment]
The performance of copyWith can be debated. But I doubt the rest introduce actual performance issues.

The generated code is ultimately just interfaces. That's no different from how most of the Dart SDK is implemented

Look at streams & co. All of them use an interface class with factory constructors that redirect to a new class.
Therefore I'm sure the compiler is smart enough to optimize this.


And the way unions works, with map/when, is likely more efficient than by doing "is".

So I don't think there's a problem. There are some optimizations possible of course. But unless I missed something, I don't see a clear flaw

**Comment by fzyzcjy** [comment]
> And the way unions works, with map/when, is likely more efficient than by doing "is".

Btw I love that syntax :)

> That's no different from how most of the Dart SDK is implemented. ... Look at streams & co. All of them use an interface class with factory constructors that redirect to a new class.

Good point! I agree that Stream etc all do that.
However, we are discussing immutable classes (or POJO in java world, data-class in kotlin, etc), which is usually very lightweight objects. In other words, there are plenty of them and it is used very frequently.

Talk in another perspective: If we have a old-style class, `apple.field` will, say, need a few assembly instructions. But with freezed, it is possible hundreds (just an example number). Then it is 10x slower. On the other hand, `Stream.listen` already have dozens lines of source code, so I guess it is already hundreds or thousands of assembly instructions. With or without class inheritance optimization does not affect much.

In addition, the case of Stream is very different from Freezed. IMHO stream naturally has multiple sub-classes, so it has to be like that - you cannot have a single class without inheritance. However, for freezed, it is originally one single class.

I still feel compiler not able to optimize. For example, consider:

```
void doSomething(Apple apple) { apple.fieldOne; }
```

Then, how can the compiler know `Apple` is indeed of type `_$Apple` with `fieldOne` just being a normal field and generate merely a few assembly instructions?

But I agree for code like `Apple(fieldOne: 42)`, the compiler will just know it is calling `_$Apple`'s constructor.

**Comment by rrousselGit** [comment]
Collections (List) are the same, and they are meant to be fast

> Then, how can the compiler know Apple is indeed of type _$Apple with fieldOne just being a normal field and generate merely a few assembly instructions

_$Apple is the only concrete implementation of the interface

The unimplemented getters are dead code and are eliminated by the tree shaking.

**Comment by fzyzcjy** [comment]
Thanks for the reply!

> Collections (List) are the same, and they are meant to be fast

```
abstract class List<E> implements EfficientLengthIterable<E> {
  external factory List([int? length]);
}
```

And that is implemented via C++ code. So I guess List is a bit different from freezed?

Anyway your thoughts are quite convincing, and I will benchmark it :)

**Comment by rrousselGit** [comment]
To be fair, you may be correct
But even if you are correct, I don't see what is expected from this issue.

The generated code can't really be changed until we have metaprogramming.

**Comment by fzyzcjy** [comment]
Thanks. A quick hacky test is in https://github.com/fzyzcjy/freezed_benchmark.

Conclusion:

1. copyWith is 30x slower(!)
2. simply constructing and accessing is same speed. guess because it is local variable and dart knows its real type even for freezed.

```
naive
          total runs:        255   
          total time:     2.0022  s
         average run:     7.8510 ms
         runs/second:     127.37   

freezed
          total runs:          7   
          total time:     2.1502  s
         average run:     307.17 ms
         runs/second:     3.2556   

naive
          total runs:        271   
          total time:     2.0031  s
         average run:     7.3910 ms
         runs/second:     135.30   

freezed
          total runs:        271   
          total time:     2.0017  s
         average run:     7.3860 ms
         runs/second:     135.39   

naive
          total runs:        271   
          total time:     2.0060  s
         average run:     7.4020 ms
         runs/second:     135.10   

freezed
          total runs:        259   
          total time:     2.0054  s
         average run:     7.7420 ms
         runs/second:     129.17 
```

**Comment by fzyzcjy** [comment]
Well, wait a minute. Field access seems to be 30% slower?

```
  final naiveApple = NaiveApple(id: Random().nextInt(1000), name: 'hello');
  syncBenchmark('naive access', () {
    var sum = 0;
    for (var i = 0; i < 10000000; ++i) {
      sum += naiveApple.id;
    }
    dummy ^= sum;
  }).report();
  final freezedApple = FreezedApple(id: Random().nextInt(1000), name: 'hello');
  syncBenchmark('freezed access', () {
    var sum = 0;
    for (var i = 0; i < 10000000; ++i) {
      sum += freezedApple.id;
    }
    dummy ^= sum;
  }).report();
```

yield

```
naive access
          total runs:        390   
          total time:     2.0000  s
         average run:     5.1280 ms
         runs/second:     195.01   

freezed access
          total runs:        276   
          total time:     2.0007  s
         average run:     7.2480 ms
         runs/second:     137.97 
```

**Comment by fzyzcjy** [comment]
Well, seem to be caused by the nature of microbenchmark.

This

<details>

```
import 'dart:math';

import 'package:benchmarking/benchmarking.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'freezed_benchmark.freezed.dart';

void main(List<String> arguments) {
  var dummy = 0;

  syncBenchmark('naive copyWith', () {
    var a = NaiveApple(id: 0, name: 'hello');
    for (var i = 0; i < 10000000; ++i) {
      a = a.copyWith(id: a.id + i, name: a.name);
    }
    dummy ^= a.id;
  }).report();
  syncBenchmark('freezed copyWith', () {
    var a = FreezedApple(id: 0, name: 'hello');
    for (var i = 0; i < 10000000; ++i) {
      a = a.copyWith(id: a.id + i, name: a.name);
    }
    dummy ^= a.id;
  }).report();

  {
    final naiveApple = createNaiveApple();
    syncBenchmark('naive access', () {
      var sum = 0;
      for (var i = 0; i < 10000000; ++i) {
        sum += naiveApple.id;
      }
      dummy ^= sum;
    }).report();
    final freezedApple = createFreezedApple();
    syncBenchmark('freezed access', () {
      var sum = 0;
      for (var i = 0; i < 10000000; ++i) {
        sum += freezedApple.id;
      }
      dummy ^= sum;
    }).report();
  }

  {
    final naiveApple = NaiveApple(id: Random().nextInt(1000), name: 'hello');
    syncBenchmark('naive access', () {
      var sum = 0;
      for (var i = 0; i < 10000000; ++i) {
        sum += naiveApple.id;
      }
      dummy ^= sum;
    }).report();
    final freezedApple = FreezedApple(id: Random().nextInt(1000), name: 'hello');
    syncBenchmark('freezed access', () {
      var sum = 0;
      for (var i = 0; i < 10000000; ++i) {
        sum += freezedApple.id;
      }
      dummy ^= sum;
    }).report();
  }

  print(dummy);
}

NaiveApple createNaiveApple() {
  if (Random().nextInt(1000) > 99999) return NaiveAppleFakeImpl();
  return NaiveApple(id: Random().nextInt(1000), name: 'hello');
}

FreezedApple createFreezedApple() {
  if (Random().nextInt(1000) > 99999) return FreezedAppleFakeImpl();
  return FreezedApple(id: Random().nextInt(1000), name: 'hello');
}

@immutable
class NaiveApple {
  final int id;
  final String name;

  const NaiveApple({
    required this.id,
    required this.name,
  });

  NaiveApple copyWith({
    int? id,
    String? name,
  }) =>
      NaiveApple(
        id: id ?? this.id,
        name: name ?? this.name,
      );
}

class NaiveAppleFakeImpl implements NaiveApple {
  @override
  NaiveApple copyWith({int? id, String? name}) {
    throw UnimplementedError();
  }

  @override
  int get id => throw UnimplementedError();

  @override
  String get name => throw UnimplementedError();
}

@freezed
class FreezedApple with _$FreezedApple {
  const factory FreezedApple({
    required int id,
    required String name,
  }) = _FreezedApple;
}

class FreezedAppleFakeImpl implements FreezedApple {
  @override
  $FreezedAppleCopyWith<FreezedApple> get copyWith => throw UnimplementedError();

  @override
  int get id => throw UnimplementedError();

  @override
  String get name => throw UnimplementedError();
}

```

</details>

yields


```
naive copyWith
          total runs:        404   
          total time:     2.0025  s
         average run:     4.9560 ms
         runs/second:     201.78   

freezed copyWith
          total runs:          6   
          total time:     2.1496  s
         average run:     358.27 ms
         runs/second:     2.7912   

naive access
          total runs:         72   
          total time:     2.0078  s
         average run:     27.885 ms
         runs/second:     35.862   

freezed access
          total runs:         74   
          total time:     2.0078  s
         average run:     27.132 ms
         runs/second:     36.857   

naive access
          total runs:        269   
          total time:     2.0018  s
         average run:     7.4410 ms
         runs/second:     134.39   

freezed access
          total runs:        418   
          total time:     2.0042  s
         average run:     4.7940 ms
         runs/second:     208.59 
```

while 

<details>

```
import 'dart:math';

import 'package:benchmarking/benchmarking.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'freezed_benchmark.freezed.dart';

void main(List<String> arguments) {
  var dummy = 0;

  syncBenchmark('naive copyWith', () {
    var a = NaiveApple(id: 0, name: 'hello');
    for (var i = 0; i < 10000000; ++i) {
      a = a.copyWith(id: a.id + i, name: a.name);
    }
    dummy ^= a.id;
  }).report();
  syncBenchmark('freezed copyWith', () {
    var a = FreezedApple(id: 0, name: 'hello');
    for (var i = 0; i < 10000000; ++i) {
      a = a.copyWith(id: a.id + i, name: a.name);
    }
    dummy ^= a.id;
  }).report();

  // {
  //   final naiveApple = createNaiveApple();
  //   syncBenchmark('naive access', () {
  //     var sum = 0;
  //     for (var i = 0; i < 10000000; ++i) {
  //       sum += naiveApple.id;
  //     }
  //     dummy ^= sum;
  //   }).report();
  //   final freezedApple = createFreezedApple();
  //   syncBenchmark('freezed access', () {
  //     var sum = 0;
  //     for (var i = 0; i < 10000000; ++i) {
  //       sum += freezedApple.id;
  //     }
  //     dummy ^= sum;
  //   }).report();
  // }

  {
    final naiveApple = NaiveApple(id: Random().nextInt(1000), name: 'hello');
    syncBenchmark('naive access', () {
      var sum = 0;
      for (var i = 0; i < 10000000; ++i) {
        sum += naiveApple.id;
      }
      dummy ^= sum;
    }).report();
    final freezedApple = FreezedApple(id: Random().nextInt(1000), name: 'hello');
    syncBenchmark('freezed access', () {
      var sum = 0;
      for (var i = 0; i < 10000000; ++i) {
        sum += freezedApple.id;
      }
      dummy ^= sum;
    }).report();
  }

  print(dummy);
}

NaiveApple createNaiveApple() {
  if (Random().nextInt(1000) > 99999) return NaiveAppleFakeImpl();
  return NaiveApple(id: Random().nextInt(1000), name: 'hello');
}

FreezedApple createFreezedApple() {
  if (Random().nextInt(1000) > 99999) return FreezedAppleFakeImpl();
  return FreezedApple(id: Random().nextInt(1000), name: 'hello');
}

@immutable
class NaiveApple {
  final int id;
  final String name;

  const NaiveApple({
    required this.id,
    required this.name,
  });

  NaiveApple copyWith({
    int? id,
    String? name,
  }) =>
      NaiveApple(
        id: id ?? this.id,
        name: name ?? this.name,
      );
}

class NaiveAppleFakeImpl implements NaiveApple {
  @override
  NaiveApple copyWith({int? id, String? name}) {
    throw UnimplementedError();
  }

  @override
  int get id => throw UnimplementedError();

  @override
  String get name => throw UnimplementedError();
}

@freezed
class FreezedApple with _$FreezedApple {
  const factory FreezedApple({
    required int id,
    required String name,
  }) = _FreezedApple;
}

class FreezedAppleFakeImpl implements FreezedApple {
  @override
  $FreezedAppleCopyWith<FreezedApple> get copyWith => throw UnimplementedError();

  @override
  int get id => throw UnimplementedError();

  @override
  String get name => throw UnimplementedError();
}

```

</details>

gives

```
naive copyWith
          total runs:        258   
          total time:     2.0064  s
         average run:     7.7760 ms
         runs/second:     128.60   

freezed copyWith
          total runs:          7   
          total time:     2.1140  s
         average run:     301.99 ms
         runs/second:     3.3113   

naive access
          total runs:        388   
          total time:     2.0016  s
         average run:     5.1580 ms
         runs/second:     193.87   

freezed access
          total runs:        278   
          total time:     2.0058  s
         average run:     7.2150 ms
         runs/second:     138.60
```

**Comment by fzyzcjy** [comment]
conclusion:

1. copyWith is slow
2. for field access, I am not sure, sometimes even faster. Sometimes Dart even optimizes the freezed better than naive approach. By adding another unrelate section of code it even dramatically change behavior of the speed.

**Comment by rrousselGit** [comment]
I believe you should separate the naive/freezed benchmarks in two different benchmark.

Also a warm-up run is probably a good idea

That could be why Freezed is sometimes faster

**Comment by fzyzcjy** [comment]
Agree. Just do not want to dig into details and want a quick benchmark.
