### ISSUE TITLE
A way of implementing abtract members

### ISSUE THREAD

**Issue by dangtuandat1995** [rrousselGit/freezed#670]
From the document, Freezed support Implements decorator, but offers no instruction when the abtract class has member. I would like to know how should I do that.

For example:
```
abstract class SampleAbtractClass {
  void doSomething();
  int returnAnInteger();
}

@freezed
class SampleClass with _$SampleClass {
  @Implements<SampleAbtractClass>()
  const factory SampleClass.firstSample({
    required int inputNumber,
    required void Function() whatToDo,
  }) = _FirstSample;
}
```

**Comment by rrousselGit** [comment]
See https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models

**Comment by dangtuandat1995** [comment]
Can you please at least give an example? I read the entire doc but couldn't figure out how to implement it.
