### ISSUE TITLE
Cannot access mixin method from instance

### ISSUE THREAD

**Issue by esenmx** [rrousselGit/freezed#679]
**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';

abstract class Abstract {
  Abstract(this.foo);

  final String foo;
}

mixin Mixin on Abstract {
  void echo() => print(foo);
}

@freezed
class Model with _$Model {
  Model._(); // If I remove this, _$_Model class also throws, but that's definitely ok

  @Implements<Abstract>()
  @With<Mixin>()
  factory Model({required String foo}) = _Model;
}

void main(List<String> args) {
  final model = Model(foo: 'bar');
  model.echo(); // ERROR
  (model as _Model).echo(); // Works well
}
```

**Comment by rrousselGit** [comment]
`@Mixin` is for applying the mixin on `_Model`
If you want it on `Model`, you don;'t need `@Mixin`

Just do:

```dart
@freezed
class Model with _$Model, MyMixin {
  Model._();
}
```

**Comment by esenmx** [comment]
> `@Mixin` is for applying the mixin on `_Model` If you want it on `Model`, you don;'t need `@Mixin`
> 
> Just do:
> 
> ```dart
> @freezed
> class Model with _$Model, MyMixin {
>   Model._();
> }
> ```

This time:
<img width="875" alt="Screen Shot 2022-06-05 at 16 49 14" src="https://user-images.githubusercontent.com/43244505/172053874-8b129382-3ef2-4579-82cb-15b021cd89ce.png">
