### ISSUE TITLE
Hash codes not equal on freezed object with same values

### ISSUE THREAD

**Issue by dpetlyuk** [rrousselGit/freezed#680]
When loading data i copy units for revert to original state? like this `units.map((u) => u.copyWith()).toList()`. When i compare object its hash codes are not equal:

![image](https://user-images.githubusercontent.com/9843741/172201110-ef198ff6-759f-4db0-b331-9fe4e1ff7ab8.png)

Classes:

```dart
@unfreezed
class Unit with _$Unit {
  factory Unit({
    required final int id,
    required final int? pieces,
    required final Location location,
  }) = _Unit;

  factory Unit.blank() => Unit(id: 0, pieces: 0, location: Location.blank());

  factory Unit.fromJson(Map<String, dynamic> json) => _$UnitFromJson(json);
}

@freezed
class Location with _$Location {
  const factory Location(int id, String groupCode, String name) = _Location;

  factory Location.blank() => Location(0, 'W', '');

  factory Location.fromJson(Map<String, dynamic> json) => _$LocationFromJson(json);
}
```

**Expected behavior**
Freezed object with same values are equal.

**Comment by rrousselGit** [comment]
You're using `@unfreezed`

With `@unfreezed`, ==/hashCode are explicitly not overridden. If you want == override, use `@freezed`
