### ISSUE TITLE
Freezed values with collection fields are not immutable

### ISSUE THREAD

**Issue by rodcheater** [rrousselGit/freezed#684]
**Describe the bug**

Values of collection types are not copied when they are used in values of classes created using Freezed. This means that they can be modified, affecting the value of an instance which is supposed to be immutable.

**To reproduce**

```
import 'package:test/test.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';

@freezed
class Model with _$Model {
  factory Model({
    required String id,
    @Default(<int>[]) List<int> counts,
  }) = _Model;
}

void main() {
  group("Given a model", () {
    final model = Model(id: "id");
    group("when dealing with a list attribute", () {
      final counts = [1, 2, 3];
      final copy = model.copyWith(counts: counts);
      test("then the model's list cannot be modified.", () {
        expect(() => {copy.counts.add(4)}, throwsUnsupportedError);
      });
      test(
        "then modifying the input list does not affect the model's list.",
        () {
          counts.add(5);
          expect(copy.counts, equals([1, 2, 3]));
        },
      );
    });
  });
}
```

This test fails:

```
package:test_api             expect
test/model/model.dart 27:11  main.<fn>.<fn>.<fn>

Expected: [1, 2, 3]
  Actual: [1, 2, 3, 5]
   Which: at location [3] is [1, 2, 3, 5] which longer than expected
```

**Expected behavior**

The test should pass.

**Comment by rrousselGit** [comment]
That's the expected behavior.

If you want to clone the list, pass a clone to Freezed.
Freezed won't clone collections it receives because that would be very inefficient

**Comment by rodcheater** [comment]
I guess that’s a valid design choice, except it wasn’t what I was expecting on reading the documentation:

> By default when using `@freezed` (but not `@unfreezed`), properties of type `List`/`Map`/`Set` are transformed to be immutable.

They’re not immutable if it’s possible to mutate them.

I’m probably therefore going to switch to using [fast immutable collections](https://pub.dev/packages/fast_immutable_collections).

**Comment by rodcheater** [comment]
I guess that’s a valid design choice, except it wasn’t what I was expecting on reading the documentation:

> By default when using `@freezed` (but not `@unfreezed`), properties of type `List`/`Map`/`Set` are transformed to be immutable.

They’re not immutable if it’s possible to mutate them.

I’m probably therefore going to switch to using [fast immutable collections](https://pub.dev/packages/fast_immutable_collections).

**Comment by rrousselGit** [comment]
Doing "model.counts.add(42)" throws, so you can't mutate the collection from the model itself.

You bypassed that check by not using going through Freezed code though

**Comment by rodcheater** [comment]
That’s exactly what a bad client’s going to do though—they’re going to pass us a collection then mutate it outside of Freezed, leading to the subtle and hard to find bugs that using Freezed is trying to avoid.
