### ISSUE TITLE
"Type variables can't be used in static members" when using decorator with generics

### ISSUE THREAD

**Issue by drinkmorecola** [rrousselGit/freezed#687]
**Describe the bug**
If you add a `@With` or `@Implements` decorator with generics (E.g. `@With<Mixin<T>>()`), it can generate proper codes, but it will cause build time error "Type variables can't be used in static members". If you remove the decorator after codes have been generated, everything works fine.

**To Reproduce**

``` dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'example.freezed.dart';

@freezed
class Example<T> with _$Example {
  @With<_Mixin<T>>()
  const factory Example() = _Example;
}

mixin _Mixin<T> on Example<T> {}
```

**Expected behavior**
I would expect it doesn't cause the build time error. Is there a workaround like passing the type as a string?

**Comment by rrousselGit** [comment]
This would need a new annotation

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/freezed/issues/757
