### ISSUE TITLE
freezed & hive

### ISSUE THREAD

**Issue by dennis-szymanski** [rrousselGit/freezed#69]
Hey,
this is not really an issue, but I don't know where else to ask this question:
Is there a way to combine freezed with hive?

For example like that:

```
@freezed
abstract class Person extends HiveObject with _$Person {
  @HiveType(typeId: 0)
  factory Person({@HiveField(0) String name, @HiveField(1) int age}) = _Person;
}
```

I know that this is not possible out of the box, but I think you know what I want to achieve .. What would be the best way to implement freezed with hive?

The only solution that I can currently think of is to store the json-String which is generated by freezed in hive .. 

I also asked this question on [stackoverflow](https://stackoverflow.com/questions/60383178/combine-freezed-hive)
Thanks in advance !
Have a great day !
Dennis

**Comment by dennis-szymanski** [comment]
someone on stackoverflow showed me this issue: [hive with immutable classes](https://github.com/hivedb/hive/issues/225) .. So this can be closed :)

**Comment by dvagala** [comment]
Did you manage to extend the `HiveObject`?
