### ISSUE TITLE
Gives errors on partOfs and _$ClassName

### ISSUE THREAD

**Issue by neevshah1273** [rrousselGit/freezed#691]
**Describe the bug**

I am getting these errors

lib/providers/userProvider.dart:12:6: Error: Error when reading 'lib/providers/userProvider.freezed.dart': The system cannot find the file specified.

part 'userProvider.freezed.dart';
     ^
lib/providers/userProvider.dart:14:6: Error: Error when reading 'lib/providers/userProvider.g.dart': The system cannot find the file specified.

part 'userProvider.g.dart';
     ^
lib/providers/userProvider.dart:12:6: Error: Can't use 'lib/providers/userProvider.freezed.dart' as a part, because it has no 'part of' declaration.
part 'userProvider.freezed.dart';
     ^
lib/providers/userProvider.dart:14:6: Error: Can't use 'lib/providers/userProvider.g.dart' as a part, because it has no 'part of' declaration.
part 'userProvider.g.dart';
     ^
lib/providers/userProvider.dart:19:36: Error: Type '_$LoginParameter' not found.
abstract class LoginParameter with _$LoginParameter{
                                   ^^^^^^^^^^^^^^^^
lib/providers/userProvider.dart:19:16: Error: The type '_$LoginParameter' can't be mixed in.
abstract class LoginParameter with _$LoginParameter{
               ^
lib/providers/userProvider.dart:23:8: Error: Couldn't find constructor '_LoginParameter'.
  }) = _LoginParameter;
       ^
lib/providers/userProvider.dart:23:8: Error: Redirection constructor target not found: '_LoginParameter'
  }) = _LoginParameter;
       ^

**To Reproduce**
(fileName : userProvider.dart)

part 'userProvider.freezed.dart';

part 'userProvider.g.dart';

@freezed
abstract class LoginParameter with _$LoginParameter{
  factory LoginParameter({
    required String mobileNumber,
    required String password
  }) = _LoginParameter;

  String get password => password;

  String get mobileNumber => mobileNumber;
}

**Expected behavior**
This should be running perfectly as per the documantation.

**Comment by rrousselGit** [comment]
Try running "flutter pub upgrade". I believe that's a bug that was fixed

**Comment by rrousselGit** [comment]
Freezed isn't the issue. If I remember correctly, that's the analyzer or `build`

**Comment by rrousselGit** [comment]
Actually I think I'm misreading the error.

It seems like the part files were generated but incorrect? Could you maybe open ` 'lib/providers/userProvider.g.dart` and show what it contains? I'd also need  `lib/providers/userProvider.dart` to see how they relate

**Comment by neevshah1273** [comment]
userProvider.g.dart hasn't been generated. 


import 'dart:convert';
import 'dart:core';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:welcome_broker/providers/authProvider.dart';
import '../models/user.dart';
import '../services/AuthService.dart';


part 'userProvider.freezed.dart';

part 'userProvider.g.dart';



@freezed
abstract class LoginParameter with _$LoginParameter{
  factory LoginParameter({
    required String mobileNumber,
    required String password
  }) = _LoginParameter;

  String get password => password;

  String get mobileNumber => mobileNumber;
}

final userFutureProvider = FutureProvider.family<User, LoginParameter>((ref, params) async{
  http.Response response = await logIn(params.mobileNumber, params.password);
  final content = json.decode(response.body) as Map<String, dynamic>;
  return User.fromJson(content);
});

**Comment by neevshah1273** [comment]
userProvider.g.dart hasn't been generated.

import 'dart:convert';
import 'dart:core';
import 'package:http/http.dart' as http;
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import '../models/user.dart';
import '../services/AuthService.dart';

part 'userProvider.freezed.dart';

part 'userProvider.g.dart';

@freezed
abstract class LoginParameter with _$LoginParameter{
factory LoginParameter({
required String mobileNumber,
required String password
}) = _LoginParameter;

String get password => password;

String get mobileNumber => mobileNumber;
}

final userFutureProvider = FutureProvider.family<User, LoginParameter>((ref, params) async{
http.Response response = await logIn(params.mobileNumber, params.password);
final content = json.decode(response.body) as Map<String, dynamic>;
return User.fromJson(content);
});

**Comment by rrousselGit** [comment]
Your error says that the.g.dart file was generated though

In any case it's likely still an analyzer/build issue, not a Freezed one.

"pub upgrade" should fix the issue. Maybe there's something that prevents you from using the latest analyzer version? 
Check "pub outdated"

**Comment by neevshah1273** [comment]
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name              Current   Upgradable  Resolvable  Latest   

direct dependencies: all up-to-date.

dev_dependencies: all up-to-date.

transitive dependencies: 
async                     *2.8.2    *2.8.2      *2.8.2      2.9.0    
characters                *1.2.0    *1.2.0      *1.2.0      1.2.1    
ffi                       *1.2.1    *1.2.1      *1.2.1      2.0.1    
material_color_utilities  *0.1.4    *0.1.4      *0.1.4      0.1.5    
meta                      *1.7.0    *1.7.0      *1.7.0      1.8.0    
path                      *1.8.1    *1.8.1      *1.8.1      1.8.2    
path_provider_windows     *2.0.7    *2.0.7      *2.0.7      2.1.0    
source_span               *1.8.2    *1.8.2      *1.8.2      1.9.0    
string_scanner            *1.1.0    *1.1.0      *1.1.0      1.1.1    
term_glyph                *1.2.0    *1.2.0      *1.2.0      1.2.1    
win32                     *2.6.1    *2.6.1      *2.6.1      2.7.0    

transitive dev_dependencies:
clock                     *1.1.0    *1.1.0      *1.1.0      1.1.1    
fake_async                *1.3.0    *1.3.0      *1.3.0      1.3.1    
matcher                   *0.12.11  *0.12.11    *0.12.11    0.12.12  
test_api                  *0.4.9    *0.4.9      *0.4.9      0.4.10   
all dependencies are up-to-date.
Process finished with exit code 0



This is pub outdated

**Comment by neevshah1273** [comment]
@rrousselGit

**Comment by javikin** [comment]
@neevshah1273 looks like you need to add json_serializable to your pubspec.yaml

**Comment by neevshah1273** [comment]
@javikin added but error still shows up

**Comment by rrousselGit** [comment]
Your pubspec does not match the installation steps mentioned in the readme
