### ISSUE TITLE
Error casting a class that has @Implements

### ISSUE THREAD

**Issue by rebaz94** [rrousselGit/freezed#695]
Hi.
I have a class that has ```@Implements<Codable>``` and that generate code correctly but I can't pass the instance to a class that accept the ```Codable``` interface.

example
```dart
abstract class Codable {
  Map<String, dynamic> toJson();
}

@freezed
class Example with _$Example {
  @Implements<Codable>()
  const factory Example({
    required String name,
  }) = _Example;

  factory Example.fromJson(Map<String, dynamic> json) => _$ExampleFromJson(json);
}
```

Even if we check the type using ```is``` works but that require to pass the value as an Object.

I can't implicitly cast to ```Codable```
```dart
final Codable ex = Example(name: ''); // error can't be assigned
```

or passing to a function
```dart
void send(Codable codable) {
  print(codable.toJson());
}

void test() {
  send(Example(name: '')); // error can't be assigned
}
```

does I'm missing something or could there is a better way to do that?
Thanks

**Comment by rrousselGit** [comment]
Use the implements keyword, yes.

`@Implements` is for implementing an interface for only one case of a union

**Comment by rebaz94** [comment]
@rrousselGit Thank you for the quick response.

**Comment by om-ha** [comment]
@rrousselGit type check is not working with freezed. Please advise?

Referring to the basic model above:

```dart
void myMethod<T>(T value) {
    // value type ia not `Example` but rather `_$_Example`
    print(value is Codable); // returns false

    print('Unsupported storage type ${value.runtimeType} i.e. $T for $value');   
}
```

```dart
myMethod(Example());
```

**Comment by om-ha** [comment]
How do we get type test operators to work with Freezed instances/classes/generic  types?

https://dart.dev/guides/language/language-tour#type-test-operators

**Comment by rrousselGit** [comment]
> During type check/test, `value` type is not `Example`. But rather `_$_Example`.

_$_Example is a subclass of Example. 

Your example should print true.

**Comment by om-ha** [comment]
It's not printing true :|

**Comment by om-ha** [comment]
These guys return false instead of true.

```dart
print(someFreezedInstance is SuperOrMixinOrInterface); 
// e.g.
print(example is Codable);
```

```dart
print(someGenericTypeIdentifier is SuperOrMixinOrInterface);
// e.g.
print(T is Codable);
```

**Comment by rrousselGit** [comment]
It works for me. Do you have a complete example?

**Comment by om-ha** [comment]
This is a complete example above, but not using freezed.

When `MyType` is a freezed type which implements `MyInterface` with the annotation mentioned in this thread `@Implements<MyInterface>()`, the the type check does not work.

**Comment by rrousselGit** [comment]
As I said, `@Implements<MyInterface>()` followed by `value is MyInterface` works for me.

So I'd like a complete example using Freezed showcasing that it does not

**Comment by om-ha** [comment]
@rrousselGit

I updated the sample above:
- `MyType` is our freezed type.
- `MyNonFreezedType` is a normal type.
- `MyInterface` is the interface we are implementing in both types.
- `myMethod` tests both.

Sorry for pining you a lot, want to help get to the bottom of this.

**Comment by rebaz94** [comment]
@om-ha @implements only work for factory constructor not instance method

Here is the readme example
```dart
abstract class GeographicArea {}
abstract class House {}
abstract class Shop {}
abstract class AdministrativeArea<T> {}

@freezed
class Example with _$Example {
  const factory Example.person(String name, int age) = Person;

  @With<AdministrativeArea<House>>()
  const factory Example.street(String name) = Street;

  @With<House>()
  @Implements<Shop>()
  @Implements<GeographicArea>()
  const factory Example.city(String name, int population) = City;
}

```

**Comment by rrousselGit** [comment]
No that wouldn't work either.

The `@Implements` annotation can only be passed to the constructors that define properties in your Freezed class.

So:

```dart
  @Implements<MyInterface>()
  const factory MyType({
    String? status,
  }) = _MyType;
```

In your example, placing the annotation anywhere else is invalid.

**Comment by om-ha** [comment]
This is working perfectly. @rebaz94 @rrousselGit . Thank you!

Maybe we can highlight this a bit more in the documentation, something like this:

Freezed class interface implementation instructions:
1. Add annotation for determining the interface implemented.
```@Implements<JsonCodable<MyInterface>>()```
2. Add Const constructor to allow defining custom methods.
```const MyFreezedType._();```
3. Add overrides to implement all interface method requirements.
```MyFreezedType? fromJsonString(String? jsonString)```
```String? toJsonString()```
4. Add constructor parameters to implement all interface field requirements.

**Comment by SunlightBro** [comment]
Can you post a full gist are a link to your git where implemented this?
Thats an interesting use case I would like to have a look at. 👀

**Comment by om-ha** [comment]
@SunlightBro I saw your comment somewhere about sharing this, will make sure to share it.
