### ISSUE TITLE
Is it possible to set aliases for fields?

### ISSUE THREAD

**Issue by wuweijian1997** [rrousselGit/freezed#710]
**Is your feature request related to a problem? Please describe.**
I have this json
```
{
page: 1,
data: [{...}],
total: 100
}
```
I want a model like this
```
@freezed
class BookList with _$BookList {
  const factory Person({
    required int page,
    required List books,
    required int total,
  }) = _BookList ;
}
````
**Describe the solution you'd like**
I want to convert the `data` field to `books `.
I wish there was a solution like this
```
class BookList with _$BookList {
  const factory Person({
    required int page,
    @Alias("data")
    required List books,
    required int total,
  }) = _BookList ;
}
```

**Comment by hadysata** [comment]
Check `@JsonKey annotation` in the [Deserializing generic classes](https://github.com/rrousselGit/freezed#deserializing-generic-classes) section:

> All decorators passed to a constructor parameter are "copy-pasted" to the generated property too.
> As such, you can write:
> 
```
@freezed
class Example with _$Example {
factory Example(@JsonKey(name: 'my_property') String myProperty) = _Example;

factory Example.fromJson(Map<String, dynamic> json) => _$ExampleFromJson(json);
}
```

You can achieve that by using [JsonKey](https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey-class.html)

**Comment by wuweijian1997** [comment]
thx.
