### ISSUE TITLE
Remove null fields on toJson

### ISSUE THREAD

**Issue by Scheideba** [rrousselGit/freezed#713]
**Is your feature request related to a problem? Please describe.**
I would like the option to remove all null fields when copying using .toJson(). Currently, when I am saving to my firebase database the null values show up in fields as something like "description: null". It doesn't actually make a difference but I feel it would be cleaner and technically (although a very small amount) save space.

**Describe the solution you'd like**
It would be nice to have an option like the make_collections_unmodifiable one, but something like remove_null_values_on_serialization.

**Describe alternatives you've considered**
Right now I create a toDocument() method that has toJson()..removeWhere((key, value) => value==null). The problem with this is it doesn't work on nested freezed objects.

**Comment by rrousselGit** [comment]
Json_serializable handles that

There are options you can pass to the JsonSerializable annotation which remove nulls.

As such, there's nothing needed for Freezed to support this.

**Comment by Scheideba** [comment]
Ahh got it I did not realize this was possible. Thank you. For other people coming here json_serializable has a build option found here https://pub.dev/packages/json_serializable for include_if_null.
