### ISSUE TITLE
Allow $ in class name

### ISSUE THREAD

**Issue by Kiruel** [rrousselGit/freezed#714]
**Is your feature request related to a problem? Please describe.**
I'm looking for a way to allow $ in class when freeze generate class. Let me explain. I use Mutation/Query from https://pub.dev/packages/graphql_codegen. So I got class model like this `Mutation$GetUserToken` with a $. But when I try to use freezed like this:
```dart
@Freezed(makeCollectionsUnmodifiable: false)
class Success with _$Success {
  const factory Success.refreshToken(
      Mutation$GetUserToken token) = RefreshTokenSuccess;
}
```
Freeze generate this:
```dart
required TResult Function(GetUserToken token) refreshSendBirdToken,
```
Without the $.
It should be:
```dart
required TResult Function(Mutation$GetUserSendBirdToken token) refreshSendBirdToken,
```
**Describe the solution you'd like**
Could be good to allow $ for name separating, a solution can be found for the moment [here](https://github.com/heftapp/graphql_codegen/tree/main/packages/graphql_codegen#change-naming-separator) , it allow to change the naming separator but by default is $.

**Comment by rrousselGit** [comment]
This works now
