### ISSUE TITLE
Allow reading common properties that share a parent class/ implementation

### ISSUE THREAD

**Issue by LewisHolliday** [rrousselGit/freezed#715]
**The problem:**
We can currently read properties that are defined on all constructors as documented [here](https://github.com/rrousselGit/freezed#shared-properties).
However, when a property shares a name but not the type we lose the ability to read those properties. This is true even when the property shares a parent class. Pattern matching is required to read the property when the user may have only wanted the members of its parent class.

Consider:
```dart
abstract class SomeInterface{}

class A implements SomeInterface{}
class B implements SomeInterface{}

class Example with _$Example {
  const factory Example.someCase(A commonProperty) = SomeCase;
  const factory Example.anotherCase(B commonProperty) = AnotherCase;
  const factory Example.aThirdCase(SomeInterface commonProperty) = ThirdCase;
}

final Example example = ...
final SomeInterface commonProperty = example.commonProperty; //does not compile
```

The above is not possible despite each case containining a property that share a name ("commonProperty") and implementation (```abstract class SomeInterface```):

Instead, pattern matching is required to read commonProperty. There may be contexts where we don't care about the union case and merely want to read the shared property as SomeInterface.

**An example API suggestion**

```dart
class Example with _$Example {
  @CommonClass<SomeInterface>("commonProperty")  
  const factory Example.someCase(A commonProperty) = SomeCase;
  const factory Example.anotherCase(B commonProperty) = AnotherCase;
  const factory Example.aThirdCase(SomeInterface commonProperty) = ThirdCase;
}
```

Which would then allow
```dart
final Example example = ...
final SomeInterface commonProperty = example.commonProperty;
```

Would something like this be possible?

**Comment by rrousselGit** [comment]
Sure, that's doable. It's been in my to-do list for a while, but is imply haven't bothered.

I don't see why this would need an annotation though

**Comment by LewisHolliday** [comment]
I was thinking of annotation as an option in more complex scenarios such as where the properties share a parent and also implement other classes. 
```dart
class A extends B implements C{}
```
Is the union's shared property ```B``` or ```C```?
I realise now that the union could expose both a ```B``` and a ```C``` but then what would the variable names be? Perhaps there is an even more elegant solution that I have overlooked.

**Comment by rrousselGit** [comment]
I don't think this scenario is very useful

To begin with, folks could introduce a shared interface between B and C. That's likely more reasonable

**Comment by rrousselGit** [comment]
This is supported in 2.3.0

**Comment by gazialankus** [comment]
When P is a parent class of A and B, and you have List<A> and List<B>, this sometimes correctly gives List<P>, but sometimes gives List<dynamic>. I couldn't see how this nondeterministic behavior occurred, but it's there. 

It's always List<dynamic> when you have List<A>, List<B> and List<C> with P being parent class of all three.

**Comment by gazialankus** [comment]
With this code, 

```
class P {}
abstract class A implements P {}
abstract class B implements P {}
abstract class C implements P {}

@freezed
class Fp with _$Fp {
  const factory Fp.a({
    required int val,
  }) = FpA;
  const factory Fp.b({
    required int val,
  }) = FpB;
  const factory Fp.c({
    required int val,
  }) = FpC;
}
```

When you use `List<A>`, `List<B>` and `List<C>`, you get `List<P>` correctly. But when you use `List<FpA>`, `List<FpB>` and `List<FpC>`, you get `List<Fp>`. 

By the way, when I use only `List<FpA>` and `List<FpB>` I sometimes get `List<Fp>`! This random behavior is what puzzles me the most. With three of them it's always `List<dynamic>`.

**Comment by rrousselGit** [comment]
The output of Freezed classes shouldn't be used as input of other Freezed classes.

So you shouldn't have a union that depends on things like `FpA`/`FpB`/...
These aren't supported and you'll likely get dynamic.

This is known but won't be fixed. Too complex. It'll have to wait until static metaprogramming
