### ISSUE TITLE
Should add field to base mixin even when nullability is inconsistent

### ISSUE THREAD

**Issue by DevNico** [rrousselGit/freezed#720]
In the following example class the `String name` will be part of the `_$Test` mixin but the `id` field isn't. I would expect it to be there since the type and name are identical just the nullability differs.

```dart
@freezed
class Test with _$Test {
  const factory Test.a({
    required SomeObject? id,
    required String name,
  }) = TestA;

  const factory Test.b({
    required SomeObject id,
    required String name,
  }) = TestB;
}
```

**Comment by rrousselGit** [comment]
Closing as dupp of https://github.com/rrousselGit/freezed/issues/715
