### ISSUE TITLE
Unfreezed class: Objects are still immutable

### ISSUE THREAD

**Issue by Losspost** [rrousselGit/freezed#725]
System:
- Flutter (3..0.5) on MacOS
- Dart 2.17.6
- Flutter running in Chrome
Problem:
Variables in Unfreezed States are immutable even through unfreezed tag is used:

Code:

```
part of 'myBloc_bloc.dart';

@unfreezed
class MyState with _$MyState {
  factory PlayercontrollerState(
      {@Default(MyStatus.intial)
          MyStatus status,
      @Default([])
          List<int> MyA,
      @Default({})
          Map<String, B> MyB}) = _MyState;
}
```
I try to modify the list in an bloc event
`state.MyB[event.my] = event.my;`

Error: 

`Error: Unsupported operation: Cannot modify unmodifiable map`

What I have tried so far:
- Rebuild freezed class
- Updated to newest freezed Version
- flutter clean

**Comment by rrousselGit** [comment]
Hello!

It's not the Freezed object that's immutable. It's your default value

Keep in mind that `@Default([])` is strictly equivalent to `@Default(const [])`. 
And with `const []`, the list is immutable.

You likely want a way to have non-constant default values, which is a separate issue. And I don't think that's going to be solved before metaprogramming

If you don't mind, I'll close this as this is expected
