### ISSUE TITLE
Fail to generate class named Forecast

### ISSUE THREAD

**Issue by bounty1342** [rrousselGit/freezed#726]
**Describe the bug**
Fail to generate class named Forecast.

**To Reproduce**

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'forecast.freezed.dart';
part 'forecast.g.dart';

@freezed
class Forecast with _$Forecast {
  const factory Forecast({
    @Default(0) int type,
  }) = _Forecast;

  factory Forecast.fromJson(Map<String, dynamic> json) =>
      _$ForecastFromJson(json);
}
```

**Expected behavior**
Generate whiteout issue.

**Comment by rrousselGit** [comment]
What is your error?

**Comment by bounty1342** [comment]
![Screenshot 2022-08-02 at 18 23 17](https://user-images.githubusercontent.com/6307253/182424631-f1c42c17-f018-4ce9-8b43-57b62be7ba07.png)

**Comment by bounty1342** [comment]
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'forecast.freezed.dart';
part 'forecast.g.dart';

@freezed
class beforetest with _$beforetest {
  const factory beforetest({
    @Default(0) int type,
  }) = _beforetest;

  factory beforetest.fromJson(Map<String, dynamic> json) =>
      _$beforetestFromJson(json);
}
```

Produce the same behavior.

I think it's related to the name of the file !

**Comment by bounty1342** [comment]
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'beforetest.freezed.dart';
part 'beforetest.g.dart';

@freezed
class beforetest with _$beforetest {
  const factory beforetest({
    @Default(0) int type,
  }) = _beforetest;

  factory beforetest.fromJson(Map<String, dynamic> json) =>
      _$beforetestFromJson(json);
}
```

No issues

**Comment by rrousselGit** [comment]
Do you still have a problem if you restart the IDE? It sounds like an analysis issue

Alternatively maybe double-check that the file name matches your parts

**Comment by bounty1342** [comment]
> Do you still have a problem if you restart the IDE? It sounds like an analysis issue
yes 

> Alternatively maybe double-check that the file name matches your parts
Might be, renaming the file to something other than forecast did the trick.

**Comment by sinxwal** [comment]
I had to run `flutter clean` to remove such errors.
