### ISSUE TITLE
Add the `fieldRename` parameter from `JsonSerializable` to `@Freezed` 

### ISSUE THREAD

**Issue by ValentinVignal** [rrousselGit/freezed#729]
**Is your feature request related to a problem? Please describe.**

Right now, if we want to override the field name in the json keys of the `toJson` and `fromJson`, we need to use `@JsonKey`:

```dart
@Freezed()
class MyClass with _$MyClass {
  const factory MyClass({
    @JsonKey(name: 'my-first-variable') String? myFirstVariable,
    @JsonKey(name: 'my-second-variable') String? mySecondVariable,
    // This list of parameters can be quite long
  }) = _MyClass;

  factory MyClass.fromJson(Map<String, dynamic> json) => _$MyClassFromJson(json);
}
```

With `@JsonSerializable`, there is a very useful parameter with is `fieldRename`. This allows me not to specify all the `@JsonKey` one by one, the correct kebab case name is used automatically in the json. This is very useful when working with url parameters.

**Describe the solution you'd like**

It would be nice if `Freezed` had a parameter `fieldRename` and I could do :

```dart
@Freezed(
  fieldRename: FieldRename.kebab,
)
class MyClass with _$MyClass {
  const factory MyClass({
    String? myFirstVariable,
    String? mySecondVariable,
    // This list of parameters can be quite long
  }) = _MyClass;

  factory MyClass.fromJson(Map<String, dynamic> json) => _$MyClassFromJson(json);
}
```

**Describe alternatives you've considered**

Using `JsonKey`, or only `json_serializable` without `freezes`

**Comment by SunlightBro** [comment]
Freezed simply copies annotations from the **constructor** to the **class** and from the **parameters** to the **class-fields**
Please try the following:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'field_rename.freezed.dart';
part 'field_rename.g.dart';

@freezed
class FieldRenameModel with _$FieldRenameModel {
  @JsonSerializable(fieldRename: FieldRename.kebab)
  const factory FieldRenameModel({
    int? foo,
    String? bar,
  }) = _FieldRenameModel;

  factory FieldRenameModel.fromJson(Map<String, dynamic> json) =>
      _$FieldRenameModelFromJson(json);
}
```
