### ISSUE TITLE
Add `@useResult` to copyWith

### ISSUE THREAD

**Issue by miDeb** [rrousselGit/freezed#734]
**Is your feature request related to a problem? Please describe.**
Sometimes when you get distracted you might forget to actually assign the result of calling `copyWith` to the variable you want to change. While an issue like this is obvious once you spot it, doing so may take some time. Also, beginners who are not yet familiar with the concept of `copyWith` may try to use it incorrectly.

**Describe the solution you'd like**
[Starting from dart 2.18 ](https://github.com/dart-lang/sdk/issues/48913) the analyzer will warn you if you do not use the result of calling a callable class whose `call` method is annotated with `@useResult`. This seems like a good opportunity to start using this annotation in `freezed`.

**Describe alternatives you've considered**
I don't think there are any alternatives apart from just not making this change.

**Additional context**
If this is a feature you want I'm ready to implement it.

**Comment by TimWhiting** [comment]
Great idea, I'm sure it would be a welcome contribution
