### ISSUE TITLE
 Unhandled Exception: type 'Freezed' is not a subtype of type 'ValueObject<String>' of 'other'

### ISSUE THREAD

**Issue by Jordanus123** [rrousselGit/freezed#738]
I have a bloc event emailChanged, and it just updates the EmailAddress property of the state. But whet it runs the event on the textformfield onchanged method, i get  Unhandled Exception: type 'Freezed' is not a subtype of type 'ValueObject<String>' of 'other'. The error also points me to the freezed file of the bloc.

specifically this part:

 @override
  $Res call({
    Object? emailAddress = freezed,
    Object? password = freezed,
    Object? isSubmitting = freezed,
    Object? showErrorMessages = freezed,
    Object? authFailureOrSuccessOption = freezed,
  }) {
    return _then(_$_SignInFormState(
      emailAddress: emailAddress == freezed
          ? _value.emailAddress
          : emailAddress // ignore: cast_nullable_to_non_nullable
              as EmailAddress,
      password: password == freezed
          ? _value.password
          : password // ignore: cast_nullable_to_non_nullable
              as Password,

is there something wrong with the equality operator? because if i change emailAddress: emailAddress == freezed into something like emailAddress: emailAddress == true, the error changes to  Unhandled Exception: type 'bool
![Screenshot_1](https://user-images.githubusercontent.com/67093162/184618772-ab273921-3e74-4c51-b641-a10deecc5e9b.png)
![Screenshot_2](https://user-images.githubusercontent.com/67093162/184618775-dcf42db8-9532-47e2-84ba-929d9ce56803.png)
![Screenshot_3](https://user-images.githubusercontent.com/67093162/184618777-4f9d23b7-4ad9-4263-937b-4b7a736fe518.png)
![Screenshot_4](https://user-images.githubusercontent.com/67093162/184618778-7b76376d-5b1b-4c08-9ac9-eea49a9811ff.png)
' is not a subtype of type 'ValueObject<String>' of 'other'

**Comment by Jordanus123** [comment]
@freezed
class SignInFormState with _$SignInFormState {
  const factory SignInFormState({
    required EmailAddress emailAddress,
    required Password password,
    required bool isSubmitting,
    required bool showErrorMessages,
    required Option<Either<AuthFailure, Unit>> authFailureOrSuccessOption,
  }) = _SignInFormState;

  factory SignInFormState.initial() => SignInFormState(
      emailAddress: EmailAddress('2@s.s'),
      password: Password(''),
      isSubmitting: false,
      showErrorMessages: true,
      authFailureOrSuccessOption: none());
}

@freezed
class SignInFormEvent with _$SignInFormEvent {
  const factory SignInFormEvent.emailChanged(String emailString) = EmailChanged;
  const factory SignInFormEvent.passwordChanged(String passwordString) =
      PasswordChanged;
  const factory SignInFormEvent.registerWithEmailAndPasswordPressed() =
      RegisterWithEmailAndPasswordPressed;
  const factory SignInFormEvent.signInWithEmailAndPasswordPressed() =
      SignInWithEmailAndPasswordPressed;
  const factory SignInFormEvent.signInWithGooglePressed() =
      SignInWithGooglePressed;
}

@injectable
class SignInFormBloc extends Bloc<SignInFormEvent, SignInFormState> {
  final IAuthFacade _authFacade;

  SignInFormBloc(this._authFacade) : super(SignInFormState.initial()) {
    on<SignInFormEvent>((event, emit) async {
      event.map(emailChanged: (e) {
        emit(state.copyWith(
            emailAddress: EmailAddress(e.emailString),
            authFailureOrSuccessOption: none()));
      }, passwordChanged: (e) {
        emit(state.copyWith(
            password: Password(e.passwordString),
            authFailureOrSuccessOption: none()));
      }, registerWithEmailAndPasswordPressed: (e) async {
        _performActionOnAuthFacadeWithEmailAndPassword(
            emit, _authFacade.registerWithEmailAndPassword);
      }, signInWithEmailAndPasswordPressed: (e) {
        _performActionOnAuthFacadeWithEmailAndPassword(
            emit, _authFacade.registerWithEmailAndPassword);
      }, signInWithGooglePressed: (e) async {
        emit(state.copyWith(
            isSubmitting: true, authFailureOrSuccessOption: none()));
        final failureOrSuccess = await _authFacade.signInWithGoogle();
        emit(state.copyWith(
            isSubmitting: false,
            authFailureOrSuccessOption: some(failureOrSuccess)));
      });
    });
  }

  _performActionOnAuthFacadeWithEmailAndPassword(
      Emitter<SignInFormState> emit,
      Future<Either<AuthFailure, Unit>> Function(
              {required EmailAddress emailAddress, required Password password})
          forwardedCall) async {
    Either<AuthFailure, Unit>? failureOrSuccess;
    bool isEmailValid = state.emailAddress
        .isValid(); //longer form: state.emailAddress.value.isRight()
    bool isPasswordValid =
        state.password.isValid(); //longer form: state.password.value.isRight()

    if (isEmailValid && isPasswordValid) {
      emit(state.copyWith(
          isSubmitting: true, authFailureOrSuccessOption: none()));

      failureOrSuccess = await forwardedCall(
          emailAddress: state.emailAddress, password: state.password);
    }
    emit(state.copyWith(
        isSubmitting: false,
        showErrorMessages: true,
        authFailureOrSuccessOption: optionOf(failureOrSuccess)
        //same as above ^
        // authFailureOrSuccessOption:
        //     failureOrSuccess == null ? none() : some(failureOrSuccess),
        ));
  }
}


class EmailAddress extends ValueObject<String> {
  @override
  final Either<ValueFailure<String>, String> value;

  const EmailAddress._(this.value);

  factory EmailAddress(String input) {
    return EmailAddress._(validateEmailAddress(input));
  }
}

class Password extends ValueObject<String> {
  @override
  final Either<ValueFailure<String>, String> value;

  const Password._(this.value);

  factory Password(String input) {
    return Password._(validatePassword(input));
  }
}

@immutable
abstract class ValueObject<T> {
  const ValueObject();
  Either<ValueFailure<T>, T> get value;

  bool isValid() => value.isRight();

//GENERATED EQUALITY CODE THRU CTRL + . start
  @override
  bool operator ==(covariant ValueObject<T> other) {
    if (identical(this, other)) return true;

    return other.value == value;
  }

  @override
  int get hashCode => value.hashCode;
  //GENERATED EQUALITY CODE THRU CTRL + . end

//GENERATED TO STRING CODE THRU CTRL + . start
  @override
  String toString() => 'Value(value: $value)';
  //GENERATED TO STRING CODE THRU CTRL + . end

  ///helper method to throw the error
  T getOrCrash() {
    return value.fold((l) => throw UnexpectedValueError(l), (r) => r);
  }
}







Restarted application in 2,235ms.
E/flutter ( 7303): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Freezed' is not a subtype of type 'ValueObject<String>' of 'other'
E/flutter ( 7303): #0      ValueObject.== (package:flutter_ddd/domain/core/value_objects.dart)
E/flutter ( 7303): #1      __$$_SignInFormStateCopyWithImpl.call
E/flutter ( 7303): #2      new SignInFormBloc.<anonymous closure>.<anonymous closure>
E/flutter ( 7303): #3      _$EmailChanged.map
E/flutter ( 7303): #4      new SignInFormBloc.<anonymous closure>
E/flutter ( 7303): #5      Bloc.on.<anonymous closure>.handleEvent
E/flutter ( 7303): #6      Bloc.on.<anonymous closure>
E/flutter ( 7303): #7      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
E/flutter ( 7303): #8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 7303): #9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 7303): #10     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
E/flutter ( 7303): #11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 7303): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7303): #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 7303): #14     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 7303): #15     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter ( 7303): #16     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 7303): #17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter ( 7303): #18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7303): #19     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter ( 7303): #20     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter ( 7303): #21     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter ( 7303): #22     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 7303): #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 7303):

**Comment by miDeb** [comment]
The problem here is that `ValueObject.==` was implemented incorrectly. You have to expect that your `==` operator is called also with objects of a different type, which you implementation does not handle. Here is how you could fix it:
```dart
  @override
  bool operator ==(dynamic other) {
    if (identical(this, other)) return true;
   if (other.runtimeType != runtimeType) return false;

    return other.value == value;
  }
```

Another option would be to make `ValueObject` a `freezed` class so you don't have to implement this manually yourself.

**Comment by Jordanus123** [comment]
it seems that the state.copywith was the issue. i chang

**Comment by SunlightBro** [comment]
No this is your issue in ValueObject not in freezed:
```dart
  @override
  bool operator ==(covariant ValueObject<T> other) { // Don't use covariant
    if (identical(this, other)) return true;

    return other.value == value;
  }
```

**Comment by miDeb** [comment]
Did updating the `==` implementation resolve your issue? I see you have reopened this issue, are you still facing an issue?

**Comment by Jordanus123** [comment]
i reopened it because the issue with emit(state.copyWith()) still exists. My code worked when i replaced it with emit(SignInFormState)

**Comment by Jordanus123** [comment]
This part specifically. I encounter the error when using copywith

```dart
 SignInFormBloc(this._authFacade) : super(SignInFormState.initial()) {
    on<SignInFormEvent>((event, emit) async {
      await event.map(emailChanged: (e) async {
        // emit(state.copyWith(
        //     emailAddress: EmailAddress(e.emailString),
        //     authFailureOrSuccessOption: none()));
       
        emit(
          SignInFormState(
            emailAddress: EmailAddress(e.emailString),
            password: state.password,
            isSubmitting: state.isSubmitting,
            showErrorMessages: state.showErrorMessages,
            authFailureOrSuccessOption: none(),
          ),
        );
      }, passwordChanged: (e) async {
        // emit(state.copyWith(
        //     emailAddress: EmailAddress(e.passwordString),
        //     authFailureOrSuccessOption: none()));
        emit(
          SignInFormState(
            emailAddress: state.emailAddress,
            password: Password(e.passwordString),
            isSubmitting: state.isSubmitting,
            showErrorMessages: state.showErrorMessages,
            authFailureOrSuccessOption: none(),
          ),
        );
      },
```

**Comment by miDeb** [comment]
Did you update the == implementation as I described [here](https://github.com/rrousselGit/freezed/issues/738#issuecomment-1214929585)? If so, which error are you now getting? I assume it has to be a different error then.

**Comment by rrousselGit** [comment]
As mentioned, your problem is your `ValueObject`'s ==
You cannot use `covariant` here. That would cause the exception you gave, as it breaks the contract of ==.

You should instead do:

```dart
operator ==(Object other) {
  if (other is! ValueObject<T>) return false;
  // TODO compare the content of this vs other
}
```
