### ISSUE TITLE
mapOrNull callback return type is non-null

### ISSUE THREAD

**Issue by DevNico** [rrousselGit/freezed#741]
Currently the generated `mapOrNull` / `whenOrNull` callbacks specify a non-null return type.

```dart
@optionalTypeArgs
TResult? mapOrNull<TResult extends Object?>({
  TResult Function(A value)? a,
  TResult Function(B value)? b,
})
```

This forces us to write something like
```dart
value.mapOrNull<int?>(a: (v) => v.abc));
```
when we access a nullable property.

**Comment by rrousselGit** [comment]
Could you clarify what's wrong in the code you gave?

**Comment by DevNico** [comment]
The top code block is an example of the current generation of the mapOrNull function.

The problem I tried to show in the bottom one is that you need to explicitly type the mapOrNull function with a nullable type if the property you are trying to access is nullable.

```dart
@freezed
class A with _$A {
  const factory A.a({String? a}) = _AA;
  const factory A.b({required String b}) = _AB;
}
```

Required type:

```dart
instanceOfA.mapOrNull<String?>(
  a: (v) => v.a,
)
```


Type not required:

```dart
instanceOfA.mapOrNull(
  b: (v) => v.b,
)
```

**Comment by TimWhiting** [comment]
Current:
```dart
@optionalTypeArgs
TResult? mapOrNull<TResult extends Object?>({
  TResult Function(A value)? a,
  TResult Function(B value)? b,
})
```

Pull Request:
```dart
@optionalTypeArgs
TResult? mapOrNull<TResult extends Object?>({
  TResult? Function(A value)? a,
  TResult? Function(B value)? b,
})
```

```dart
@freezed
class A with _$A {
  const factory A.a({String? a}) = _AA;
  const factory A.b({required String b}) = _AB;
}

instanceOfA.mapOrNull( // ERROR HERE
  b: (v) => v.b,
)
```
Am I correct in where the error is happening.

I'm a little confused why the type inference would instantiate TResult to be String in your example causing the error, this is most likely an issue with dart's inference, but your change makes sense if it is something they do not wish to fix. What version of dart / flutter are you on. I know they have been working on inference across callbacks passed to functions recently, which previously was not really a thing.

**Comment by DevNico** [comment]
Yes, you are correct in where the error is happening (I should really work on my issue descriptions). I tested this on the flutter stable channel (3.0.5 / Dart 2.17.2).

Even if this eventually gets fixed by the dart team this change doesn't have any negative impact as far as I can tell.
