### ISSUE TITLE
when using @unfreezed no setters are generated

### ISSUE THREAD

**Issue by ekuleshov-idexx** [rrousselGit/freezed#743]
**Describe the bug**

When using the `@unfreezed` annotation fields are generated, as well as the getters for those fields. However no setters are generated, so it is not possible to set values on the unfreezed instances.

**To Reproduce**

Consider the following class definition

```
@unfreezed
class Person with _$Person {
  const factory Person({
    required String firstName,
    required String lastName,
    int? age,
  }) = _Person;
}
```

Then the following code is failing to compile using generated `Person` class:

```
Person p = Person(firstName: 'Joe', lastName: 'Bins');
p.age = 20; // <--- this cause error
```

**Expected behavior**

It would be great if the above example worked out of the box

**Comment by rrousselGit** [comment]
Your snippet isn't valid.
`age` must either be nullable or with a default value

I assume you have this error because Freezed didn't generate anything due to this error.


If `age` is nullable, your code works for me.

**Comment by ekuleshov-idexx** [comment]
> If `age` is nullable, your code works for me.

My bad. The `@unfreezed` works. I also missed to remove the `const` in the factory constructor and also had to explicitly specify parameters of the `@Freezed` annotation to keep copyWith and equals generators.

Perhaps it might be a good idea to warn about the `const` factory when `addImplicitFinal: false` is used directly or indirectly.
