### ISSUE TITLE
why 'A freezed union cannot have private constructors'?

### ISSUE THREAD

**Issue by IlyaMax** [rrousselGit/freezed#744]
**Is your feature request related to a problem? Please describe.**
I use flutter bloc and freezed for events. but some of them are used internally in bloc only so it would be very useful if it could be possible to hide them.

Is there some explanation why this made like that? Maybe it causes any problems?

**Comment by rrousselGit** [comment]
Because it's not possible to have private named parameters.

So freezed cannot generate something like `when(_union: ..., _union2: ...)`

**Comment by IlyaMax** [comment]
I mean generator looks for constructors names with _ and instead of creating `when(_union: ..., _union2: ...)` it generates`when(union: ..., union2: ...)`

**Comment by rrousselGit** [comment]
We could, yes.  
But then that'd mean the private constructors would leak into the public API.

In that case, they might as well be public

**Comment by IlyaMax** [comment]
@rrousselGit I understand that some api will leak but at least we could forbid the construction of models. So we could create instances of models within library only

**Comment by IlyaMax** [comment]
Yeap, thx, I think that's enough for my case

**Comment by rrousselGit** [comment]
Closing in favor of https://github.com/rrousselGit/freezed/issues/925
