### ISSUE TITLE
[WARNING] json_serializable 

### ISSUE THREAD

**Issue by Shiba-Kar** [rrousselGit/freezed#746]
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'totem_body.freezed.dart';
part 'totem_body.g.dart';

@freezed
abstract class TotemCreateBody with _$TotemCreateBody {
  const factory TotemCreateBody({
    @Default("") String number,
    @Default("") String name,
    @JsonKey(name: "underworld_pin", defaultValue: 0) int underworldPin,
    @Default(0) int underworld_mode,
    @Default(0.0) double latitude,
    @Default(0.0) double longitude,
    @Default(false) bool request_to_join,
  }) = _TotemCreateBody;

  factory TotemCreateBody.fromJson(Map<String, dynamic> json) =>
      _$TotemCreateBodyFromJson(json);
}

```

[WARNING] json_serializable:json_serializable on lib/features/totem/models/totem_poles_result.dart:
The constructor parameter for `id` has a default value `""`, but the `JsonKey.defaultValue` value `''` will be used for missing or `null` values in JSON decoding.

**Comment by SunlightBro** [comment]
Please upgrade to the latest version of freezed, you are declaring your class **`abstract`**
which is deprecated since version 0.14.0 of freezed. (_current version is 2.1.0_)
[#0.14.0 and null-safety](https://github.com/rrousselGit/freezed/blob/d46a672811f7f592adeb3449526f30dac9149d11/packages/freezed/README.md#0140-and-null-safety)

> Important note:
>
> From 0.14.0 and onwards, Freezed only supports null-safe code.
>
> If you want to keep using Freezed but cannot migrate to null-safety yet, use the version 0.12.7 instead.
Note that this version is no-longer maintained (so bugs found there won't be fixed).

**Comment by SunlightBro** [comment]
@Shiba-Kar Please check if this snippet works for you (on the latest version of freezed), so this issue can be closed:
```dart
// ignore_for_file: invalid_annotation_target
import 'package:freezed_annotation/freezed_annotation.dart';
part 'totem_body.freezed.dart';
part 'totem_body.g.dart';

@freezed
class TotemCreateBody with _$TotemCreateBody {
  const factory TotemCreateBody({
    @Default("") String number,
    @Default("") String name,
    @Default(0) @JsonKey(name: "underworld_pin") int underworldPin,
    @Default(0) @JsonKey(name: "underworld_mode") int underworldMode,
    @Default(0.0) double latitude,
    @Default(0.0) double longitude,
    @Default(false) @JsonKey(name: "request_to_join") bool requestToJoin,
  }) = _TotemCreateBody;

  factory TotemCreateBody.fromJson(Map<String, dynamic> json) =>
      _$TotemCreateBodyFromJson(json);
}
```
