### ISSUE TITLE
@Default using static const will generate code that does not compile

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/freezed#75]
```dart
@Default(Duration.zero)
```

**Comment by doc-rj-celltrak** [comment]
I have a question that may be related to this, but forgive me if it's not. Do you have a recommendation for using @Default with a dart enum? json_serializable seems to support dart enums and default values, but if I use freezed @Default (which i need), I get failures during source generation. Thanks.

**Comment by rrousselGit** [comment]
Fixed (enums too) as part of 0.9.1
