### ISSUE TITLE
Code generation for third party classes

### ISSUE THREAD

**Issue by FaFre** [rrousselGit/freezed#750]
Let's say some package is providing me an immutable class as a result. Unfortunately, there is no equality support and `copyWith`, as I know and love from `freezed`. Package authors want to have as less dependencies as possible, so depending on freezed for code generation is often not appreciated, although it would be perfect for those scenarios.

It would be great to be able to "upgrade" those classes inside my own project, to combine it with the power of freezed. It would be great to have a feature like mockito (https://pub.dev/packages/mockito) to generate code for foreign classes `@GenerateMocks([Cat])`. I guess the configuration possibilities of freezed would be a bit less, but still providing core functionality.

What do you think about this?

Maybe there is also another easier workaround for this, I haven thought of?

**Comment by rrousselGit** [comment]
Hello!

That's not something I would like to have in Freezed. The goal of Freezed is to ultimately be deprecated once Dart catches up.
Such a feature would be counter-productive as there's no way Dart would implement it.

As such, I don't plan on implementing it in Freezed either. Especially considering this likely is a fairly rare scenario.


I'd suggest manually implementing the ==/hashCode for this edge case.
