### ISSUE TITLE
Cannot add to an unmodifiable list

### ISSUE THREAD

**Issue by 4-alok** [rrousselGit/freezed#758]
Unhandled Exception: Unsupported operation: Cannot add to an unmodifiable list

```dart
TimeTable t = await getTimeTable();
t.week.add(         // ===> Error at here
    Day(day: field[i][_dayColIndex], subjects: getSubjects(field[i])),  // Some data
);

```

My model

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'time_table.freezed.dart';
part 'time_table.g.dart';

@freezed
class TimeTable with _$TimeTable {
  const factory TimeTable({
    required List<Day> week,
    required String creatorId,
    required String batch,
    required int year,
    required int slot,
    required DateTime date,
  }) = _TimeTable;

  factory TimeTable.fromJson(Map<String, dynamic> json) =>
      _$TimeTableFromJson(json);
}

@freezed
class Day with _$Day {
  const factory Day({
    required String day,
    required List<Subject> subjects,
  }) = _Day;

  factory Day.fromJson(Map<String, dynamic> json) => _$DayFromJson(json);
}

@freezed
class Subject with _$Subject {
  const factory Subject({
    required String subjectName,
    @Default("") String subjectAddBy,
    @Default("") String remark,
    @Default("") String remarkAddBy,
    @Default("") String googleClassRoomLink,
    @Default("") String gLinkAddBy,
    @Default(null) String? roomNo,
    @Default("") String roomNoAddBy,
    @Default("") String zoomLink,
    @Default("") String zLinkAddBy,
    required DayTime startTime,
  }) = _Subject;

  factory Subject.fromJson(Map<String, dynamic> json) =>
      _$SubjectFromJson(json);
}

@freezed
class DayTime with _$DayTime {
  const factory DayTime({
    required int hour,
    required int minute,
  }) = _DayTime;

  factory DayTime.fromJson(Map<String, dynamic> json) =>
      _$DayTimeFromJson(json);
}

```

**Comment by rrousselGit** [comment]
Hello!

How is this related to Freezed?

**Comment by rorystephenson** [comment]
@4-alok Have you seen this part of the README: https://github.com/rrousselGit/freezed#allowing-the-mutation-of-listsmapssets

Collections (including lists) are unmodifiable by default when using freezed however this is configurable.

**Comment by gonzalogauto** [comment]
@rorystephenson Sorry I see the same error. From which version was the behavior changed so that by default all collections cannot be modified?

**Comment by rorystephenson** [comment]
> @rorystephenson Sorry I see the same error. From which version was the behavior changed so that by default all collections cannot be modified?

Even when setting the flag to make the collections modifiable or using @unfreezed as linked in the Readme?

I'm not sure when it changed.

**Comment by gonzalogauto** [comment]
> > @rorystephenson Sorry I see the same error. From which version was the behavior changed so that by default all collections cannot be modified?
> 
> Even when setting the flag to make the collections modifiable or using @unfreezed as linked in the Readme?
> 
> I'm not sure when it changed.

No no, with the flag works fine I was asking if you known the version of that change only.

**Comment by rorystephenson** [comment]
> > > @rorystephenson Sorry I see the same error. From which version was the behavior changed so that by default all collections cannot be modified?
> > 
> > 
> > Even when setting the flag to make the collections modifiable or using @unfreezed as linked in the Readme?
> > I'm not sure when it changed.
> 
> No no, with the flag works fine I was asking if you known the version of that change only.

Ah nice I'm glad it's working.

I had a quick search of the CHANGELOG.md and it looks like it was part of v2: https://github.com/rrousselGit/freezed/blob/master/packages/freezed/CHANGELOG.md#200

**Comment by rrousselGit** [comment]
So can this be closed as expected @4-alok ?
