### ISSUE TITLE
Allow a configuration to not include some fields in `copyWith`

### ISSUE THREAD

**Issue by ValentinVignal** [rrousselGit/freezed#761]
**Is your feature request related to a problem? Please describe.**

Let's consider a `Post` class with `content` and `authorId` fields

```dart
class Post {
  final String content;
  final String authorId;
}
```

I would like to use freezed with it but _"hide"_ the parameter `authorId` in the generated `copyWith` method to have something similar to :

```dart
class Post {
  final String content;
  final String authorId;

  Post copyWith({String? content}); // No authorId parameter available.
}
```

**Describe the solution you'd like**

A decorator could be added?

```dart
@freezed
class Post with _$Post {
  const factory Post({
    required String content,
    @CopyWith(false) required String authorId,
  }) = _Post;
```

or whatever would be the best way to set this parameter

**Describe alternatives you've considered**

For now, we ignore those parameters and we try to remember we should not use them.

**Additional context**

Here, the class has only 2 fields, 1 visible and 1 hidden in the `copyWith` but there could be many more.

**Comment by rrousselGit** [comment]
Hello!

What is the goal? What's wrong with having that parameter? Could you simply ignore it?

**Comment by ValentinVignal** [comment]
Yes yes, I could simply ignore it.

I'll try to explain a bit better what I would use it for though. Let's say I have an object `Post` (like a facebook post):

```dart
class Post {
  final String id;
  final String authorId;
  final String content;
  final DateTime postedAt;
  final DateTime lastUpdatedAt;
}
```

A `Post` can be created:

```dart
final post = Post(
  id: id,
  authorId: userId,
  content: 'my content',
  postedAt: DateTime.now(),
  lastUpdatedAt: DateTime.now(),
);
```

and also modified, but when modified, only the `content` and `lastUpdatedAt` should be changed, not the `id`, `authorId` or `postedAt`:

```dart
final modifiedPost = post.copyWith(
  content: 'my new content',
  lastUpdatedAt: DateTime.now(),
);
```

That's why it could be neat to not even have the option to set it in the `copyWith` so it is clear what can be modified and what cannot be modified.

**Comment by rrousselGit** [comment]
I don't plan on working on such a thing for now. For now I don't think it's very important.

If people are interested in this, I encourage you to add a :+1:

**Comment by berdroid** [comment]
This feature would be very nice to have indeed.
I would suggest a shorter decorator, such as `@Const` or `@Frozen`.

**Comment by rrousselGit** [comment]
I have no plan to implement this. So closing :)
