### ISSUE TITLE
Incorrect generating generic Class for typedef

### ISSUE THREAD

**Issue by atretiakMobidev** [rrousselGit/freezed#764]
Hi. I cought incorrect behavior during generation. I have next class

```
@freezed
class VisitTileMode with _$VisitTileMode {
    const factory VisitTileMode.addScheduledJob({
        JobScheduledUnscheduled? selectedJob,
        required JobScheduledUnscheduled job,
        required ValueChanged<JobScheduledUnscheduled> onChanged,
     }) = _VisitTileModeScheduled
}
```

But generation process creates next code, where ValueChanged generic is dynamic
```
const factory _VisitTileModeScheduled(
          {final JobScheduledUnscheduled? selectedJob,
          required final JobScheduledUnscheduled job,
          required final ValueChanged<dynamic> onChanged}) =
      _$_VisitTileModeScheduled;
```

JobScheduledUnscheduled is also generated by freezed class.

Freezed version: 2.1.0+1
Flutter doctor
```
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.22622.590], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by rrousselGit** [comment]
Do you have a complete example? You haven't shared `JobSceduledUnscheduled`

**Comment by atretiakMobidev** [comment]
Here it is
```
@freezed
class Job with _$Job {
  const Job._();
  
  factory Job.scheduledUnscheduled({
    required String name,
    required JobStatusEnum status,
    required ContactGeneral contact,
    required Jobsite jobSite,
    int? id,
    String? customId,
    required JobCrewLead crewLead,
    @Default([]) List<ServiceInfo> items,
    int? estimatedDurationMinutes,
  }) = JobScheduledUnscheduled;
}
```

ContactGeneral, Jobsite, JobCrewLead, ServiceInfo also freezed generated classes

**Comment by atretiakMobidev** [comment]
I've read about this issue on old freezed versions, and that it was fixed, but I still can reproduce it.
The only way I can deal with it, is create 
`typedef onJobScheduledUnscheduledChanged = void Function(JobScheduledUnscheduled value);`

**Comment by rrousselGit** [comment]
Thanks! I was missing your typedef.


That's """expected""".   
You cannot use generated classes (such as JobScheduledUnscheduled) as the input of other Freezed classes. When Freezed runs, these classes do not exist yet. So the analyzer picks them up as "dynamic". Hence why Freezed generates "dynamic".



Fixing that is not entirely impossible, but requires far too much work for a small edge case that would be in part fixed by static-metaprogramming.

So I'm not going to work on such a scenario.


Rather than using `JobScheduledUnscheduled`, consider using `Job` directly.
