### ISSUE TITLE
pub.dev API Reference link goes to broken page

### ISSUE THREAD

**Issue by dalewking** [rrousselGit/freezed#773]
**Describe the bug**
The documentation link from pub.dev goes to broken page

**To Reproduce**

- Go to https://pub.dev/packages/freezed
- Note that the documentation looks nice
- Click on the API reference link under Documentation on the right side
- The browser goes to https://pub.dev/documentation/freezed/latest/
- The documentation here is somewhat broken
  - The before and after images don't load
  - links in the index to parts of the document do not work 

**Expected behavior**
That the documentation looks and works like the main page

**Comment by SunlightBro** [comment]
pub.dev /packages site gets the images via redirect [302] from github
https://github.com/rrousselGit/freezed/raw/master/resources/before.png

/documentation gets generated "made with love by dartdoc 6.1.1" by pub.dev and some how tries to access the images via
https://pub.dev/documentation/freezed/latest/resources/before.png with does not exist [404] 

**A solution would be to use raw.githubusercontent.com**
https://raw.githubusercontent.com/rrousselGit/freezed/master/resources/before.png
