### ISSUE TITLE
Does this is a valid usage of Freezed?

### ISSUE THREAD

**Issue by a313** [rrousselGit/freezed#774]
I have an entity class with some getter and setter, then i want to make an model extends from that entity. But I cant find a solution for this with freezed.
That's how did i do

![Screen Shot 2022-10-06 at 13 47 47](https://user-images.githubusercontent.com/6405454/194234331-251fb096-cacc-460e-a929-d33e4d6a817e.png)
![Screen Shot 2022-10-06 at 13 49 32](https://user-images.githubusercontent.com/6405454/194234385-95c61f84-8b73-4283-b923-e704da7ea3f9.png)

then it's showing the error
![194234473-b17f944a-4cf4-41d5-ba9d-c56eca0cc887](https://user-images.githubusercontent.com/6405454/194242449-99628860-815d-44ff-afbd-1ed53ad60ec6.png)

**Comment by rrousselGit** [comment]
As the doc mentions, when extending something of defining getters, you need to define an empty private constructor

**Comment by a313** [comment]
@rrousselGit 

I followed the document but still can't make it work
![Screen Shot 2022-12-09 at 09 12 53](https://user-images.githubusercontent.com/6405454/206608769-b396dec1-547c-45a1-8dbc-86da3d1bf5ca.png)
