### ISSUE TITLE
`copyWith` getter causing `inconsistent_inheritance_getter_and_method` error.

### ISSUE THREAD

**Issue by timnew** [rrousselGit/freezed#782]
**Is your feature request related to a problem? Please describe.**

I'm using freezed generated class for [ThemeExtension](https://api.flutter.dev/flutter/material/ThemeExtension-class.html), but quickly run into a unresolvable issue `inconsistent_inheritance_getter_and_method`, which is caused by the generated `copyWith` conflicts with abstract method declared in `ThemeExtension`.

I know there had been some discussion on this issue(https://github.com/rrousselGit/freezed/issues/689), and I understand Freezed is heavily depends on the getter to distinguish `null` and unchanged(aka `freezed`). So getter is mandatory for freezed to work.

But still wondering is it possible to provide a bit granular control to developer on the generator, such as use a different name for the getter or disable the generation for a certain method. So developer can decide what to do in those tricky situations.

**Describe the solution you'd like**

The issue can be solved if freezed allow developer to rename the generated `copyWith` to a different name:

```dart
@freezed
@FreezedOptions(renameCopyWith: "_copyWith") // Give an explicit name for generated `copyWith`
class ColorPalette extends ThemeExtension<ColorPalette> with _$ColorPalette {
  const ColorPalette._();

  const factory ColorPalette({   
    required Color error,
    required Color info,
    required Color success,
    Color? optionalColor,
  }) = _ColorPalette;


  @override
  ColorPalette lerp(ColorPalette? other, double t) {
     // ...
  }

  @override
  ColorPalette copyWith({Color? error, Color? info, Color? success, Color? optionalColor}) => 
    // Forward call to freezed generated copyWith.
    _copyWith(
      error: error ?? this.error,
      info: info ?? this.info,
      success: success ?? this.success,
      // Let the manual `copyWith` implementation to decide what to do with optional value.
      optionalColor: optionalColor ?? this.optionalColor,
   );
}

```
 
**Describe alternatives you've considered**

Or if freezed allow developer to disable `copyWith` generation, and let the developer to fulfil the contract with manual implementation.

```dart
@freezed
@FreezedOptions(noCopyWith: true) // Disable `copyWith` generation
class ColorPalette extends ThemeExtension<ColorPalette> with _$ColorPalette {
  const ColorPalette._();

  const factory ColorPalette({   
    required Color error,
    required Color info,
    required Color success,
    Color? optionalColor,
  }) = _ColorPalette;


  @override
  ColorPalette lerp(ColorPalette? other, double t) {
     // ...
  }

  @override
  ColorPalette copyWith({Color? error, Color? info, Color? success, Color? optionalColor}) =>
    // Manual implementation 
    ColorPalette(
      error: error ?? this.error,
      info: info ?? this.info,
      success: success ?? this.success,
      optionalColor: optionalColor ?? this.optionalColor,
    );
}
```

**Comment by rrousselGit** [comment]
Hello!

Are you maybe looking for `Freezed(copyWith: false)`?

**Comment by timnew** [comment]
Thanks @rrousselGit I should read the doco better.
That's exactly what I'm looking for.
