### ISSUE TITLE
@JsonKey(ignore: true) request @Default parameter

### ISSUE THREAD

**Issue by saveKenny** [rrousselGit/freezed#786]
I want to ignore a specific key, so I'm using `@JsonKey(ignore: true)`.

    @freezed
    class ObjectA with _$ObjectA {
      const factory ObjectA({
        @JsonKey(ignore: true) 
        List<ObjectB> ObjectBList,
      }) = _ObjectA;
    
      factory ObjectA.fromJson(Map<String, dynamic> json) => _$ObjectA(json);
    }

When I try to run the build_runner, I'm getting the above exception:

> The parameter `ObjectBList` of `ObjectA.` is non-nullable but is neither required nor marked with @Default

Why doesn't it been ignored?

### Update

It works when I'm adding a dummy @Default value. But I think it should not fail if it's flagged ignore.

freezed: ^2.1.0+1
freezed_annotation: ^2.1.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by rrousselGit** [comment]
It being ignored has nothing to do with the problem at hand:

Non-nullable parameters must either be "required" or have a default value.
So this is expected

**Comment by saveKenny** [comment]
> It being ignored has nothing to do with the problem at hand:
> 
> Non-nullable parameters must either be "required" or have a default value.
> So this is expected 

Hey thanks for replying. But if its been ignored, why is it needed to be declared?

**Comment by rrousselGit** [comment]
As I said, it has nothing to do with from/toJson.  
It's about how constructor parameter works.

The constructor you defined is not valid Dart code.

**Comment by saveKenny** [comment]
Thanks for the clarification
