### ISSUE TITLE
Add updateWith, or mapWith, or whatever name you like

### ISSUE THREAD

**Issue by norpan** [rrousselGit/freezed#788]
**Is your feature request related to a problem? Please describe.**
I find myself writing a lot of code like this:
```dart
someObject.copyWith(someField: someFunction(someObject.someField)
```
and it gets more and more error prone (having to specify the correct previous field value) when you have a few levels of copyWith.
```dart
someObject.copyWith.someField(someSubfield: someFunction(someObject.someField.someSubfield)
```

**Describe the solution you'd like**
I'd like it to be done this way:
```dart
someObject.updateWith(someField: someFunction)
```
and also of course having
```dart
someObject.updateWith.someField(someSubfield: someFunction)
```

**Comment by rrousselGit** [comment]
This is a subset of https://github.com/rrousselGit/freezed/issues/685
