### ISSUE TITLE
Use `SharedPartBuilder` instead of `PartBuilder`

### ISSUE THREAD

**Issue by afgriffiths** [rrousselGit/freezed#790]
**Is your feature request related to a problem? Please describe.**
I do not see any benefit to having a seperate `.freezed.dart` file as opposed to simply using a `PartBuilder`.

Many people use freezed in combination with json_serializable and this results in two auto-generated file being created for each source file, cluttering the project file tree, and necessitating writing two `part` directives in each source file.

In the official `source_gen` docs for `PartBuilder` it even says:  'This builder should be avoided - prefer using `SharedPartBuilder` and generating content that can be merged with output from other builders into a common `.g.dart` part file.'

**Describe the solution you'd like**
I would like `PartBuilder` to be replaced with `SharedPartBuilder` so that the number of auto-generated files is reduced when using freezed in combination with other `SharedPartBuilder` based code generating libraries.

**Describe alternatives you've considered**
I suppose there may be a good reason why freezed needs it's own auto-generated file, if so I'd like to hear it and have it well documented somewhere for future reference.

**Comment by rrousselGit** [comment]
It's a technical limitation. If Freezed generated a .g.dart, json_serializable wouldn't work when combined with freezed.  
This is necessary and cannot be changed.


I'd suggest:
- hiding generated files in your IDE (vscode has a few options for this)
- waiting for static metaprogramming (in which case this will not be an issue anymore)
