### ISSUE TITLE
Allow union key to come from sibling object

### ISSUE THREAD

**Issue by lukepighetti** [rrousselGit/freezed#795]
Consider these two objects where the key is `metadata.message_type` and the json object is in `payload`, I don't believe there's a way to handle this case in freezed (without manually moving `metadata.message_type` to `payload.runtimeType` for example.

```json
{
  "metadata": {
    "message_id": "96a3f3b5-5dec-4eed-908e-e11ee657416c",
    "message_type": "session_welcome",
    "message_timestamp": "2022-10-19T14:56:51.634234626Z"
  },
  "payload": {
    "session": {
      "id": "AQoQILE98gtqShGmLD7AM6yJThAB",
      "status": "connected",
      "connected_at": "2022-10-19T14:56:51.616329898Z",
      "keepalive_timeout_seconds": 10,
      "reconnect_url": null
    }
  }
}
```

```json
{
  "metadata": {
      "message_id": "84c1e79a-2a4b-4c13-ba0b-4312293e9308",
      "message_type": "session_keepalive",
      "message_timestamp": "2019-11-16T10:11:12.123Z"
  },
  "payload": {}
}
```

**Comment by rrousselGit** [comment]
There's no built-in way to do that. You could make a custom fromJson (as you did in another issue)

We could have support for this. Although it's low priority for me.

**Comment by lukepighetti** [comment]
I'm going to close this. It's totally reasonable to transform the payload before serialization. Probably too "automagic" and not common enough to warrant a new feature.
