### ISSUE TITLE
How to define a custom json parser without overriding the default constructor? Documentation unclear.

### ISSUE THREAD

**Issue by maikeriva** [rrousselGit/freezed#798]
Hello, I think the current documentation doesn't explain very clearly the following scenario. I have a freezed model such as:
```
@freezed
class MyModel with _$MyModel {
  const factory MyModel({
  required String id,
  required String name,
  }) = _MyModel;
```
And I want to be able to instantiate it either locally (by calling `MyModel(id: 'a', name: 'someName')`) and from a Json response. Problem is, the json response is complicated and I need to parse it to extract the `id` and `name` parameters. To do so, I am looking at the **Custom converter** section of the documentation, but it looks like this approach would require using a different model constructor specifically tailored for the custom converter.

Is there a way to have a custom json parser for the `.fromJson` method, while keeping a normal constructor at the same time?

**Side note**: In the custom converter example we also have:
```
@freezed
class MyModel with _$MyModel {
  const factory MyModel(@MyResponseConverter() MyResponse myResponse) = MyModelData;

  factory MyModel.fromJson(Map<String, dynamic> json) => _$MyModelFromJson(json);
}
``` 
What is `MyModelData` and where is it defined?

Thanks for any support :)

**Comment by rrousselGit** [comment]
Honestly I don't understand what this is about.

Are you maybe looking for adding a `fromjson`on `MyResponse`?

**Comment by maikeriva** [comment]
Thanks for your reply. I'm sorry, I'll try to be more clear.

As I said, I have a fairly trivial freezed class:
```
@freezed
class MyModel with _$MyModel {
  const factory MyModel({
  required String id,
  required String name,
  }) = _MyModel;
```
Normally, I instantiate it like this:
``
final model = MyModel(id: `a`, name: `b`);
```
However, I'd like to be able to instantiate it also from some JSON responses. To do so, I see that an integration with the json_serializable package is available so that I can do:
``
final model = MyModel.fromJson(jsonMap);
```
Unfortunately, `jsonMap` is from a JSON response which is somewhat different, like:
```
{
  id: 'a',
  params: {
    name: 'b'
  }
}
```
To tackle this issue, I saw in the documentation that it is possible to define a custom JSON converter, such as in this example:
```
class MyResponseConverter implements JsonConverter<MyResponse, Map<String, dynamic>> {
  const MyResponseConverter();

  @override
  MyResponse fromJson(Map<String, dynamic> json) {
    // type data was already set (e.g. because we serialized it ourselves)
    if (json['runtimeType'] != null) {
      return MyResponse.fromJson(json);
    }
    // you need to find some condition to know which type it is. e.g. check the presence of some field in the json
    if (isTypeData) {
      return MyResponseData.fromJson(json);
    } else if (isTypeSpecial) {
      return MyResponseSpecial.fromJson(json);
    } else if (isTypeError) {
      return MyResponseError.fromJson(json);
    } else {
      throw Exception('Could not determine the constructor for mapping from JSON');
    }
 }

  @override
  Map<String, dynamic> toJson(MyResponse data) => data.toJson();
}

@freezed
class MyModel with _$MyModel {
  const factory MyModel(@MyResponseConverter() MyResponse myResponse) = **MyModelData**;

  factory MyModel.fromJson(Map<String, dynamic> json) => _$MyModelFromJson(json);
}
```
However, in this example I see that MyModel completely replaced the constructor, and thus I don't think it can be instantiated anymore with:
```
final model = MyModel(id: `a`, name: `b`);
``` 
My question thus is: is it possible to instantiate with `final model = MyModel(id: `a`, name: `b`);` even if I define a custom JSON converter?

**Comment by rrousselGit** [comment]
Do you maybe want to manually define the fromJson?

```dart
@freezed
class MyModel with _$MyModel {
  const factory MyModel({
    required String id,
    required String name,
  }) = _MyModel;

  factory MyModel.fromJson(Map<String, dynamic> json) {
    return MyModel(id: json['id'] as String, name: json['param']['name'] as String);
  }
}
```

**Comment by maikeriva** [comment]
Yeah, that's what I am going with so far, I manually defined both my .fromJson and .toJson methods, but I wondered whether there was a better way to do so by using json_serializer. I guess there isn't :)

Thanks for the input, and thanks for your great work!

**Comment by rrousselGit** [comment]
That's the expected way to do it yes :)
