### ISSUE TITLE
Does Freezed support Flutter Web?

### ISSUE THREAD

**Issue by erluxman** [rrousselGit/freezed#799]
**Describe the bug**
The documentation doesn't mention Flutter Web support

**To Reproduce**

I don't feel like there is any reason for not supporting flutter web as it's a code generator. But I am surprised not to see Flutter Web support in its pub. dev listing.

Will it be safe to use Freezed for an app that needs to support Flutter web?

**Comment by SunlightBro** [comment]
`freezed` is only a `dev_dependencies` (not part of the final app!)
It has transitive dependency on `dart:io` (reading, writing files)

But that doesn't matter, check pub [freezed_annotation](https://pub.dev/packages/freezed_annotation) instead.

**Comment by rrousselGit** [comment]
Freezed works with any platforms that Dart supports, as the generated code is plain Dart with nothing special in there.

The code-generator specifically though doesn't run on web. It's executed locally in your terminal, not in your client app.


Overall pub saying web isn't supported is more a technicality of code-generators than an actual issue. Web is supported.
