### ISSUE TITLE
Return Future from when  

### ISSUE THREAD

**Issue by passsy** [rrousselGit/freezed#8]
What's the reason for `Result when<Result extends Object>`? With the `extends Object` restriction it isn't possible to return `Future<T>` or `FutureOr<T>`

<img width="452" alt="Screen-Shot-2020-02-09-13-57-31 54" src="https://user-images.githubusercontent.com/1096485/74102538-80dc4500-4b44-11ea-8c15-612ec8cdc6f0.png">

How do you imagine to use when with `Futures` or `FutureOr`?

With `Result when<Result>` it simply works but I don't know if other code requires a `Object` somewhere.

**Comment by rrousselGit** [comment]
That's for `Result` to not fallback to `dynamic`:

```dart
foo.when(
  something: () {
    doSomething();
  }
)
```

**Comment by rrousselGit** [comment]
Did you forget to import `FutureOr` somehow?

For me this works:

```dart

@immutable
abstract class NoDefault with _$NoDefault {
  const factory NoDefault.first(String a) = NoDefault1;
  const factory NoDefault.second(String a) = NoDefault2;
}

test('when & co can use FutureOr', () {
  var res = NoDefault.first('a').when<FutureOr<int>>(
    first: (a) => 21,
    second: (b) => Future.value(42),
  );

  expectLater(res, completion(21));

  res = NoDefault.second('a').when<FutureOr<int>>(
    first: (a) => 21,
    second: (b) => Future.value(42),
  );

  expectLater(res, completion(42));
});
```

**Comment by passsy** [comment]
The issue was on my side. Another library was declaring a class [`Object`](https://github.com/xsahil03x/super_enum/blob/f3330439ff05b71ae56ac0aa169dea9c36128b26/super_enum/lib/src/annotations.dart#L13) which the analyzer used instead of `dart:core` `Object`. 🤦‍♂
