### ISSUE TITLE
Support deep copy

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/freezed#80]
Consider two classes:

```dart
@freezed
abstract class Person with _$Person {
  factory Person(String name, int age) = _Person;
}

@freezed
abstract class Company with _$Company {
  factory Company(String name, Person director) = _Company;
}
```

Now say we want to change the director's name, then we would have to write:

```dart
Company company;

company = company.copyWith(
  director: company.director.copyWith(name: 'New name'),
)
```

This is not ideal, especially on very nested objects.

Another solution would be to, on `Company`, generate methods to update `director` directly:
```dart
Company company;

company = company.$director.copyWith(name: 'New name')
```

**Comment by rrousselGit** [comment]
Another syntax could be to use Dart's callable classes to achieve:

```dart
Company company;

company = company.copyWith.director(name: 'New name')
```

Which is more readable IMO (and remove that ugly `$`).

It may even scale with property-specific copy:

```dart
company = company.copyWith.name('New name');
company = company.copyWith.director.name('New name');
```

**Comment by rrousselGit** [comment]
The benefits of the `company.$director.copyWith()` approach is that it is more flexible.

It allows:

```dart
company.$director(Person(...));
company.$director.copyWith(name: 'Name');
```

Whereas with `company.copyWith.director`, trying to achieve the same thing leads to weird names:

```dart
company.copyWith.director(Person(...))
company.copyWith.director.copyWith(name: 'Name')
```

**Comment by rrousselGit** [comment]
A third solution could be:

```dart
company.copy.director(Person(...))
company.copy.director.with(Person(...))
```

**Comment by SunlightBro** [comment]
Don't if this should be part of this issue or if I should create a new one:
```dart
@freezed
abstract class Company with _$Company {
  factory Company(String name, List<Person> ceos) = _Company;
}
```

Now say I wanna change the name of one Person in ceos.

```dart
Company company;

var ceos = company.ceos.toList();
ceos[1] = ceos[1].copyWith(name: 'NewName');

company = company.copyWith(ceos: updatedCeos);
```

This is not very intuitive.

**Comment by rrousselGit** [comment]
Yes, lists and maps are definitely in the scope of this feature. Maybe not in the first release though.

We can think of: 

```dart
@freezed
abstract class TodoList with _$TodoList {
  factory TodoList(List<Todo> todos) = _TodoList;
}
@freezed
abstract class Todo with _$Todo {
  factory Todo(String name, bool checked) = _Todo;
}
```


Which would allow:

```dart
TodoList list;

list = list.$todos[0].checked(true);
list = list.$todos.where(...).checked(true);
list = list.$todos([]);
```

**Comment by rrousselGit** [comment]
I probably won't work on collections in the first release of such feature.

In the meantime, we can use spread operator and if/for inside collections:


```dart
TodoList list;

list = list.copyWith([...list.todos, Todo()]);
list = list.copyWith([
  for (final todo in list.todos)
    todo.copyWith(checked: true),
]);
```

So it's not too bad.

**Comment by smiLLe** [comment]
What happens if director is nullable?

**Comment by rrousselGit** [comment]
@smiLLe nothing special.
What's your concern?

**Comment by smiLLe** [comment]
Let's say director is null in my company object.
And director may have a Person assistant.

what happens if i'd call company.$director.$assistant.copyWith(age: 22);

**Comment by rrousselGit** [comment]
`$director` would be nullable

So you'd have:

```dart
company.$director?.assistant.copyWith(age: 22);
```

**Comment by smiLLe** [comment]
@rrousselGit ok ... that was too obvious :) i need a coffee. right. now....

**Comment by rrousselGit** [comment]
No worries, that's a fair question! 😄

**Comment by rrousselGit** [comment]
Thinking about it, the previous issue of:

```dart
company.copyWith.director(Person(...))
company.copyWith.director.copyWith(name: 'Name')
```

This is actually not a problem.

We could instead have:

```dart
company.copyWith(director: Person(...))
company.copyWith.director(name: 'Name')
```

And this logic applies to deeper copies too:


```dart
company.copyWith.director(assistant: Assistant(...));
company.copyWith.director.assistant(age: 22);
```

**Comment by rrousselGit** [comment]
I think I'll go with that syntax, as `copyWith.director(name: 'Foo')` free-up the `$director` slot for something else

`$director` may be needed for #60
