### ISSUE TITLE
Lack of information about web support

### ISSUE THREAD

**Issue by erluxman** [rrousselGit/freezed#800]
Based on the nature of this project as it's a code generator, normally it would not be platform dependent. But still, I am concerned about why Web support is not mentioned in the pub.dev?

Or it does it not support web for some reason?

**Comment by SunlightBro** [comment]
Duplicate of [#799](https://github.com/rrousselGit/freezed/issues/799#issuecomment-1313950341). Can be closed.

**Comment by rrousselGit** [comment]
You already made an issue about it, and it was already answered
