### ISSUE TITLE
Use other non-freezed classes in @freezed classes

### ISSUE THREAD

**Issue by bambinoua** [rrousselGit/freezed#802]
Let's say I have and objects:

```dart
class Money extends ValueObject<Money> {
  ...
}
```

and 

```dart
@freezed
class Product extends DTO with _$Product {
  factory Product({
    @Assert('title.isNotEmpty') required String title,
    @Default(Money.zero) Money price,
  }) = _Product;

  factory Product.fromJson(JsonMap map) => _$ProductFromJson(map);
}
```
`build_runner` failed when I generate files - `freezed.dart` file does not know the `Money` class (I didn't notice the `import` of file with it in `product.freezed.dart`).

So question are: _Must I also mark `Money` as `@freezed` or is there any feature/workaround to do not do this?_ 

P.S. In any case `json_serializable` allows this so it is bug of `freezed` maybe?

**Comment by rrousselGit** [comment]
If you could share your error, that'd be great.

Does your Money class maybe not have a `fromJson`/toJson?

**Comment by rrousselGit** [comment]
I'll close this in the lack of an answer
