### ISSUE TITLE
"Depend on referenced packages" linter warning

### ISSUE THREAD

**Issue by Mikhail-Ivanou** [rrousselGit/freezed#806]
**Describe the bug**
import 'package:freezed_annotation/freezed_annotation.dart';
causes "Depend on referenced packages" linter warning

**To Reproduce**
I use https://pub.dev/packages/lint for linter rules and get "Depend on referenced packages" linter warning

**Expected behavior**
No linter warnings

**Comment by rrousselGit** [comment]
you need to add `freezed_annnotation` in your pubspec.yaml

**Comment by Mikhail-Ivanou** [comment]
Thanks!
Probably it worth to update description here too?
https://pub.dev/packages/freezed/install

**Comment by rrousselGit** [comment]
That's not something I have control over. It's generated by pub, not written by me.
