### ISSUE TITLE
Generic freezed generates an incorrect copyWith

### ISSUE THREAD

**Issue by shilangyu** [rrousselGit/freezed#807]
**Describe the bug**

When using a generic freezed object, the copywith implementation defaults fields to `null` which is incorrect since the type argument can be a nullable type which violates the feature of freezed: copyWith can set `null`s.

**To Reproduce**

I created a repo with the described bug and generated files: https://github.com/shilangyu/freezed-copywith-null

Here is a summary:

Given a freezed object

```dart
@freezed
class State<T> with _$State<T> {
  const factory State({
    required T value,
  }) = _State<T>;
}
```

The generated copyWith defaults to `null`

```dart
// ...
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? value = null,
  }) {
    return _then(_value.copyWith(
      value: null == value
          ? _value.value
          : value // ignore: cast_nullable_to_non_nullable
              as T,
    ) as $Val);
  }
// ...
```

Which breaks usages such as 

```dart
  test('copy null', () {
    const state = State<int?>(value: 123);

    // all good
    expect(state.value, 123);

    // ugh-oh, that should work, but it does not
    final copied = state.copyWith(value: null);
    expect(copied.value, null);
  });
```

**Expected behavior**

The above copyWith with a null value should work, as previous versions of freezed worked like that and no such breaking change was stated in the changelog. Luckily when upgrading freezed in our project tests caught this issue.

**Additional info**

The problem originates from this https://github.com/rrousselGit/freezed/pull/735 PR. I would argue, that the change with conditional `null` and `freezed` should be reverted. The speed gain is negligible and creates many edge cases, another example would be https://github.com/rrousselGit/freezed/issues/803 which IMO is not a low priority bug since it broke existing code. The PR uses some `e.isNullable` to decide whether to use `freezed` or `null`, my educated guess would be that this only handles types which are explicitly marked as nullable but not those that can have instances which are `null`.

**Comment by rrousselGit** [comment]
I'll see what can be done.

**Comment by shilangyu** [comment]
That was quick, thanks
