### ISSUE TITLE
Invalid `copyWith` overrides

### ISSUE THREAD

**Issue by jpnurmi** [rrousselGit/freezed#811]
**Describe the bug**

2.3.0 generates invalid `copyWith` overrides for unions with fields by the same name but different types where the first type is `dynamic`.

```
  error • lib/src/union.freezed.dart:263:8 • '_$$_UnionSecondCopyWith.call' ('$Res Function({int value})') isn't a valid override of '$UnionCopyWith.call' ('$Res Function({dynamic
          value})'). • invalid_override
           - The member being overridden at lib/src/union.freezed.dart:80:8.
  error • lib/src/union.freezed.dart:411:8 • '_$$_UnionThirdCopyWith.call' ('$Res Function({double value})') isn't a valid override of '$UnionCopyWith.call' ('$Res Function({dynamic
          value})'). • invalid_override
           - The member being overridden at lib/src/union.freezed.dart:80:8.
```

**To Reproduce**

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'union.freezed.dart';

@freezed
class Union with _$Union {
  factory Union.first({required dynamic value}) = _UnionFirst; // NOT OK
  factory Union.second({required int value}) = _UnionSecond; // OK
  factory Union.third({required double value}) = _UnionThird; // OK
  factory Union.fourth({required dynamic value}) = _UnionFourth; // OK
}
```
If you comment out `Union.first`, the rest are valid overrides.

**Comment by rrousselGit** [comment]
Interesting, I'll check.

In the meantime, you probably could use `Object?` instead of `dynamic`

**Comment by NarekManukyan** [comment]
Same problem for fields "name" and "id"

``` Dart
@freezed
class CompanyAbstractDto with _$CompanyAbstractDto {
  CompanyAbstractDto._();

  factory CompanyAbstractDto.response({
    required String id,
    required String name,
  }) = CompanyDto;

  factory CompanyAbstractDto.preview({
    String? id,
    String? name,
  }) = CompanyPreviewDto;

  factory CompanyAbstractDto.fromJson(Json json) =>
      _$CompanyAbstractDtoFromJson(json);
}
```

**Comment by jpnurmi** [comment]
I suppose the above case boils down to mixing any nullable vs. non-nullable types. 

```dart
@freezed
class Union with _$Union {
  factory Union.foo({int? arg}) = _UnionFoo;
  factory Union.bar({required int arg}) = _UnionBar;
}
```

`_$$_UnionBarCopyWith.call' ('$Res Function({int arg})` isn't a valid override of `$UnionCopyWith.call' ('$Res Function({int? arg})`

You can swap the constructors as a workaround, though:

```dart
@freezed
class Union with _$Union {
  factory Union.bar({required int arg}) = _UnionBar;
  factory Union.foo({int? arg}) = _UnionFoo;
}
```

`_$$_UnionFooCopyWith.call' ('$Res Function({int? arg})` is a valid override of `$UnionCopyWith.call' ('$Res Function({int arg})`

**Comment by NarekManukyan** [comment]
> 

Please check my comment, your answer doesn't work for me. In my case, the first constructor contains only required fields, while the second constructor contains similar fields that can be null and it doesn't compile.

**Comment by NarekManukyan** [comment]
> I suppose the above case boils down to mixing any nullable vs. non-nullable types.
> 
> ```dart
> @freezed
> class Union with _$Union {
>   factory Union.foo({int? arg}) = _UnionFoo;
>   factory Union.bar({required int arg}) = _UnionBar;
> }
> ```
> 
> Doesn't compile because `_$$_UnionBarCopyWith.call' ('$Res Function({int arg})` isn't a valid override of `$UnionCopyWith.call' ('$Res Function({int? arg})`
> 
> You can swap the constructors as a workaround, though:
> 
> ```dart
> @freezed
> class Union with _$Union {
>   factory Union.bar({required int arg}) = _UnionBar;
>   factory Union.foo({int? arg}) = _UnionFoo;
> }
> ```
> 
> This is ok because `_$$_UnionFooCopyWith.call' ('$Res Function({int? arg})` is a valid override of `$UnionCopyWith.call' ('$Res Function({int arg})`


Please check my comment, your answer doesn't work for me. In my case, the first constructor contains only required fields, while the second constructor contains similar fields that can be null and it doesn't compile.

**Comment by jpnurmi** [comment]
@NarekManukyan Strange, your example actually compiles for me. Only if I swap the constructors, it doesn't.

**Comment by NarekManukyan** [comment]
> @NarekManukyan Strange, your example actually compiles for me. Only if I swap the constructors, it doesn't.

Maybe, but in 2.2.1 Unions worked fine. You can have many "union" constructors that can mix non-null and null types. I think this issue is due to this change
`Union types now expose properties with the same name but different type on the shared interface. `

**Comment by rrousselGit** [comment]
Thanks a lot everyone for the nice examples. These have been massively helpful in fixing the issue!

**Comment by jpnurmi** [comment]
> ```dart
> @freezed
> class Union with _$Union {
>   factory Union.foo({int? arg}) = _UnionFoo;
>   factory Union.bar({required int arg}) = _UnionBar;
> }
> ```
> 
> Doesn't compile because `_$$_UnionBarCopyWith.call' ('$Res Function({int arg})` isn't a valid override of `$UnionCopyWith.call' ('$Res Function({int? arg})`

This variation is still broken with 2.3.1.
