### ISSUE TITLE
@pragma annotations

### ISSUE THREAD

**Issue by stevehayles** [rrousselGit/freezed#812]
**Is your feature request related to a problem? Please describe.**
Flutter 3.3.x appears to have created a number of problems around it's more aggressive tree-shaking and optimisations.  Lots of issues are being reported in previously working code that utilises Isolates as the message objects are getting pruned in any release builds. The easiest fix in most situations before libraries start using 'lightweight flutter isolates', is to indicate to the compiler that classes or methods should be retained in the final output using @pragma('vm:entry-point')

**Describe the solution you'd like**
I would like to see any 'input' class annotated with @pragma('vm:entry-point') have those annotations passed onto to the resulting freezed classes.  In most cases the class inheritance produced in the freezed class includes one abstract class (`abstract class _MyModel extends MyModel`) and then a concrete class (`class _$_MyModel extends MyModel`) that is annotated as `@JsonSerializable()`.  This second class is almost certainly the class that needs the pragma annotation added. 

**Describe alternatives you've considered**
Manually editing the file is not too hard and it's fairly easy to modify the `concrete_template.dart` but I don't know the codebase well enough and that feels brittle when it might be beneficial to have this fixed by someone that knows what they are doing...

**Additional context**
This link explains the general problem with Isolates in Flutter 3.3.x [link](https://github.com/flutter/flutter/issues/109248)

**Comment by rrousselGit** [comment]
Isn't that already how it works? Annotations are passed around.

**Comment by stevehayles** [comment]
Thanks for the prompt response, I will check carefully what I might be doing wrong but  I'm not seeing it work as described.  I think constructor / factory parameters that are annotated get passed around but annotating the class itself appears to have no effect on the generated freezed classes.

**Comment by rrousselGit** [comment]
Annotating the constructor should be what you want

**Comment by stevehayles** [comment]
@rrousselGit You are totally right!   I had a number of code generators running, I am not totally sure why but adjusting the order that they ran fixed the problem.  Really sorry to have bothered you, closing the issue... Thanks for an awesome library!
