### ISSUE TITLE
freezed field require manual renaming

### ISSUE THREAD

**Issue by SuTechs** [rrousselGit/freezed#813]
Consider the below UserData class. After a while, if I want to rename the filed `id` to `userId`.  Running build runner again will generate the files again with the changes, but we'll have to manually rename all the old `id` to the new `userId`,. It would be great if `freezed` field could support IDE refactoring.

```
@freezed
class UserData with _$UserData {
  const factory UserData({
    required String id, // rename it to userId
    required String phone,
    @Default("") String name,
    @Default("") String imageUrl,
  }) = _USerData;

  factory UserData.fromJson(Map<String, dynamic> json) =>
      _$UserDataFromJson(json);
}
```

**Describe the solution you'd like**
If possible, renaming the field using the IDE refactor option should rename the field automatically.
Or else a possible feature would be a new `@renameField('userId')` annotation, after which generating classes again should automatically rename the field everywhere.

**Describe alternatives you've considered**
For now, I'm using `@JsonKey()` annotation to only rename the toJson and fromJson keys, because the key changed in the API, but I wanted to change the UserData id field too, which requires little manual editing.

**Comment by rrousselGit** [comment]
That's not something I have control over. 
I doubt anything can be done.

**Comment by SuTechs** [comment]
Yea, I thought so. Let's hope the flutter team soon introduces data class.
