### ISSUE TITLE
Invalid copyWith override for nested models with direct types

### ISSUE THREAD

**Issue by fryette** [rrousselGit/freezed#820]
With latest version(2.3.2) I have same issue with incorrect overriding copyWith

Example:

```
@freezed
class Item with _$Item {
  const factory Item.one({required SettingsOne settings}) = ItemOne;
  const factory Item.two({required SettingsTwo settings}) = ItemTwo;
}

@freezed
class Settings with _$Settings {
  const factory Settings.one() = SettingsOne;
  const factory Settings.two() = SettingsTwo;
}
```

After generation next error appeared:

`_$$ItemOneCopyWith.call' ('$Res Function({SettingsOne settings})') isn't a valid override of '$ItemCopyWith.call' ('$Res Function({dynamic settings})').dart[invalid_override](https://dart.dev/diagnostics/invalid_override)`

for the next peace of code:

```
/// @nodoc
abstract class _$$ItemOneCopyWith<$Res> implements $ItemCopyWith<$Res> {
  factory _$$ItemOneCopyWith(_$ItemOne value, $Res Function(_$ItemOne) then) =
      __$$ItemOneCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({SettingsOne settings});
}
```

**Comment by fryette** [comment]
Also, I would like to highlight, that if dynamic will be used so much, for big projects it may be a problem.
https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html

**Comment by fryette** [comment]
@rrousselGit is it possible to disable union types then?
For large projects keeping related classes in the same file definitely a good approach(flutter heavily use it).
If let's say we have json based file with 10-15 classes you have to create 10-15 files which is from my point of view wrong strategy and instead of saving time, it takes more.
Also, I cannot find any warnings in the console output(or maybe missed).

For the current project now I have to create 200-300 additional files, and it looks crazy a bit.

**Comment by fryette** [comment]
That is not a problem. The main problem is when you have a lot of classes like that-> a few dozen files will be added. For my project(50+). And now it's less comfortable to write/design classes when you have such cases. 
Before it was easy to write related classes in the same file as the flutter team does. 

I will close the issue for now.

Thanks!

**Comment by rrousselGit** [comment]
I understand. But to begin with, you were relying on something that isn't officially supported.

This use-case should be pretty rare. You shouldn't have to create one file per class. Only those where you rely on generated types.

**Comment by esenmx** [comment]
> As explained in the previous copyWith issues, this one is expected.
> 
> Relying on the output of a code-generator class as input of Freezed class within the same file is not supported.
> 
> So either don't rely on `SettingsOne`/`SettingsTwo` or split those Settings and Item in two different libraries (different Dart files, and they must not be of the same "part")

This one was not an issue until latest releases and I'm stuck on `2.2.1`. I can't upgrade since then, because some union classes relied on other classes' union types. Honestly, I prefer this way because of the type safety and less verbosity of code. Can't even imagine to having to use type cast or `map/maybeMap` each time I try to use union type.
