### ISSUE TITLE
Code generation works but running the app fails

### ISSUE THREAD

**Issue by KhnifesKyrillus** [rrousselGit/freezed#823]
**Describe the bug**
I created a class with Freezed and the code generation succeeds, but when I try to run the app it fails.

**To Reproduce**
This is my class:
```
import 'package:freezed_annotation/freezed_annotation.dart';

import 'process_id.dart';

part 'process.freezed.dart';
part 'process.g.dart';

@freezed
class Process with _$Process {
  const factory Process({
    required final ProcessId id,
    required final String name,
    required final bool isArchived,
    required final bool isLocked,
    required final DateTime createdAt,
  }) = _Process;

  factory Process.fromJson(Map<String, Object?> json) =>
      _$ProcessFromJson(json);
}
```
This is the output I get when I try running the app:
```
: Error: Using 'lib/data/Processes/process.freezed.dart' as part of 'package:app/data/Processes/Process.dart' but its 'part of' declaration says 'package:app/data/Processes/process.dart'.
part 'process.freezed.dart';
     ^
: Error: Using 'lib/data/Processes/process.g.dart' as part of 'package:app/data/Processes/Process.dart' but its 'part of' declaration says 'package:app/data/Processes/process.dart'.

part 'process.g.dart';
     ^
: Error: Type '_$Process' not found.
class Process with _$Process {
                   ^^^^^^^^^
: Error: The type '_$Process' can't be mixed in.
class Process with _$Process {
      ^
: Error: Couldn't find constructor '_Process'.
  }) = _Process;
       ^
: Error: Redirection constructor target not found: '_Process'
  }) = _Process;
       ^
: Error: Method not found: '_$ProcessFromJson'.
      _$ProcessFromJson(json);
      ^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

```

**Expected behavior**
It should compile without any issues

**Comment by rrousselGit** [comment]
It sounds like you named your file `Process.dart` instead of `process.dart`

**Comment by KhnifesKyrillus** [comment]
The file name is process.dart
<img width="147" alt="image" src="https://user-images.githubusercontent.com/43353117/207039356-2632e8df-7473-410b-b664-8c1610d62e2e.png">

**Comment by rrousselGit** [comment]
Try deleting the .dart_tool folder and restarting

In any case, it's very unlikely to be a Freezed issue. At best it's a build_runner issue. Especially considering json_serialiable seems to be facing the same problem (the .g.dart)

**Comment by KhnifesKyrillus** [comment]
> Try deleting the .dart_tool folder and restarting
> 
> In any case, it's very unlikely to be a Freezed issue. At best it's a build_runner issue. Especially considering json_serialiable seems to be facing the same problem (the .g.dart)

Deleting the generated files like 10 times worked for me. Thanks
