### ISSUE TITLE
treat string as a custom (uuid) object

### ISSUE THREAD

**Issue by antony-amdl** [rrousselGit/freezed#824]
### Discussed in https://github.com/rrousselGit/freezed/discussions/805

<div type='discussions-op-text'>

<sup>Originally posted by **antony-amdl** November 26, 2022</sup>
I have
```dart
import 'package:uuid/uuid.dart' as uuid_lib;

const uuidGen = uuid_lib.Uuid();

class Uuid {
  final String _val;
  Uuid._private(this._val);

  factory Uuid() => Uuid._private(uuidGen.v4());

  factory Uuid.fromJson(String json) => Uuid._private(json);

  String toJson() => _val;
}
```
This is very similar to `sample2` in https://pub.dev/packages/json_serializable#custom-types-and-custom-encoding  
I try to use it in
```dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

import '../util/uuid.dart';

part 'organization.freezed.dart';
part 'organization.g.dart';

@freezed
class Organization with _$Organization {
  const factory Organization({
    required Uuid pkid,
    required String name,
  }) = _Organization;

  factory Organization.fromJson(Map<String, dynamic> json) =>
      _$OrganizationFromJson(json);
}
```
The idea is to send and receive uuid fields as just string, but treat it as an opaque object throughout the flutter code.
But this does not work since the generated code for the container class `Organization`  does not call the `toJson` method on the `Uuid` type field.
(If I find a way to do this, I plan to apply similar methods on iso-8601 timestamps, email, phone etc)
Please help.</div>

**Comment by antony-amdl** [comment]
I am not particular about how this should be done - my requirement is to be able to send and receive a simple string for the UUID as json while having a proper object encapsulating that value within my flutter app code.

**Comment by rrousselGit** [comment]
Why make an issue if you've already made a discussion about it?

**Comment by antony-amdl** [comment]
I thought no one is looking at the discussion since there were no responses. I can delete whichever makes sense.

**Comment by rrousselGit** [comment]
Issues are for bug/feature requests, not help requests.

Discussions are the correct place. StackOverflow works too. Or Riverpod's discord (which also answers to Freezed questions)
