### ISSUE TITLE
ThemeExtension generator

### ISSUE THREAD

**Issue by socramm9** [rrousselGit/freezed#825]
Disclaimer: I don't know how code generation works in Flutter and if it is even possible to archive what I want. My feature request could also be a litte of topic for the `freezed` package and maybe requires its own package...

**Is your feature request related to a problem? Please describe.**
Flutter introduced `ThemeExtensions` with v3. At the moment a lot of boilerplate code is need to create such extension class.
More info: https://medium.com/geekculture/flutter-3-how-to-extend-themedata-56b8923bf1aa

```
class ThemeColor extends ThemeExtension<ThemeColor> {
  const ThemeColor({
    this.color,
  });

  final Color? color;

  factory ThemeColor.icon({Color? color}) => ThemeColor(
        color: color,
      );

  @override
  ThemeExtension<ThemeColor> copyWith({Color? color}) => ThemeColor(
        color: color ?? this.color,
      );

  @override
  ThemeExtension<ThemeColor> lerp(
    ThemeExtension<ThemeColor>? other,
    double t,
  ) {
    if (other is! ThemeColor) {
      return this;
    }

    return ThemeColor(
      color: Color.lerp(color, other.color, t),
    );
  }
}
```

**Describe the solution you'd like**
It would be nice to be able to let build_runner generate all functions needed for `ThemeExtension`. The Generation should be similar to how properties are defined in `freezed`

```
@themeExtension
class ThemeColor with _$ThemeColor {
  factory ThemeColor({
    required Color color,
  }) = _ThemeColor;
}
```

**Describe alternatives you've considered**
I couldn't find any package that has this functionality.

**Comment by rrousselGit** [comment]
This isn't in the scope of Freezed.   
Freezed isn't even related to Flutter

If you want such a thing, I'd suggest making a separate package.

**Comment by TesteurManiak** [comment]
@socramm9 check [theme_tailor](https://pub.dev/packages/theme_tailor) it's exactly what you are looking for.
