### ISSUE TITLE
Is there a way to make base freezed class and extend it ?

### ISSUE THREAD

**Issue by mjd-dalloul** [rrousselGit/freezed#827]
Is there a way to make base freezed class and extend it

```
@freezed
class BaseEvent  with _$BaseEvent {
  const factory BaseEvent.testEvent() = TestEvent;
}
```

```

@freezed
class Test extends BaseEvent  with _$Test {
  const factory Test.testEvent() = TestEvent;
  //this factory will be included since Test class extends BaseEvent
  //const factory BaseEvent.testEvent() = TestEvent;
}
```

**Comment by rrousselGit** [comment]
No. Inheritance doesn't work well with the current Freezed syntax. It's a known issue. There are some issues related to this already

Metaprogramming might help whenever it comes out though.

For now, either make your base class a "normal" class. Or use composition instead of inheritance
