### ISSUE TITLE
fields contains `$` failed!

### ISSUE THREAD

**Issue by medz** [rrousselGit/freezed#833]
**Describe the bug**
Including `$` strings in classes fields will cause dart run build_runner to fail.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/5564821/210706078-a9b6a7bf-efa6-4a27-9fe7-d9d197b7d217.png">

**Comment by medz** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/5564821/210706128-51e67eb5-6d12-431b-a175-890cd972cfe4.png">

**Comment by SunlightBro** [comment]
this is not a freezed issue.
You either need to escape the $ character `'\$'`
or use a raw String `r'$'`

**Comment by medz** [comment]
> Fancy fixing it?

I need to try it when I have some free time.

> I hate the Dart Build System, but I have to use it now.

**Comment by medz** [comment]
@rrousselGit The PR fixed:

- #835
