### ISSUE TITLE
Lists toString readability 

### ISSUE THREAD

**Issue by z-dmitri** [rrousselGit/freezed#84]
Big lists make logs and toString unusable
It could be nice to have option or attribute or default to shorten toString

Maybe in this way: `List [0, ..., N]`
Or in this way: `List [COUNT]`

**Comment by z-dmitri** [comment]
+ #62 Custom toString methods for Unions - has no any solution yet, what about reopen issue?

**Comment by rrousselGit** [comment]
What you're looking for is a visualizer instead.
It's in the scope of https://github.com/flutter/devtools, your IDE, or your log tool to make the object nicely readable.

That's one of the reasons Freezed implements Diagnosticable if possible. To make your object compatible with Flutter's devtool.

**Comment by z-dmitri** [comment]
logging is not about IDE only - it could be ELK, Firebase and many other cases

**Comment by rrousselGit** [comment]
Which themselves have their own visualizers.

Your objects are serializable in theory. You could log the json, which most modern visualizers supports natively.

**Comment by z-dmitri** [comment]
Then we will not be able to use simple logging `BlocSupervisor.delegate = AppBlocDelegate();`

**Comment by rrousselGit** [comment]
Why?

**Comment by z-dmitri** [comment]
For example, some toString() composing are in the BLoC inner classes
```dart
class Transition<Event, State> {
  String toString() => 'Transition { currentState: $currentState, event: $event, nextState: $nextState }';
}
```
so when we using `BlocSupervisor.delegate` to log Transition toString() we will have big lists toString() in place

**Comment by rrousselGit** [comment]
And what is preventing you from making `Transition` serializable too?

**Comment by z-dmitri** [comment]
`Transition` - is inner class of BLoC library - and it is just one of possible cases

**Comment by rrousselGit** [comment]
Then you could use #83 to override the default toString to do a json serialization I suppose

**Comment by z-dmitri** [comment]
`Transition ` is NOT my class to override - it is part of the BLoC library

**Comment by z-dmitri** [comment]
ah, you mean override my State/Event classes, it is clear, thanks a lot

**Comment by rrousselGit** [comment]
Since we have #83, I'll close this
