### ISSUE TITLE
Using union type along with typedef leads to an error

### ISSUE THREAD

**Issue by ValeriusGC** [rrousselGit/freezed#840]
Hi!
When doing something like this
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'union_class.freezed.dart';

@freezed
class UnionClass with _$UnionClass {
  const factory UnionClass.first() = FirstUnionClass;
  const factory UnionClass.second() = SecondUnionClass;
}
```

and then something like
```dart
@freezed
class Client with _$Client {
  const factory Client({
    required UnionMap union,
  }) = _Client;
}

typedef UnionMap = Map<String, FirstUnionClass>;
```

we get lossing of type
![image](https://user-images.githubusercontent.com/3320861/212254810-5d19b1c0-a353-498f-8c98-d942aac9ecb4.png)

**Comment by rrousselGit** [comment]
Relying on the ouput of a Freezed class as input of another Freezed class is not supported.
As such, avoid doing `Map<String, FirstUnionClass>`

One workaround is to have both classes in separate files. Alternatively wait for static metaprogramming.

I'm not going to work on this before metaprogramming.

**Comment by ValeriusGC** [comment]
Ok, well, no problem.
But, ehhh, when i remove typedef
```dart
    // required UnionMap union,
    required Map<String, FirstUnionClass> union,
```
it works well and types are been recognizing without problem.
So maybe problem lies not in "_Relying on the ouput of a Freezed class as input of another Freezed class is not supported._" 
but in another place? Maybe  in typedefs?

**Comment by rrousselGit** [comment]
No it's definitely relying on generated code the problem

It's behavior is unspecified, and it can sometimes randomly work because of build_runner shenanigans. But that's random.
