### ISSUE TITLE
json_serializable upgrade

### ISSUE THREAD

**Issue by feduke-nukem** [rrousselGit/freezed#844]
json_serializable have been updated to 6.6.0 recently with some improvements of JsonKey annotation

Is it possible to upgrade dependencies?

Related [pull-request ](https://github.com/google/json_serializable.dart/pull/1256)

**Comment by SunlightBro** [comment]
It's not a major-version upgrade, so it might simply already work.
You can run the tests in this repo or watch the next [build](https://github.com/rrousselGit/freezed/actions/workflows/build.yml).

**Comment by SunlightBro** [comment]
@feduke-nukem FYI I've run
`dart pub upgrade && dart test` in `/freezed`
```sh
Building package executable... (2.5s)
Built test:test.
00:07 +304 ~1: All tests passed! 
```
also `dart pub outdated` shows
```sh
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name        Current              Upgradable           Resolvable           Latest  

direct dependencies:
freezed_annotation  *2.2.0 (overridden)  *2.2.0 (overridden)  *2.2.0 (overridden)  2.2.0   

dev_dependencies:  
build_runner        *2.3.3               *2.3.3               *2.3.3               2.4.0   
You are already using the newest resolvable versions listed in the 'Resolvable' column.
Newer versions, listed in 'Latest', may not be mutually compatible.
```
