### ISSUE TITLE
Support `FreezedCopyWithOption(nullSupport: false))`

### ISSUE THREAD

**Issue by ataberkw** [rrousselGit/freezed#846]
I see freezed supports null in copyWith. When you send null as copyWith property, it makes the property null. That's a feature. But in some of my objects, I don't want this behavior. I want that property to not change if I pass null. I don't want to write `if null` boilerplate in my copyWith logic to accomplish it. 
 
This is how I'm forced to use copyWith functions.

    updateLocalAutomationData({
      int? requestedAirTemp,
      int? requestedAirTempTolerance,
      int? requestedCo2,
    }) {
      emit(state.copyWith(
        requestedAirTemp: requestedAirTemp ?? state.requestedAirTemp,
        requestedAirTempTolerance: requestedAirTempTolerance ?? state.requestedAirTempTolerance,
        requestedCo2: requestedCo2 ?? state.requestedCo2,
      ));
    }

I don't want to use ?? operators in every conditional copyWith. I want freezed to have such option like 
`@Freezed(copyWithOption: FreezedCopyWithOption(nullSupport: false))` so that freezed generate if null operators in low level.

**Comment by rrousselGit** [comment]
I have no plans to implement this, so closing
