### ISSUE TITLE
Allow toString() to generate dart code 

### ISSUE THREAD

**Issue by ciprig** [rrousselGit/freezed#852]
When using large objects for expected results in tests be great if I can copy and paste the printout of toString() to create the expected results. However, the current toString() printout doesn't compile as dart code.

Have an extra parameter to Freezed annotation that will make toString() generate dart code 

We could use a custom encoder for toJson but I don't use/need toJson in all data classes
Overriding toString will require a lot of boilerplate code to write and maintain as the classes have lots of fields
Reflection is not available in flutter not even for dev dependencies  
Reflectable will generate a lot of code that I only need it for tests

**Comment by rrousselGit** [comment]
That's low priority for me. I probably won't work on this.

**Comment by ciprig** [comment]
@rrousselGit I could work on this

**Comment by rrousselGit** [comment]
I'm not fond of the idea. To begin with, it's a bit unreliable; and it's not how most toString behave anyway. It would also be breaking

**Comment by rrousselGit** [comment]
I have no plan to implement this as it's too unreliable anyway. I'd suggest making your own toString implementation in such cases
