### ISSUE TITLE
Dart/Flutter lint fail: variable isn't a lowerCamelCase style

### ISSUE THREAD

**Issue by ratsey** [rrousselGit/freezed#856]
When using Freezed with Flutter, generated code produces variable names that trigger lint rules.

**To Reproduce**

I have a class called Categories that is marked as freezed.  When generating the code, it generates a FromJson function as:

```
_$_Categories _$$_CategoriesFromJson(Map<String, dynamic> json) =>
    _$_Categories(
```

The latest Flutter lint rules are tagging that with 

```
The variable name '_$$_CategoriesFromJson' isn't a lowerCamelCase identifier.
Try changing the name to follow the lowerCamelCase style.
```

**Expected behavior**
Variables should follow lowerCamelCase style

**Comment by rrousselGit** [comment]
Ah yeah, it's been around for a while.

There's likely an issue about it already (although possibly closed)

I don't really care about this too much. Fancy fixing it? It should be straightforward

**Comment by ratsey** [comment]
@rrousselGit I figured I couldn't have been the first!

It's really going to apply to any generated code, so I found that just excluding it from the linter is likely the easiest solution!

analysis_options.yaml
```
analyzer:
  exclude:
    - *.g.dart
```

**Comment by Sp4Rx** [comment]
for ` - *.g.dart` if you are getting this error `Can't resolve alias .g.dart` use the following.

```
analyzer:
  exclude:
    - lib/**/*.g.dart 
```

Source: [analysis-options#excluding-files](https://dart.dev/guides/language/analysis-options#excluding-files)

> flutter version: 3.7.12
> flutter_lints: ^2.0.0
> lints: ^2.0.1
