### ISSUE TITLE
Nested Freezed class not converted TO JSON

### ISSUE THREAD

**Issue by ResoDev** [rrousselGit/freezed#86]
👋
Given two freezed classes where one is "nested" in the other.
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'contrived_example.g.dart';
part 'contrived_example.freezed.dart';

@freezed
abstract class TopLevel with _$TopLevel {
  const factory TopLevel(
    String niceString,
    Nested doesNotSerializeButDoesDeserialize,
  ) = _TopLevel;
  factory TopLevel.fromJson(Map<String, dynamic> json) =>
      _$TopLevelFromJson(json);
}

@freezed
abstract class Nested with _$Nested {
  const factory Nested(int niceInteger) = _Nested;
  factory Nested.fromJson(Map<String, dynamic> json) => _$NestedFromJson(json);
}
```

The generated code for json_serializable doesn't **serialize** the nested object. **DE**serialization works as expected.

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'contrived_example.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TopLevel _$_$_TopLevelFromJson(Map<String, dynamic> json) {
  return _$_TopLevel(
    json['niceString'] as String,
    json['doesNotSerializeButDoesDeserialize'] == null
        ? null
        : Nested.fromJson(
            json['doesNotSerializeButDoesDeserialize'] as Map<String, dynamic>),
  );
}

Map<String, dynamic> _$_$_TopLevelToJson(_$_TopLevel instance) =>
    <String, dynamic>{
      'niceString': instance.niceString,
      // 👇 should have toJson() or map((element) => element.toJson()) for Lists
      'doesNotSerializeButDoesDeserialize':
          instance.doesNotSerializeButDoesDeserialize,
    };

_$_Nested _$_$_NestedFromJson(Map<String, dynamic> json) {
  return _$_Nested(
    json['niceInteger'] as int,
  );
}

Map<String, dynamic> _$_$_NestedToJson(_$_Nested instance) => <String, dynamic>{
      'niceInteger': instance.niceInteger,
    };
```

At first, I thought that it's an issue with json_serializable but if that library is used by itself, it serializes nested objects marked with `@JsonSerializable` just fine.

**Comment by rrousselGit** [comment]
I have a very deeply nested object and it works fine for me.

The generated code you gave is generated by `json_serializable`, so I have no control over it.
Is `freezed` correctly adding `@JsonSerializable` annotation on `Nested`?
If it does, then it's unlikely to be a bug with `freezed`

**Comment by ResoDev** [comment]
The `_$_Nested` is annotated.
```dart
@JsonSerializable()
class _$_Nested implements _Nested {...}
```

**Comment by rrousselGit** [comment]
Then it may be an issue with build_runner.

Try regenerating the sources (potentially deleting `.dart_tool`) and see if it works.

In any case, freezed does nothing besides adding this annotation. So if it's there, then I can't do anything 🙃

**Comment by ResoDev** [comment]
Whoops! Sorry to break it to you, Rémi, but the bug is _probably_ on your side 😅

I replicated the non-serializing behavior with regular classes too. All it took for the nested class to serialize was `@JsonSerializable(explicitToJson: true)` on the top-level class.

**Comment by rrousselGit** [comment]
I mean it depends on what encoder you use.

The documentation of `explicitToJson` explicitly says that it's not needed using `dart:convert`.

If you need it, it's your job to add it or your encoder's job

**Comment by ResoDev** [comment]
OK, pardon me 🤦‍♂️ I'll leave the `build.yaml` set up here for any time travelers from the future.
```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
```
Thank you!

**Comment by david-legend** [comment]
thanks, resoDev and Remi, I am from the future and this conversation helped me

**Comment by theweiweiway** [comment]
Works great!  

But I was wondering if we can set ``explicitToJson`` to ``true`` for specific fields, and ``false`` for other fields. 

I tried annotating each field but that didn't seem to work

**Comment by rrousselGit** [comment]
I don't think you can, no

**Comment by theweiweiway** [comment]
Thanks for the quick response. I was able to fix this by setting ``explicitToJson`` to true, and using ``@JsonKey(toJson: CategoryEnum.serializeToList)`` to define a custom toJson function for my enum class

``
@freezed
abstract class CategoryEnum implements _$CategoryEnum {
  const CategoryEnum._();
  const factory CategoryEnum(String label) = _CategoryEnum;
  static const category1 = CategoryEnum("1");
  static const category2 = CategoryEnum("2");

  factory CategoryEnum.fromJson(String val) {
    return CategoryEnum(val);
  }

  static List<String> serializeToList(List<CategoryEnum> e) {
    return e.map((a) => a.toString()).toList();
  }

  @override
  String toString() => this.label;
}
``

**Comment by mathiasgodwin** [comment]
Hey guys, I think [QuickType](https://app.quicktype.io/) is worth giving consideration. I thus use Freezed and work with many languages, It converts JSON like magic.

**Comment by neiljaywarner** [comment]
@mathiasgodwin  i love the idea of quicktype a LOT but it doesn't add the explicityTOJson and it doesn't handle underscores

**Comment by neiljaywarner** [comment]
a-ha, the build also handles snake field renaming. good call then @mathiasgodwin

**Comment by pishguy** [comment]
Hi, where is `build.yaml` to change `explicit_to_json` value?

**Comment by golane-august** [comment]
@pishguy You have to create it on root folder (where `pubspec.yaml` is), if it's not present yet.

**Comment by stact** [comment]
Without build.yaml we can specify like this:

```dart
@freezed
class TopLevel with _$TopLevel {
  // Here 👇 the magic 
  JsonSerializable(explicitToJson: true)
  TopLevel._();

  const factory TopLevel(
    String niceString,
    Nested doesNotSerializeButDoesDeserialize,
  ) = _TopLevel;
  factory TopLevel.fromJson(Map<String, dynamic> json) =>
      _$TopLevelFromJson(json);
}
```

**Comment by stact** [comment]
Without build.yaml we can specify like this:

```dart
@freezed
class TopLevel with _$TopLevel {
  
  TopLevel._();
  // Here 👇 the magic 
  JsonSerializable(explicitToJson: true)
  const factory TopLevel(
    String niceString,
    Nested doesNotSerializeButDoesDeserialize,
  ) = _TopLevel;
  factory TopLevel.fromJson(Map<String, dynamic> json) =>
      _$TopLevelFromJson(json);
}

@freezed
class Nested with _$Nested {
  Nested._();

  const factory Nested(int niceInteger) = _Nested;
  factory Nested.fromJson(Map<String, dynamic> json) => _$NestedFromJson(json);
}
```

**Comment by rrousselGit** [comment]
Well I agree. But the problem isn't Freezed, it's json_serializable.

Anyway, yo enable explicit_to_json, create a `build.yaml` file next to your `pubspec.yaml` which contains:

```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
```

**Comment by mrRedSun** [comment]
It works, just doesn't feel right 😆 
Gonna look into json_serializable if they have the ticket already

**Comment by ormoyal** [comment]
after trying most of the solutions here and non of them worked for me, I found my own solution.
since I'm using [Drift](https://pub.dev/packages/drift) as a local database and I'm implementing their class I needed to add the `@JsonSerializable(explicitToJson: true)` between the 2 constructors and on top of the Factory one.
like this: 

```dart
@freezed
class ChargingProfile with _$ChargingProfile implements Insertable<ChargingProfile> {
  const ChargingProfile._();
  @Implements<Insertable<ChargingProfile>>()
  // Here 👇🏼 is the important line 
  @JsonSerializable(explicitToJson: true)
  const factory ChargingProfile({
    final int? profileId,
    final String? name,
    final int? stackLevel,
    final int? operatorId,
    final DateTime? validFromDate,
    final DateTime? validToDate,
    @Default(ProfilePurposeEnum.TxDefaultProfile) final ProfilePurposeEnum profilePurpose,
    final ProfileKindEnum? profileKind,
    final RecurrencyKindEnum? recurrencyKind,
    final ChargingSchedule? chargingSchedule,
  }) = _Profile;

  factory ChargingProfile.fromJson(Map<String, dynamic> json) => _$ChargingProfileFromJson(json);

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    return ChargingProfilesCompanion(
      profileId: Value(profileId),
      name: Value(name),
      stackLevel: Value(stackLevel),
      operatorId: Value(operatorId),
      validFromDate: Value(validFromDate),
      validToDate: Value(validToDate),
      profilePurpose: Value(profilePurpose),
      profileKind: Value(profileKind),
      recurrencyKind: Value(recurrencyKind),
      chargingSchedule: Value(chargingSchedule),
    ).toColumns(nullToAbsent);
  }
}
```
