### ISSUE TITLE
Is it possible to use `extend`ing from base class?

### ISSUE THREAD

**Issue by bambinoua** [rrousselGit/freezed#860]
Let's say I have a common properties which are used for other classes which I want to generate using `freezed`?
```dart
abstract class BaseState {
  const BaseState({this.status = 0});
  final int status;

  bool get isStatusOne => status == 1;
  bool get isStatusTwo => status == 2;
}
```
Is it possble to use `BaseClass` for `freezed` class declaration? I.e. I want this:
```dart
class MyState extends BaseState with $_MyState {
  const MyState._();
  const factory MyState({
    // ??
  }) = _MyState;
}
```

**Comment by rrousselGit** [comment]
You can extend it. You cannot pass parameters to its constructor.

**Comment by bambinoua** [comment]
So how can I set `status` to change state for example?
```dart
final newState = state.copyWith(status: 1) // Is this working?
```

**Comment by rrousselGit** [comment]
No, because this isn't defined by your Freezed class but the base class

**Comment by bambinoua** [comment]
@rrousselGit what about this one?
```dart
final newState = state.copyWith()..status = 1;
```
So I can inherit only classes with no final properties or use mixins, right?
