### ISSUE TITLE
Make `default` callback optional named parameter like other callbacks in `maybe[When/Map]`

### ISSUE THREAD

**Issue by anqit** [rrousselGit/freezed#863]
**Is your feature request related to a problem? Please describe.**
When I want to do partial pattern matching using `maybe[When/Map]` and I want the default instance to use the `orElse` case, I must still pass `null` as the default callback, whereas the other cases do not require a callback to be passed. Pardon my ignorance if this is necessary, but to me it seems like it is not. I guess the only reason I can think of why it is setup this way is because potentially a named parameter name could clash with a factory method, and it is not currently possible to combine optional positional and optional named parameters?

**Describe the solution you'd like**
Make the `default` callback optional, so that instead of having to do this:

```dart
myInstance.maybeMap(
    null,
    // ... other cases,
    orElse: () { /*...stuff*/ }
)
```
I can omit the default parameter:
```dart
myInstance.maybeMap(
    // ... other cases,
    orElse: () { /*...stuff*/ }
)
```

**Comment by rrousselGit** [comment]
This is a breaking change and pattern matching is coming later this year.
I'd suggest waiting for that and use pattern matching instead of map/when

**Comment by anqit** [comment]
Alright, makes sense. I'm curious if you have any insight as to why this was designed this way to begin with?

**Comment by rrousselGit** [comment]
There's no name associated with "default".

**Comment by anqit** [comment]
perhaps the name of the class could be used, as that is essentially the name of the factory

**Comment by rrousselGit** [comment]
Possibly. But I still don't plan on making a breaking change at this point.

Unless there is a high demand for this, I won't be implementing it.

**Comment by rrousselGit** [comment]
Now that pattern matching is here, I don't think there's a reason to implement this.

Rather than using map/when, you should use Dart's official pattern matching solution.
