### ISSUE TITLE
Make freezed types recognizable

### ISSUE THREAD

**Issue by JCKodel** [rrousselGit/freezed#865]
**Is your feature request related to a problem? Please describe.**

I'm building a package that requires value equatable objects to work well, but the user can really provide any type (as `Event<T extends Object>`). This `Event` can have an instance of `T`. `Event` is value equatable, but it will fail when `T` is not.

**Describe the solution you'd like**

I would like the freezed generator to include a `implements IEquatable`. This `IEquatable` is a simple interface:

```dart
@immutable
abstract class IEquatable {
  bool equals(IEquatable other);
}
```

The generated code would be:

```dart
bool equals(ThisClass other) {
  return this == other;
}
```

Since `ThisClass` is freezed, I know `this == other` will work.

This way, I can throw an exception whenever my package user tries to use my `Event` with something that is not value equatable (or, better yet, just write `Event<T implements IEquatable>`)

**Describe alternatives you've considered**

I could create this interface myself and force my users to implement that, but there is no way to ensure that `class Something implements IEquatable` is really value equatable, unless there is a `bool equals(IEquatable other)` method (either being generated by freezed or implemented by the user).

**Comment by rrousselGit** [comment]
I don't quite understand what this is about. What do you expect Freezed to do exactly?

Note that you could make a mixin for a default `equals` implementation:

```dart
mixin IEquatableMixin implements IEquatable {
  bool equals(IEquatable other) => this == other;
}
```

and use that in your freezed classes

```dart
@freezed
class Example with _$Example, IEqualtableMixin {
  Example._();
  factory Example(int a) = _Example;
} 
```

**Comment by JCKodel** [comment]
> and use that in your freezed classes
>
The problem is: they are not MY freezed class.

I'm doing a Flutter package that requires user objects with value equality (what freezed does), but there is no way to enforce that because there is no way to recognize classes that overrides `==` and `hash`.

Since freezes is (well deserved) the most common package to build value equality objects, it would be easy saying to my users: "hey, use my package, but it requires you to write your classes with freezed, ok?"

**Comment by rrousselGit** [comment]
Expose a mixin and ask your users to use that mixin then.

```dart
@freezed
class SomeClass with _$SomeClass, YourMixin {
  SomeClass._();
  factory SomeClass() = _SomeClass;
}

...

mixin YourMixin implements IEquatable {
  @override
  bool equals(ThisClass other) {
    return this == other;
  }
}
```



I have no plan to expose an interface unique to Freezed objects.  
To begin with, users could disable the == generation in Freezed objects anyway.
