### ISSUE TITLE
[question] Is it possible to implement conditional initialization of final property with `freezed` package?

### ISSUE THREAD

**Issue by bambinoua** [rrousselGit/freezed#868]
Is it possible to implement this kind of initialization `data` property using `freezed` package?
```dart
class Image {
  Image(Uint8List? data) : data = data ?? Uint8List(0);

  final Uint8List data;
}
```

**Comment by SunlightBro** [comment]
You can try using `@Default()` annotation, but its value must be `const`.
But Uint8List doesn't have a const constructor, if I remember correctly.

**Comment by rrousselGit** [comment]
Closing in favour of https://github.com/rrousselGit/freezed/issues/64
