### ISSUE TITLE
Support case insensitive keys

### ISSUE THREAD

**Issue by romk1n** [rrousselGit/freezed#870]
**Is your feature request related to a problem? Please describe.**
It would be great to allow keys to be case insenstivive, like timeStamp, timestamp

**Describe the solution you'd like**
there is no error thrown if the json has a key which case is different

**Describe alternatives you've considered**
n/a

**Additional context**
client side would be more robust if backend changes the case

**Comment by rrousselGit** [comment]
This isn't a Freezed thing, but rather a json_serializable thing.

I don't remember if json_serializable supports it. See its `@JsonSerializable` annotation. In any case if it doesn't, the issue should be on their repo instead

**Comment by romk1n** [comment]
@rrousselGit thank you, raised here as there seem to be no option for it https://github.com/google/json_serializable.dart/issues/1294
