### ISSUE TITLE
Operation + on Freezed classes

### ISSUE THREAD

**Issue by DattatreyaReddy** [rrousselGit/freezed#872]
**Is your feature request related to a problem? Please describe.**
When I want to merge two Freezed objects I need to create a new Object and check the null condition or use copyWith on every variable which essentially defeats the purpose of the copyWith function. 

**Describe the solution you'd like**
Need an Operator + function to combine 2 Objects as mentioned below

```dart
void main() {
  Hello a = Hello(i: 1,d: 1.2);
  Hello b = Hello(d: 1.5, s: "nameste");
  
  print(a + b);
}

class Hello {
  int? i;
  double? d;
  String? s;
  
  Hello({ this.i, this.d, this.s});
  
  @override
  String toString() {
    return "Hello{ i: $i, d: $d, s: $s}";
  }
 
  Hello operator + (Hello b) {
    return Hello(
      i: i ?? b.i,
      d: d ?? b.d,
      s: s ?? b.s,
    );         
  }
}
```

**Comment by rrousselGit** [comment]
Feel free to manually implement this. I don't plan on implementing such a thing. It's not really a + after-all
