### ISSUE TITLE
FIC becomes dynamic type when used with `freezed`

### ISSUE THREAD

**Issue by shtse8** [rrousselGit/freezed#880]
I'm using the `fast_immutable_collections` package with the `freezed` package in my Dart project, and I've noticed that the generated code for the `@freezed` classes is using dynamic types instead of `IList` and other types from the `fast_immutable_collections` package.

For example, when I define a class with a property of type `IList<int>` like this:

```dart
import 'package:fast_immutable_collections/fast_immutable_collections.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'my_class.freezed.dart';

@freezed
abstract class MyClass with _$MyClass {
  const factory MyClass({
    @Default(IListConst([])) IList<int> numbers,
  }) = _MyClass;
}
```
The generated code for the MyClass class uses dynamic types instead of IList<int>:

```dart
abstract class MyClass implements _$MyClass {
  const MyClass({final dynamic numbers}) : super._();

  dynamic get numbers; // instead of IList<int> get numbers;
}
```
I expected the generated code to use the `IList<int>` type instead of dynamic. Am I doing something wrong, or is this a bug in the `freezed` package? Is there a way to make the `freezed` package generate code that uses `fast_immutable_collections` types instead of dynamic types?

Thanks for your help!

**Comment by rimidalv** [comment]
I have got the same issue on freezed 2.3.3:

```
part 'editable_items.freezed.dart';

@freezed
class EditableItem with _$EditableItem {
  const EditableItem._();

  const factory EditableItem.image({
    required String filePath,
    required GlobalKey key,
    required OffsetBase position,
    @Default(1) double scale,
    @Default(0) double rotation,
    @Default(false) bool positioningEnabled,
    @Default(false) bool gesturesEnabled,
  }) = EditableImageItem;

  const factory EditableItem.text({
    required String text,
    required ImageEditorTextWidgetStyle style,
    required GlobalKey key,
    required OffsetBase position,
    @Default(1) double scale,
    @Default(0) double rotation,
    @Default(true) bool positioningEnabled,
    @Default(true) bool gesturesEnabled,
    @Default(0) double renderedTextWidth,
    @Default(Colors.transparent) Color color,
  }) = EditableTextItem;
}
```


generates this code:
```
/// @nodoc
mixin _$EditableItem {
  GlobalKey<State<StatefulWidget>> get key =>
      throw _privateConstructorUsedError;
  dynamic get position => throw _privateConstructorUsedError;
  double get scale => throw _privateConstructorUsedError;
  double get rotation => throw _privateConstructorUsedError;
  bool get positioningEnabled => throw _privateConstructorUsedError;
  bool get gesturesEnabled => throw _privateConstructorUsedError;
  @optionalTypeArgs
  TResult when<TResult extends Object?>({
```

**Comment by fennelhans** [comment]
We ran into a similar issue where our tests were failing. We are employing mockito to generate mocks of our APIs, which have generated classes related to our GraphQL responses. When one of our API methods had a return type of one of those generated GraphQL classes, mockito was unable to find the class, leaving us with a dynamic return type in the generated code.

The solution, for us, was to ensure that we weren't returning any generated classes from our responses, instead either returning a primitive or a custom Freezed class which maps to the generated class. Interestingly, we also had the issue when the generated class was an enum - so we had to create a duplicate enum, and match the values.

I don't know if this is helpful, but I figured I'd share our insights, just in case.

**Comment by megamaddu** [comment]
Also running into this where the field on type A is generated as `dynamic`. The generated type should be one of the union classes (B.a) of another freezed type B. That type, B.a, is generated as an abstract class, in case that matters for some reason. The generator worked correctly on 2.1.0+1. Type A is generic, but the field in question, B, and B.a are not.

**Comment by rrousselGit** [comment]
@megamaddu This isn't something which can be supported.

**Comment by h3x4d3c1m4l** [comment]
I have just had this issue, this might not be helpful at all as it was due to a kinda stupid mistake.

I forgot to save some files that I opened and edited in VS Code. After saving hem and rerunning build_runner, the issues disappeared. Perhaps a warning that a certain class name could not be resolved could aid in debugging?

**Comment by shtse8** [comment]
I want to reproduce the issue but the project I faced this issue was few months ago. So I try to reproduce it in another project. But I couldn't. I think @h3x4d3c1m4l is right. The issue may due to unsaved file but vs code can analyze it but the generate file couldn't resolve it. I think it should better to produce some warnings to make it clear instead of dynamic type which makes the typing gone.

**Comment by rrousselGit** [comment]
The issue is very much known: Generated types are not supported.
