### ISSUE TITLE
name shouldn't end with a '.'

### ISSUE THREAD

**Issue by B33pin** [rrousselGit/freezed#883]
I don't think it's because i put . in some class name or like that because even if i rollback code to previous stable version, still can't generate with runner. 
I already tried flutter clean, cache clear, delete previous generated block, and version downgrade. 

build runner --verbose result:
[FINE] freezed on lib/src/modules/opening_closing_check/models/response_global_description.dart:Running FreezedGenerator
[FINE] freezed on lib/src/modules/opening_closing_check/blocs/global_description/global_description_cubit.dart:Running FreezedGenerator
[FINE] freezed on lib/src/modules/opening_closing_check/blocs/oc_action/oc_action_cubit.dart:Running FreezedGenerator
[FINE] freezed on lib/src/modules/image_pick/blocs/image_pick/imagepick_cubit.dart:Running FreezedGenerator
[FINE] freezed on lib/src/modules/opening_closing_check/blocs/oc_check/oc_check_cubit.dart:Running FreezedGenerator
[SEVERE] Build:
Unhandled build failure!
Invalid argument(s): name shouldn't end with a '.'
package:logging/src/logger.dart 82:7   new Logger._named
package:logging/src/logger.dart 64:47  new Logger.<fn>
dart:collection                        _LinkedHashMapMixin.putIfAbsent
package:logging/src/logger.dart 64:16  new Logger
package:logging/src/logger.dart 93:16  new Logger._named
package:logging/src/logger.dart 64:47  new Logger.<fn>
dart:collection                        _LinkedHashMapMixin.putIfAbsent
package:logging/src/logger.dart 64:16  new Logger
package:build_runner_core              _SingleBuild._runForInput.<fn>.<fn>
package:pool/pool.dart 127:14          Pool.withResource

[SEVERE] Build:
Failed after 11.9s
[+20122 ms] "flutter run" took 20,234ms.
[   +3 ms] pub finished with exit code 1
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:586:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:250:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +234 ms] ensureAnalyticsSent: 231ms
[        ] Running 0 shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by rrousselGit** [comment]
Without some code to reproduce, there's really not much I can do.

To begin with it sounds like Freezed isn't even reached. Could be that your file had a syntax error, in which case code generators don't execute

**Comment by Zeehshan** [comment]
I have the same issue, i am tired

**Comment by parmeetmaster** [comment]
I fixed this issue in intellij  via dual press shift key and write **..** in search.The file appears have wrong name as widget..dart then i correct name as widget.dart it work fine like charm.

**Comment by rrousselGit** [comment]
So this is because a file is named `my_file..dart` instead of `my_file.dart`?

Looks like this is unrelated to Freezed then. The error comes from build_runner itself anyway.
If you want a better error message, raise an issue there :)

**Comment by Dreamta** [comment]
> I fixed this issue in intellij via dual press shift key and write **..** in search.The file appears have wrong name as widget..dart then i correct name as widget.dart it work fine like charm.

you are my god！thanks
