### ISSUE TITLE
[Proposal] generate toString() even if the user overridden it

### ISSUE THREAD

**Issue by Hwan-seok** [rrousselGit/freezed#886]
**Is your feature request related to a problem? Please describe.**

At present, the toString() method is not generated if the user-defined toString() is present.
Maybe it's intentional and I understand why it doesn't generate.

But there are some cases in that the user wants to override `toString()` based on the generated one.
For example, line breaking or removing the type, etc...
by, 
```dart
pseudo-code:
super.toString().split(',')...
super.toString().split('(')[1]...
```

**Describe the solution you'd like**
No matter user overridden the `toString()`, code generation will generate it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rrousselGit** [comment]
That's not doable.

With:

```dart
@freezed
class A with _$A {
  factory A() = _A;
}
```

Then `_A` extends `A`, not the other way around.   
So `super.toString` inside `A` would point to `Object.toString`, not `_A.toString()`.

**Comment by gregslusarski** [comment]
You can alter like that default toString, from Object (Instance of '_$Something'). For example:

`@override
  String toString() =>
      '${super.toString().split('\$').last.split('\'').first}()';`
      
toString will be 'Something()'

This is handy if you have a lot of named constructors
