### ISSUE TITLE
Can't create constructor with required nullable property and ignored in to/from json

### ISSUE THREAD

**Issue by MiniSuperDev** [rrousselGit/freezed#889]
I want to serialized this class, and I want that the property be required to have static analysis when I used so I don't forget to assign it.

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'failure.freezed.dart';
part 'failure.g.dart';

@freezed
class Failure with _$Failure {
  const factory Failure({
    required String message,
    @JsonKey(ignore: true, defaultValue: null) required StackTrace? stackTrace,
  }) = _Failure;

  factory Failure.fromJson(Map<String, dynamic> json) =>
      _$FailureFromJson(json);
}
```

```text
Cannot populate the required constructor argument: stackTrace. It is assigned to a field not meant to be used in fromJson.
```

This work if is not required, but I need to be required because in code I ever want to assign it, the only case when not is in serialization.

```dart
    @JsonKey(ignore: true, defaultValue: null) StackTrace? stackTrace,
```

**Comment by rrousselGit** [comment]
That's not possible. How is the fromJson supposed to ignore decoding this property if it's required?

Also this isn't a Freezed error but a json_serializable one.
I'm not responsible for this and it would happen with plain json_serializable too.

So if you have a solution in mind, I'd suggest making an issue in the JsonSerializable repo

**Comment by rrousselGit** [comment]
Oh wait if you're expecting the property to be decoded with null, I guess that's possible.

But still that's not Freezed's responsibility.

**Comment by MiniSuperDev** [comment]
Thank you @rrousselGit 
Yes, decode/encode to null.
I opened an issue in json_serializable
https://github.com/google/json_serializable.dart/issues/1304
