### ISSUE TITLE
Lists for union types have missing type in generated code

### ISSUE THREAD

**Issue by maks** [rrousselGit/freezed#89]
Given a model class which has a list of a "union subtype":
```dart
@freezed
abstract class FApp with _$FApp {
  factory FApp({Header head, List<Page> pages}) = _FApp;
}
```
where the union is:
```dart
@freezed
abstract class WidgetType with _$WidgetType {
  const factory WidgetType.page({Body body, Header header}) = Page;
  const factory WidgetType.body() = Body;
  const factory WidgetType.header({String title}) = Header;
}
```
the type for the list in the generated code is `dynamic` instead of the actual type:
```dart
mixin _$FApp {
  Header get head;
  List<dynamic> get pages;

  FApp copyWith({Header head, List<dynamic> pages});
}
```
but in that generated code I expected page getter to be `List<Page>` not `List<dynamic>`.

It all works fine if I use `List<WidgetType>` but I really want to ensure I'm getting a List of `Pages` and not just any `WidgetType`

I've got [a repo with the full demo code](https://github.com/maks/esky)

**Comment by rrousselGit** [comment]
Do you still have the issue if you extract `FApp` in a different file?

**Comment by maks** [comment]
Sorry I didn't explain it well, in my example repo FApp is in a separate file.

**Comment by rrousselGit** [comment]
This was fixed as part of 10.0.3 but I forgot to close the issue

**Comment by maks** [comment]
@rrousselGit I'm sorry if I'm doing something wrong, but with [my demo repo](https://github.com/maks/esky) that I tested with using freezed 0.10.9 now and I am still seeing the same problem, the generated code still has:
```dart
mixin _$FApp {
  Header get head;
  List<dynamic> get pages;

  $FAppCopyWith<FApp> get copyWith;
}
``` 
so still a `dynamic` List instead of the actual type from the freezed "union" that I defined 😞

**Comment by rrousselGit** [comment]
What is Page then?

**Comment by maks** [comment]
Sorry, Page is from the "union" I have:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'widget_type.freezed.dart';

@freezed
abstract class WidgetType with _$WidgetType {
  const factory WidgetType.page({Body body, Header header}) = Page;
  const factory WidgetType.body() = Body;
  const factory WidgetType.header({String title}) = Header;
}
```

**Comment by rrousselGit** [comment]
Oh I didn't realize, my bad. 

Indeed this is not supported.

**Comment by maks** [comment]
@rrousselGit I would really like to have this for a project I'm working on - is this something I could help to add to freezed or is there something fundamental that would stop freezed being able to support this?

**Comment by rrousselGit** [comment]
This is a bit difficult to support, as `analyzer` doesn't give the name of the type if it fails to resolve.
So Freezed never knows that it's a `List<Page>`, it receives `List<dynamic>` directly.

A first step would be to ask the Dart team to add the name of the type that failed to resolve.

**Comment by maks** [comment]
@rrousselGit I've started having a look and try to figure out what's happening. As you pointed out, freezed is just using what its given, I can see by setting a breakpoint inside `ParserGenerator.generate()` at line 29 that the `LibraryReader` object that `parseElement()` extracts a `List<dynamic>` for the pages parameter.

But my suspicion now is that this is actually something to do with how source_gen is working rather than the analyser as the first non generic parameter, header does get assigned the correct `Header` type which also comes out of the same freezed generated file as the Pages type that is supposed to be assigned to the List parameter.

I'll keeping digging down this rabbit hole and see if I can find where this is being processed inside source_gen...

**Comment by rrousselGit** [comment]
The real reason is because the class Page is generated by freezed.

So when the analyzer analyzes the dart file, Page doesn't exist yet and the
analyzer says "dynamic" instead.

**Comment by maks** [comment]
That's what I thought at first too, but it works fine for the first parameter of FApp, which is `Header` type which is *also* a class generated by freezed: https://github.com/maks/esky/blob/master/lib/src/widget_type.dart

**Comment by maks** [comment]
I did also think that it might be due to an existing [open issue in source_gen](https://github.com/dart-lang/source_gen/issues/423) around depending on generated classes but it doesn't seem to be the case as per my last comment, the generated `Header` type from the same freezed generated file is correctly handled.

**Comment by rrousselGit** [comment]
Header works because Freezed does a manual parsing in this scenario

When an object is analyzed as dynamic, Freezed does an extra parsing to try and extract the type name.

But with List<Header> that wouldn't work as we're not receiving dynamic but List<dynamic>, which is a lot more complex to handle.

**Comment by maks** [comment]
Ah ok, sorry @rrousselGit I think I am beginning to understand now.
Oh this is super annoying! I can see the actual type stashed away inside the `DefaultParameterElementImpl` which is what the constructor.parameters objects actually are, but looks like there is no way to get at the property as the `ParameterElement` class "interface" doesn't expose any of it 😞 

![Screenshot 2020-06-10 at 18 25 24](https://user-images.githubusercontent.com/71999/84245328-372e5600-ab48-11ea-9a36-d8c865cb032d.png)

**Comment by maks** [comment]
@rrousselGit so I read through your code some more and once I figured out how it did the extra parsing, I had a basic go at extending your extra parsing to cope with generics which refer to freezed generated code classes, though I think most use cases would just be for `List` and `Map`: 

https://github.com/maks/freezed/commit/82b757a8252d7e5d9972adb5960d09ac8d6d868b

It seems to work in my initial manual testing.

If this is something that you'd be interested in using? I can add some unit tests for it and check my changes don't break existing tests.

**Comment by rrousselGit** [comment]
For sure. Feel free to make a pull request 😊
