### ISSUE TITLE
Please add a check for omission of type

### ISSUE THREAD

**Issue by biancashouse** [rrousselGit/freezed#891]
freezed: ^2.2.0

I added a bool to my bloc state, but I misstyped this:

    @Default(true) preferA4,

instead of this:

    @Default(true) bool preferA4,

It took ages to track down, because it only showed up as a hydrated box exception without pointing out the source.

Anyway, my suggestion, if feasible, would be for the syntax to be checked to protect us from ourselves ;-)

Fantastic pkg BTW - many thanks

**Comment by rrousselGit** [comment]
That's not Freezed's responsibility. The code is valid (it uses dynamic).


You can reject implicit dynamics your analysis_options.yaml
