### ISSUE TITLE
Transform / Validation implementation

### ISSUE THREAD

**Issue by NeroThroN** [rrousselGit/freezed#893]
Coming from typescript world, I wonder if there is a [Zod](https://zod.dev/) way of handling validation of the data.
I don't know if it's out of context for this package, but with the generation of models with [freezed](https://pub.dev/packages/freezed) and [json_serializable](https://pub.dev/packages/json_serializable), the ability to do more than just `@Assert` but transformation, validation and above all that default value can be used in case of an assertion failed (example below)

## Validation - [doc](https://zod.dev/?id=basic-usage)
Validation of the input data with default value: 
```typescript
const ObjectSchema = z.object({
  email: z.string().email().nullable().catch(null),
  facebook: z.string().url().regex(/^https:\/\/(?:www.)?facebook.com\//).nullable().catch(null),
  instagram: z.string().url().regex(/^https:\/\/(?:www.)?instagram.com\//).nullable().catch(null),
})

ObjectSchema.parse({
  "email": "bad@email",
  "facebook": "https://www.facebook.com/foo",
  "instagram": "https://www.google.com/bar",
}) // => {  "email": null, "facebook": "https://www.facebook.com/foo", "instagram": null }
```

## Transformation - [doc](https://zod.dev/?id=transform)
```typescript
const ObjectSchema = z.object({
  startDate: z.string().transform(date => new Date(date)).nullable().catch(null),
  endDate: z.string().transform(date => new Date(date)).nullable().catch(null),
})

ObjectSchema.parse({ startDate: '2023-04-28', endDate: null }) // => { startDate: "Fri Apr 28 2023 15:23:30 GMT+0200 (Central European Summer Time)", endDate: null }
```

I imagine it's doable by overriding some generated methods of the models, but is there a much cleaner and no-boilerplate workaround, like this validation layer describe above ?

**Comment by rrousselGit** [comment]
This is kind of out of the scope of Freezed. I would expect this to be the responsibility of a validation package.

Freezed is mostly a language patch, granting access early to some upcoming Dart features in a roundabout way. Anything outside of that is not something I'd want to do.
