### ISSUE TITLE
Is it possible to integrate freezed with equatable

### ISSUE THREAD

**Issue by orestesgaolin** [rrousselGit/freezed#90]
I use freezed to generate state classes for bloc and would like to have equality operator overwritten (most conveniently with equatable). Sometimes I copy state with `.copyWith()` and it seems that implemented equality operator doesn't work in such case:

```
  @override
  bool operator ==(dynamic other) {
    return identical(this, other) || (other is AcceptedTerms);
  }
```

where class is:

```
part 'terms_state.freezed.dart';

@freezed
abstract class TermsState with _$TermsState {
  factory TermsState.loading() = LoadingTerms;
  factory TermsState.termsToAccept(
    TermsModel terms, {
    @Default(false) bool loading,
  }) = TermsToAccept;
  factory TermsState.accepted() = AcceptedTerms;
  factory TermsState.error() = ErrorTerms;
}
```

**Comment by orestesgaolin** [comment]
My mistake. It works as expected i.e. changing field changes object.

**Comment by pro100svitlo** [comment]
@orestesgaolin can you please provide a code example of how you achieved it?
Cos in your code example you do not use `equatable`...

**Comment by rrousselGit** [comment]
@pro100svitlo equatable is not necessary, since Freezed already overrides the ==/hashCode operators

**Comment by pro100svitlo** [comment]
Yeah, but if in the state i have list and items of it were changed, it will not make any effect, cos list comparation do not rely on the children :(

**Comment by rrousselGit** [comment]
Don't mutate lists in Freezed classes.

**Comment by pro100svitlo** [comment]
>Don't mutate lists in Freezed classes.

strange advice to be honest.
with the same effect I can give advice do not use freezed classes.

**Comment by rrousselGit** [comment]
Freezed classes are immutable.

You're mutating part of an immutable class that Freezed has no control over.

To begin with, mutating a list but overriding == to deeply compare the list is anti pattern.
Overriding == on classes that are possibly mutable means you end up with a possibly inconsistent hashCode

This will break HashMaps/HashSets among others.



If you were to use Freezed 2.0, then the list would be be made immutable using UnmodifiableListView and you'd get an exception when trying to modify it.

So yes, you should not mutate the list.

**Comment by pro100svitlo** [comment]
Hm, maybe there is a misunderstanding?

In my case, I have a state, one of the parameters of the state is `List`.
And sometimes I would like to emit a new state (same type) with the updated list (f.e. added new item).

And with the original freezed setup it is impossible to do, cos bose states will look equal.

In my case, I solved this problem by adding `DateTime? timestamp` variable. When I would like to push the updated list, I update this variable as well. In this way, I can guarantee that the new state will be treated as a `new`.
@tomasatisocco ^

**Comment by rrousselGit** [comment]
> And sometimes I would like to emit a new state (same type) with the updated list (f.e. added new item).
> 
> And with the original freezed setup it is impossible to do, cos bose states will look equal.

You can do that, just without mutating the list

Like:

```dart
@freezed
class Example with _$Example {
  factory Example(List<int> list) = _Example;
}

void main() {
  final a = Example([]);
  final b = a.copyWith(list: [...a.list, 42]);

  print(a == b); // false
}
```

**Comment by tomasatisocco** [comment]
> Hm, maybe there is a misunderstanding?
> 
> In my case, I have a state, one of the parameters of the state is `List`. And sometimes I would like to emit a new state (same type) with the updated list (f.e. added new item).
> 
> And with the original freezed setup it is impossible to do, cos bose states will look equal.
> 
> In my case, I solved this problem by adding `DateTime? timestamp` variable. When I would like to push the updated list, I update this variable as well. In this way, I can guarantee that the new state will be treated as a `new`. @tomasatisocco ^

Thank you, will try with this solution and see what happen, I came to this problem because en debug mode the list in my stat update normally without problem, but in profile mode it dosent work

**Comment by tomasatisocco** [comment]
> > And sometimes I would like to emit a new state (same type) with the updated list (f.e. added new item).
> > And with the original freezed setup it is impossible to do, cos bose states will look equal.
> 
> You can do that, just without mutating the list
> 
> Like:
> 
> ```dart
> @freezed
> class Example with _$Example {
>   factory Example(List<int> list) = _Example;
> }
> 
> void main() {
>   final a = Example([]);
>   final b = a.copyWith(list: [...a.list, 42]);
> 
>   print(a == b); // false
>   print(a.list); // []
>   print(b.list); // [42]
> }
> ```

I'm not understanding how this is going to work

**Comment by Stardusted1** [comment]
@pro100svitlo, emit before your state with an updated list loading state, it takes a millisecond, but you don't need to hack your bloc 

> In my case, I solved this problem by adding DateTime? timestamp variable

**Comment by pro100svitlo** [comment]
> @pro100svitlo, emit before your state with an updated list loading state, it takes a millisecond, but you don't need to hack your bloc

@Stardusted1 Have you try that?
It's not working for me. 
the copied `state` with the different list (different content) is treated as the same `state`.

**Comment by Stardusted1** [comment]
@pro100svitlo, hah, I assume you have in your code something like: 
```
final currentState = state;

emit(currentState.copyWith(someField: "..."));
```
Bad news: this approach will lead you to state bloating, after some time you will break the **S** principle from SOLID. 
+ your bloc flow is now very fragile to adding new states. 

try to split the state into different states and store all needed information inside bloc fields, after that you can emit loaders without any problems & timestamp fields. 

//I came to this solution after working on a bloc with a state consisting of 11 fields for any screen.

**Comment by pro100svitlo** [comment]
> Bad news:

@Stardusted1 
I am sorry, but I do not see any direct relationship between SOLID, list comparison in a state, and having different constructors / different states. It's 3 unrelated topics.

Imagine next: 
I have a cubit state with 2 inheritors: first - for the loading state, second - for the ready state, and a list with items.
In this case, the second state contains only one param - list with items.

Users can interact with the list: bookmark, add, delete, edit. But the state type is the same: it's the second state with the list, and only the content of that list is changed.
And in that case, cubit will not emit copied (or newly created if you wish) state, cos those 2 states will be equal for it: both contain List object.

**Comment by Stardusted1** [comment]
@pro100svitlo, why do you create limitations for yourself? 

store your list inside the cubit, not inside the cubit's state, because it`s only reflects current inner cubit`s state. Then you could easily perform actions on your list without any magic with two equal states. 

refactor your code like this: 

```
class Cubit<S>{
    List<Item> items = [];

    void makeAction(Item item){
        emit(CubitLoading());
        // some actions with Cubit.items data 
        emit(CubitLoaded(items));
    }
}
```

**Comment by tomasatisocco** [comment]
You chould check if the items in yout List extends Equatable and has a toString method overrided, because if is not the case when the list in current and previus state is compared, and the number of items in the list is the same, the difference between states will not be visible because in the comparation, both will be lie List[Instance of..., Instance of..., Instance of...].

Anothe thing that you could try is to build when current.toString() != previous.toString() or do the same thing with one of the params of your state (like the lists)

**Comment by pro100svitlo** [comment]
> why do you create limitations for yourself?

what are you talking about? what did I create? 
I am telling you about the limitations of the `freezed`.

> refactor your code like this:

@Stardusted1 you proposing to me just a different workaround. Thank you fo sure, but I already have one, and I do not see much difference between them.
And yes, emitting a different state looks to me as a workaround, instead of solving a problem.

**Comment by pro100svitlo** [comment]
> check if the items in yout List extends Equatable

@tomasatisocco thank you. 
This is what I am already doing. But it's not working. Before the items comparator, the `List` object comparator is going. And 2 lists will be treated as equals by `freezed` even though the content might be different.

**Comment by tomasatisocco** [comment]
> > check if the items in yout List extends Equatable
> 
> @tomasatisocco thank you. This is what I am already doing. But it's not working. Before the items comparator, the `List` object comparator is going. And 2 lists will be treated as equals by `freezed` even though the content might be different.

And also have an toString overrided method?

**Comment by gorkemunuvar** [comment]
> Okay, I found another solution 🎉
> 
> when I am emitting a new state with a list with the updated items, I need to make sure that the `List` object is different. We can do that by simply calling `List.from(_myOldList)`
> 
> Here is a bit more expanded example:
> 
> ```dart
> void updateMyState(){
>   final newList = List.from(state.myList);
>   newList.add(newItem);  // any other manipulation with items
>   
>   final newState = state.copyWith(myList: newList);
>   emit(newState);
> }
> ```
> 
> So, actually, we do not need any `random` date in the state. We just need to make sure that the `List` object is a different one.
> 
> p.s. I still believe that it would be nice if we can reuse the same `List` object and just compare its content. But, it is what it is 😄
> 
> Cheers 🍻

Hey thanks for the answer but there is another situation. Instead of adding a new item into list if you change one of the items  inside the list, it still does not emit the new state. 

```
For example:
final newList = List.from(instance.boolList); // instance.boolList = [false, false, false];
newList.[0] = true;

emit(instance.copyWith(boolList: newList);
```
