### ISSUE TITLE
Abstract function implementation issue with Freezed

### ISSUE THREAD

**Issue by Mahm0ud-Ahmed** [rrousselGit/freezed#900]
I am trying to implement an abstract function in a class that uses Freezed. However, I'm encountering an error message stating that there is a missing concrete implementation of the abstract function. This is unexpected, as I would expect the implementation of the abstract function to be automatically generated by Freezed.

**Example code:**
```dart
abstract class BaseModel {
  BaseModel getModel(Map<String, dynamic> json);
}

@freezed
class UserModel with _$UserModel implements BaseModel {
  const factory UserModel({
    required final int id,
    required final String name,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);

  // Compiler error: Missing concrete implementation of 'UserModel.getModel'
  @override
  BaseModel getModel(Map<String, dynamic> json) => UserModel.fromJson(json);
}
```

In the above code, `UserModel` is a class that implements the `BaseModel` abstract class. It has a required method `getModel`, which I have attempted to implement by creating a factory method `fromJson` that returns an instance of `UserModel`. However, the compiler throws an error stating that there is a missing concrete implementation of the `getModel` method.

**Expected behavior:**
I would expect Freezed to automatically generate the implementation of the `getModel` method in the `UserModel` class, since it is marked as implementing the `BaseModel` abstract class.

**Actual behavior:**
Freezed is not generating the implementation of the `getModel` method in the `UserModel` class, causing a compiler error.

**Steps to reproduce:**
1. Create an abstract class with a required method
2. Create a class that implements the abstract class using Freezed
3. Attempt to implement the required method using a factory method
4. Observe the compiler error

**Possible solution:**
It would be helpful if Freezed could automatically generate the implementation of required methods in classes that implement abstract classes, such as in the example above.

Thank you for your time and attention to this issue.

**Comment by rrousselGit** [comment]
When defining methods, you need to also define an empty private constructor

```dart
freezed
class UserModel with _$UserModel implements BaseModel {
  const UserModel._():
  const factory UserModel({
    required final int id,
    required final String name,
  }) = _UserModel;
```

**Comment by digu3120** [comment]
👉 Try it out now: https://dartfreezed.tech/

 💬 I’d love your feedback and suggestions!

🚀 Introducing dartfreezed.tech – Your AI-Powered Flutter Freezed Model Generator! ⚡

Tired of manually converting complex JSON into Dart models?

 Say hello to dartfreezed.tech – a smart, lightning-fast tool that uses AI to generate Freezed and JsonSerializable Dart models from any JSON response in seconds!

 ✅ Powered by AI for intelligent field detection

 ✅ Clean, reliable Freezed models with built-in null safety

 ✅ Boosts productivity for Flutter developers

 ✅ Handles deeply nested and complex structures with ease
