### ISSUE TITLE
Can't generate class with switch expressions

### ISSUE THREAD

**Issue by orevial** [rrousselGit/freezed#912]
Dart 3 now allow switch expressions that can be used where switch statements were used.

However Freezed fails when trying to generate classes that contain Dart 3 switch expressions.

**To Reproduce**

What is currently working:

```dart
ColorVariant get getColorVariant {
  switch (linkColor) {
      case LinkColor.blue:
        return kLinkColors.blue;
      case LinkColor.lightGrey:
        return kLinkColors.lightGrey;
      case LinkColor.darkGrey:
        return kLinkColors.darkGrey;
    }
  }
```

What is **not** working: 

```dart
ColorVariant get getColorVariant {
    return switch (linkColor) {
      LinkColor.blue => kLinkColors.blue,
      LinkColor.lightGrey => kLinkColors.lightGrey,
      LinkColor.darkGrey => kLinkColors.darkGrey,
    };
  }
```

When generated, we get this type of errors: 

```shell
link.entity.dart:11:5: Expected to find ';'.
link.entity.dart:12:7: Expected to find 'case'.
```

**Expected behavior**

I would expect being able to write Dart 3 switch expressions:

```dart
ColorVariant get getColorVariant {
    return switch (linkColor) {
      LinkColor.blue => kLinkColors.blue,
      LinkColor.lightGrey => kLinkColors.lightGrey,
      LinkColor.darkGrey => kLinkColors.darkGrey,
    };
  }
```

**Comment by rrousselGit** [comment]
> When generated, we get this type of errors:
> 
> ```shell
> link.entity.dart:11:5: Expected to find ';'.
> link.entity.dart:12:7: Expected to find 'case'.
> ```

The error appears to be on your sie.

Could you share a full example instead of just the getter?

**Comment by 2shrestha22** [comment]
Facing same issue. Syntax was correct no warning/error. But running build runner fails.

**Comment by 2shrestha22** [comment]
Make sure to use latest `riverpod_generator: ^2.3.5`. I was getting issue with `2.1.5`. Fixed after updating.

**Comment by rrousselGit** [comment]
The error is most definitely caused by an out-of-date `analyzer` version.

Make sure to run `pub upgrade` and this should go away
