### ISSUE TITLE
Format doesn't match dart format

### ISSUE THREAD

**Issue by davestimpert** [rrousselGit/freezed#913]
**Describe the bug**
Since we upgraded to flutter 3.10, the freezed generated classes don't match what dart format produced.
We have a check in ci that makes sure dart format doesn't produce any changes, so now our freezed classes are making that fail.

This is specifically related to newlines following annotations on fields.

**To Reproduce**
1. Run build_runner to produce freezed classes
2. Run `dart format .`
3. Note that dart format changes freezed classes

<img width="690" alt="image" src="https://github.com/rrousselGit/freezed/assets/8226537/c1f99594-1a31-448b-a496-33d35f9f1bee">

**Expected behavior**
dart format should not modify *.freezed.dart classes.

**Comment by rrousselGit** [comment]
Nothing I can do. Freezed isn't doing any formatting.

It's a dependency thing. Your `dart_styles` version might be out of date. Try running `pub ugprade` or check `pub outdated` if there's something constraining `dart_styles`

**Comment by davestimpert** [comment]
Thanks, yeah I tried adding `dart_style: ^2.3.1` to pubspec.yaml and it just changed it from `transitive` to `direct_main` in pubpec.lock. Still same issue. I've also made sure I'm on the latest build_runner and freezed. I'll post here if I get it resolved.

For now, I'm just going to always run dart format after running build_runner.

**Comment by davestimpert** [comment]
It seems there's a difference in the output of dart format between flutter 3.10.0 and 3.10.1 🤔 
So to be specific, it is 3.10.1 where we began having this issue.

**Comment by rrousselGit** [comment]
There's a dart_style 2.3.2 coming. That's what'll fix the issue. See the changelog https://github.com/dart-lang/dart_style/blob/main/CHANGELOG.md

**Comment by davestimpert** [comment]
Thanks Remi, 2.3.2 landed, and as you predicted, this is now resolved 🎉
