### ISSUE TITLE
JsonConverter: generics & non-null/nullable issues

### ISSUE THREAD

**Issue by cpboyd** [rrousselGit/freezed#915]
**Describe the bug**

1. Generic `JsonConverter`s  don't seem to work as I'd expect: https://github.com/google/json_serializable.dart/blob/master/example/lib/json_converter_example.dart#L46-L83
2. When a `JsonConverter` returns an explicitly non-nullable type (e.g. `List<String>` instead of `List<String>?`), `@Default()` should be optional.
3. A `JsonConverter` returning a nullable type (e.g. `List<String>?`) cannot use `@Default()` to enforce non-null because the generated code refuses to use the JsonConverter due to a mismatch in types: `List<String>` instead of `List<String>?`

Maybe a `Union` type would also work for what I'm trying specifically to do: Accept JSON of either a single item or `List` of that item, while transforming that to a `List` in Dart.

**To Reproduce**

```dart
@freezed
class Event with _$Event {
  const factory Event({
    required String name,
    required List<DateTime> times,
    @MaybeListConverter() List<String> tickets,
  }) = _Event;

  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);
}
```

```dart
class MaybeListConverter<T> implements JsonConverter<List<T>, Object?> {
  const MaybeListConverter();

  @override
  List<T> fromJson(Object? json) {
    switch (json) {
      case T json:
        return [json];
      case List<dynamic> json:
        return json.map((e) => e as T).toList();
      default:
        return const [];
    }
  }

  @override
  Object? toJson(List<T> object) => object;
}
```

A workaround:
```dart
class StringListConverter extends MaybeListConverter<String> {
  const StringListConverter();
}

class Event with _$Event {
  const factory Event({
    required String name,
    required List<DateTime> times,
    @StringListConverter() @Default([]) List<String> tickets,
  }) = _Event;

  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);
}
```

Using without `@Default([])` throws:

```
The parameter `tickets` of `Event.` is non-nullable but is neither required nor marked with @Default
```

**Expected behavior**

I'd expect the generic version to work: `@MaybeListConverter() List<String> tickets,`
Note, I've even tried `@MaybeListConverter<String>() List<String> tickets,`

**Comment by rrousselGit** [comment]
> 2\. When a `JsonConverter` returns an explicitly non-nullable type (e.g. `List<String>` instead of `List<String>?`), `@Default()` should be optional.

No, the current behavior is correct. Because you can instantiate the class without passing by `fromJson`. So the default value is still necessary.  
If the value is known to be present, you can alternatively mark the parameter as required instead of using default.



> 3\. A `JsonConverter` returning a nullable type (e.g. `List<String>?`) cannot use `@Default()` to enforce non-null because the generated code refuses to use the JsonConverter due to a mismatch in types: `List<String>` instead of `List<String>?`

This seems unrelated to Default. If your property is non-nullable, the converter cannot return a null value, even if the constructor parameter was required.


So all in all, the current behavior seems expected.

**Comment by cpboyd** [comment]
It also seems like this type of generic `JsonConverter` doesn't work with the `JsonSerializable` annotation, perhaps because the type constraint is wrapped in a `List<>`
