### ISSUE TITLE
InvalidType with  Freezed Union/Sealed classes with json serialization in other Freezed classes.

### ISSUE THREAD

**Issue by JoanSchi** [rrousselGit/freezed#920]
Hi,

I am using Freezed Union/Sealed classes with json serialization in other Freezed classes. In de past this worked fine, but now I get a InvalidType error.

**Example:**

```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'model.freezed.dart';
part 'model.g.dart';

@freezed
sealed class Model with _$Model {
  factory Model.first(String a) = First;
  factory Model.second(int b, bool c) = Second;

  factory Model.fromJson(Map<String, dynamic> json) => _$ModelFromJson(json);
}
```

```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:simple_test/src/model.dart';

part 'test.freezed.dart';
part 'test.g.dart';

@freezed
class Test with _$Test {
  const factory Test({
    required First first,
  }) = _Test;

  factory Test.fromJson(Map<String, Object?> json) => _$TestFromJson(json);
}
```

**Error**
Could not generate `fromJson` code for `first`.
To support the type `InvalidType` you can:
* Use `JsonConverter`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
* Use `JsonKey` fields `fromJson` and `toJson`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
package:simple_test/src/test.freezed.dart:99:21
   ╷
99 │   final InvalidType first;

**Expected behavior**
Generated the code

**Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.1, on openSUSE Tumbleweed 6.3.1-1-default, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)
[✓] Network resources

**pubspec**

name: simple_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0

**Comment by SunlightBro** [comment]
Known issue with analyzer 5.13.0
In your pubspec.yaml add
```yaml
dependency_overrides:
  analyzer: 5.12.0
```

**Comment by rrousselGit** [comment]
Closing in favour of https://github.com/rrousselGit/freezed/issues/916

**Comment by oowliq** [comment]
> Known issue with analyzer 5.13.0 In your pubspec.yaml add
> 
> ```yaml
> dependency_overrides:
>   analyzer: 5.12.0
> ```

I ❤️‍🔥 U
