### ISSUE TITLE
Linter - invalid_required_positional_param, avoid_equals_and_hash_code_on_mutable_classes

### ISSUE THREAD

**Issue by petrnymsa** [rrousselGit/freezed#93]
For positional params ```@required``` annotation is generated which is unnecessary and produces invalid_required_positional_param

Another linter warning: *avoid_equals_and_hash_code_on_mutable_classes* 
-> ```AVOID overloading operator == and hashCode on classes not marked `@immutable```

Not so important, but it can help keep code cleaner and fewer warnings.

**Comment by rrousselGit** [comment]
Closing this as I don't plan on supporting every single lint possible.

Instead consider ignoring generated files, as described here: https://dash-overflow.net/articles/getting_started/
