### ISSUE TITLE
Importing package from monorepo breaks toJson() code generation

### ISSUE THREAD

**Issue by peer-f** [rrousselGit/freezed#930]
**Describe the bug**
I have an issue where importing a package from my monorepo for example a common package that contains commonly used entities the toJson() code is not generated. Each package of the monorepo contains `freezed`, `freezed_annotation`, `build_runner` and all of the other depdencies needed so there is no export happening in the common package. It worked fine before using freezed 2.2.0 and Flutter 3.7.

For example this code doesn't work:
```
import 'package:common/common.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
part 'get_user_notifications_response.freezed.dart';
part 'get_user_notifications_response.g.dart';

@freezed
class GetUserNotificationsResponse with _$GetUserNotificationsResponse {
  const factory GetUserNotificationsResponse({
    required List<UserNotification> notification_messages,
  }) = _GetUserNotificationsResponse;

  factory GetUserNotificationsResponse.fromJson(Map<String, dynamic> json) =>
      _$GetUserNotificationsResponseFromJson(json);
}
```
A solution that works is specifying the path of the entity used:
```
import 'package:common/src/entities/notification/user_notification.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
part 'get_user_notifications_response.freezed.dart';
part 'get_user_notifications_response.g.dart';

@freezed
class GetUserNotificationsResponse with _$GetUserNotificationsResponse {
  const factory GetUserNotificationsResponse({
    required List<UserNotification> notification_messages,
  }) = _GetUserNotificationsResponse;

  factory GetUserNotificationsResponse.fromJson(Map<String, dynamic> json) =>
      _$GetUserNotificationsResponseFromJson(json);
}
```
While using a show combinator leads to the same issue:
```
import 'package:common/common.dart' show UserNotification;
import 'package:freezed_annotation/freezed_annotation.dart';
part 'get_user_notifications_response.freezed.dart';
part 'get_user_notifications_response.g.dart';

@freezed
class GetUserNotificationsResponse with _$GetUserNotificationsResponse {
  const factory GetUserNotificationsResponse({
    required List<UserNotification> notification_messages,
  }) = _GetUserNotificationsResponse;

  factory GetUserNotificationsResponse.fromJson(Map<String, dynamic> json) =>
      _$GetUserNotificationsResponseFromJson(json);
}

```

**To Reproduce**

I ran my example code in a package of the monorepo using these dependency versions:
```
 Flutter 3.10.2  
 Dart 3.0.2
 
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
```
  
**Expected behavior**
I expect the toJson() generation to work without having to specify each entity used from other packages.

**Comment by rrousselGit** [comment]
What do you mean by "doesn't work" exactly?

**Comment by rrousselGit** [comment]
Could you maybe share a complete example? A github repository to reproduce the issue would be great.

As it is, it's a bit too abstract to determine what the issue is. It could be anything and seems closely tied to your setup.

**Comment by rrousselGit** [comment]
@peer-f What are the steps to reproduce the issue with your repo?

All .g.dart seems to be present in the git repository

**Comment by rrousselGit** [comment]
I doubt that this has anything to do with mono-repos. I use nothing but mono-repositories

I'd suggest looking elsewhere, like maybe one of your packages not depending on `json_serializable`
