### ISSUE TITLE
code generation warning when using sealed for pattern matching

### ISSUE THREAD

**Issue by romaingyh** [rrousselGit/freezed#937]
Hello, I'm trying to implements new Dart 3 pattern matching with freezed, I did like the example in Readme. It works well but there is a waning in the code generation terminal because of the sealed keyword detected as abstract.

```dart
@freezed
sealed class Example with _$Example {
  const factory Example.person(String name, int age) = Person;
  const factory Example.city(String name, int population) = City;
}

String sampleSwitch(Example example) {
  return switch (example) {
    Person() => 'Person',
    City() => 'City',
  };
}
```

```console
WARNING] freezed on lib/example.dart:
The class Example was declared as abstract, but it is not needed anymore.
Read here: https://github.com/rrousselGit/freezed/blob/master/packages/freezed/CHANGELOG.md#0140
```

Since this is just a warning and the feature still works, I'm posting in this category, perhaps I should file a bug report or just a discussion post.  I apologize in that case.

**Comment by rrousselGit** [comment]
This was fixed in 2.3.4.
This warnign is completely removed.

Upgrade your version of Freezed and it should disappear
