### ISSUE TITLE
Add mergeWith

### ISSUE THREAD

**Issue by gleesonger** [rrousselGit/freezed#94]
It would be useful to have a mergeWith function. This would be similar to copyWith but instead of passing individual parameters you pass an object.

For example:
`newSearchParameters = widget.defaultSearchParameters.mergeWith(updatedSearchParameters)`

where a field is null in the update the default will be used

**Comment by rrousselGit** [comment]
What's the purpose?

**Comment by gleesonger** [comment]
In my use case (flutter app) I have a number different tabs where each tab shows a different filter of an overall data set. On each tab the user can further refine the search filter. Something similar to the YouTube app with the home/trending/subscription tabs.

My approach is to pass a different default/inital SearchParameters object to the main widget on each tab. When the user calls the filter dialog on a particular tab the object returned is also a SearchParameters object. This object may not be fully completed (ie have some fields set to null) as the filter may not have exposed all parameters to the user. I then merge the inital with the updated parameters to get the new effective SearchParameters object. The main widget on each tab where this merging happens does need to know anything about the individual fields in the object so it cleaner to have a simple mergeWith.

For the moment I am thinking of including this as an extension to the "freezed" object:
`  SearchParams mergeWith(SearchParams other) {
    final map = this.toJson()..addAll(other.toJson());
    return SearchParams.fromJson(map);
  }`

**Comment by rrousselGit** [comment]
But how is that different to `copyWith` and would would that work with non-nullable types?

**Comment by gleesonger** [comment]
mergeWith is just syntax sugar for copyWith but it has a few advantages:
1) When merging the object the class doing the work does not need to know about the fields in the object. I think my project is a good example, the main UI calls a filter dialog which returns a settings object, the main UI doesn't know about the fields in this object, it just merges it with the default settings and then passes the updated settings on to the destination.
2) It can in some scenarios be cleaner, in the above example if I change the fields in the settings object I dont need to check the main UI, I know it will do it correctly.

For non-nullable types, I suppose you could allow the user the select which object takes priority:
`T mergeWith(T newValue,[bool newValueOverridesNonNullables])`

**Comment by rrousselGit** [comment]
> For non-nullable types, I suppose you could allow the user the select which object takes priority:
T mergeWith(T newValue,[bool newValueOverridesNonNullables])

Can you expand on this with a full example (including the generated code)?

**Comment by gleesonger** [comment]
Given the standard Person class:
```
@freezed
abstract class Person with _$Person {
  const factory Person(
    String name, {
    @required int age,
    Gender gender,
  }) = _Person;
}
```

I might expect this code to be generated:
```
  @override
  _$_Person mergeWith(_$_Person newValue, [bool newValueOverridesNonNullables = false]) {
    return _$_Person(
      newValueOverridesNonNullables ? newValue.name : this.name,
      age: newValueOverridesNonNullables ? newValue.age : this.age,
      gender: newValue.gender ?? this.gender,
    );
  }
```

**Comment by rrousselGit** [comment]
How would you, say, change a Person's name without changing its age?\
What if we want to purposefully assign `null` to a property?


Do you mind sharing more about your _problem_ rather than the _solution_? It's possible that there is a different solution that does not rely on such a thing.

**Comment by rrousselGit** [comment]
I'll close this as I don't plan on working on it – I'm not satisfied with the API.
