### ISSUE TITLE
Computed property by @late is misleading due to interior mutablity

### ISSUE THREAD

**Issue by znjameswu** [rrousselGit/freezed#95]
In the doc it says

> Since Freezed relies on immutable classes only, then this may be very helpful for computed properties.
> 
> For example, you may write:
> 
> 
```
abstract class Todos with _$Todos {
   factory Todos(List<Todo> todos) = _Todos;
 
   @late
   List<Todo> get completed => todos.where((t) => t.completed).toList();
 }
```
> As opposed to a normal getter, this will cache the result of completed, which is more efficient.

However dart's List class is mutable, so it can easily be manipulated. Such as

```
@freezed
abstract class Test with _$Test {
  factory Test(List<int> nums) = _Test;
  @late
  String get print => nums.toString();
}

void main(List<String> arguments) {
  final test = Test([1,2,3]);
  print(test.print); // [1, 2, 3]
  test.nums.add(4);
  print(test.print); // Still [1, 2, 3]
}
```
Calling this behavior "computed property" might be slightly misleading.

**Comment by rrousselGit** [comment]
You are violating the very first line mentioned by the doc:

Freezed relies on immutable classes only

You did not respect that rule and made a mutation on the Freezed class, hence the error.

**Comment by znjameswu** [comment]
@rrousselGit Yes, but the doc example uses mutable List itself, so it as an example for "computed property" is demonstrating a bad practice. Probably we should change the example to immutable BuiltList.

**Comment by rrousselGit** [comment]
The example does not demonstrate a bad practice. It does do any mutation.
Similarly, `List` can be immutable (constant lits or lists created with `List.immutable`)

This also matches with what Flutter does. Widgets are immutable too, but `Column`/`ListView`/... takes a `List` for children.

**Comment by znjameswu** [comment]
Okay, thank you for the clarification. This is mainly a style issue. I'll close this issue.
