### ISSUE TITLE
Destructuring doesn't work for regular constructors

### ISSUE THREAD

**Issue by feinstein** [rrousselGit/freezed#961]
I am pretty new to patterns in Dart 3, so I apologize if this is not a bug, but definitely should be included in the docs.

I have the following freezed class:

```dart
@freezed
sealed class SettingsState with _$SettingsState {
  const factory SettingsState({required bool isEnabled}) = _SettingsState;

  const SettingsState._();

  const factory SettingsState.loading() = SettingsStateLoading;
  const factory SettingsState.empty() = SettingsStateEmpty;

  factory SettingsState.fromJson(Map<String, Object?> json) => _$SettingsStateFromJson(json);
}
```

All the destructuring examples only show named constructors, there's no example with a regular constructor. I tried this:

```dart
return switch (state) {
  SettingsStateLoading() => Text('1'),
  SettingsStateEmpty() => Text('2'),
  SettingsState(:final isEnabled) => Text('3'),
};
```

But the compiler complains that `The getter 'isEnabled' isn't defined for the type 'SettingsState'.`, which makes sense, as this class doesn't have this getter.

I tried to change `_SettingsState` to something else, like `SettingsStateDefault` but the same error happens. Renaming the Mixin also didn't help.

Is it possible to use freezed with destructuring without using only named constructors?

**Comment by feinstein** [comment]
I commented the private constructor, run the build again and restarted the Dart Analysis server and it worked. I uncommented the private constructor, run the build one more time, and it works now.

I think this might be a bug on the Dart Analysis server or build_runner, but destructuring appears to work with regular constructors if they are not private like:

```dart
  const factory SettingsState({required bool isEnabled}) = SettingsStateDefault;
```

For now the analyzer isn't complaining anymore.

@rrousselGit could you please add an example without named constructors? Thanks.

**Comment by rrousselGit** [comment]
There's nothing unexpected here.

loading/empty don't have isEnabled, so SettingsState does not have it.
Only _SettingsState has it

Do:

```dart
switch (state) {
  _SettingsState(:final isEnabled) => ...
}
```

You may want to make _SettingsState public

**Comment by feinstein** [comment]
Yes, but don't you think the Readme should be updated with an example that doesn't include a named constructor?

**Comment by rrousselGit** [comment]
There's strictly no difference between whether a constructor is named or not when using pattern matching

We always use the redirected class name, never the constructor.

**Comment by feinstein** [comment]
Yes, but the docs don't state that explicitly. Users might copy paste, and the named constructor examples have public redirecting constructors, while the simple non-named constructor examples comes before in the readme, and they are private.

I think this is very obvious for an advanced user, that understands what are factory constructors and how patterns and frezzed magic works, but I am not so sure how obvious it is for begginers.

**Comment by chiphan-makebetter** [comment]
I still wonder about this so how do we implement this?

**Comment by feinstein** [comment]
Don't declare your constructors as private, and use them.

```dart
const factory SettingsState({required bool isEnabled}) = SettingsStateDefault;
```

Use the `SettingsStateDefault`.

**Comment by chiphan-makebetter** [comment]
> Don't declare your constructors as private, and use them.
> 
> ```dart
> const factory SettingsState({required bool isEnabled}) = SettingsStateDefault;
> ```
> 
> Use the `SettingsStateDefault`.

Thank you, can I ask how you use it in a switch case?

**Comment by chiphan-makebetter** [comment]
> Don't declare your constructors as private, and use them.
> 
> ```dart
> const factory SettingsState({required bool isEnabled}) = SettingsStateDefault;
> ```
> 
> Use the `SettingsStateDefault`.

Thank you 🙏
