### ISSUE TITLE
Use with go_builder

### ISSUE THREAD

**Issue by andrm** [rrousselGit/freezed#962]
**Is your feature request related to a problem? Please describe.**
I'm using sdk restriction sdk: ">=3.0.0 <4.0.0". As soon as I want to use go_router_builder it says:
Because go_router_builder >=1.0.13 depends on analyzer >=4.4.0 <6.0.0 and freezed 2.4.2 depends on analyzer ^6.0.0, go_router_builder >=1.0.13 is incompatible with freezed 2.4.2.

**Describe the solution you'd like**
Is it possible to use it with the newer sdk restrictions?

**Describe alternatives you've considered**
Downgrade sdk ?

**Comment by rrousselGit** [comment]
go_router_builder needs to support analyzer 6.0.0

**Comment by andrm** [comment]
Ah thanks. Sorry.
