### ISSUE TITLE
Mockito creates incomplete mocks for freezed generated classes

### ISSUE THREAD

**Issue by Mark-Toten** [rrousselGit/freezed#969]
**Describe the bug**
Mocks generated for freezed classes are incomplete. There is a (dirty) workaround: by adding json_serializable as dev-dependency, the generated mocks are correct again. This issue only occurs if both the freezed- and mock-classes are generated. When you do not generate the freezed-classes, the mock-classes are fine.  Related issue for Mockito: https://github.com/dart-lang/mockito/issues/689

**To Reproduce**
In this repository as simple reproduction scenario is included. Notice the difference in generated mock-classes when json_serializable is included. 
[https://github.com/Mark-Toten/mockito_freezed](https://github.com/Mark-Toten/mockito_freezed)

**Expected behavior**
Generated mock-classes should be complete and compatible. This issue started popping up for me when trying to move from Mockito 5.2.0 to 5.4.0

**Comment by rrousselGit** [comment]
I'm not responsible for mockito. It's not a Freezed issue :)

**Comment by Mark-Toten** [comment]
Thanks @rrousselGit  for looking into it. I wasn't too sure if it wasn't a freezed issue, since it happens only during code generation, so it could be caused by a build config issue in freezed as well. 

p.s. Thanks for all your contributions over the years and making Dart/Flutter even greater. Really appreciated!
