### ISSUE TITLE
[Question] JSON value which may change

### ISSUE THREAD

**Issue by amebrahimi** [rrousselGit/freezed#97]
Hello, I have a JSON response from the network in which one of its values may vary from one request to another. For example :

```
{
    "data": {
        "name": "john",
        "last_name": "doe"
    }
}
```
And sometimes:
```
{
    "data": [
        {
            "name": "john",
            "last_name": "doe"
        }
    ]
}
```

The data is sometimes a list and sometimes an object. Is there any way I can check the type of the runtime type and decide which object I want to transform the data to. for example the UserModel or List<UserModel>.

**Comment by amebrahimi** [comment]
any soloution?

**Comment by rrousselGit** [comment]
You can do:

```dart
Map<String, dynamic> json;

if (json['data'] is List) {

} else if (json['data'] is Map) {

}
```

**Comment by amebrahimi** [comment]
I know but what if we are using json_serializable
