### ISSUE TITLE
Support for Dart 3 Interfaces 

### ISSUE THREAD

**Issue by khari998** [rrousselGit/freezed#974]
I am trying to build model and entity classes using clean architecture. Previously there was no way to properly have models implement all of the characteristics of entities in a clean way. Now with the new class modifiers in Dart 3, we can use interfaces to do this easily. The problem is that Freezed fails when doing this because it is looking for a .copyWith method of the interface class.

```dart
@freezed 
interface class User with _$User {
  const factory User({
    required String id,
    required String name,
  }) = _$User;
}

@freezed 
class UserModel with _$UserModel implements User {
  const factory UserModel({
    required String id,
    required String name,
  }) = _$UserModel;

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);
}

```

Gives me the error: 

```
Superinterfaces don't have a valid override for 'copyWith': _$UserModel.copyWith ($UserModelCopyWith<UserModel> Function()), _$User..copyWith ($UserCopyWith<User> Function()).
Try adding an explicit override that is consistent with all of the inherited members.
```

**Comment by rrousselGit** [comment]
Feel free to disable copyWith on the interface

`@Freezed(copyWith: false)`

**Comment by khari998** [comment]
> Feel free to disable copyWith on the interface
> 
> `@Freezed(copyWith: false)`

This worked! Thanks. It would be nice to keep copy with in the future in case it is needed but this should do for now

**Comment by rrousselGit** [comment]
Closing in favour of https://github.com/rrousselGit/freezed/issues/975
