### ISSUE TITLE
Ability to pinpoint where fromJson throws an error

### ISSUE THREAD

**Issue by aytunch** [rrousselGit/freezed#980]
I have a huge Json I am trying to parse and this is the only log I get:

> Failure: type 'Null' is not a subtype of type 'String' in type cast

Is there a utility or method I can use to pinpoint which field or nested class'es fromJson is failing so I can investigate what is wrong.

I tried to log my decoded Json before feeding it to fromJson and used an online json prettifier but not luck

**Comment by rrousselGit** [comment]
While I understand the problem, there's not much I can do here.
Freezed doesn't really do deserialization. It only integrates with other packages for it (json_serializable).

If you want better error messages, you should ask json_serializable instead.

**Comment by martinralfreindl** [comment]
FYI - I opened this issue with the json_serializable folks to see if something can be done: 
https://github.com/google/json_serializable.dart/issues/1381
