### ISSUE TITLE
Support for JsonSerializable Options in @freezed Annotation

### ISSUE THREAD

**Issue by ahmadjz** [rrousselGit/freezed#982]
**Is your feature request related to a problem? Please describe.**
Yes, the issue I'm facing is that I cannot add any options to `@JsonSerializable` when using the `@freezed` annotation. For example, I cannot use `@JsonSerializable(explicitToJson: true)` settings.

**Describe the solution you'd like**
I would like to have the ability to pass options to `@JsonSerializable` via the `@freezed` annotation. Maybe something like this:
```
@freezed(jsonOptions: JsonSerializable(explicitToJson: true))
class MyClass with _$MyClass {
  factory MyClass({String? field}) = _MyClass;
}
```
Or even simply allow `@JsonSerializable` to be stacked above `@freezed`:
```
@JsonSerializable(explicitToJson: true)
@freezed
class MyClass with _$MyClass {
  factory MyClass({String? field}) = _MyClass;
}
```

**Describe alternatives you've considered**
As of now, I manually edit the `.g.dart` files generated by `freezed` to include `explicitToJson: true` in the `@JsonSerializable()` annotation.

**Additional context**
Being able to configure `JsonSerializable` via `@freezed` would greatly improve my workflow, and I'm sure it would help others as well. This would provide a more streamlined experience when using both packages.

**Comment by rrousselGit** [comment]
> Or even simply allow `@JsonSerializable` to be stacked above `@freezed`:
> 
> ```
> @JsonSerializable(explicitToJson: true)
> @freezed
> class MyClass with _$MyClass {
>   factory MyClass({String? field}) = _MyClass;
> }
> ```

You can do that.

More specifically, the syntax is to put the annotation on the "factory". Freezed copy-paste all annotations on the factory to the generated class.

**Comment by ahmadjz** [comment]
@rrousselGit 
Thank you for pointing out that the `@JsonSerializable` annotation can be stacked above `@freezed`. I tried it out and it works functionally, but I do get a warning on this line: `@JsonSerializable(explicitToJson: true)`.

The warning message is:
```
The annotation 'JsonSerializable' can only be used on classes.dartinvalid_annotation_target
```
code example 
```
@freezed
class MyClass with _$MyClass {
  @JsonSerializable(explicitToJson: true)
  factory MyClass({String? field}) = _MyClass;
}
```
Do you have any ideas on how to suppress or resolve this warning? While the functionality seems to be there, the warning could be a bit distracting.

**Comment by rrousselGit** [comment]
There's an issue about it with some suggestions https://github.com/rrousselGit/freezed/issues/488
