### ISSUE TITLE
Warnings on Generated Code Regarding lowerCamelCase Identifier

### ISSUE THREAD

**Issue by ahmadjz** [rrousselGit/freezed#983]
**Describe the bug**
When using Freezed to generate classes for JsonSerializable, the generated `.g.dart` files produce Dart Analyzer warnings about not following lowerCamelCase naming conventions.

**To Reproduce**
Here is a simplified code example to demonstrate the issue:
```
@freezed
class AttributeValueResponse with _$AttributeValueResponse {
  const factory AttributeValueResponse({
    required int id,
    required String name,
    String? color,
  }) = _AttributeValueResponse;

  factory AttributeValueResponse.fromJson(Map<String, Object?> json) =>
      _$AttributeValueResponseFromJson(json);
}
```

In the generated `.g.dart` file, the function name `_$$_AttributeValueResponseFromJson` triggers a Dart Analyzer warning:
```
The variable name '_$$_AttributeValueResponseFromJson' isn't a lowerCamelCase identifier.
Try changing the name to follow the lowerCamelCase style.
```

**Expected behavior**
he generated code should not produce Dart Analyzer warnings and should adhere to Dart's naming conventions, specifically lowerCamelCase for variable names.

**Comment by khari998** [comment]
A temporary workaround is adding this to the `analysis_options.yaml`

```dart
analyzer:
  exclude:
    - "**/*.g.dart"
```
