### ISSUE TITLE
InvalidType is generated when accessing common freezed property

### ISSUE THREAD

**Issue by Azandowski** [rrousselGit/freezed#987]
**Describe the bug**

I have an OptionContent class which is freezed and has some public sealed classes in it:

```
@freezed
abstract class OptionContent with _$OptionContent {
  const factory OptionContent.text({
    required String text,
  }) = OptionContentText;

 
  const factory OptionContent.textWithHeader({
    required String text,
    required String headerText,
  }) = OptionContentTextWithHeader;

 
  const factory OptionContent.popup({
    required String text,
    required ContentPopUp contentPopUp,
  }) = OptionContentPopup;

 
  const factory OptionContent.enter({
    required String text,
    String? hint,
    String? additionalInfo,
    String? value,
  }) = OptionContentEnter;
}
```

Then I have an other class which has this OptionContent as a common property for all sealed classes, so I can easily get .content:

```
abstract class BaseOption {
  String get id;
  OptionContent get content;
}

@freezed
abstract class Option implements BaseOption, _$Option {
  @Implements<BaseOption>()
  const factory Option({
    required String id,
    required OptionContentText content,
  }) = OptionText;

  @Implements<BaseOption>()
  const factory Option.withSubtitle({
    required String id,
    required OptionContentTextWithHeader content,
  }) = OptionTextWithSubtitle;

  @Implements<BaseOption>()
  const factory Option.enter({
    required String id,
    required OptionContentEnter content,
    @Default([]) List<OptionEnterValidation> validations,
  }) = OptionEnter;

  @Implements<BaseOption>()
  const factory Option.popup({
    required String id,
    required OptionContentPopup content,
  }) = OptionPopUp;
}
```

When I run build runner, I get an error InvalidType in the latest freezed version, however before it worked fine. Error:
```
mixin _$Option {
  String get id => throw _privateConstructorUsedError;
  InvalidType get content => throw _privateConstructorUsedError;
```

So, now I can not get content as a base property, and workaround is just to get rid of this common content name, and in one of the sealed classes to change like popUpContent.

**To Reproduce**

You can insert this code and try build runner
Flutter 3.13.0 • channel stable 
Dart 3.1.0
freezed: 2.4.1
freezed_annotation: 2.4.1
build_runner: 2.4.6

**Expected behavior**
I want to access base OptionContent from Option class without doing .when or .map every time 

Thanks is advance, if I am doing something wrong, please contact me.
I did pub upgrade, clean and etc

**Comment by rrousselGit** [comment]
You've passed generated types as input to a Freezed class. This is not supported at the moment and won't be until macros.

There are already issues about this, so I'll close this
