### ISSUE TITLE
`@Default({})` still uses an unmodifiable map with `@unfreezed`.

### ISSUE THREAD

**Issue by jaysephjw** [rrousselGit/freezed#996]
*problem*

`@Default({})` generates an unmodifiable map, even if used with `@unfreezed`.

*example*
```
@unfreezed
class QuizStats with _$QuizStats {
  factory QuizStats({
    @Default({})
    Map <String, (int, int)> results,
  }) = _QuizResults;
}

// generates...
class _$QuizResultsImpl implements _QuizResults {
_$QuizResultsImpl({this.results = const {}});
...

// Leading to `Unsupported operation: Cannot modify unmodifiable map`. 
```

*thoughts*

Since Default is a `const` class,  doesn't seem like there's an obvious fix. Maybe should just be an error on the build step if the two annotations are incompatible in this case.

**Comment by jaysephjw** [comment]
Ah just found https://github.com/rrousselGit/freezed/issues/725. 

I can close for now, will consider submitting a PR to add a warning on the buildstep.

**Comment by rrousselGit** [comment]
A warning wouldn't make sense I think. It's a totally normal behavior. The list itself is immutable, but the list instance can be changed.
