### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by KopaczPatryk** [rrousselGit/freezed#999]
https://github.com/rrousselGit/freezed/blob/078fd6e5c6337a03a9a560da0cb37f6902754e6a/packages/freezed_annotation/lib/freezed_annotation.dart#L558

Hey, I've found typo in words Hoouse and Codee. There is cool vsc addon called [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) that highlights typos as you go.

Best regards

**Comment by rrousselGit** [comment]
Thanks for the extension suggestion! It'll definitely help :)
